-- MZMOB-673. Mediation Development work to process MMSC CDRr's from SINCH

CREATE TABLE MZ_MOB_DATA_OWNER.CDR_INPUT_MMSC_SINCH
(
  TRANSACTION_ID                NUMBER NOT NULL,
  CREATED_DATE                  DATE DEFAULT sysdate NOT NULL,
  INPUT_FILENAME                VARCHAR2(80 BYTE),
  A_NUMBER                      VARCHAR2 (31 BYTE),
  B_NUMBER                      VARCHAR2 (31 BYTE),
  SEQ_NUM                       VARCHAR2 (30 BYTE),
  CDR_TYPE                      VARCHAR2 (30 BYTE),
  MESSAGE_ID                    VARCHAR2 (30 BYTE),
  DESTINATION_ID                VARCHAR2 (30 BYTE),
  ORIG_ADDRESS                  VARCHAR2 (30 BYTE),
  ORIG_IMSI                     VARCHAR2 (30 BYTE),
  ORIG_DOMAIN                   VARCHAR2 (30 BYTE),
  ORIG_NA                       VARCHAR2 (1 BYTE),
  ORIG_NP                       VARCHAR2 (1 BYTE),
  ORIG_IP                       VARCHAR2 (30 BYTE),
  ORIG_ADDRESS_WITH_TYPE        VARCHAR2 (30 BYTE),
  DEST_ADDRESS                  VARCHAR2 (30 BYTE),
  DEST_NA                       VARCHAR2 (1 BYTE),
  DEST_NP                       VARCHAR2 (1 BYTE),
  DESTINATION_RS_ADDRESS        VARCHAR2 (30 BYTE),
  SUBMISSION_TIME               VARCHAR2 (30 BYTE),
  RECORD_TIMESTAMP              VARCHAR2 (30 BYTE),
  MM_PRIORITY                   VARCHAR2 (30 BYTE),
  MESSAGE_SIZE                  VARCHAR2 (30 BYTE),
  DELIVERY_REPORT_REQUESTED     VARCHAR2 (30 BYTE),
  MM_PROTOCOL_VERSION           VARCHAR2 (30 BYTE),
  MM_TYPE                       VARCHAR2 (30 BYTE),
  MM_STATUS_CODE                VARCHAR2 (30 BYTE),
  STATUS_TEXT                   VARCHAR2 (256 BYTE),
  MMS_EVENT_TYPE                VARCHAR2 (30 BYTE),
  ORIG_LOCATION                 VARCHAR2 (30 BYTE),
  ORIG_LOCATION_IP              VARCHAR2 (30 BYTE),
  ORIG_NETWORK_NODE             VARCHAR2 (30 BYTE),
  DEST_IP                       VARCHAR2 (30 BYTE),
  DEST_LOCATION                 VARCHAR2 (30 BYTE),
  DEST_LOCATION_IP              VARCHAR2 (30 BYTE),
  DEST_NETWORK_NODE             VARCHAR2 (30 BYTE),
  DEST_PLMN_ID                  VARCHAR2 (30 BYTE),
  SGSN_MCC_MNC                  VARCHAR2 (30 BYTE),
  REQUEST_STATUS                VARCHAR2 (30 BYTE),
  SOURCE_NAME                   VARCHAR2 (30 BYTE),
  SOURCE_TYPE                   VARCHAR2 (30 BYTE),
  SINK_NAME                     VARCHAR2 (30 BYTE),
  SINK_TYPE                     VARCHAR2 (30 BYTE),
  SINK_PROVIDER_TYPE            VARCHAR2 (30 BYTE),
  SUBMIT_STATUS_CODE            VARCHAR2 (30 BYTE),
  COMPONENT_GROUP_LIST          VARCHAR2 (256 BYTE),
  COMPONENT_LIST                VARCHAR2 (256 BYTE),
  CONTENT_TYPE                  VARCHAR2 (30 BYTE),
  COST                          VARCHAR2 (30 BYTE),
  DELIVERED_TIME                VARCHAR2 (30 BYTE),
  DELIVERY_ATTEMPT_TIME         VARCHAR2 (30 BYTE),
  DEST_ADDRESS_WITH_TYPE        VARCHAR2 (30 BYTE),
  DEST_DOMAIN                   VARCHAR2 (30 BYTE),
  DEST_IMSI                     VARCHAR2 (30 BYTE),
  READ_REPLY_REPORT_REQUESTED   VARCHAR2 (30 BYTE),
  ROW_NUM                       VARCHAR2 (30 BYTE),
  VAS_ID                        VARCHAR2 (30 BYTE),
  VASP_ID                       VARCHAR2 (30 BYTE),
  SUBJECT_SIZE                  VARCHAR2 (30 BYTE),
  EXPIRE_TIME                   VARCHAR2 (30 BYTE),
  CDR_CHARGED_PARTY_TYPE        VARCHAR2 (30 BYTE)
)
SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE MZ_MOB_CDR_DATA
partition by range(CREATED_DATE)
(
  PARTITION PMAXVALUE  VALUES LESS THAN (MAXVALUE) TABLESPACE  MZ_MOB_CDR_DATA);

CREATE INDEX CDR_INPUT_MMSC_SINCH_IDX1 ON CDR_INPUT_MMSC_SINCH (ORIG_ADDRESS) LOCAL;

CREATE INDEX CDR_INPUT_MMSC_SINCH_IDX2 ON CDR_INPUT_MMSC_SINCH (DEST_ADDRESS) LOCAL;

CREATE INDEX CDR_INPUT_MMSC_SINCH_IDX3 ON CDR_INPUT_MMSC_SINCH (CREATED_DATE) LOCAL;

CREATE INDEX CDR_INPUT_MMSC_SINCH_IDX4 ON CDR_INPUT_MMSC_SINCH (TRANSACTION_ID) LOCAL;