-- MED-205 - Create two holding tables and a combined view of fixed and mobile data to replace the DN_ENHANCED_BU_LOOKUP table
--
-- Create the new mobile BU lookup table
--
CREATE TABLE DN_BU_LOOKUP_MOBILE
(
	DIRECTORY_NUMBER  VARCHAR2(40),
	UNIT_ID           NUMBER,
	START_DATE        DATE,
	SKCI_FLAG         NUMBER,
	CEASE_DATE        DATE,
	CKCI_FLAG         NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;



-- Create the new fixed BU lookup table by copying contents from existing DN_ENHANCED_BU_LOOKUP table
--
CREATE TABLE DN_BU_LOOKUP_FIXED AS
(
	SELECT *
	  FROM DN_ENHANCED_BU_LOOKUP
);



-- Drop the DN_ENHANCED_BU_LOOKUP table here, before attempting to create the replacement view
--
DROP TABLE DN_ENHANCED_BU_LOOKUP CASCADE CONSTRAINTS;



-- Create the new combined view and name it DN_ENHANCED_BU_LOOKUP. Assumes the original table DN_ENHANCED_BU_LOOKUP has been dropped
--
CREATE OR REPLACE VIEW DN_ENHANCED_BU_LOOKUP AS
SELECT DIRECTORY_NUMBER, UNIT_ID, START_DATE, SKCI_FLAG, CEASE_DATE, CKCI_FLAG
  FROM DN_BU_LOOKUP_FIXED
 UNION ALL
SELECT DIRECTORY_NUMBER, UNIT_ID, START_DATE, SKCI_FLAG, CEASE_DATE, CKCI_FLAG
  FROM DN_BU_LOOKUP_MOBILE;


 
-- Create indexes on the new DN_BU_LOOKUP_MOBILE table
--
CREATE UNIQUE INDEX DN_BU_LOOKUP_MOBILE_PK ON DN_BU_LOOKUP_MOBILE (DIRECTORY_NUMBER, UNIT_ID);
 
CREATE INDEX DN_BU_LOOKUP_MOBILE_FK1 ON DN_BU_LOOKUP_MOBILE (UNIT_ID);


-- Create indexes on the new DN_BU_LOOKUP_FIXED table
--
CREATE UNIQUE INDEX DN_BU_LOOKUP_FIXED_PK  ON DN_BU_LOOKUP_FIXED (DIRECTORY_NUMBER, UNIT_ID);

CREATE INDEX DN_BU_LOOKUP_FIXED_FK1 ON DN_BU_LOOKUP_FIXED (UNIT_ID);



-- Create constraints on the new DN_BU_LOOKUP_MOBILE table
--
ALTER TABLE DN_BU_LOOKUP_FIXED ADD CONSTRAINT DN_BU_LOOKUP_FIXED_PK PRIMARY KEY (DIRECTORY_NUMBER, UNIT_ID);

ALTER TABLE DN_BU_LOOKUP_FIXED ADD CONSTRAINT DN_BU_LOOKUP_FIXED_FK1 FOREIGN KEY (UNIT_ID) REFERENCES BUSINESS_UNITS (UNIT_ID);



-- Create constraints on the new DN_BU_LOOKUP_FIXED table
--
ALTER TABLE DN_BU_LOOKUP_MOBILE ADD CONSTRAINT DN_BU_LOOKUP_MOBILE_PK PRIMARY KEY (DIRECTORY_NUMBER, UNIT_ID);

ALTER TABLE DN_BU_LOOKUP_MOBILE ADD CONSTRAINT DN_BU_LOOKUP_MOBILE_FK1 FOREIGN KEY (UNIT_ID) REFERENCES BUSINESS_UNITS (UNIT_ID);
