-- Create a new business unit for ROI NEXUS
-- 18	ROITLK
-- 20	ROITRT

--
INSERT INTO MZ_CDR_OWNER.BUSINESS_UNITS VALUES (18, 'ROITLK');

--
INSERT INTO MZ_CDR_OWNER.BUSINESS_UNITS VALUES (20, 'ROITRT');

