-- CREATE TABLE DN_SHORTCODE_SUFFIX_CODES_ROI
--
CREATE TABLE MZ_CDR_OWNER.DN_SHORTCODE_SUFFIX_CODES_ROI
(
  SHORTCODE    VARCHAR2(10 BYTE)                NOT NULL,
  DESCRIPTION  VARCHAR2(200 BYTE)
)
TABLESPACE MZ_CDR_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

 
-- CREATE INDEX ON DN_SHORTCODE_SUFFIX_CODES_ROI
--
CREATE UNIQUE INDEX MZ_CDR_OWNER.DN_SHORTCODE_SUFFIX_CODES_ROI_PK ON MZ_CDR_OWNER.DN_SHORTCODE_SUFFIX_CODES_ROI
(SHORTCODE)
LOGGING
TABLESPACE MZ_CDR_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


-- CREATE SYNONYM
--
CREATE SYNONYM MZ_CDR_USER.DN_SHORTCODE_SUFFIX_CODES_ROI FOR MZ_CDR_OWNER.DN_SHORTCODE_SUFFIX_CODES_ROI;


-- ADD CONSTRAINT TO DN_SHORTCODE_SUFFIX_CODES_ROI
--
ALTER TABLE MZ_CDR_OWNER.DN_SHORTCODE_SUFFIX_CODES_ROI ADD (
  CONSTRAINT DN_SHORTCODE_SUFFIX_CODES_ROI
 PRIMARY KEY
 (SHORTCODE));


-- GRANT SELECT TO THE TABLE FOR MZ_CDR_READONLY
--
GRANT SELECT ON MZ_CDR_OWNER.DN_SHORTCODE_SUFFIX_CODES_ROI TO MZ_CDR_READONLY;


-- INSERT DATA INTO THE DN_SHORTCODE_SUFFIX_CODES_ROI TABLE
--
INSERT INTO DN_SHORTCODE_SUFFIX_CODES_ROI ( SHORTCODE, DESCRIPTION ) VALUES ( 
'11213239', 'ES'); 
INSERT INTO DN_SHORTCODE_SUFFIX_CODES_ROI ( SHORTCODE, DESCRIPTION ) VALUES ( 
'99913239', 'ES'); 

