-- MZMOB-961.5G-SA

INSERT INTO MZ_MOB_DATA_OWNER.MZ_CONFIGURATION (PARAMETER,PARAMETER_VALUE) values ('ACHF_DUP_BATCH_CHECK', 1);
INSERT INTO MZ_MOB_DATA_OWNER.MZ_CONFIGURATION (PARAMETER,PARAMETER_VALUE) values ('BCHF_DUP_BATCH_CHECK', 1);

CREATE TABLE MZ_MOB_DATA_OWNER.CDR_INPUT_CHF_AMDOCS
(
  TRANSACTION_ID                    NUMBER      NOT NULL,
  CREATED_DATE                      DATE        DEFAULT sysdate               NOT NULL,
  INPUT_FILENAME                    VARCHAR2(80 BYTE),
  A_NUMBER                          VARCHAR2(64 BYTE),
  RECORDING_NET_FUNCTION_ID         VARCHAR2(50 BYTE),
  SERVED_MSISDN                     VARCHAR2(20 BYTE),
  IMSI                              VARCHAR2(20 BYTE),
  IMEI                              VARCHAR2(20 BYTE),
  RAT_TYPE                          NUMBER(38),
  NCHF_RAT_TYPE                     VARCHAR2(30 BYTE),
  REC_OPEN_TIME                     VARCHAR2(30 BYTE),
  REC_OPEN_TIME_UTC                 DATE,
  DURATION                          NUMBER(15),
  CAUSE_FOR_REC_CLOSE               NUMBER(5),
  CHARGING_ID                       NUMBER(20),
  LOCAL_SEQ_NUM                     VARCHAR2(64 BYTE),
  PARTIAL_REC_SEQ_NUM               INTEGER,
  DNN_ID_APN                        VARCHAR2(80 BYTE),
  EUTRALOCATION                     VARCHAR2(512 BYTE),
  NRLOCATION                        VARCHAR2(512 BYTE),
  N3GALOCATION                      VARCHAR2(512 BYTE),
  UTRALOCATION                      VARCHAR2(512 BYTE),
  GERALOCATION                      VARCHAR2(512 BYTE),
  MCC                               VARCHAR2(5 BYTE),
  MNC                               VARCHAR2(5 BYTE),
  LAC                               VARCHAR2(10 BYTE),
  CELL_ID                           VARCHAR2(10 BYTE),
  SAC                               VARCHAR2(20 BYTE),
  RAC                               VARCHAR2(5 BYTE),
  TAC                               VARCHAR2(20 BYTE),
  EUTRA_CELL_ID                     VARCHAR2(20 BYTE),
  ENODEB_ID                         VARCHAR2(50 BYTE),
  NRCELL_ID                         VARCHAR2(20 BYTE),
  NID                               VARCHAR2(50 BYTE),
  N3IWF_ID                          VARCHAR2(128 BYTE),
  GNB_ID                            VARCHAR2(128 BYTE),
  NGENB_ID                          VARCHAR2(128 BYTE),
  WAGF_ID                           VARCHAR2(128 BYTE),
  TNGF_ID                           VARCHAR2(128 BYTE),
  SSID                              VARCHAR2(128 BYTE),
  BSSID                             VARCHAR2(128 BYTE),
  CIVIC_ADDRESS                     VARCHAR2(128 BYTE),
  HFC_NODE_ID                       VARCHAR2(128 BYTE),
  IPBINV4ADDRESS                    VARCHAR2(32 BYTE),
  IPBINV6ADDRESS                    VARCHAR2(32 BYTE),
  LOCATION_NUMBER                   VARCHAR2(128 BYTE),
  VLR_NUMBER                        VARCHAR2(128 BYTE),
  MSC_NUMBER                        VARCHAR2(128 BYTE),
  GEOGRAPHIC_INFO                   VARCHAR2(128 BYTE),
  GEODETIC_INFO                     VARCHAR2(128 BYTE),
  NETWORK_FUNCTIONALITY             VARCHAR2(20 BYTE),
  PDU_STARTTIME                     VARCHAR2(30 BYTE),
  PDU_STOPTIME                      VARCHAR2(30 BYTE),
  NF_IPADD                          VARCHAR2(50 BYTE),
  SESSION_ID                        VARCHAR2(200 BYTE),
  SNSSAI_SST                        NUMBER(20),
  SNSSAI_SD                         VARCHAR2(36 BYTE),
  NETWORKFUNCTION_IP                VARCHAR2(50 BYTE),
  RECORD_CLOSURE_TIME               VARCHAR2(30 BYTE),
  PCI_SRVNG_CN_PLMNID               VARCHAR2(6 BYTE),
  FIVEG_QI                          NUMBER(20),
  ARP_LEVEL                         NUMBER(20),
  PRIORITY_LEVEL                    NUMBER(20),
  AVG_WINDOW                        NUMBER(20),
  MAX_DATA_BURST_VOL                NUMBER(20),
  MAX_BIT_RATE_UL                   NUMBER(20),
  MAX_BIT_RATE_DL                   NUMBER(20),
  GUARANTEED_BIT_RATE_UL            NUMBER(20),
  GUARANTEED_BIT_RATE_DL            NUMBER(20),
  AGGR_MAX_BR_UL                    NUMBER(20),
  AGGR_MAX_BR_DL                    NUMBER(20),
  NGRAN_SEC_RAT_TYPE_5GN            VARCHAR2(5 BYTE),
  NGRAN_START_TIME_5GN              VARCHAR2(30 BYTE),
  NGRAN_END_TIME_5GN                VARCHAR2(30 BYTE),
  DATA_VOL_UPLINK_5GN               NUMBER(20),
  DATA_VOL_DOWNLINK_5GN             NUMBER(20),
  BE_ID                             NUMBER(10),
  MUU_RATING_GRP_C1               NUMBER(38),
  MUU_UPFID_C1                    VARCHAR2(36 BYTE),
  UUC_FIRST_USG_C1                VARCHAR2(30 BYTE),
  UUC_LAST_USG_C1                 VARCHAR2(30 BYTE),
  UUC_TIME_USG_C1                 VARCHAR2(30 BYTE),
  UUC_SMF_TRIGR_C1                VARCHAR2(50 BYTE),
  UUC_DATA_VOL_UP_C1              NUMBER(20),
  UUC_DATA_VOL_DL_C1              NUMBER(20),
  UUC_RAT_C1                      NUMBER(38),
  UUC_NCHF_RAT_C1                 VARCHAR2(20 BYTE),
  UUC_LOCAL_SEQ_NUM_C1            VARCHAR2(64 BYTE),
  UUC_AF_CHARGING_ID_C1           VARCHAR2(256 BYTE),
  MUU_PDU_ADDR_V4_C1              VARCHAR2(50 BYTE),
  MUU_PDU_ADDR_V6_C1              VARCHAR2(50 BYTE),
  EUTRALOCATION_C1                VARCHAR2(512 BYTE),
  NRLOCATION_C1                   VARCHAR2(512 BYTE),
  N3GALOCATION_C1                 VARCHAR2(512 BYTE),
  UTRALOCATION_C1                 VARCHAR2(512 BYTE),
  GERALOCATION_C1                 VARCHAR2(512 BYTE),
  MCC_C1                          VARCHAR2(5 BYTE),
  MNC_C1                          VARCHAR2(5 BYTE),
  LAC_C1                          VARCHAR2(10 BYTE),
  CELL_ID_C1                      VARCHAR2(10 BYTE),
  SAC_C1                          VARCHAR2(20 BYTE),
  RAC_C1                          VARCHAR2(5 BYTE),
  TAC_C1                          VARCHAR2(20 BYTE),
  EUTRA_CELL_ID_C1                VARCHAR2(20 BYTE),
  ENODEB_ID_C1                    VARCHAR2(50 BYTE),
  NRCELL_ID_C1                    VARCHAR2(20 BYTE),
  NID_C1                          VARCHAR2(50 BYTE),
  N3IWF_ID_C1                     VARCHAR2(128 BYTE),
  GNB_ID_C1                       VARCHAR2(128 BYTE),
  NGENB_ID_C1                     VARCHAR2(128 BYTE),
  WAGF_ID_C1                      VARCHAR2(128 BYTE),
  TNGF_ID_C1                      VARCHAR2(128 BYTE),
  SSID_C1                         VARCHAR2(128 BYTE),
  BSSID_C1                        VARCHAR2(128 BYTE),
  CIVIC_ADDRESS_C1                VARCHAR2(128 BYTE),
  HFC_NODE_ID_C1                  VARCHAR2(128 BYTE),
  IPBINV4ADDRESS_C1               VARCHAR2(32 BYTE),
  IPBINV6ADDRESS_C1               VARCHAR2(32 BYTE),
  LOCATION_NUMBER_C1              VARCHAR2(128 BYTE),
  VLR_NUMBER_C1                   VARCHAR2(128 BYTE),
  MSC_NUMBER_C1                   VARCHAR2(128 BYTE),
  GEOGRAPHIC_INFO_C1              VARCHAR2(128 BYTE),
  GEODETIC_INFO_C1                VARCHAR2(128 BYTE),
  UUC_FIVEG_QI_C1                 VARCHAR2(5 BYTE),
  UUC_ARP_C1                      NUMBER(20),
  UUC_MAX_BIT_RATE_UL_C1          NUMBER(20),
  UUC_MAX_BIT_RATE_DL_C1          NUMBER(20),
  UUC_GUARANTEED_BIT_RATE_UL_C1   NUMBER(20),
  UUC_GUARANTEED_BIT_RATE_DL_C1   NUMBER(20),
  MUU_RATING_GRP_C2               NUMBER(38),
  MUU_UPFID_C2                    VARCHAR2(36 BYTE),
  UUC_FIRST_USG_C2                VARCHAR2(30 BYTE),
  UUC_LAST_USG_C2                 VARCHAR2(30 BYTE),
  UUC_TIME_USG_C2                 VARCHAR2(30 BYTE),
  UUC_SMF_TRIGR_C2                VARCHAR2(50 BYTE),
  UUC_DATA_VOL_UP_C2              NUMBER(20),
  UUC_DATA_VOL_DL_C2              NUMBER(20),
  UUC_RAT_C2                      NUMBER(38),
  UUC_NCHF_RAT_C2                 VARCHAR2(20 BYTE),
  UUC_LOCAL_SEQ_NUM_C2            VARCHAR2(64 BYTE),
  UUC_AF_CHARGING_ID_C2           VARCHAR2(256 BYTE),
  MUU_PDU_ADDR_V4_C2              VARCHAR2(50 BYTE),
  MUU_PDU_ADDR_V6_C2              VARCHAR2(50 BYTE),
  EUTRALOCATION_C2                VARCHAR2(512 BYTE),
  NRLOCATION_C2                   VARCHAR2(512 BYTE),
  N3GALOCATION_C2                 VARCHAR2(512 BYTE),
  UTRALOCATION_C2                 VARCHAR2(512 BYTE),
  GERALOCATION_C2                 VARCHAR2(512 BYTE),
  MCC_C2                          VARCHAR2(5 BYTE),
  MNC_C2                          VARCHAR2(5 BYTE),
  LAC_C2                          VARCHAR2(10 BYTE),
  CELL_ID_C2                      VARCHAR2(10 BYTE),
  SAC_C2                          VARCHAR2(20 BYTE),
  RAC_C2                          VARCHAR2(5 BYTE),
  TAC_C2                          VARCHAR2(20 BYTE),
  EUTRA_CELL_ID_C2                VARCHAR2(20 BYTE),
  ENODEB_ID_C2                    VARCHAR2(50 BYTE),
  NRCELL_ID_C2                    VARCHAR2(20 BYTE),
  NID_C2                          VARCHAR2(50 BYTE),
  N3IWF_ID_C2                     VARCHAR2(128 BYTE),
  GNB_ID_C2                       VARCHAR2(128 BYTE),
  NGENB_ID_C2                     VARCHAR2(128 BYTE),
  WAGF_ID_C2                      VARCHAR2(128 BYTE),
  TNGF_ID_C2                      VARCHAR2(128 BYTE),
  SSID_C2                         VARCHAR2(128 BYTE),
  BSSID_C2                        VARCHAR2(128 BYTE),
  CIVIC_ADDRESS_C2                VARCHAR2(128 BYTE),
  HFC_NODE_ID_C2                  VARCHAR2(128 BYTE),
  IPBINV4ADDRESS_C2               VARCHAR2(32 BYTE),
  IPBINV6ADDRESS_C2               VARCHAR2(32 BYTE),
  LOCATION_NUMBER_C2              VARCHAR2(128 BYTE),
  VLR_NUMBER_C2                   VARCHAR2(128 BYTE),
  MSC_NUMBER_C2                   VARCHAR2(128 BYTE),
  GEOGRAPHIC_INFO_C2              VARCHAR2(128 BYTE),
  GEODETIC_INFO_C2                VARCHAR2(128 BYTE),
  UUC_FIVEG_QI_C2                 VARCHAR2(5 BYTE),
  UUC_ARP_C2                      NUMBER(20),
  UUC_MAX_BIT_RATE_UL_C2          NUMBER(20),
  UUC_MAX_BIT_RATE_DL_C2          NUMBER(20),
UUC_GUARANTEED_BIT_RATE_UL_C2   NUMBER(20),
  UUC_GUARANTEED_BIT_RATE_DL_C2   NUMBER(20),
  MUU_RATING_GRP_C3               NUMBER(38),
  MUU_UPFID_C3                    VARCHAR2(36 BYTE),
  UUC_FIRST_USG_C3                VARCHAR2(30 BYTE),
  UUC_LAST_USG_C3                 VARCHAR2(30 BYTE),
  UUC_TIME_USG_C3                 VARCHAR2(30 BYTE),
  UUC_SMF_TRIGR_C3                VARCHAR2(50 BYTE),
  UUC_DATA_VOL_UP_C3              NUMBER(20),
  UUC_DATA_VOL_DL_C3              NUMBER(20),
  UUC_RAT_C3                      NUMBER(38),
  UUC_NCHF_RAT_C3                 VARCHAR2(20 BYTE),
  UUC_LOCAL_SEQ_NUM_C3            VARCHAR2(64 BYTE),
  UUC_AF_CHARGING_ID_C3           VARCHAR2(256 BYTE),
  MUU_PDU_ADDR_V4_C3              VARCHAR2(50 BYTE),
  MUU_PDU_ADDR_V6_C3              VARCHAR2(50 BYTE),
  EUTRALOCATION_C3                VARCHAR2(512 BYTE),
  NRLOCATION_C3                   VARCHAR2(512 BYTE),
  N3GALOCATION_C3                 VARCHAR2(512 BYTE),
  UTRALOCATION_C3                 VARCHAR2(512 BYTE),
  GERALOCATION_C3                 VARCHAR2(512 BYTE),
  MCC_C3                          VARCHAR2(5 BYTE),
  MNC_C3                          VARCHAR2(5 BYTE),
  LAC_C3                          VARCHAR2(10 BYTE),
  CELL_ID_C3                      VARCHAR2(10 BYTE),
  SAC_C3                          VARCHAR2(20 BYTE),
  RAC_C3                          VARCHAR2(5 BYTE),
  TAC_C3                          VARCHAR2(20 BYTE),
  EUTRA_CELL_ID_C3                VARCHAR2(20 BYTE),
  ENODEB_ID_C3                    VARCHAR2(50 BYTE),
  NRCELL_ID_C3                    VARCHAR2(20 BYTE),
  NID_C3                          VARCHAR2(50 BYTE),
  N3IWF_ID_C3                     VARCHAR2(128 BYTE),
  GNB_ID_C3                       VARCHAR2(128 BYTE),
  NGENB_ID_C3                     VARCHAR2(128 BYTE),
  WAGF_ID_C3                      VARCHAR2(128 BYTE),
  TNGF_ID_C3                      VARCHAR2(128 BYTE),
  SSID_C3                         VARCHAR2(128 BYTE),
  BSSID_C3                        VARCHAR2(128 BYTE),
  CIVIC_ADDRESS_C3                VARCHAR2(128 BYTE),
  HFC_NODE_ID_C3                  VARCHAR2(128 BYTE),
  IPBINV4ADDRESS_C3               VARCHAR2(32 BYTE),
  IPBINV6ADDRESS_C3               VARCHAR2(32 BYTE),
  LOCATION_NUMBER_C3              VARCHAR2(128 BYTE),
  VLR_NUMBER_C3                   VARCHAR2(128 BYTE),
  MSC_NUMBER_C3                   VARCHAR2(128 BYTE),
  GEOGRAPHIC_INFO_C3              VARCHAR2(128 BYTE),
  GEODETIC_INFO_C3                VARCHAR2(128 BYTE),
  UUC_FIVEG_QI_C3                 VARCHAR2(5 BYTE),
  UUC_ARP_C3                      NUMBER(20),
  UUC_MAX_BIT_RATE_UL_C3          NUMBER(20),
  UUC_MAX_BIT_RATE_DL_C3          NUMBER(20),
  UUC_GUARANTEED_BIT_RATE_UL_C3   NUMBER(20),
  UUC_GUARANTEED_BIT_RATE_DL_C3   NUMBER(20),
  MUU_RATING_GRP_C4               NUMBER(38),
  MUU_UPFID_C4                    VARCHAR2(36 BYTE),
  UUC_FIRST_USG_C4                VARCHAR2(30 BYTE),
  UUC_LAST_USG_C4                 VARCHAR2(30 BYTE),
  UUC_TIME_USG_C4                 VARCHAR2(30 BYTE),
  UUC_SMF_TRIGR_C4                VARCHAR2(50 BYTE),
  UUC_DATA_VOL_UP_C4              NUMBER(20),
  UUC_DATA_VOL_DL_C4              NUMBER(20),
  UUC_RAT_C4                      NUMBER(38),
  UUC_NCHF_RAT_C4                 VARCHAR2(20 BYTE),
  UUC_LOCAL_SEQ_NUM_C4            VARCHAR2(64 BYTE),
  UUC_AF_CHARGING_ID_C4           VARCHAR2(256 BYTE),
  MUU_PDU_ADDR_V4_C4              VARCHAR2(50 BYTE),
  MUU_PDU_ADDR_V6_C4              VARCHAR2(50 BYTE),
  EUTRALOCATION_C4                VARCHAR2(512 BYTE),
  NRLOCATION_C4                   VARCHAR2(512 BYTE),
  N3GALOCATION_C4                 VARCHAR2(512 BYTE),
  UTRALOCATION_C4                 VARCHAR2(512 BYTE),
  GERALOCATION_C4                 VARCHAR2(512 BYTE),
  MCC_C4                          VARCHAR2(5 BYTE),
  MNC_C4                          VARCHAR2(5 BYTE),
  LAC_C4                          VARCHAR2(10 BYTE),
  CELL_ID_C4                      VARCHAR2(10 BYTE),
  SAC_C4                          VARCHAR2(20 BYTE),
  RAC_C4                          VARCHAR2(5 BYTE),
  TAC_C4                          VARCHAR2(20 BYTE),
  EUTRA_CELL_ID_C4                VARCHAR2(20 BYTE),
  ENODEB_ID_C4                    VARCHAR2(50 BYTE),
  NRCELL_ID_C4                    VARCHAR2(20 BYTE),
  NID_C4                          VARCHAR2(50 BYTE),
  N3IWF_ID_C4                     VARCHAR2(128 BYTE),
  GNB_ID_C4                       VARCHAR2(128 BYTE),
  NGENB_ID_C4                     VARCHAR2(128 BYTE),
  WAGF_ID_C4                      VARCHAR2(128 BYTE),
  TNGF_ID_C4                      VARCHAR2(128 BYTE),
  SSID_C4                         VARCHAR2(128 BYTE),
  BSSID_C4                        VARCHAR2(128 BYTE),
  CIVIC_ADDRESS_C4                VARCHAR2(128 BYTE),
  HFC_NODE_ID_C4                  VARCHAR2(128 BYTE),
  IPBINV4ADDRESS_C4               VARCHAR2(32 BYTE),
  IPBINV6ADDRESS_C4               VARCHAR2(32 BYTE),
  LOCATION_NUMBER_C4              VARCHAR2(128 BYTE),
  VLR_NUMBER_C4                   VARCHAR2(128 BYTE),
  MSC_NUMBER_C4                   VARCHAR2(128 BYTE),
  GEOGRAPHIC_INFO_C4              VARCHAR2(128 BYTE),
  GEODETIC_INFO_C4                VARCHAR2(128 BYTE),
  UUC_FIVEG_QI_C4                 VARCHAR2(5 BYTE),
  UUC_ARP_C4                      NUMBER(20),
  UUC_MAX_BIT_RATE_UL_C4          NUMBER(20),
  UUC_MAX_BIT_RATE_DL_C4          NUMBER(20),
  UUC_GUARANTEED_BIT_RATE_UL_C4   NUMBER(20),
  UUC_GUARANTEED_BIT_RATE_DL_C4   NUMBER(20),
  MUU_RATING_GRP_C5               NUMBER(38),
  MUU_UPFID_C5                    VARCHAR2(36 BYTE),
  UUC_FIRST_USG_C5                VARCHAR2(30 BYTE),
  UUC_LAST_USG_C5                 VARCHAR2(30 BYTE),
  UUC_TIME_USG_C5                 VARCHAR2(30 BYTE),
  UUC_SMF_TRIGR_C5                VARCHAR2(50 BYTE),
  UUC_DATA_VOL_UP_C5              NUMBER(20),
  UUC_DATA_VOL_DL_C5              NUMBER(20),
  UUC_RAT_C5                      NUMBER(38),
  UUC_NCHF_RAT_C5                 VARCHAR2(20 BYTE),
  UUC_LOCAL_SEQ_NUM_C5            VARCHAR2(64 BYTE),
  UUC_AF_CHARGING_ID_C5           VARCHAR2(256 BYTE),
  MUU_PDU_ADDR_V4_C5              VARCHAR2(50 BYTE),
  MUU_PDU_ADDR_V6_C5              VARCHAR2(50 BYTE),
  EUTRALOCATION_C5                VARCHAR2(512 BYTE),
  NRLOCATION_C5                   VARCHAR2(512 BYTE),
  N3GALOCATION_C5                 VARCHAR2(512 BYTE),
  UTRALOCATION_C5                 VARCHAR2(512 BYTE),
  GERALOCATION_C5                 VARCHAR2(512 BYTE),
  MCC_C5                          VARCHAR2(5 BYTE),
  MNC_C5                          VARCHAR2(5 BYTE),
  LAC_C5                          VARCHAR2(10 BYTE),
  CELL_ID_C5                      VARCHAR2(10 BYTE),
  SAC_C5                          VARCHAR2(20 BYTE),
  RAC_C5                          VARCHAR2(5 BYTE),
  TAC_C5                          VARCHAR2(20 BYTE),
  EUTRA_CELL_ID_C5                VARCHAR2(20 BYTE),
  ENODEB_ID_C5                    VARCHAR2(50 BYTE),
  NRCELL_ID_C5                    VARCHAR2(20 BYTE),
  NID_C5                          VARCHAR2(50 BYTE),
  N3IWF_ID_C5                     VARCHAR2(128 BYTE),
  GNB_ID_C5                       VARCHAR2(128 BYTE),
  NGENB_ID_C5                     VARCHAR2(128 BYTE),
  WAGF_ID_C5                      VARCHAR2(128 BYTE),
  TNGF_ID_C5                      VARCHAR2(128 BYTE),
  SSID_C5                         VARCHAR2(128 BYTE),
  BSSID_C5                        VARCHAR2(128 BYTE),
  CIVIC_ADDRESS_C5                VARCHAR2(128 BYTE),
  HFC_NODE_ID_C5                  VARCHAR2(128 BYTE),
  IPBINV4ADDRESS_C5               VARCHAR2(32 BYTE),
  IPBINV6ADDRESS_C5               VARCHAR2(32 BYTE),
  LOCATION_NUMBER_C5              VARCHAR2(128 BYTE),
  VLR_NUMBER_C5                   VARCHAR2(128 BYTE),
  MSC_NUMBER_C5                   VARCHAR2(128 BYTE),
  GEOGRAPHIC_INFO_C5              VARCHAR2(128 BYTE),
  GEODETIC_INFO_C5                VARCHAR2(128 BYTE),
  UUC_FIVEG_QI_C5                 VARCHAR2(5 BYTE),
  UUC_ARP_C5                      NUMBER(20),
  UUC_MAX_BIT_RATE_UL_C5          NUMBER(20),
  UUC_MAX_BIT_RATE_DL_C5          NUMBER(20),
  UUC_GUARANTEED_BIT_RATE_UL_C5   NUMBER(20),
  UUC_GUARANTEED_BIT_RATE_DL_C5   NUMBER(20),
  MUU_RATING_GRP_C6               NUMBER(38),
  MUU_UPFID_C6                    VARCHAR2(36 BYTE),
  UUC_FIRST_USG_C6                VARCHAR2(30 BYTE),
  UUC_LAST_USG_C6                 VARCHAR2(30 BYTE),
  UUC_TIME_USG_C6                 VARCHAR2(30 BYTE),
  UUC_SMF_TRIGR_C6                VARCHAR2(50 BYTE),
  UUC_DATA_VOL_UP_C6              NUMBER(20),
  UUC_DATA_VOL_DL_C6              NUMBER(20),
  UUC_RAT_C6                      NUMBER(38),
  UUC_NCHF_RAT_C6                 VARCHAR2(20 BYTE),
  UUC_LOCAL_SEQ_NUM_C6            VARCHAR2(64 BYTE),
  UUC_AF_CHARGING_ID_C6           VARCHAR2(256 BYTE),
  MUU_PDU_ADDR_V4_C6              VARCHAR2(50 BYTE),
  MUU_PDU_ADDR_V6_C6              VARCHAR2(50 BYTE),
  EUTRALOCATION_C6                VARCHAR2(512 BYTE),
  NRLOCATION_C6                   VARCHAR2(512 BYTE),
  N3GALOCATION_C6                 VARCHAR2(512 BYTE),
  UTRALOCATION_C6                 VARCHAR2(512 BYTE),
  GERALOCATION_C6                 VARCHAR2(512 BYTE),
  MCC_C6                          VARCHAR2(5 BYTE),
  MNC_C6                          VARCHAR2(5 BYTE),
  LAC_C6                          VARCHAR2(10 BYTE),
  CELL_ID_C6                      VARCHAR2(10 BYTE),
  SAC_C6                          VARCHAR2(20 BYTE),
  RAC_C6                          VARCHAR2(5 BYTE),
  TAC_C6                          VARCHAR2(20 BYTE),
  EUTRA_CELL_ID_C6                VARCHAR2(20 BYTE),
  ENODEB_ID_C6                    VARCHAR2(50 BYTE),
  NRCELL_ID_C6                    VARCHAR2(20 BYTE),
  NID_C6                          VARCHAR2(50 BYTE),
  N3IWF_ID_C6                     VARCHAR2(128 BYTE),
  GNB_ID_C6                       VARCHAR2(128 BYTE),
  NGENB_ID_C6                     VARCHAR2(128 BYTE),
  WAGF_ID_C6                      VARCHAR2(128 BYTE),
  TNGF_ID_C6                      VARCHAR2(128 BYTE),
  SSID_C6                         VARCHAR2(128 BYTE),
  BSSID_C6                        VARCHAR2(128 BYTE),
  CIVIC_ADDRESS_C6                VARCHAR2(128 BYTE),
  HFC_NODE_ID_C6                  VARCHAR2(128 BYTE),
  IPBINV4ADDRESS_C6               VARCHAR2(32 BYTE),
  IPBINV6ADDRESS_C6               VARCHAR2(32 BYTE),
  LOCATION_NUMBER_C6              VARCHAR2(128 BYTE),
  VLR_NUMBER_C6                   VARCHAR2(128 BYTE),
  MSC_NUMBER_C6                   VARCHAR2(128 BYTE),
  GEOGRAPHIC_INFO_C6              VARCHAR2(128 BYTE),
  GEODETIC_INFO_C6                VARCHAR2(128 BYTE),
  UUC_FIVEG_QI_C6                 VARCHAR2(5 BYTE),
  UUC_ARP_C6                      NUMBER(20),
  UUC_MAX_BIT_RATE_UL_C6          NUMBER(20),
  UUC_MAX_BIT_RATE_DL_C6          NUMBER(20),
  UUC_GUARANTEED_BIT_RATE_UL_C6   NUMBER(20),
  UUC_GUARANTEED_BIT_RATE_DL_C6   NUMBER(20),
  MUU_RATING_GRP_C7               NUMBER(38),
  MUU_UPFID_C7                    VARCHAR2(36 BYTE),
  UUC_FIRST_USG_C7                VARCHAR2(30 BYTE),
  UUC_LAST_USG_C7                 VARCHAR2(30 BYTE),
  UUC_TIME_USG_C7                 VARCHAR2(30 BYTE),
  UUC_SMF_TRIGR_C7                VARCHAR2(50 BYTE),
  UUC_DATA_VOL_UP_C7              NUMBER(20),
  UUC_DATA_VOL_DL_C7              NUMBER(20),
  UUC_RAT_C7                      NUMBER(38),
  UUC_NCHF_RAT_C7                 VARCHAR2(20 BYTE),
  UUC_LOCAL_SEQ_NUM_C7            VARCHAR2(64 BYTE),
  UUC_AF_CHARGING_ID_C7           VARCHAR2(256 BYTE),
  MUU_PDU_ADDR_V4_C7              VARCHAR2(50 BYTE),
  MUU_PDU_ADDR_V6_C7              VARCHAR2(50 BYTE),
  EUTRALOCATION_C7                VARCHAR2(512 BYTE),
  NRLOCATION_C7                   VARCHAR2(512 BYTE),
  N3GALOCATION_C7                 VARCHAR2(512 BYTE),
  UTRALOCATION_C7                 VARCHAR2(512 BYTE),
  GERALOCATION_C7                 VARCHAR2(512 BYTE),
  MCC_C7                          VARCHAR2(5 BYTE),
  MNC_C7                          VARCHAR2(5 BYTE),
  LAC_C7                          VARCHAR2(10 BYTE),
  CELL_ID_C7                      VARCHAR2(10 BYTE),
  SAC_C7                          VARCHAR2(20 BYTE),
  RAC_C7                          VARCHAR2(5 BYTE),
  TAC_C7                          VARCHAR2(20 BYTE),
  EUTRA_CELL_ID_C7                VARCHAR2(20 BYTE),
  ENODEB_ID_C7                    VARCHAR2(50 BYTE),
  NRCELL_ID_C7                    VARCHAR2(20 BYTE),
  NID_C7                          VARCHAR2(50 BYTE),
  N3IWF_ID_C7                     VARCHAR2(128 BYTE),
  GNB_ID_C7                       VARCHAR2(128 BYTE),
  NGENB_ID_C7                     VARCHAR2(128 BYTE),
  WAGF_ID_C7                      VARCHAR2(128 BYTE),
  TNGF_ID_C7                      VARCHAR2(128 BYTE),
  SSID_C7                         VARCHAR2(128 BYTE),
  BSSID_C7                        VARCHAR2(128 BYTE),
  CIVIC_ADDRESS_C7                VARCHAR2(128 BYTE),
  HFC_NODE_ID_C7                  VARCHAR2(128 BYTE),
  IPBINV4ADDRESS_C7               VARCHAR2(32 BYTE),
  IPBINV6ADDRESS_C7               VARCHAR2(32 BYTE),
  LOCATION_NUMBER_C7              VARCHAR2(128 BYTE),
  VLR_NUMBER_C7                   VARCHAR2(128 BYTE),
  MSC_NUMBER_C7                   VARCHAR2(128 BYTE),
  GEOGRAPHIC_INFO_C7              VARCHAR2(128 BYTE),
  GEODETIC_INFO_C7                VARCHAR2(128 BYTE),
  UUC_FIVEG_QI_C7                 VARCHAR2(5 BYTE),
  UUC_ARP_C7                      NUMBER(20),
  UUC_MAX_BIT_RATE_UL_C7          NUMBER(20),
  UUC_MAX_BIT_RATE_DL_C7          NUMBER(20),
  UUC_GUARANTEED_BIT_RATE_UL_C7   NUMBER(20),
  UUC_GUARANTEED_BIT_RATE_DL_C7   NUMBER(20),
  MUU_RATING_GRP_C8               NUMBER(38),
  MUU_UPFID_C8                    VARCHAR2(36 BYTE),
  UUC_FIRST_USG_C8                VARCHAR2(30 BYTE),
  UUC_LAST_USG_C8                 VARCHAR2(30 BYTE),
  UUC_TIME_USG_C8                 VARCHAR2(30 BYTE),
  UUC_SMF_TRIGR_C8                VARCHAR2(50 BYTE),
  UUC_DATA_VOL_UP_C8              NUMBER(20),
  UUC_DATA_VOL_DL_C8              NUMBER(20),
  UUC_RAT_C8                      NUMBER(38),
  UUC_NCHF_RAT_C8                 VARCHAR2(20 BYTE),
  UUC_LOCAL_SEQ_NUM_C8            VARCHAR2(64 BYTE),
  UUC_AF_CHARGING_ID_C8           VARCHAR2(256 BYTE),
  MUU_PDU_ADDR_V4_C8              VARCHAR2(50 BYTE),
  MUU_PDU_ADDR_V6_C8              VARCHAR2(50 BYTE),
  EUTRALOCATION_C8                VARCHAR2(512 BYTE),
  NRLOCATION_C8                   VARCHAR2(512 BYTE),
  N3GALOCATION_C8                 VARCHAR2(512 BYTE),
  UTRALOCATION_C8                 VARCHAR2(512 BYTE),
  GERALOCATION_C8                 VARCHAR2(512 BYTE),
  MCC_C8                          VARCHAR2(5 BYTE),
  MNC_C8                          VARCHAR2(5 BYTE),
  LAC_C8                          VARCHAR2(10 BYTE),
  CELL_ID_C8                      VARCHAR2(10 BYTE),
  SAC_C8                          VARCHAR2(20 BYTE),
  RAC_C8                          VARCHAR2(5 BYTE),
  TAC_C8                          VARCHAR2(20 BYTE),
  EUTRA_CELL_ID_C8                VARCHAR2(20 BYTE),
  ENODEB_ID_C8                    VARCHAR2(50 BYTE),
  NRCELL_ID_C8                    VARCHAR2(20 BYTE),
  NID_C8                          VARCHAR2(50 BYTE),
  N3IWF_ID_C8                     VARCHAR2(128 BYTE),
  GNB_ID_C8                       VARCHAR2(128 BYTE),
  NGENB_ID_C8                     VARCHAR2(128 BYTE),
  WAGF_ID_C8                      VARCHAR2(128 BYTE),
  TNGF_ID_C8                      VARCHAR2(128 BYTE),
  SSID_C8                         VARCHAR2(128 BYTE),
  BSSID_C8                        VARCHAR2(128 BYTE),
  CIVIC_ADDRESS_C8                VARCHAR2(128 BYTE),
  HFC_NODE_ID_C8                  VARCHAR2(128 BYTE),
  IPBINV4ADDRESS_C8               VARCHAR2(32 BYTE),
  IPBINV6ADDRESS_C8               VARCHAR2(32 BYTE),
  LOCATION_NUMBER_C8              VARCHAR2(128 BYTE),
  VLR_NUMBER_C8                   VARCHAR2(128 BYTE),
  MSC_NUMBER_C8                   VARCHAR2(128 BYTE),
  GEOGRAPHIC_INFO_C8              VARCHAR2(128 BYTE),
  GEODETIC_INFO_C8                VARCHAR2(128 BYTE),
  UUC_FIVEG_QI_C8                 VARCHAR2(5 BYTE),
  UUC_ARP_C8                      NUMBER(20),
  UUC_MAX_BIT_RATE_UL_C8          NUMBER(20),
  UUC_MAX_BIT_RATE_DL_C8          NUMBER(20),
  UUC_GUARANTEED_BIT_RATE_UL_C8   NUMBER(20),
  UUC_GUARANTEED_BIT_RATE_DL_C8   NUMBER(20),
  MUU_RATING_GRP_C9               NUMBER(38),
  MUU_UPFID_C9                    VARCHAR2(36 BYTE),
  UUC_FIRST_USG_C9                VARCHAR2(30 BYTE),
  UUC_LAST_USG_C9                 VARCHAR2(30 BYTE),
  UUC_TIME_USG_C9                 VARCHAR2(30 BYTE),
  UUC_SMF_TRIGR_C9                VARCHAR2(50 BYTE),
  UUC_DATA_VOL_UP_C9              NUMBER(20),
  UUC_DATA_VOL_DL_C9              NUMBER(20),
  UUC_RAT_C9                      NUMBER(38),
  UUC_NCHF_RAT_C9                 VARCHAR2(20 BYTE),
  UUC_LOCAL_SEQ_NUM_C9            VARCHAR2(64 BYTE),
  UUC_AF_CHARGING_ID_C9           VARCHAR2(256 BYTE),
  MUU_PDU_ADDR_V4_C9              VARCHAR2(50 BYTE),
  MUU_PDU_ADDR_V6_C9              VARCHAR2(50 BYTE),
  EUTRALOCATION_C9                VARCHAR2(512 BYTE),
  NRLOCATION_C9                   VARCHAR2(512 BYTE),
  N3GALOCATION_C9                 VARCHAR2(512 BYTE),
  UTRALOCATION_C9                 VARCHAR2(512 BYTE),
  GERALOCATION_C9                 VARCHAR2(512 BYTE),
  MCC_C9                          VARCHAR2(5 BYTE),
  MNC_C9                          VARCHAR2(5 BYTE),
  LAC_C9                          VARCHAR2(10 BYTE),
  CELL_ID_C9                      VARCHAR2(10 BYTE),
  SAC_C9                          VARCHAR2(20 BYTE),
  RAC_C9                          VARCHAR2(5 BYTE),
  TAC_C9                          VARCHAR2(20 BYTE),
  EUTRA_CELL_ID_C9                VARCHAR2(20 BYTE),
  ENODEB_ID_C9                    VARCHAR2(50 BYTE),
  NRCELL_ID_C9                    VARCHAR2(20 BYTE),
  NID_C9                          VARCHAR2(50 BYTE),
  N3IWF_ID_C9                     VARCHAR2(128 BYTE),
  GNB_ID_C9                       VARCHAR2(128 BYTE),
  NGENB_ID_C9                     VARCHAR2(128 BYTE),
  WAGF_ID_C9                      VARCHAR2(128 BYTE),
  TNGF_ID_C9                      VARCHAR2(128 BYTE),
  SSID_C9                         VARCHAR2(128 BYTE),
  BSSID_C9                        VARCHAR2(128 BYTE),
  CIVIC_ADDRESS_C9                VARCHAR2(128 BYTE),
  HFC_NODE_ID_C9                  VARCHAR2(128 BYTE),
  IPBINV4ADDRESS_C9               VARCHAR2(32 BYTE),
  IPBINV6ADDRESS_C9               VARCHAR2(32 BYTE),
  LOCATION_NUMBER_C9              VARCHAR2(128 BYTE),
  VLR_NUMBER_C9                   VARCHAR2(128 BYTE),
  MSC_NUMBER_C9                   VARCHAR2(128 BYTE),
  GEOGRAPHIC_INFO_C9              VARCHAR2(128 BYTE),
  GEODETIC_INFO_C9                VARCHAR2(128 BYTE),
  UUC_FIVEG_QI_C9                 VARCHAR2(5 BYTE),
  UUC_ARP_C9                      NUMBER(20),
  UUC_MAX_BIT_RATE_UL_C9          NUMBER(20),
  UUC_MAX_BIT_RATE_DL_C9          NUMBER(20),
  UUC_GUARANTEED_BIT_RATE_UL_C9   NUMBER(20),
  UUC_GUARANTEED_BIT_RATE_DL_C9   NUMBER(20),
  MUU_RATING_GRP_C10              NUMBER(38),
  MUU_UPFID_C10                   VARCHAR2(36 BYTE),
  UUC_FIRST_USG_C10               VARCHAR2(30 BYTE),
  UUC_LAST_USG_C10                VARCHAR2(30 BYTE),
  UUC_TIME_USG_C10                VARCHAR2(30 BYTE),
  UUC_SMF_TRIGR_C10               VARCHAR2(50 BYTE),
  UUC_DATA_VOL_UP_C10             NUMBER(20),
  UUC_DATA_VOL_DL_C10             NUMBER(20),
  UUC_RAT_C10                     NUMBER(38),
  UUC_NCHF_RAT_C10                VARCHAR2(20 BYTE),
  UUC_LOCAL_SEQ_NUM_C10           VARCHAR2(64 BYTE),
  UUC_AF_CHARGING_ID_C10          VARCHAR2(256 BYTE),
  MUU_PDU_ADDR_V4_C10             VARCHAR2(50 BYTE),
  MUU_PDU_ADDR_V6_C10             VARCHAR2(50 BYTE),
  EUTRALOCATION_C10               VARCHAR2(512 BYTE),
  NRLOCATION_C10                  VARCHAR2(512 BYTE),
  N3GALOCATION_C10                VARCHAR2(512 BYTE),
  UTRALOCATION_C10                VARCHAR2(512 BYTE),
  GERALOCATION_C10                VARCHAR2(512 BYTE),
  MCC_C10                         VARCHAR2(5 BYTE),
  MNC_C10                         VARCHAR2(5 BYTE),
  LAC_C10                         VARCHAR2(10 BYTE),
  CELL_ID_C10                     VARCHAR2(10 BYTE),
  SAC_C10                         VARCHAR2(20 BYTE),
  RAC_C10                         VARCHAR2(5 BYTE),
  TAC_C10                         VARCHAR2(20 BYTE),
  EUTRA_CELL_ID_C10               VARCHAR2(20 BYTE),
  ENODEB_ID_C10                   VARCHAR2(50 BYTE),
  NRCELL_ID_C10                   VARCHAR2(20 BYTE),
  NID_C10                         VARCHAR2(50 BYTE),
  N3IWF_ID_C10                    VARCHAR2(128 BYTE),
  GNB_ID_C10                      VARCHAR2(128 BYTE),
  NGENB_ID_C10                    VARCHAR2(128 BYTE),
  WAGF_ID_C10                     VARCHAR2(128 BYTE),
  TNGF_ID_C10                     VARCHAR2(128 BYTE),
  SSID_C10                        VARCHAR2(128 BYTE),
  BSSID_C10                       VARCHAR2(128 BYTE),
  CIVIC_ADDRESS_C10               VARCHAR2(128 BYTE),
  HFC_NODE_ID_C10                 VARCHAR2(128 BYTE),
  IPBINV4ADDRESS_C10              VARCHAR2(32 BYTE),
  IPBINV6ADDRESS_C10              VARCHAR2(32 BYTE),
  LOCATION_NUMBER_C10             VARCHAR2(128 BYTE),
  VLR_NUMBER_C10                  VARCHAR2(128 BYTE),
  MSC_NUMBER_C10                  VARCHAR2(128 BYTE),
  GEOGRAPHIC_INFO_C10             VARCHAR2(128 BYTE),
  GEODETIC_INFO_C10               VARCHAR2(128 BYTE),
  UUC_FIVEG_QI_C10                VARCHAR2(5 BYTE),
  UUC_ARP_C10                     NUMBER(20),
  UUC_MAX_BIT_RATE_UL_C10         NUMBER(20),
  UUC_MAX_BIT_RATE_DL_C10         NUMBER(20),
  UUC_GUARANTEED_BIT_RATE_UL_C10  NUMBER(20),
  UUC_GUARANTEED_BIT_RATE_DL_C10  NUMBER(20)
);