CREATE SEQUENCE CRM_OUTPUT_SEQ
  MINVALUE 1 
  MAXVALUE 99999 
  INCREMENT BY 1 
  START WITH 1 
  NOCACHE  
  NOORDER  
  NOCYCLE;
  
  
 CREATE TABLE MZ_MOB_DATA_OWNER.CDR_OUTPUT_CRM_GPRS (
	TRANSACTION_ID       NUMBER NOT NULL,
	CREATED_DATE         DATE DEFAULT SYSDATE               NOT NULL,
	INPUT_FILENAME       VARCHAR2(100),
	RECORD_TYPE          VARCHAR2(10),
	TYPE_ID_USG          VARCHAR2(10),
	TRANS_DT             VARCHAR2(20),
	CYCLE_START_DATE     VARCHAR2(6),
	POINT_ORIGIN         VARCHAR2(30),
	PRIMARY_UNITS        VARCHAR2(30),
	PROVIDER_ID          VARCHAR2(10),
	EXT_TRACKING_ID      VARCHAR2(40),
	AMOUNT               VARCHAR2(20),
	RPP_STATE            VARCHAR2(10),
	VISIT_COUNTRY_CODE   VARCHAR2(60),
	OCS_CHARGE_CODE_ID   VARCHAR2(30),
	LOCAL_FILE_SEQ       VARCHAR2(6),
	EXTERNAL_ID          VARCHAR2(80),
	EXTERNAL_ID_TYPE     VARCHAR2(10),
	CUSTOMER_TAG         VARCHAR2(30),
	BILL_CYCLE_END_DATE  VARCHAR2(8)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
partition by range(CREATED_DATE)
(
  PARTITION PMAXVALUE  VALUES LESS THAN (MAXVALUE) TABLESPACE  MZ_MOB_CDR_DATA);


CREATE INDEX CDR_OUTPUT_CRM_GPRS_IDX1 ON CDR_OUTPUT_CRM_GPRS (INPUT_FILENAME) LOCAL;


-- CREATE PARTITION LOCAL INDEX ON CREATED_DATE
--
CREATE INDEX CDR_OUTPUT_CRM_GPRS_IDX2 ON CDR_OUTPUT_CRM_GPRS (CREATED_DATE) LOCAL;
