-- Insert parameter values
--
Insert into MZ_CONFIGURATION
   (PARAMETER, PARAMETER_VALUE)
 Values
   ('OCS_DUP_BATCH_CHECK', 1);

Insert into MZ_CONFIGURATION
   (PARAMETER, PARAMETER_VALUE)
 Values
   ('IMS_DUP_BATCH_CHECK', 1);

Insert into MZ_CONFIGURATION
   (PARAMETER, PARAMETER_VALUE)
 Values
   ('SMSC_DUP_BATCH_CHECK', 1);

Insert into MZ_CONFIGURATION
   (PARAMETER, PARAMETER_VALUE)
 Values
   ('MMSC_DUP_BATCH_CHECK', 1);   

Insert into MZ_CONFIGURATION
   (PARAMETER, PARAMETER_VALUE)
 Values
   ('PGW_DUP_BATCH_CHECK', 1);  

Insert into MZ_CONFIGURATION
   (PARAMETER, PARAMETER_VALUE)
 Values
   ('OCS_DUP_UDR_CHECK', 1);

Insert into MZ_CONFIGURATION
   (PARAMETER, PARAMETER_VALUE)
 Values
   ('IMS_DUP_UDR_CHECK', 1);

Insert into MZ_CONFIGURATION
   (PARAMETER, PARAMETER_VALUE)
 Values
   ('SMSC_DUP_UDR_CHECK', 1);
   
Insert into MZ_CONFIGURATION
   (PARAMETER, PARAMETER_VALUE)
 Values
   ('MMSC_DUP_UDR_CHECK', 1);   
   
Insert into MZ_CONFIGURATION
   (PARAMETER, PARAMETER_VALUE)
 Values
   ('PGW_DUP_UDR_CHECK', 1);    
   