-- MED-529. Handle further NIC code prefixes in Nokia IBCF CDRs

Insert into NIC_PREFIX_CODES (NIC_PREFIX,NIC_PREFIX_DESC) values ('6104','IBCF NCP');
Insert into NIC_PREFIX_CODES (NIC_PREFIX,NIC_PREFIX_DESC) values ('6105','IBCF NCP');
Insert into NIC_PREFIX_CODES (NIC_PREFIX,NIC_PREFIX_DESC) values ('6106','IBCF NCP');
Insert into NIC_PREFIX_CODES (NIC_PREFIX,NIC_PREFIX_DESC) values ('6107','IBCF NCP');
Insert into NIC_PREFIX_CODES (NIC_PREFIX,NIC_PREFIX_DESC) values ('6108','IBCF NCP');
Insert into NIC_PREFIX_CODES (NIC_PREFIX,NIC_PREFIX_DESC) values ('6109','IBCF NCP');
Insert into NIC_PREFIX_CODES (NIC_PREFIX,NIC_PREFIX_DESC) values ('6110','IBCF NCP');