-- MZMOB-518 - Create a Sky SMSC SMSoLTE GT lookup table [amg]
--
CREATE TABLE SKY_SMSC_LTE_GT
(
  GT	VARCHAR2(25 BYTE),
  ROLE_OF_NODE	NUMBER,
  DESCRIPTION	VARCHAR2(40 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;


-- INSERT SKY SMSC LTE GT NUMBERS
--
INSERT INTO SKY_SMSC_LTE_GT ( GT, ROLE_OF_NODE,
DESCRIPTION ) VALUES (
'447488200001', 0, 'DR MO GT'); 

INSERT INTO SKY_SMSC_LTE_GT ( GT, ROLE_OF_NODE,
DESCRIPTION ) VALUES (
'447488200007', 0, 'ENGLO MO GT'); 

INSERT INTO SKY_SMSC_LTE_GT ( GT, ROLE_OF_NODE,
DESCRIPTION ) VALUES (
'447488200011', 0, 'MIMNC MO GT'); 

INSERT INTO SKY_SMSC_LTE_GT ( GT, ROLE_OF_NODE,
DESCRIPTION ) VALUES (
'447488200015', 0, 'LAB MO GT'); 

