-- Create tables for MON files 
-- MZMOB-342. Process OCS MON files to enable the roaming daily pass requirement [amg]
-- 
CREATE TABLE CDR_INPUT_OCS_MON 
(
  TRANSACTION_ID NUMBER NOT NULL
, CREATED_DATE DATE DEFAULT sysdate NOT NULL 
, INPUT_FILENAME VARCHAR2(80) 
, CDR_ID VARCHAR2(20) 
, CDR_SUB_ID VARCHAR2(20) 
, CDR_TYPE VARCHAR2(1) 
, SPLIT_CDR_REASON VARCHAR2(1) 
, CDR_BATCH_ID VARCHAR2(20) 
, SRC_REC_LINE_NO VARCHAR2(10) 
, SRC_CDR_ID VARCHAR2(20) 
, SRC_CDR_NO VARCHAR2(20) 
, STATUS VARCHAR2(1) 
, RE_RATING_TIMES VARCHAR2(3) 
, CREATE_DATE VARCHAR2(14) 
, START_DATE VARCHAR2(14) 
, END_DATE VARCHAR2(14)
, DURATION VARCHAR2(20)
, CUST_LOCAL_START_DATE VARCHAR2(14) 
, CUST_LOCAL_END_DATE VARCHAR2(14) 
, STD_EVT_TYPE_ID VARCHAR2(10) 
, EVT_SOURCE_CAT VARCHAR2(1) 
, OBJ_TYPE VARCHAR2(1) 
, OBJ_ID  VARCHAR2(64)
, OWNER_CUST_ID VARCHAR2(20) 
, DEFAULT_ACCT_ID VARCHAR2(20) 
, PRI_IDENTITY VARCHAR2(64) 
, BILL_CYCLE_ID VARCHAR2(20) 
, SERVICE_CATEG VARCHAR2(10) 
, USAGE_SERVICE_TYPE VARCHAR2(10) 
, SESSION_ID VARCHAR2(128) 
, RESULT_CODE VARCHAR2(10) 
, RESULT_REASON VARCHAR2(256) 
, BE_ID VARCHAR2(10) 
, HOT_SEQ VARCHAR2(10) 
, CP_ID VARCHAR2(10) 
, RECIPIENT_NUMBER VARCHAR2(64) 
, USAGE_MEASURE_ID VARCHAR2(10) 
, ACTUAL_USAGE VARCHAR2(20) 
, RATE_USAGE VARCHAR2(20) 
, SERVICE_UNIT_TYPE VARCHAR2(10) 
, DEBIT_AMOUNT VARCHAR2(20) 
, BRAND_ID VARCHAR2(20) 
, MAIN_OFFERING_ID VARCHAR2(20) 
, PAY_TYPE VARCHAR2(1) 
, CHARGING_PARTY_NUMBER VARCHAR2(64) 
, A_NUMBER VARCHAR2(64)
, CHARGING_PARTY_TYPE VARCHAR2(1) 
, CYCLE_BEGIN_TIME VARCHAR2(14)
, CYCLE_END_TIME VARCHAR2(14)
, CYCLE_LENGTH VARCHAR2(10)
, ELAPSE_CYCLES VARCHAR2(10)
, INNER_CYCLE_BEGIN_TIME VARCHAR2(14)
, INNER_CYCLE_END_TIME VARCHAR2(14)
, PRODUCT_ID VARCHAR2(20) 
, OFFERING_ID VARCHAR2(20) 
, OFFERING_INST_ID VARCHAR2(20) 
, ORDER_STATUS VARCHAR2(1)
, PRORATE_FLAG VARCHAR2(1)
, START_TIME_OF_BILL_CYCLE VARCHAR2(14)
, CHARGE_PARTY_INDICATOR   VARCHAR2(1)
, POS_RENT_MODE	VARCHAR2(1)
, TRIGGER_MODE	VARCHAR2(1)
, EXECUTE_FLAG	VARCHAR2(1)
, PRODUCT_CODE	VARCHAR2(64)
, MAIN_BALANCE_INFO	VARCHAR2(255)
, CHG_BALANCE_INFO	VARCHAR2(255)
, CHG_FREE_UNIT_INFO	VARCHAR2(255)
, USER_STATE	VARCHAR2(10)
, CALLING_VPN_TOP_GROUP_NUMBER	VARCHAR2(64)
, CALLING_VPN_GROUP_NUMBER	VARCHAR2(64)
, GROUP_PAY_FLAG	VARCHAR2(10)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

-- OCS_MON_OFFERING_LOOKUP
CREATE TABLE OCS_MON_OFFERING_LOOKUP
(
OFFERING_ID VARCHAR2(20)
, DESCRIPTION VARCHAR2(100)
, TIMEZONE    VARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

-- Create indexes
--
CREATE INDEX CDR_INPUT_OCS_MON_IDX1 ON CDR_INPUT_OCS_MON(A_NUMBER);

CREATE UNIQUE INDEX OFFERING_LOOKUP_PK ON OCS_MON_OFFERING_LOOKUP(OFFERING_ID);

-- Add contraints
--
--

ALTER TABLE OCS_MON_OFFERING_LOOKUP ADD
  CONSTRAINT OFFERING_LOOKUP_PK
  PRIMARY KEY  (OFFERING_ID);
