-- MZMOB-349 - Increase field sizes in CDR_INPUT_OCS_MMS
--
ALTER TABLE CDR_INPUT_OCS_MMS 
MODIFY 
( 
   B_NUMBER VARCHAR2(128),
   CALLED_PARTY_NUMBER VARCHAR2(128),
   DIALED_NUMBER VARCHAR2(128)
);

