-- MZMOB-358 Add Auditing Control Checks to IGOR processing
-- Author: B Knowles 
-- Date: 15th August 2017

-- Create TADIG tables
--

-- 
--  -------------------------------------------------- 
--  Generated by Enterprise Architect Version 9.3.931
--  Created On : Monday, 22 May, 2017 
--  DBMS       : Oracle 
--  -------------------------------------------------- 
DROP TABLE GSMA_TADIG CASCADE CONSTRAINTS;
CREATE TABLE GSMA_TADIG
(
	TADIG          VARCHAR2(5)  NOT NULL,   -- This is the primary TADIG code assigned to a Mobile Operator by the GSMA. 
	MCC            VARCHAR2(3)  NOT NULL,   -- The Mobile Country Code. 
	MNC            VARCHAR2(3)  NOT NULL,   -- Mobile Network Code 
	MGT_CC         VARCHAR2(10) NOT NULL,   -- Mobile Global Title Country Code 
	MGT_NC         VARCHAR2(10) NOT NULL,   -- Mobile Global Title Network Destination Code 
	OPERATOR_NAME  VARCHAR2(80) NOT NULL,   -- Network Operator Name 
	COUNTRY        VARCHAR2(80) NOT NULL,   -- Country of Network Operator with the assigned TADIG code 
	INPUT_FILENAME VARCHAR2(50) NOT NULL    -- This column is intended to reflect the source data set (file name) from which a particular row is created/updated. 
);

COMMENT ON TABLE GSMA_TADIG IS 'This table stores the static information of a Mobile operator.';
COMMENT ON COLUMN GSMA_TADIG.TADIG          IS 'This is the primary TADIG code assigned to a Mobile Operator by the GSMA.';
COMMENT ON COLUMN GSMA_TADIG.MCC            IS 'The Mobile Country Code.';
COMMENT ON COLUMN GSMA_TADIG.MNC            IS 'Mobile Network Code';
COMMENT ON COLUMN GSMA_TADIG.MGT_CC         IS 'Mobile Global Title Country Code';
COMMENT ON COLUMN GSMA_TADIG.MGT_NC         IS 'Mobile Global Title Network Destination Code';
COMMENT ON COLUMN GSMA_TADIG.OPERATOR_NAME  IS 'Network Operator Name';
COMMENT ON COLUMN GSMA_TADIG.COUNTRY        IS 'Country of Network Operator with the assigned TADIG code';
COMMENT ON COLUMN GSMA_TADIG.INPUT_FILENAME IS 'This column is intended to reflect the source data set (file name) from which a particular row is created/updated.';

CREATE INDEX GSMA_TADIG_IDX1 ON GSMA_TADIG (MCC ASC, MNC ASC);

CREATE INDEX GSMA_TADIG_IDX2 ON GSMA_TADIG (MGT_CC ASC, MGT_NC ASC);

CREATE INDEX GSMA_TADIG_IDX3 ON GSMA_TADIG (INPUT_FILENAME ASC);

ALTER TABLE GSMA_TADIG ADD CONSTRAINT GSMA_TADIG_PK 
	PRIMARY KEY (TADIG) 
 USING INDEX ;

--  -------------------------------------------------- 
--  Generated by Enterprise Architect Version 9.3.931
--  Created On : Tuesday, 23 May, 2017 
--  DBMS       : Oracle 
--  -------------------------------------------------- 

DROP TABLE GSMA_CC_NDC_MAP2TADIG CASCADE CONSTRAINTS;
CREATE TABLE GSMA_CC_NDC_MAP2TADIG
(
	CC             VARCHAR2(10) NOT NULL,   -- Country code for E.164 formatted destination 
	NDC            VARCHAR2(20) NOT NULL,   -- Network Destination Code 
	TADIG          VARCHAR2(5)  NOT NULL,   -- This is the primary TADIG code assigned to a Mobile Operator by the GSMA. 
	INPUT_FILENAME VARCHAR2(50) NOT NULL    -- This column is intended to reflect the source data set (file name) from which a particular row is created/updated. 
);

COMMENT ON COLUMN GSMA_CC_NDC_MAP2TADIG.CC             IS 'Country code for E.164 formatted destination';
COMMENT ON COLUMN GSMA_CC_NDC_MAP2TADIG.NDC            IS 'Network Destination Code';
COMMENT ON COLUMN GSMA_CC_NDC_MAP2TADIG.TADIG          IS 'This is the primary TADIG code assigned to a Mobile Operator by the GSMA.';
COMMENT ON COLUMN GSMA_CC_NDC_MAP2TADIG.INPUT_FILENAME IS 'This column is intended to reflect the source data set (file name) from which a particular row is created/updated.';


CREATE INDEX GSMA_CC_NDC_MAP2TADIG_IDX1 ON GSMA_CC_NDC_MAP2TADIG (CC ASC, NDC ASC);

CREATE INDEX GSMA_CC_NDC_MAP2TADIG_IDX2 ON GSMA_CC_NDC_MAP2TADIG (TADIG ASC);

CREATE INDEX GSMA_CC_NDC_MAP2TADIG_IDX3 ON GSMA_CC_NDC_MAP2TADIG (INPUT_FILENAME ASC);

ALTER TABLE GSMA_CC_NDC_MAP2TADIG ADD CONSTRAINT GSMA_CC_NDC_MAP2TADIG_TADIG_FK 
	FOREIGN KEY (TADIG) REFERENCES GSMA_TADIG (TADIG);

--  -------------------------------------------------- 
--  Generated by Enterprise Architect Version 9.3.931
--  Created On : Monday, 22 May, 2017 
--  DBMS       : Oracle 
--  -------------------------------------------------- 

DROP TABLE GSMA_GT_NODE CASCADE CONSTRAINTS;
CREATE TABLE GSMA_GT_NODE
(
	GT_START       VARCHAR2(15),           -- This column identifies the start of a Global Title Range of Network Nodes owned by a network. 
	GT_STOP        VARCHAR2(15),           -- This column identifies the end of a Global Title Range of Network Nodes owned by a network. 
	IP_START       NUMBER(15),             -- Numeric equivalent of an IP version 4 address. Start of range. 
	IP_STOP        NUMBER(15),             -- Numeric equivalent of an IP version 4 address. End of range 
	IP_ADDRESS     VARCHAR2(18),           -- Keep this for information purposes. 
	TADIG          VARCHAR2(5)   NOT NULL, -- TADIG Code identifier of the owning network 
	EFF_DATE       DATE          NOT NULL, -- Date from which this row is effective. 
	LOCATION       VARCHAR2(80),           -- Supplemental location supplied by some operators (optional). 
	NODE_TYPE      VARCHAR2(30),           -- Type of Node for this global title. 
	MOD_TADIG      VARCHAR2(5),            -- Alternative TADIG Code. Initial intention is to use this to override the Channel Island TADIG codes with a unique value to identify which island is visited. 
	INPUT_FILENAME VARCHAR2(50)  NOT NULL  -- This column is intended to reflect the source data set (file name) from which a particular row is created/updated. 
);

COMMENT ON TABLE GSMA_GT_NODE IS 'This table stores the IP address and Global Title and network node type details published in the IR.21 document that may be interacted by a third party network.';
COMMENT ON COLUMN GSMA_GT_NODE.GT_START       IS 'This column identifies the start of a Global Title Range of Network Nodes owned by a network.';
COMMENT ON COLUMN GSMA_GT_NODE.GT_STOP        IS 'This column identifies the end of a Global Title Range of Network Nodes owned by a network.';
COMMENT ON COLUMN GSMA_GT_NODE.IP_START       IS 'Numeric equivalent of an IP version 4 address. Start of range.';
COMMENT ON COLUMN GSMA_GT_NODE.IP_STOP        IS 'Numeric equivalent of an IP version 4 address. End of range'; 
COMMENT ON COLUMN GSMA_GT_NODE.IP_ADDRESS     IS 'Keep this for information purposes.';
COMMENT ON COLUMN GSMA_GT_NODE.TADIG          IS 'TADIG Code identifier of the owning network';
COMMENT ON COLUMN GSMA_GT_NODE.EFF_DATE       IS 'Date from which this row is effective.';
COMMENT ON COLUMN GSMA_GT_NODE.LOCATION       IS 'Supplemental location supplied by some operators (optional).';
COMMENT ON COLUMN GSMA_GT_NODE.NODE_TYPE      IS 'Type of Node for this global title.';
COMMENT ON COLUMN GSMA_GT_NODE.MOD_TADIG      IS 'Alternative TADIG Code. Initial intention is to use this to override the Channel Island TADIG codes with a unique value to identify which island is visited.';
COMMENT ON COLUMN GSMA_GT_NODE.INPUT_FILENAME IS 'This column is intended to reflect the source data set (file name) from which a particular row is created/updated.';

CREATE INDEX GSMA_GT_NODE_IDX1 ON GSMA_GT_NODE (GT_START DESC, GT_STOP ASC);
CREATE INDEX GSMA_GT_NODE_IDX2 ON GSMA_GT_NODE (IP_START DESC, IP_STOP ASC);
CREATE INDEX GSMA_GT_NODE_IDX3 ON GSMA_GT_NODE (EFF_DATE DESC);
CREATE INDEX GSMA_GT_NODE_IDX4 ON GSMA_GT_NODE (TADIG ASC);
CREATE INDEX GSMA_GT_NODE_IDX5 ON GSMA_GT_NODE (INPUT_FILENAME ASC);

ALTER TABLE GSMA_GT_NODE ADD CONSTRAINT GSMA_GT_NODE_GSMA_TADIG_FK
	FOREIGN KEY (TADIG) REFERENCES GSMA_TADIG (TADIG);

--  -------------------------------------------------- 
--  Generated by Enterprise Architect Version 9.3.931
--  Created On : Monday, 22 May, 2017 
--  DBMS       : Oracle 
--  -------------------------------------------------- 

DROP TABLE GSMA_GT_RANGES CASCADE CONSTRAINTS;
CREATE TABLE GSMA_GT_RANGES
(
	GT_START     VARCHAR2(15)   NOT NULL,    -- This column identifies the start of a Global Title Range of Network Nodes owned by a network. 
	GT_STOP      VARCHAR2(15)   NOT NULL,    -- This column identifies the end of a Global Title Range of Network Nodes owned by a network. 
	TADIG        VARCHAR2(5)    NOT NULL,    -- TADIG Code identifier of the owning network 
	EFF_DATE     DATE           NOT NULL,    -- Effective date. 
	INPUT_FILENAME VARCHAR2(50) NOT NULL     -- This column is intended to reflect the source data set (file name) from which a particular row is created/updated. 
);

COMMENT ON TABLE GSMA_GT_RANGES IS 'This table stores the Global Title Range information of a Mobile Networks network nodes.';
COMMENT ON COLUMN GSMA_GT_RANGES.GT_START       IS 'This column identifies the start of a Global Title Range of Network Nodes owned by a network.';
COMMENT ON COLUMN GSMA_GT_RANGES.GT_STOP        IS 'This column identifies the end of a Global Title Range of Network Nodes owned by a network.';
COMMENT ON COLUMN GSMA_GT_RANGES.TADIG          IS 'TADIG Code identifier of the owning network';
COMMENT ON COLUMN GSMA_GT_RANGES.EFF_DATE       IS 'Effective date. ';
COMMENT ON COLUMN GSMA_GT_RANGES.INPUT_FILENAME IS 'This column is intended to reflect the source data set (file name) from which a particular row is created/updated.';

CREATE INDEX GSMA_GT_RANGES_IDX1 ON GSMA_GT_RANGES (GT_START DESC, GT_STOP ASC);

CREATE INDEX GSMA_GT_RANGES_IDX2 ON GSMA_GT_RANGES (EFF_DATE DESC);

CREATE INDEX GSMA_GT_RANGES_IDX3 ON GSMA_GT_RANGES (TADIG ASC);

CREATE INDEX GSMA_GT_RANGES_IDX4 ON GSMA_GT_RANGES (INPUT_FILENAME ASC);

ALTER TABLE GSMA_GT_RANGES ADD CONSTRAINT GSMA_GT_RANGES_TADIG_FK 
	FOREIGN KEY (TADIG) REFERENCES GSMA_TADIG (TADIG);

--  -------------------------------------------------- 
--  Generated by Enterprise Architect Version 9.3.931
--  Created On : Tuesday, 23 May, 2017 
--  DBMS       : Oracle 
--  -------------------------------------------------- 

DROP TABLE GSMA_IP_RANGES CASCADE CONSTRAINTS;
CREATE TABLE GSMA_IP_RANGES
(
	IP_START       NUMBER(15)   NOT NULL,    -- Numeric equivalent of an IP version 4 address. Start of range. 
	IP_STOP        NUMBER(15)   NOT NULL,    -- Numeric equivalent of an IP version 4 address. End of range 
	IP_ADDRESS     VARCHAR2(18) NOT NULL,    -- Keep this for information purposes. 
	TADIG          VARCHAR2(5)  NOT NULL,    -- TADIG Code of the owning Mobile Network. 
	EFF_DATE       DATE         NOT NULL,    -- Effective date.  
	INPUT_FILENAME VARCHAR2(50) NOT NULL     -- This column is intended to reflect the source data set (file name) from which a particular row is created/updated. 
);

COMMENT ON COLUMN GSMA_IP_RANGES.IP_START       IS 'Numeric equivalent of an IP version 4 address. Start of range.';
COMMENT ON COLUMN GSMA_IP_RANGES.IP_STOP        IS 'Numeric equivalent of an IP version 4 address. End of range';
COMMENT ON COLUMN GSMA_IP_RANGES.IP_ADDRESS     IS 'Keep this for information purposes.';
COMMENT ON COLUMN GSMA_IP_RANGES.TADIG          IS 'TADIG Code of the owning Mobile Network.';
COMMENT ON COLUMN GSMA_IP_RANGES.EFF_DATE       IS 'Effective date. ';
COMMENT ON COLUMN GSMA_IP_RANGES.INPUT_FILENAME IS 'This column is intended to reflect the source data set (file name) from which a particular row is created/updated.';

CREATE INDEX GSMA_IP_RANGES_IDX1 ON GSMA_IP_RANGES (IP_START DESC, IP_STOP ASC);

CREATE INDEX GSMA_IP_RANGES_IDX2 ON GSMA_IP_RANGES (EFF_DATE DESC);

CREATE INDEX GSMA_IP_RANGES_IDX3 ON GSMA_IP_RANGES (TADIG ASC);

CREATE INDEX GSMA_IP_RANGES_IDX4 ON GSMA_IP_RANGES (INPUT_FILENAME ASC);

ALTER TABLE GSMA_IP_RANGES ADD CONSTRAINT GSMA_IP_RANGES_TADIG_FK 
	FOREIGN KEY (TADIG) REFERENCES GSMA_TADIG (TADIG);

