-- MZMOB-344 - SQL Script to create partitions for MZMOB-344 script to work
--
-- This step was done manually by DBAs for TS1MMZ and PRODMMZ so in the event of a rebuild
-- of ANY mobile DB environment, this script MUST be run AFTER im24 AND BEFORE im25 
-- is migrated to
--

-- Rename tables to keep a copy of existing data
--
RENAME cdr_input_ims to cdr_input_ims_old;

RENAME cdr_input_ocs_gprs to cdr_input_ocs_gprs_old;

RENAME cdr_input_ocs_sms to cdr_input_ocs_sms_old;

RENAME cdr_input_ocs_voice to cdr_input_ocs_voice_old;

RENAME cdr_input_pgw to cdr_input_pgw_old;

RENAME cdr_input_smsc to cdr_input_smsc_old;

RENAME cdr_input_tap to cdr_input_tap_old;

RENAME mz_audit_filtered to mz_audit_filtered_old;

RENAME mz_audit_input to mz_audit_input_old;

RENAME mz_audit_output to mz_audit_output_old;

-- Recreate the tables with partitioning
--
-- CDR_INPUT_IMS
--
  CREATE TABLE "MZ_MOB_DATA_OWNER"."CDR_INPUT_IMS" 
   (	"TRANSACTION_ID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"INPUT_FILENAME" VARCHAR2(80 BYTE), 
	"RECORD_TYPE" NUMBER, 
	"NODE_ADDRESS" VARCHAR2(128 BYTE), 
	"CALLING_PARTY" VARCHAR2(128 BYTE), 
	"CALLED_PARTY" VARCHAR2(128 BYTE), 
	"CHARGED_PARTY" VARCHAR2(128 BYTE), 
	"DIALLED_PARTY" VARCHAR2(128 BYTE), 
	"A_NUMBER" VARCHAR2(30 BYTE), 
	"B_NUMBER" VARCHAR2(30 BYTE), 
	"DELIVERY_START" TIMESTAMP (6), 
	"DELIVERY_END" TIMESTAMP (6), 
	"DURATION" NUMBER(22,0), 
	"ACCOUNTING_REC_TYPE" NUMBER, 
	"ROLE_OF_NODE" NUMBER, 
	"SERVICE_IDENTIFIER" NUMBER, 
	"CAUSE_FOR_RECORD_CLOSING" NUMBER, 
	"LOCAL_REC_SEQ_NUMBER" VARCHAR2(10 BYTE), 
	"RECORD_SEQ_NUMBER" NUMBER, 
	"SESSION_ID" VARCHAR2(128 BYTE), 
	"IMS_CHARGING_ID" VARCHAR2(128 BYTE), 
	"INCOMP_CDR_IND_ACRLOST_START" VARCHAR2(1 BYTE), 
	"INCOMP_CDR_IND_ACRLOST_INTRM" NUMBER, 
	"INCOMP_CDR_IND_ACRLOST_STOP" VARCHAR2(1 BYTE), 
	"SIP_METHOD" VARCHAR2(30 BYTE), 
	"SRVC_REASON_RTN_CODE" VARCHAR2(10 BYTE), 
	"INCOMING_TRUNK_GRP_ID" VARCHAR2(30 BYTE), 
	"OUTGOING_TRUNK_GRP_ID" VARCHAR2(30 BYTE), 
	"ACCESS_NETWORK_INFORMATION" VARCHAR2(200 BYTE), 
	"ACCESS_TYPE_OR_CLASS" VARCHAR2(30 BYTE), 
	"MCC" VARCHAR2(5 BYTE), 
	"MNC" VARCHAR2(5 BYTE), 
	"LAC" NUMBER, 
	"CI" NUMBER, 
	"SAC" NUMBER, 
	"TAC" NUMBER, 
	"UCI" NUMBER, 
	"ECI" NUMBER, 
	"MAC" VARCHAR2(15 BYTE), 
	"DELIVERY_START_TZ_OFFSET" VARCHAR2(10 BYTE), 
	"OPTIONAL_NUMBER" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE MZ_MOB_CDR_DATA
partition by range(CREATED_DATE)
(
  PARTITION PMAXVALUE  VALUES LESS THAN (MAXVALUE) TABLESPACE  MZ_MOB_CDR_DATA);


-- CDR_INPUT_OCS_GPRS
--
  CREATE TABLE "MZ_MOB_DATA_OWNER"."CDR_INPUT_OCS_GPRS" 
   (	"TRANSACTION_ID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"INPUT_FILENAME" VARCHAR2(80 BYTE), 
	"CDR_ID" VARCHAR2(30 BYTE), 
	"CDR_SUB_ID" VARCHAR2(30 BYTE), 
	"CDR_TYPE" VARCHAR2(5 BYTE), 
	"SPLIT_CDR_REASON" VARCHAR2(5 BYTE), 
	"CDR_BATCH_ID" VARCHAR2(30 BYTE), 
	"SRC_REC_LINE_NO" VARCHAR2(20 BYTE), 
	"SRC_CDR_ID" VARCHAR2(30 BYTE), 
	"SRC_CDR_NO" VARCHAR2(30 BYTE), 
	"STATUS" VARCHAR2(5 BYTE), 
	"RE_RATING_TIMES" VARCHAR2(10 BYTE), 
	"CREATE_DATE" VARCHAR2(30 BYTE), 
	"START_DATE" VARCHAR2(30 BYTE), 
	"END_DATE" VARCHAR2(30 BYTE), 
	"CUST_LOCAL_START_DATE" VARCHAR2(30 BYTE), 
	"CUST_LOCAL_END_DATE" VARCHAR2(30 BYTE), 
	"STD_EVT_TYPE_ID" VARCHAR2(20 BYTE), 
	"EVT_SOURCE_CAT" VARCHAR2(5 BYTE), 
	"OBJ_TYPE" VARCHAR2(5 BYTE), 
	"OBJ_ID" VARCHAR2(80 BYTE), 
	"OWNER_CUST_ID" VARCHAR2(30 BYTE), 
	"DEFAULT_ACCT_ID" VARCHAR2(30 BYTE), 
	"PRI_IDENTITY" VARCHAR2(70 BYTE), 
	"BILL_CYCLE_ID" VARCHAR2(30 BYTE), 
	"SERVICE_CATEG" VARCHAR2(20 BYTE), 
	"USAGE_SERVICE_TYPE" VARCHAR2(20 BYTE), 
	"SESSION_ID" VARCHAR2(128 BYTE), 
	"RESULT_CODE" VARCHAR2(20 BYTE), 
	"RESULT_REASON" VARCHAR2(256 BYTE), 
	"BE_ID" VARCHAR2(20 BYTE), 
	"HOT_SEQ" VARCHAR2(20 BYTE), 
	"CP_ID" VARCHAR2(20 BYTE), 
	"RECIPIENT_NUMBER" VARCHAR2(70 BYTE), 
	"USAGE_MEASURE_ID" VARCHAR2(20 BYTE), 
	"ACTUAL_USAGE" VARCHAR2(30 BYTE), 
	"RATE_USAGE" VARCHAR2(30 BYTE), 
	"SERVICE_UNIT_TYPE" VARCHAR2(15 BYTE), 
	"DEBIT_AMOUNT" VARCHAR2(20 BYTE), 
	"TOTAL_TAX" VARCHAR2(20 BYTE), 
	"CALLING_PARTY_NUMBER" VARCHAR2(70 BYTE), 
	"A_NUMBER" VARCHAR2(70 BYTE), 
	"APN" VARCHAR2(30 BYTE), 
	"URL" VARCHAR2(30 BYTE), 
	"CALLING_PARTY_IMSI" VARCHAR2(64 BYTE), 
	"ACCESS_NETWORK_ADDR" VARCHAR2(30 BYTE), 
	"GGSN_ADDR" VARCHAR2(30 BYTE), 
	"CALLING_ROAM_INFO" VARCHAR2(256 BYTE), 
	"CALLING_CELL_ID" VARCHAR2(60 BYTE), 
	"TIMESTAMP_OF_SGSN" VARCHAR2(30 BYTE), 
	"TIMEZONE_OF_SGSN" VARCHAR2(15 BYTE), 
	"CHARGING_TIME" VARCHAR2(30 BYTE), 
	"TOTAL_FLUX" VARCHAR2(30 BYTE), 
	"UP_FLUX" VARCHAR2(30 BYTE), 
	"DOWN_FLUX" VARCHAR2(30 BYTE), 
	"ELAPSE_DURATION" VARCHAR2(20 BYTE), 
	"IMEI" VARCHAR2(30 BYTE), 
	"SERVICE_ID" VARCHAR2(30 BYTE), 
	"SP_ID" VARCHAR2(30 BYTE), 
	"CATEG_ID" VARCHAR2(30 BYTE), 
	"CONTENT_ID" VARCHAR2(30 BYTE), 
	"QOS" VARCHAR2(40 BYTE), 
	"BEARER_PROTOCOL_TYPE" VARCHAR2(20 BYTE), 
	"START_TIME" VARCHAR2(30 BYTE), 
	"STOP_TIME" VARCHAR2(30 BYTE), 
	"CHARGING_ID" VARCHAR2(30 BYTE), 
	"MAIN_OFFERING_ID" VARCHAR2(30 BYTE), 
	"CHARGING_PARTY_NUMBER" VARCHAR2(70 BYTE), 
	"PAY_TYPE" VARCHAR2(5 BYTE), 
	"CHARGING_TYPE" VARCHAR2(5 BYTE), 
	"ROAM_STATE" VARCHAR2(5 BYTE), 
	"CALLING_HOME_CC" VARCHAR2(10 BYTE), 
	"CALLING_HOME_AREA_CODE" VARCHAR2(10 BYTE), 
	"CALLING_HOME_NETWORK_CODE" VARCHAR2(10 BYTE), 
	"CALLING_ROAM_CC" VARCHAR2(10 BYTE), 
	"CALLING_ROAM_AREA_CODE" VARCHAR2(10 BYTE), 
	"CALLING_ROAM_NETWORK_CODE" VARCHAR2(10 BYTE), 
	"CALLING_NETWORK_TYPE" VARCHAR2(20 BYTE), 
	"ONLINE_CHARGING_FLAG" VARCHAR2(5 BYTE), 
	"START_TIME_OF_BILL_CYCLE" VARCHAR2(30 BYTE), 
	"LAST_EFFECT_OFFERING" VARCHAR2(30 BYTE), 
	"DT_DISCOUNT" VARCHAR2(20 BYTE), 
	"PRIMARY_OFFER_CHG_AMT" VARCHAR2(30 BYTE), 
	"CHARGE_CODE_INFO" VARCHAR2(256 BYTE), 
	"CALLING_HOME_COUNTRY" VARCHAR2(64 BYTE), 
	"CALLING_ROAM_COUNTRY" VARCHAR2(64 BYTE), 
	"RATING_GROUP" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE MZ_MOB_CDR_DATA
partition by range(CREATED_DATE)
(
  PARTITION PMAXVALUE  VALUES LESS THAN (MAXVALUE) TABLESPACE  MZ_MOB_CDR_DATA);
  
  
-- CDR_INPUT_OCS_SMS
--
  CREATE TABLE "MZ_MOB_DATA_OWNER"."CDR_INPUT_OCS_SMS" 
   (	"TRANSACTION_ID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"INPUT_FILENAME" VARCHAR2(80 BYTE), 
	"CDR_ID" VARCHAR2(20 BYTE), 
	"CDR_SUB_ID" VARCHAR2(20 BYTE), 
	"CDR_TYPE" VARCHAR2(1 BYTE), 
	"SPLIT_CDR_REASON" VARCHAR2(1 BYTE), 
	"CDR_BATCH_ID" VARCHAR2(20 BYTE), 
	"SRC_REC_LINE_NO" VARCHAR2(10 BYTE), 
	"SRC_CDR_ID" VARCHAR2(20 BYTE), 
	"SRC_CDR_NO" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(1 BYTE), 
	"RE_RATING_TIMES" VARCHAR2(3 BYTE), 
	"CREATE_DATE" VARCHAR2(14 BYTE), 
	"START_DATE" VARCHAR2(14 BYTE), 
	"END_DATE" VARCHAR2(14 BYTE), 
	"CUST_LOCAL_START_DATE" VARCHAR2(14 BYTE), 
	"CUST_LOCAL_END_DATE" VARCHAR2(14 BYTE), 
	"STD_EVT_TYPE_ID" VARCHAR2(10 BYTE), 
	"EVT_SOURCE_CAT" VARCHAR2(1 BYTE), 
	"OBJ_TYPE" VARCHAR2(1 BYTE), 
	"OBJ_ID" VARCHAR2(80 BYTE), 
	"OWNER_CUST_ID" VARCHAR2(20 BYTE), 
	"DEFAULT_ACCT_ID" VARCHAR2(20 BYTE), 
	"PRI_IDENTITY" VARCHAR2(64 BYTE), 
	"BILL_CYCLE_ID" VARCHAR2(20 BYTE), 
	"SERVICE_CATEG" VARCHAR2(10 BYTE), 
	"USAGE_SERVICE_TYPE" VARCHAR2(10 BYTE), 
	"SESSION_ID" VARCHAR2(128 BYTE), 
	"RESULT_CODE" VARCHAR2(10 BYTE), 
	"RESULT_REASON" VARCHAR2(256 BYTE), 
	"BE_ID" VARCHAR2(10 BYTE), 
	"HOT_SEQ" VARCHAR2(10 BYTE), 
	"CP_ID" VARCHAR2(10 BYTE), 
	"RECIPIENT_NUMBER" VARCHAR2(64 BYTE), 
	"USAGE_MEASURE_ID" VARCHAR2(10 BYTE), 
	"ACTUAL_USAGE" VARCHAR2(20 BYTE), 
	"RATE_USAGE" VARCHAR2(20 BYTE), 
	"SERVICE_UNIT_TYPE" VARCHAR2(10 BYTE), 
	"DEBIT_AMOUNT" VARCHAR2(20 BYTE), 
	"TOTAL_TAX" VARCHAR2(20 BYTE), 
	"CALLING_PARTY_NUMBER" VARCHAR2(64 BYTE), 
	"CALLED_PARTY_NUMBER" VARCHAR2(64 BYTE), 
	"A_NUMBER" VARCHAR2(64 BYTE), 
	"B_NUMBER" VARCHAR2(64 BYTE), 
	"CALLING_PARTY_IMSI" VARCHAR2(64 BYTE), 
	"CALLED_PARTY_IMSI" VARCHAR2(64 BYTE), 
	"DIALED_NUMBER" VARCHAR2(64 BYTE), 
	"ORIGINAL_CALLED_PARTY" VARCHAR2(64 BYTE), 
	"SERVICE_FLOW" VARCHAR2(1 BYTE), 
	"CALL_FORWARD_INDICATOR" VARCHAR2(2 BYTE), 
	"CALLING_ROAM_INFO" VARCHAR2(256 BYTE), 
	"CALLING_CELL_ID" VARCHAR2(60 BYTE), 
	"CALLED_ROAM_INFO" VARCHAR2(256 BYTE), 
	"CALLED_CELL_ID" VARCHAR2(60 BYTE), 
	"TIMESTAMP_OF_SSP" VARCHAR2(14 BYTE), 
	"TIMEZONE_OF_SSP" VARCHAR2(10 BYTE), 
	"BEARER_CAPABILITY" VARCHAR2(32 BYTE), 
	"CHARGING_TIME" VARCHAR2(14 BYTE), 
	"SEND_RESULT" VARCHAR2(10 BYTE), 
	"SMS_ID" VARCHAR2(20 BYTE), 
	"IMEI" VARCHAR2(24 BYTE), 
	"SMS_LENGTH" VARCHAR2(10 BYTE), 
	"SMSC_ADDRESS" VARCHAR2(20 BYTE), 
	"REFUND_INDICATOR" VARCHAR2(20 BYTE), 
	"BRAND_ID" VARCHAR2(20 BYTE), 
	"MAIN_OFFERING_ID" VARCHAR2(20 BYTE), 
	"CHARGING_PARTY_NUMBER" VARCHAR2(64 BYTE), 
	"CHARGE_PARTY_INDICATOR" VARCHAR2(1 BYTE), 
	"PAY_TYPE" VARCHAR2(1 BYTE), 
	"CHARGING_TYPE" VARCHAR2(1 BYTE), 
	"SMS_TYPE" VARCHAR2(10 BYTE), 
	"ON_NET_INDICATOR" VARCHAR2(1 BYTE), 
	"ROAM_STATE" VARCHAR2(1 BYTE), 
	"CALLING_HOME_COUNTRY_CODE" VARCHAR2(10 BYTE), 
	"CALLING_HOME_AREA_NUMBER" VARCHAR2(10 BYTE), 
	"CALLING_HOME_NETWORK_CODE" VARCHAR2(10 BYTE), 
	"CALLING_ROAM_COUNTRY_CODE" VARCHAR2(10 BYTE), 
	"CALLING_ROAM_AREA_NUMBER" VARCHAR2(10 BYTE), 
	"CALLING_ROAM_NETWORK_CODE" VARCHAR2(10 BYTE), 
	"CALLED_HOME_COUNTRY_CODE" VARCHAR2(10 BYTE), 
	"CALLED_HOME_AREA_NUMBER" VARCHAR2(10 BYTE), 
	"CALLED_HOME_NETWORK_CODE" VARCHAR2(10 BYTE), 
	"CALLED_ROAM_COUNTRY_CODE" VARCHAR2(10 BYTE), 
	"CALLED_ROAM_AREA_NUMBER" VARCHAR2(10 BYTE), 
	"CALLED_ROAM_NETWORK_CODE" VARCHAR2(10 BYTE), 
	"SERVICE_TYPE" VARCHAR2(128 BYTE), 
	"SPECIAL_NUMBER_INDICATOR" VARCHAR2(10 BYTE), 
	"NP_FLAG" VARCHAR2(1 BYTE), 
	"NP_PREFIX" VARCHAR2(6 BYTE), 
	"CALLING_CUG_NO" VARCHAR2(20 BYTE), 
	"CALLED_CUG_NO" VARCHAR2(20 BYTE), 
	"OPPOSE_NETWORK_TYPE" VARCHAR2(10 BYTE), 
	"OPPOSE_NUMBER_TYPE" VARCHAR2(10 BYTE), 
	"CALLING_NETWORK_TYPE" VARCHAR2(10 BYTE), 
	"CALLED_NETWORK_TYPE" VARCHAR2(10 BYTE), 
	"CALLING_VPN_TOP_GROUP_NUMBER" VARCHAR2(64 BYTE), 
	"CALLING_VPN_GROUP_NUMBER" VARCHAR2(64 BYTE), 
	"CALLING_VPN_SHORT_NUMBER" VARCHAR2(10 BYTE), 
	"CALLED_VPN_TOP_GROUP_NUMBER" VARCHAR2(64 BYTE), 
	"CALLED_VPN_GROUP_NUMBER" VARCHAR2(64 BYTE), 
	"CALLED_VPN_SHORT_NUMBER" VARCHAR2(10 BYTE), 
	"GROUP_CALL_TYPE" VARCHAR2(10 BYTE), 
	"ONLINE_CHARGING_FLAG" VARCHAR2(1 BYTE), 
	"START_TIME_OF_BILL_CYCLE" VARCHAR2(14 BYTE), 
	"LAST_EFFECT_OFFERING" VARCHAR2(20 BYTE), 
	"DT_DISCOUNT" VARCHAR2(10 BYTE), 
	"OPPOSE_MAIN_OFFERING_ID" VARCHAR2(20 BYTE), 
	"HOME_ZONE_ID" VARCHAR2(10 BYTE), 
	"SPECIAL_ZONE_ID" VARCHAR2(10 BYTE), 
	"USER_STATE" VARCHAR2(10 BYTE), 
	"GROUP_PAY_FLAG" VARCHAR2(10 BYTE), 
	"ROAMING_ZONE_ID" VARCHAR2(20 BYTE), 
	"PRIMARY_OFFER_CHG_AMT" VARCHAR2(20 BYTE), 
	"CHARGE_CODE_INFO" VARCHAR2(256 BYTE), 
	"CALLING_HOME_COUNTRY" VARCHAR2(64 BYTE), 
	"CALLING_ROAM_COUNTRY" VARCHAR2(64 BYTE), 
	"CALLED_HOME_COUNTRY" VARCHAR2(64 BYTE), 
	"CALLED_ROAM_COUNTRY" VARCHAR2(64 BYTE), 
	"CALLED_HOME_AREA" VARCHAR2(64 BYTE)
   )  SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE MZ_MOB_CDR_DATA
partition by range(CREATED_DATE)
(
  PARTITION PMAXVALUE  VALUES LESS THAN (MAXVALUE) TABLESPACE  MZ_MOB_CDR_DATA);


-- CDR_INPUT_OCS_VOICE
--
  CREATE TABLE "MZ_MOB_DATA_OWNER"."CDR_INPUT_OCS_VOICE" 
   (	"TRANSACTION_ID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"INPUT_FILENAME" VARCHAR2(80 BYTE), 
	"CDR_ID" VARCHAR2(20 BYTE), 
	"CDR_SUB_ID" VARCHAR2(20 BYTE), 
	"CDR_TYPE" VARCHAR2(1 BYTE), 
	"SPLIT_CDR_REASON" VARCHAR2(1 BYTE), 
	"CDR_BATCH_ID" VARCHAR2(20 BYTE), 
	"SRC_REC_LINE_NO" VARCHAR2(10 BYTE), 
	"SRC_CDR_ID" VARCHAR2(20 BYTE), 
	"SRC_CDR_NO" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(1 BYTE), 
	"RE_RATING_TIMES" VARCHAR2(3 BYTE), 
	"CREATE_DATE" VARCHAR2(14 BYTE), 
	"START_DATE" VARCHAR2(14 BYTE), 
	"END_DATE" VARCHAR2(14 BYTE), 
	"DURATION" VARCHAR2(20 BYTE), 
	"CUST_LOCAL_START_DATE" VARCHAR2(14 BYTE), 
	"CUST_LOCAL_END_DATE" VARCHAR2(14 BYTE), 
	"STD_EVT_TYPE_ID" VARCHAR2(10 BYTE), 
	"EVT_SOURCE_CAT" VARCHAR2(1 BYTE), 
	"OBJ_TYPE" VARCHAR2(1 BYTE), 
	"OBJ_ID" VARCHAR2(80 BYTE), 
	"OWNER_CUST_ID" VARCHAR2(20 BYTE), 
	"DEFAULT_ACCT_ID" VARCHAR2(20 BYTE), 
	"PRI_IDENTITY" VARCHAR2(64 BYTE), 
	"BILL_CYCLE_ID" VARCHAR2(20 BYTE), 
	"SERVICE_CATEG" VARCHAR2(10 BYTE), 
	"USAGE_SERVICE_TYPE" VARCHAR2(10 BYTE), 
	"SESSION_ID" VARCHAR2(128 BYTE), 
	"RESULT_CODE" VARCHAR2(10 BYTE), 
	"RESULT_REASON" VARCHAR2(256 BYTE), 
	"BE_ID" VARCHAR2(10 BYTE), 
	"HOT_SEQ" VARCHAR2(10 BYTE), 
	"CP_ID" VARCHAR2(10 BYTE), 
	"RECIPIENT_NUMBER" VARCHAR2(64 BYTE), 
	"USAGE_MEASURE_ID" VARCHAR2(10 BYTE), 
	"ACTUAL_USAGE" VARCHAR2(20 BYTE), 
	"RATE_USAGE" VARCHAR2(20 BYTE), 
	"SERVICE_UNIT_TYPE" VARCHAR2(10 BYTE), 
	"DEBIT_AMOUNT" VARCHAR2(20 BYTE), 
	"TOTAL_TAX" VARCHAR2(20 BYTE), 
	"CALLING_PARTY_NUMBER" VARCHAR2(64 BYTE), 
	"CALLED_PARTY_NUMBER" VARCHAR2(64 BYTE), 
	"A_NUMBER" VARCHAR2(64 BYTE), 
	"B_NUMBER" VARCHAR2(64 BYTE), 
	"CALLING_PARTY_IMSI" VARCHAR2(64 BYTE), 
	"CALLED_PARTY_IMSI" VARCHAR2(64 BYTE), 
	"SERVICE_FLOW" VARCHAR2(1 BYTE), 
	"CALL_FORWARD_INDICATOR" VARCHAR2(2 BYTE), 
	"CALLING_ROAM_INFO" VARCHAR2(256 BYTE), 
	"CALLING_CELL_ID" VARCHAR2(60 BYTE), 
	"CALLED_ROAM_INFO" VARCHAR2(256 BYTE), 
	"CALLED_CELL_ID" VARCHAR2(60 BYTE), 
	"TIMESTAMP_OF_SSP" VARCHAR2(14 BYTE), 
	"TIMEZONE_OF_SSP" VARCHAR2(10 BYTE), 
	"BEARER_CAPABILITY" VARCHAR2(32 BYTE), 
	"CHARGING_TIME" VARCHAR2(14 BYTE), 
	"WAITING_DURATION" VARCHAR2(10 BYTE), 
	"TERMINATION_REASON" VARCHAR2(10 BYTE), 
	"CALL_REFERENCE_NUMBER" VARCHAR2(128 BYTE), 
	"IMEI" VARCHAR2(24 BYTE), 
	"ACCESS_PREFIX" VARCHAR2(20 BYTE), 
	"ROUTING_PREFIX" VARCHAR2(20 BYTE), 
	"REDIRECTING_PARTY_ID" VARCHAR2(64 BYTE), 
	"MSC_ADDRESS" VARCHAR2(24 BYTE), 
	"BRAND_ID" VARCHAR2(20 BYTE), 
	"MAIN_OFFERING_ID" VARCHAR2(20 BYTE), 
	"CHARGING_PARTY_NUMBER" VARCHAR2(64 BYTE), 
	"CHARGING_PARTY_INDICATOR" VARCHAR2(1 BYTE), 
	"PAY_TYPE" VARCHAR2(1 BYTE), 
	"CHARGING_TYPE" VARCHAR2(1 BYTE), 
	"CALL_TYPE" VARCHAR2(1 BYTE), 
	"ROAM_STATE" VARCHAR2(1 BYTE), 
	"CALLING_HOME_COUNTRY_CODE" VARCHAR2(10 BYTE), 
	"CALLING_HOME_AREA_NUMBER" VARCHAR2(10 BYTE), 
	"CALLING_HOME_NETWORK_CODE" VARCHAR2(10 BYTE), 
	"CALLING_ROAM_COUNTRY_CODE" VARCHAR2(10 BYTE), 
	"CALLING_ROAM_AREA_NUMBER" VARCHAR2(10 BYTE), 
	"CALLING_ROAM_NETWORK_CODE" VARCHAR2(10 BYTE), 
	"CALLED_HOME_COUNTRY_CODE" VARCHAR2(10 BYTE), 
	"CALLED_HOME_AREA_NUMBER" VARCHAR2(10 BYTE), 
	"CALLED_HOME_NETWORK_CODE" VARCHAR2(10 BYTE), 
	"CALLED_ROAM_COUNTRY_CODE" VARCHAR2(10 BYTE), 
	"CALLED_ROAM_AREA_NUMBER" VARCHAR2(10 BYTE), 
	"CALLED_ROAM_NETWORK_CODE" VARCHAR2(10 BYTE), 
	"SERVICE_TYPE" VARCHAR2(128 BYTE), 
	"HOT_LINE_INDICATOR" VARCHAR2(10 BYTE), 
	"HOME_ZONE_ID" VARCHAR2(10 BYTE), 
	"SPECIAL_ZONE_ID" VARCHAR2(10 BYTE), 
	"NP_FLAG" VARCHAR2(1 BYTE), 
	"NP_PREFIX" VARCHAR2(1 BYTE), 
	"CALLING_CUG_NO" VARCHAR2(20 BYTE), 
	"CALLED_CUG_NO" VARCHAR2(20 BYTE), 
	"OPPOSE_NUMBER_TYPE" VARCHAR2(10 BYTE), 
	"CALLING_NETWORK_TYPE" VARCHAR2(10 BYTE), 
	"CALLED_NETWORK_TYPE" VARCHAR2(10 BYTE), 
	"CALLING_VPN_TOP_GROUP_NUMBER" VARCHAR2(64 BYTE), 
	"CALLING_VPN_GROUP_NUMBER" VARCHAR2(64 BYTE), 
	"CALLING_VPN_SHORT_NUMBER" VARCHAR2(10 BYTE), 
	"CALLED_VPN_TOP_GROUP_NUMBER" VARCHAR2(64 BYTE), 
	"CALLED_VPN_GROUP_NUMBER" VARCHAR2(64 BYTE), 
	"CALLED_VPN_SHORT_NUMBER" VARCHAR2(10 BYTE), 
	"GROUP_CALL_TYPE" VARCHAR2(10 BYTE), 
	"ONLINE_CHARGING_FLAG" VARCHAR2(1 BYTE), 
	"START_TIME_OF_BILL_CYCLE" VARCHAR2(14 BYTE), 
	"LAST_EFFECT_OFFERING" VARCHAR2(20 BYTE), 
	"DT_DISCOUNT" VARCHAR2(10 BYTE), 
	"OPPOSE_MAIN_OFFERING_ID" VARCHAR2(20 BYTE), 
	"USER_STATE" VARCHAR2(10 BYTE), 
	"GROUP_PAY_FLAG" VARCHAR2(10 BYTE), 
	"ROAMING_ZONE_ID" VARCHAR2(20 BYTE), 
	"PRIMARY_OFFER_CHG_AMT" VARCHAR2(20 BYTE), 
	"IMS_CHARGING_IDENTIFIER" VARCHAR2(64 BYTE), 
	"CHARGE_CODE_INFO" VARCHAR2(256 BYTE), 
	"CALLING_HOME_COUNTRY" VARCHAR2(64 BYTE), 
	"CALLING_ROAM_COUNTRY" VARCHAR2(64 BYTE), 
	"CALLED_HOME_COUNTRY" VARCHAR2(64 BYTE), 
	"CALLED_ROAM_COUNTRY" VARCHAR2(64 BYTE), 
	"CALLED_HOME_AREA" VARCHAR2(64 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE MZ_MOB_CDR_DATA
partition by range(CREATED_DATE)
(
  PARTITION PMAXVALUE  VALUES LESS THAN (MAXVALUE) TABLESPACE  MZ_MOB_CDR_DATA);


-- CDR_INPUT_PGW
--
  CREATE TABLE "MZ_MOB_DATA_OWNER"."CDR_INPUT_PGW" 
   (	"TRANSACTION_ID" NUMBER(15,0) NOT NULL ENABLE, 
	"CREATED_DATE" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"INPUT_FILENAME" VARCHAR2(80 BYTE), 
	"MSISDN" VARCHAR2(30 BYTE), 
	"IMSI" VARCHAR2(20 BYTE), 
	"IMEISV" VARCHAR2(20 BYTE), 
	"RAT" NUMBER(*,0), 
	"RECORDOPENINGTIME" VARCHAR2(30 BYTE), 
	"REC_OPEN_TIME_UTC" DATE, 
	"MSTZ" VARCHAR2(10 BYTE), 
	"DURATION" NUMBER(15,0), 
	"CAUSE_REC_CLOSE" NUMBER(*,0), 
	"CHARGINGID" NUMBER(*,0), 
	"LOCAL_SEQ_NUM" NUMBER(*,0), 
	"SEQ_NUM" NUMBER(*,0), 
	"APN" VARCHAR2(80 BYTE), 
	"ULI_ORIGINAL" VARCHAR2(50 BYTE), 
	"MCC" VARCHAR2(5 BYTE), 
	"MNC" VARCHAR2(5 BYTE), 
	"LAC" VARCHAR2(10 BYTE), 
	"CI" VARCHAR2(10 BYTE), 
	"SAC" VARCHAR2(20 BYTE), 
	"RAC" VARCHAR2(5 BYTE), 
	"TAC" VARCHAR2(20 BYTE), 
	"ECI" VARCHAR2(20 BYTE), 
	"SERVING_NODE_TYPE" VARCHAR2(5 BYTE), 
	"IPADD" VARCHAR2(50 BYTE), 
	"STARTTIME" VARCHAR2(30 BYTE), 
	"STOPTIME" VARCHAR2(30 BYTE), 
	"QOS_REQ1" VARCHAR2(100 BYTE), 
	"QOS_NEG1" VARCHAR2(100 BYTE), 
	"UPVOL1" NUMBER(20,0), 
	"DOWNVOL1" NUMBER(20,0), 
	"CHANGE_CONDITION1" NUMBER(5,0), 
	"CHANGE_TIME1" VARCHAR2(30 BYTE), 
	"ULI_ORIG1" VARCHAR2(50 BYTE), 
	"MCC1" VARCHAR2(5 BYTE), 
	"MNC1" VARCHAR2(5 BYTE), 
	"LAC1" VARCHAR2(10 BYTE), 
	"CI1" VARCHAR2(10 BYTE), 
	"SAC1" VARCHAR2(20 BYTE), 
	"RAC1" VARCHAR2(5 BYTE), 
	"TAC1" VARCHAR2(20 BYTE), 
	"ECI1" VARCHAR2(20 BYTE), 
	"QOS_REQ2" VARCHAR2(100 BYTE), 
	"QOS_NEG2" VARCHAR2(100 BYTE), 
	"UPVOL2" NUMBER(20,0), 
	"DOWNVOL2" NUMBER(20,0), 
	"CHANGE_CONDITION2" NUMBER(5,0), 
	"CHANGE_TIME2" VARCHAR2(30 BYTE), 
	"ULI_ORIG2" VARCHAR2(50 BYTE), 
	"MCC2" VARCHAR2(5 BYTE), 
	"MNC2" VARCHAR2(5 BYTE), 
	"LAC2" VARCHAR2(10 BYTE), 
	"CI2" VARCHAR2(10 BYTE), 
	"SAC2" VARCHAR2(20 BYTE), 
	"RAC2" VARCHAR2(5 BYTE), 
	"TAC2" VARCHAR2(20 BYTE), 
	"ECI2" VARCHAR2(20 BYTE), 
	"QOS_REQ3" VARCHAR2(100 BYTE), 
	"QOS_NEG3" VARCHAR2(100 BYTE), 
	"UPVOL3" NUMBER(20,0), 
	"DOWNVOL3" NUMBER(20,0), 
	"CHANGE_CONDITION3" NUMBER(5,0), 
	"CHANGE_TIME3" VARCHAR2(30 BYTE), 
	"ULI_ORIG3" VARCHAR2(50 BYTE), 
	"MCC3" VARCHAR2(5 BYTE), 
	"MNC3" VARCHAR2(5 BYTE), 
	"LAC3" VARCHAR2(10 BYTE), 
	"CI3" VARCHAR2(10 BYTE), 
	"SAC3" VARCHAR2(20 BYTE), 
	"RAC3" VARCHAR2(5 BYTE), 
	"TAC3" VARCHAR2(20 BYTE), 
	"ECI3" VARCHAR2(20 BYTE), 
	"QOS_REQ4" VARCHAR2(100 BYTE), 
	"QOS_NEG4" VARCHAR2(100 BYTE), 
	"UPVOL4" NUMBER(20,0), 
	"DOWNVOL4" NUMBER(20,0), 
	"CHANGE_CONDITION4" NUMBER(5,0), 
	"CHANGE_TIME4" VARCHAR2(30 BYTE), 
	"ULI_ORIG4" VARCHAR2(50 BYTE), 
	"MCC4" VARCHAR2(5 BYTE), 
	"MNC4" VARCHAR2(5 BYTE), 
	"LAC4" VARCHAR2(10 BYTE), 
	"CI4" VARCHAR2(10 BYTE), 
	"SAC4" VARCHAR2(20 BYTE), 
	"RAC4" VARCHAR2(5 BYTE), 
	"TAC4" VARCHAR2(20 BYTE), 
	"ECI4" VARCHAR2(20 BYTE), 
	"QOS_REQ5" VARCHAR2(100 BYTE), 
	"QOS_NEG5" VARCHAR2(100 BYTE), 
	"UPVOL5" NUMBER(20,0), 
	"DOWNVOL5" NUMBER(20,0), 
	"CHANGE_CONDITION5" NUMBER(5,0), 
	"CHANGE_TIME5" VARCHAR2(30 BYTE), 
	"ULI_ORIG5" VARCHAR2(50 BYTE), 
	"MCC5" VARCHAR2(5 BYTE), 
	"MNC5" VARCHAR2(5 BYTE), 
	"LAC5" VARCHAR2(10 BYTE), 
	"CI5" VARCHAR2(10 BYTE), 
	"SAC5" VARCHAR2(20 BYTE), 
	"RAC5" VARCHAR2(5 BYTE), 
	"TAC5" VARCHAR2(20 BYTE), 
	"ECI5" VARCHAR2(20 BYTE), 
	"RATING_GRP1" NUMBER(*,0), 
	"FIRST_USAGE1" VARCHAR2(30 BYTE), 
	"LAST_USAGE1" VARCHAR2(30 BYTE), 
	"SVC_COND_CHANGE1" VARCHAR2(40 BYTE), 
	"SVCUPVOL1" NUMBER(20,0), 
	"SVCDOWNVOL1" NUMBER(20,0), 
	"RAT1" NUMBER(*,0), 
	"LOCAL_SEQ_NUM1" NUMBER(20,0), 
	"RATING_GRP2" NUMBER(*,0), 
	"FIRST_USAGE2" VARCHAR2(30 BYTE), 
	"LAST_USAGE2" VARCHAR2(30 BYTE), 
	"SVC_COND_CHANGE2" VARCHAR2(40 BYTE), 
	"SVCUPVOL2" NUMBER(20,0), 
	"SVCDOWNVOL2" NUMBER(20,0), 
	"RAT2" NUMBER(*,0), 
	"LOCAL_SEQ_NUM2" NUMBER(20,0), 
	"RATING_GRP3" NUMBER(*,0), 
	"FIRST_USAGE3" VARCHAR2(30 BYTE), 
	"LAST_USAGE3" VARCHAR2(30 BYTE), 
	"SVC_COND_CHANGE3" VARCHAR2(40 BYTE), 
	"SVCUPVOL3" NUMBER(20,0), 
	"SVCDOWNVOL3" NUMBER(20,0), 
	"RAT3" NUMBER(*,0), 
	"LOCAL_SEQ_NUM3" NUMBER(20,0), 
	"RATING_GRP4" NUMBER(*,0), 
	"FIRST_USAGE4" VARCHAR2(30 BYTE), 
	"LAST_USAGE4" VARCHAR2(30 BYTE), 
	"SVC_COND_CHANGE4" VARCHAR2(40 BYTE), 
	"SVCUPVOL4" NUMBER(20,0), 
	"SVCDOWNVOL4" NUMBER(20,0), 
	"RAT4" NUMBER(*,0), 
	"LOCAL_SEQ_NUM4" NUMBER(20,0), 
	"RATING_GRP5" NUMBER(*,0), 
	"FIRST_USAGE5" VARCHAR2(30 BYTE), 
	"LAST_USAGE5" VARCHAR2(30 BYTE), 
	"SVC_COND_CHANGE5" VARCHAR2(40 BYTE), 
	"SVCUPVOL5" NUMBER(20,0), 
	"SVCDOWNVOL5" NUMBER(20,0), 
	"RAT5" NUMBER(*,0), 
	"LOCAL_SEQ_NUM5" NUMBER(20,0), 
	"RATING_GRP6" NUMBER(*,0), 
	"FIRST_USAGE6" VARCHAR2(30 BYTE), 
	"LAST_USAGE6" VARCHAR2(30 BYTE), 
	"SVC_COND_CHANGE6" VARCHAR2(40 BYTE), 
	"SVCUPVOL6" NUMBER(20,0), 
	"SVCDOWNVOL6" NUMBER(20,0), 
	"RAT6" NUMBER(*,0), 
	"LOCAL_SEQ_NUM6" NUMBER(20,0), 
	"RATING_GRP7" NUMBER(*,0), 
	"FIRST_USAGE7" VARCHAR2(30 BYTE), 
	"LAST_USAGE7" VARCHAR2(30 BYTE), 
	"SVC_COND_CHANGE7" VARCHAR2(40 BYTE), 
	"SVCUPVOL7" NUMBER(20,0), 
	"SVCDOWNVOL7" NUMBER(20,0), 
	"RAT7" NUMBER(*,0), 
	"LOCAL_SEQ_NUM7" NUMBER(20,0), 
	"RATING_GRP8" NUMBER(*,0), 
	"FIRST_USAGE8" VARCHAR2(30 BYTE), 
	"LAST_USAGE8" VARCHAR2(30 BYTE), 
	"SVC_COND_CHANGE8" VARCHAR2(40 BYTE), 
	"SVCUPVOL8" NUMBER(20,0), 
	"SVCDOWNVOL8" NUMBER(20,0), 
	"RAT8" NUMBER(*,0), 
	"LOCAL_SEQ_NUM8" NUMBER(20,0), 
	"RATING_GRP9" NUMBER(*,0), 
	"FIRST_USAGE9" VARCHAR2(30 BYTE), 
	"LAST_USAGE9" VARCHAR2(30 BYTE), 
	"SVC_COND_CHANGE9" VARCHAR2(40 BYTE), 
	"SVCUPVOL9" NUMBER(20,0), 
	"SVCDOWNVOL9" NUMBER(20,0), 
	"RAT9" NUMBER(*,0), 
	"LOCAL_SEQ_NUM9" NUMBER(20,0), 
	"RATING_GRP10" NUMBER(*,0), 
	"FIRST_USAGE10" VARCHAR2(30 BYTE), 
	"LAST_USAGE10" VARCHAR2(30 BYTE), 
	"SVC_COND_CHANGE10" VARCHAR2(40 BYTE), 
	"SVCUPVOL10" NUMBER(20,0), 
	"SVCDOWNVOL10" NUMBER(20,0), 
	"RAT10" NUMBER(*,0), 
	"LOCAL_SEQ_NUM10" NUMBER(20,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE MZ_MOB_CDR_DATA
partition by range(CREATED_DATE)
(
  PARTITION PMAXVALUE  VALUES LESS THAN (MAXVALUE) TABLESPACE  MZ_MOB_CDR_DATA);


-- CDR_INPUT_SMSC
--
  CREATE TABLE "MZ_MOB_DATA_OWNER"."CDR_INPUT_SMSC" 
   (	"TRANSACTION_ID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"INPUT_FILENAME" VARCHAR2(80 BYTE), 
	"TIME_SERIAL_NUMBER" VARCHAR2(20 BYTE), 
	"SM_ID" VARCHAR2(15 BYTE), 
	"ORIGINAL_ADDRESS" VARCHAR2(30 BYTE), 
	"TON_OF_ORIG_ADDR" VARCHAR2(5 BYTE), 
	"NPI_OF_ORIG_ADDR" VARCHAR2(5 BYTE), 
	"PROPERTIES_OF_ORIG_ADDR" VARCHAR2(5 BYTE), 
	"DESTINATION_DELIVERY_ADDRESS" VARCHAR2(30 BYTE), 
	"TON_OF_DEST_ADDR" VARCHAR2(5 BYTE), 
	"NPI_OF_DEST_ADDR" VARCHAR2(5 BYTE), 
	"PROPERTIES_OF_DEST_ADDR" VARCHAR2(5 BYTE), 
	"ORG_SUBMISSION_TIME" VARCHAR2(30 BYTE), 
	"FINAL_TIME" VARCHAR2(30 BYTE), 
	"PRIORITY_LEVEL" VARCHAR2(5 BYTE), 
	"SM_LENGTH" VARCHAR2(20 BYTE), 
	"SRR" VARCHAR2(5 BYTE), 
	"PID" VARCHAR2(5 BYTE), 
	"DCS" VARCHAR2(5 BYTE), 
	"SMSTATUS" VARCHAR2(5 BYTE), 
	"ERROR_CODE" VARCHAR2(5 BYTE), 
	"TYPE_OF_THE_SM" VARCHAR2(15 BYTE), 
	"UDHI" VARCHAR2(5 BYTE), 
	"MR" VARCHAR2(10 BYTE), 
	"RN" VARCHAR2(10 BYTE), 
	"MN" VARCHAR2(5 BYTE), 
	"SN" VARCHAR2(5 BYTE), 
	"MOMSCADDR" VARCHAR2(30 BYTE), 
	"MTMSCADDR" VARCHAR2(30 BYTE), 
	"LASTERR" VARCHAR2(5 BYTE), 
	"ORGIMSI" VARCHAR2(30 BYTE), 
	"DESTIMSI" VARCHAR2(30 BYTE), 
	"ORIGINAL_DELIVERY_ADDRESS" VARCHAR2(30 BYTE), 
	"TON_OF_ORIG_DEST" VARCHAR2(5 BYTE), 
	"NPI_OF_ORIG_DEST" VARCHAR2(5 BYTE), 
	"MESSAGETYPE" VARCHAR2(5 BYTE), 
	"BILLTYPE" VARCHAR2(5 BYTE), 
	"BILLINGIDENTIFICATION" VARCHAR2(50 BYTE), 
	"SERVINGCELLID" VARCHAR2(20 BYTE), 
	"SERVINGMSCID" VARCHAR2(20 BYTE), 
	"IMEIADDR" VARCHAR2(20 BYTE), 
	"MSGREFERENCENUMBER" VARCHAR2(10 BYTE), 
	"TOTALSEGMENT" VARCHAR2(5 BYTE), 
	"SEGMENTSEQUENCE" VARCHAR2(5 BYTE), 
	"LOCUSSMSTATUS" VARCHAR2(15 BYTE), 
	"SERIAL_NUMBER" VARCHAR2(15 BYTE), 
	"IFROAMING" VARCHAR2(5 BYTE), 
	"TRANSACTIONID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE MZ_MOB_CDR_DATA
partition by range(CREATED_DATE)
(
  PARTITION PMAXVALUE  VALUES LESS THAN (MAXVALUE) TABLESPACE  MZ_MOB_CDR_DATA);


-- CDR_INPUT_TAP
--
  CREATE TABLE "MZ_MOB_DATA_OWNER"."CDR_INPUT_TAP" 
   (	"TRANSACTION_ID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"INPUT_FILENAME" VARCHAR2(50 BYTE), 
	"SOURCE_TADIG" VARCHAR2(10 BYTE), 
	"POS_IN_FILE" NUMBER, 
	"CALL_EVENT_TYPE" VARCHAR2(5 BYTE), 
	"CHARGEABLE_IMSI" VARCHAR2(30 BYTE), 
	"CHARGEABLE_MSISDN" VARCHAR2(30 BYTE), 
	"CHARGEABLE_IMEI" VARCHAR2(30 BYTE), 
	"CALLED_NUMBER" VARCHAR2(30 BYTE), 
	"DIALLED_DIGITS" VARCHAR2(30 BYTE), 
	"CALLING_NUMBER" VARCHAR2(30 BYTE), 
	"THIRD_PTY_NUMBER" VARCHAR2(30 BYTE), 
	"SMS_NUMBER" VARCHAR2(30 BYTE), 
	"A_NUMBER" VARCHAR2(30 BYTE), 
	"B_NUMBER" VARCHAR2(30 BYTE), 
	"START_TIME" VARCHAR2(30 BYTE), 
	"DURATION" VARCHAR2(30 BYTE), 
	"CAUSE_FOR_TERM" VARCHAR2(30 BYTE), 
	"CALL_REFERENCE" VARCHAR2(30 BYTE), 
	"REC_ENT_TYPE1" VARCHAR2(30 BYTE), 
	"REC_ENT_ID1" VARCHAR2(100 BYTE), 
	"REC_ENT_TYPE2" VARCHAR2(30 BYTE), 
	"REC_ENT_ID2" VARCHAR2(100 BYTE), 
	"REC_ENT_TYPE3" VARCHAR2(30 BYTE), 
	"REC_ENT_ID3" VARCHAR2(100 BYTE), 
	"LAC" VARCHAR2(30 BYTE), 
	"CI" VARCHAR2(30 BYTE), 
	"SERVING_NETWORK" VARCHAR2(30 BYTE), 
	"CHARGE" VARCHAR2(30 BYTE), 
	"SERVICE_CODE" VARCHAR2(30 BYTE), 
	"CAMEL_SERVICE_KEY" VARCHAR2(30 BYTE), 
	"CAMEL_DESTINATION" VARCHAR2(30 BYTE), 
	"SS_CODE" VARCHAR2(30 BYTE), 
	"SS_ACTION" VARCHAR2(30 BYTE), 
	"SS_PARAMS" VARCHAR2(30 BYTE), 
	"CHARGED_PTY_STATUS" VARCHAR2(30 BYTE), 
	"NON_CHARGED_NUMBER" VARCHAR2(30 BYTE), 
	"ORIG_NETWORK" VARCHAR2(30 BYTE), 
	"DEST_NETWORK" VARCHAR2(30 BYTE), 
	"PDP_ADDRESS" VARCHAR2(100 BYTE), 
	"APN_NI" VARCHAR2(30 BYTE), 
	"APN_OI" VARCHAR2(30 BYTE), 
	"CHARGING_ID" VARCHAR2(30 BYTE), 
	"DATA_VOL_IN" VARCHAR2(30 BYTE), 
	"DATA_VOL_OUT" VARCHAR2(30 BYTE), 
	"MODIFIED_IMSI" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE MZ_MOB_CDR_DATA
partition by range(CREATED_DATE)
(
  PARTITION PMAXVALUE  VALUES LESS THAN (MAXVALUE) TABLESPACE  MZ_MOB_CDR_DATA);


-- MZ_AUDIT_FILTERED
--
  CREATE TABLE "MZ_MOB_DATA_OWNER"."MZ_AUDIT_FILTERED" 
   (	"TXN_ID" NUMBER, 
	"WF_NAME" VARCHAR2(100 BYTE), 
	"INPUT_FILE_NAME" VARCHAR2(100 BYTE), 
	"OUTPUT_ID" VARCHAR2(32 BYTE), 
	"CDR_COUNT" NUMBER(15,0), 
	"TOTAL_WSALE_PRICE" NUMBER(15,0), 
	"TIMESTAMP_FWD" DATE, 
	"TOTAL_USAGE" NUMBER(17,2), 
	"OUTPUT_FILE_NAME" VARCHAR2(100 BYTE), 
	"FILE_TIMESTAMP" DATE, 
	"FILTER_REASON_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE MZ_MOB_CDR_DATA
partition by range(FILE_TIMESTAMP)
(
  PARTITION PMAXVALUE  VALUES LESS THAN (MAXVALUE) TABLESPACE  MZ_MOB_CDR_DATA);


-- MZ_AUDIT_INPUT
--
  CREATE TABLE "MZ_MOB_DATA_OWNER"."MZ_AUDIT_INPUT" 
   (	"TXN_ID" NUMBER, 
	"WF_NAME" VARCHAR2(100 BYTE), 
	"FILE_NAME" VARCHAR2(100 BYTE), 
	"TIMESTAMP_COLL" DATE, 
	"FILE_SIZE" NUMBER(15,0), 
	"CDR_COUNT" NUMBER(15,0), 
	"FIRST_CDR_DATE" DATE, 
	"LAST_CDR_DATE" DATE, 
	"TOTAL_WSALE_PRICE" NUMBER(15,0), 
	"FILE_VALID_FLAG" NUMBER(15,0), 
	"TIMESTAMP_FWD" DATE, 
	"TOTAL_USAGE" NUMBER(17,2), 
	"FILE_TIMESTAMP" DATE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE MZ_MOB_CDR_DATA
partition by range(FILE_TIMESTAMP)
(
  PARTITION PMAXVALUE  VALUES LESS THAN (MAXVALUE) TABLESPACE  MZ_MOB_CDR_DATA);


-- MZ_AUDIT_OUTPUT
--
  CREATE TABLE "MZ_MOB_DATA_OWNER"."MZ_AUDIT_OUTPUT" 
   (	"TXN_ID" NUMBER, 
	"WF_NAME" VARCHAR2(100 BYTE), 
	"INPUT_FILE_NAME" VARCHAR2(100 BYTE), 
	"OUTPUT_ID" VARCHAR2(32 BYTE), 
	"CDR_COUNT" NUMBER(15,0), 
	"TOTAL_WSALE_PRICE" NUMBER(15,0), 
	"TIMESTAMP_FWD" DATE, 
	"TOTAL_USAGE" NUMBER(17,2), 
	"OUTPUT_FILE_NAME" VARCHAR2(100 BYTE), 
	"FILE_TIMESTAMP" DATE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE MZ_MOB_CDR_DATA
partition by range(FILE_TIMESTAMP)
(
  PARTITION PMAXVALUE  VALUES LESS THAN (MAXVALUE) TABLESPACE  MZ_MOB_CDR_DATA);


-- Drop and Recreate the indexes on the partitioned tables
--
DROP INDEX CDR_INPUT_IMS_IDX1;

DROP INDEX CDR_INPUT_IMS_IDX2;

CREATE INDEX "MZ_MOB_DATA_OWNER"."CDR_INPUT_IMS_IDX1" ON "MZ_MOB_DATA_OWNER"."CDR_INPUT_IMS" ("A_NUMBER");

CREATE INDEX "MZ_MOB_DATA_OWNER"."CDR_INPUT_IMS_IDX2" ON "MZ_MOB_DATA_OWNER"."CDR_INPUT_IMS" ("B_NUMBER");

DROP INDEX CDR_INPUT_OCS_GPRS_IDX1;

CREATE INDEX "MZ_MOB_DATA_OWNER"."CDR_INPUT_OCS_GPRS_IDX1" ON "MZ_MOB_DATA_OWNER"."CDR_INPUT_OCS_GPRS" ("A_NUMBER");

DROP INDEX CDR_INPUT_OCS_SMS_IDX1;

DROP INDEX CDR_INPUT_OCS_SMS_IDX2;

CREATE INDEX "MZ_MOB_DATA_OWNER"."CDR_INPUT_OCS_SMS_IDX1" ON "MZ_MOB_DATA_OWNER"."CDR_INPUT_OCS_SMS" ("A_NUMBER");

CREATE INDEX "MZ_MOB_DATA_OWNER"."CDR_INPUT_OCS_SMS_IDX2" ON "MZ_MOB_DATA_OWNER"."CDR_INPUT_OCS_SMS" ("B_NUMBER");

DROP INDEX CDR_INPUT_OCS_VOICE_IDX1;

DROP INDEX CDR_INPUT_OCS_VOICE_IDX2;

CREATE INDEX "MZ_MOB_DATA_OWNER"."CDR_INPUT_OCS_VOICE_IDX1" ON "MZ_MOB_DATA_OWNER"."CDR_INPUT_OCS_VOICE" ("A_NUMBER");

CREATE INDEX "MZ_MOB_DATA_OWNER"."CDR_INPUT_OCS_VOICE_IDX2" ON "MZ_MOB_DATA_OWNER"."CDR_INPUT_OCS_VOICE" ("B_NUMBER");

DROP INDEX CDR_INPUT_PGW_IDX1;

CREATE INDEX "MZ_MOB_DATA_OWNER"."CDR_INPUT_PGW_IDX1" ON "MZ_MOB_DATA_OWNER"."CDR_INPUT_PGW" ("MSISDN");

DROP INDEX CDR_INPUT_SMSC_IDX1;

DROP INDEX CDR_INPUT_SMSC_IDX2;

CREATE INDEX "MZ_MOB_DATA_OWNER"."CDR_INPUT_SMSC_IDX1" ON "MZ_MOB_DATA_OWNER"."CDR_INPUT_SMSC" ("ORIGINAL_ADDRESS");

CREATE INDEX "MZ_MOB_DATA_OWNER"."CDR_INPUT_SMSC_IDX2" ON "MZ_MOB_DATA_OWNER"."CDR_INPUT_SMSC" ("DESTINATION_DELIVERY_ADDRESS");

DROP INDEX CDR_INPUT_TAP_IDX1;

DROP INDEX CDR_INPUT_TAP_IDX2;

CREATE INDEX "MZ_MOB_DATA_OWNER"."CDR_INPUT_TAP_IDX1" ON "MZ_MOB_DATA_OWNER"."CDR_INPUT_TAP" ("A_NUMBER");

CREATE INDEX "MZ_MOB_DATA_OWNER"."CDR_INPUT_TAP_IDX2" ON "MZ_MOB_DATA_OWNER"."CDR_INPUT_TAP" ("B_NUMBER");

DROP INDEX IDX_AUD_F_TXN;

DROP INDEX IDX_MZ_AUD_FLT_IFN;

CREATE INDEX "MZ_MOB_DATA_OWNER"."IDX_AUD_F_TXN" ON "MZ_MOB_DATA_OWNER"."MZ_AUDIT_FILTERED" ("TXN_ID");

CREATE INDEX "MZ_MOB_DATA_OWNER"."IDX_MZ_AUD_FLT_IFN" ON "MZ_MOB_DATA_OWNER"."MZ_AUDIT_FILTERED" ("INPUT_FILE_NAME");

DROP INDEX IDX_AUD_I_TXN;

DROP INDEX IDX_MZ_AUD_IN_FN;

CREATE INDEX "MZ_MOB_DATA_OWNER"."IDX_AUD_I_TXN" ON "MZ_MOB_DATA_OWNER"."MZ_AUDIT_INPUT" ("TXN_ID");

CREATE INDEX "MZ_MOB_DATA_OWNER"."IDX_MZ_AUD_IN_FN" ON "MZ_MOB_DATA_OWNER"."MZ_AUDIT_INPUT" ("FILE_NAME");

DROP INDEX IDX_AUD_O_TXN;

DROP INDEX IDX_MZ_AUD_OUT_OFN;

CREATE INDEX "MZ_MOB_DATA_OWNER"."IDX_AUD_O_TXN" ON "MZ_MOB_DATA_OWNER"."MZ_AUDIT_OUTPUT" ("TXN_ID");

CREATE INDEX "MZ_MOB_DATA_OWNER"."IDX_MZ_AUD_OUT_OFN" ON "MZ_MOB_DATA_OWNER"."MZ_AUDIT_OUTPUT" ("OUTPUT_FILE_NAME");


-- Recompile the MONSOL views
--
ALTER VIEW MONSOL_OCS_GPRS_ROAMING COMPILE;

ALTER VIEW MONSOL_OCS_IMS_VOICE_ROAMING COMPILE;

ALTER VIEW MONSOL_OCS_SMS_ROAMING COMPILE;


-- MZMOB-344 - Add indexes to the CDR input tables to improve performance
--
CREATE INDEX CDR_INPUT_IMS_IDX3 ON CDR_INPUT_IMS (CREATED_DATE) LOCAL;

CREATE INDEX CDR_INPUT_OCS_GPRS_IDX2 ON CDR_INPUT_OCS_GPRS (CREATED_DATE) LOCAL;

CREATE INDEX CDR_INPUT_OCS_SMS_IDX3 ON CDR_INPUT_OCS_SMS (CREATED_DATE) LOCAL;

CREATE INDEX CDR_INPUT_OCS_VOICE_IDX3 ON CDR_INPUT_OCS_VOICE (CREATED_DATE) LOCAL;

CREATE INDEX CDR_INPUT_PGW_IDX2 ON CDR_INPUT_PGW (CREATED_DATE) LOCAL;

CREATE INDEX CDR_INPUT_SMSC_IDX3 ON CDR_INPUT_SMSC (CREATED_DATE) LOCAL;

CREATE INDEX CDR_INPUT_TAP_IDX3 ON CDR_INPUT_TAP (CREATED_DATE) LOCAL;