-- Rename ECS IMS and CS2K output tables to keep a copy of existing pre-migration ECS data
--
RENAME CDR_OUTPUT_CS2K_ECS TO CDR_OUTPUT_CS2K_ECS_PRE_I203;

RENAME CDR_OUTPUT_IMS_ECS TO CDR_OUTPUT_IMS_ECS_PRE_I203;


-- Recreate the ECS IMS and CS2K output tables
--
-- CDR_OUTPUT_CS2K_ECS
--
CREATE TABLE CDR_OUTPUT_CS2K_ECS
(
  FILE_CONTROL_ID         NUMBER                NOT NULL,
  FILE_REC_ID             NUMBER                NOT NULL,
  CREATED_DATE            DATE                  NOT NULL,
  TRANSACTION_ID          NUMBER                NOT NULL,
  CALLING_NUMBER          VARCHAR2(30 BYTE),
  CALLED_NUMBER           VARCHAR2(30 BYTE),
  SWITCH_NUMBER           VARCHAR2(2 BYTE),
  SESSION_NUMBER          VARCHAR2(12 BYTE),
  SEQUENCE_NUMBER         VARCHAR2(10 BYTE),
  IN_TRUNK                VARCHAR2(10 BYTE),
  OUT_TRUNK               VARCHAR2(10 BYTE),
  CDR_DATE                VARCHAR2(8 BYTE),
  CDR_START_TIME          VARCHAR2(8 BYTE),
  CDR_DURATION            VARCHAR2(10 BYTE),
  ERROR_CODE              VARCHAR2(30 BYTE),
  TIMESTAMP_IN            TIMESTAMP(6),
  TIMESTAMP_REPROCESSING  TIMESTAMP(6)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


-- CDR_OUTPUT_IMS_ECS
--
CREATE TABLE CDR_OUTPUT_IMS_ECS
(
  FILE_CONTROL_ID         NUMBER                NOT NULL,
  FILE_REC_ID             NUMBER                NOT NULL,
  CREATED_DATE            DATE                  NOT NULL,
  TRANSACTION_ID          NUMBER                NOT NULL,
  CALLING_NUMBER          VARCHAR2(30 BYTE),
  CALLED_NUMBER           VARCHAR2(30 BYTE),
  SWITCH_ID               VARCHAR2(20 BYTE),
  SESSION_NUMBER          VARCHAR2(12 BYTE),
  SEQUENCE_NUMBER         VARCHAR2(10 BYTE),
  IN_TRUNK                VARCHAR2(10 BYTE),
  OUT_TRUNK               VARCHAR2(10 BYTE),
  CDR_TIMESTAMP           TIMESTAMP(6),
  CDR_DURATION_MS         NUMBER(22),
  ERROR_CODE              VARCHAR2(30 BYTE),
  TIMESTAMP_IN            TIMESTAMP(6),
  TIMESTAMP_REPROCESSING  TIMESTAMP(6),
  ORIG_FNAME_TIMESTAMP    VARCHAR2(18 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


-- Drop and recreate CDR_OUTPUT_CS2K_ECS Indexes
--
DROP INDEX IDX_O_CS2K_ECS_CALLED_NUMBER;

DROP INDEX IDX_O_CS2K_ECS_CALLING_NUMBER;

DROP INDEX IDX_O_CS2K_ECS_COMPOSITE;

CREATE INDEX IDX_O_CS2K_ECS_CALLED_NUMBER ON CDR_OUTPUT_CS2K_ECS
(CALLED_NUMBER);

CREATE INDEX IDX_O_CS2K_ECS_CALLING_NUMBER ON CDR_OUTPUT_CS2K_ECS
(CALLING_NUMBER);

CREATE INDEX IDX_O_CS2K_ECS_COMPOSITE ON CDR_OUTPUT_CS2K_ECS
(SWITCH_NUMBER, SESSION_NUMBER, SEQUENCE_NUMBER);


-- Drop and recreate CDR_OUTPUT_IMS_ECS Indexes
--
DROP INDEX IDX_O_IMS_ECS_CALLED_NUMBER;

DROP INDEX IDX_O_IMS_ECS_CALLING_NUMBER;

DROP INDEX IDX_O_IMS_ECS_IDX1;

CREATE INDEX IDX_O_IMS_ECS_CALLED_NUMBER ON CDR_OUTPUT_IMS_ECS 
(CALLED_NUMBER);

CREATE INDEX IDX_O_IMS_ECS_CALLING_NUMBER ON CDR_OUTPUT_IMS_ECS
(CALLING_NUMBER);

CREATE INDEX IDX_O_IMS_ECS_IDX1 ON CDR_OUTPUT_IMS_ECS
(SWITCH_ID, SESSION_NUMBER, SEQUENCE_NUMBER);