-- CREATE ADDITIONAL INDEXES ON CDR_INPUT_IMS_NOKIA
-- MED-546 ADD ADDITIONAL LOCAL INDEXING USING CREATED_DATE AND TRANSACTION_ID INTO THE CDR_INPUT_IMS_NOKIA TABLE

CREATE INDEX CDR_INPUT_IMS_IDX4 ON CDR_INPUT_IMS_NOKIA (CREATED_DATE) LOCAL;

CREATE INDEX CDR_INPUT_IMS_IDX5 ON CDR_INPUT_IMS_NOKIA (TRANSACTION_ID) LOCAL;

-- CREATE INDEXES ON CDR_OUTPUT_BW_ECS
-- MED-545 ADD INDEXES INTO THE BROADWORKS ECS OUTPUT TABLE TO IMPROVE PERFORMANCE OF THE BW.WF0119_BW_ECS_Write WORKFLOW.

CREATE INDEX IDX_O_BW_ECS_CALLED_NUMBER ON CDR_OUTPUT_BW_ECS (CALLED_NUMBER);

CREATE INDEX IDX_O_BW_ECS_CALLING_NUMBER ON CDR_OUTPUT_BW_ECS (CALLING_NUMBER);

CREATE INDEX IDX_O_BW_ECS_COMPOSITE ON CDR_OUTPUT_BW_ECS (NODE, RECORD_ID);