
-- Create new table CDR_INPUT_OCS_VOICE_AMDOCS
--
CREATE TABLE "MZ_MOB_DATA_OWNER"."CDR_INPUT_OCS_VOICE_AMDOCS" 
(
	"TRANSACTION_ID"	NUMBER NOT NULL, 
	"CREATED_DATE"		DATE DEFAULT sysdate NOT NULL, 
	"INPUT_FILENAME"	VARCHAR2(80),
	"A_NUMBER"		VARCHAR2(64),
	"B_NUMBER"		VARCHAR2(64),
	"EVENT_ID"		VARCHAR2(20),	-- Common
	"EVENT_SPLIT_REASON"	VARCHAR2(1),
	"EVENT_START_TIME"	VARCHAR2(14),
	"EVENT_END_TIME"	VARCHAR2(14),
	"EVENT_LOCAL_START_TIME"	VARCHAR2(14),
	"EVENT_LOCAL_END_TIME"	VARCHAR2(14),
	"OBJECT_TYPE"	VARCHAR2(1),
	"EXTERNAL_SUBSCRIBER_ID"	VARCHAR2(64),	-- Increased to 64
	"CUSTOMER_ID"		VARCHAR2(9),
	"SUBSCRIBER_ID"		VARCHAR2(9),
	"PRIMARY_RESOURCE_VALUE"	VARCHAR2(32),
	"BILL_CYCLE_IDENTIFIER"	VARCHAR2(8),
	"SERVICE_SUBTYPE"	VARCHAR2(10),
	"SESSION_ID"		VARCHAR2(128),
	"INTERNAL_RESULT_CODE"	VARCHAR2(10),
	"UOM"			VARCHAR2(1),
	"ACTUAL_USAGE"		VARCHAR2(20),	-- Increased to 20
	"ROUNDED_UNIT"		VARCHAR2(20),	-- Increased to 20
	"SERVICE_TYPE"		VARCHAR2(1),
	"CHARGE_AMOUNT"		VARCHAR2(10),
	"CALLING_NUMBER"	VARCHAR2(64),
	"IMSI_CALLING_PARTY"	VARCHAR2(64),
	"CALLING_PARTY_ROAMING_INFO"	VARCHAR2(256),
	"PRIMARY_OFFER_ID"	VARCHAR2(20),
	"CHARGED_NUMBER"	VARCHAR2(64),
	"ROAMING_IND"		VARCHAR2(1),
	"HOME_COUNTRY_CODE_CALLING"	VARCHAR2(3),
	"NETWORK_CODE_CALLING_PARTY"	VARCHAR2(10),
	"ROAMING_COUNTRY_CODE_CALLING"	VARCHAR2(3),
	"ROAMING_NETWORK_CODE_CALLING"	VARCHAR2(10),
	"IS_ONLINE"		VARCHAR2(1),
	"CYCLE_START_TIME"	VARCHAR2(14),
	"LAST_EFFECT_OFFER_ID"	VARCHAR2(20),	
	"CHARGE_CODE_INFO_CODE1"	VARCHAR2(64),
	"CHARGE_CODE_INFO_NAME1"	VARCHAR2(128),
	"CHARGE_CODE_INFO_AMOUNT1"	VARCHAR2(9),
	"CHARGE_CODE_INFO_CODE2"	VARCHAR2(64),
	"CHARGE_CODE_INFO_NAME2"	VARCHAR2(128),
	"CHARGE_CODE_INFO_AMOUNT2"	VARCHAR2(9),
	"CHARGE_CODE_INFO_CODE3"	VARCHAR2(64),
	"CHARGE_CODE_INFO_NAME3"	VARCHAR2(128),
	"CHARGE_CODE_INFO_AMOUNT3"	VARCHAR2(9),
	"SUMMARY_CHARGE_CODE_INFO"	VARCHAR2(64),	
	"SUMMARY_CHARGE_CODE_NAME"	VARCHAR2(128),
	"SUMMARY_CHARGE_AMOUNT"		VARCHAR2(9),
	"HOME_COUNTRY_NAME_CALLING"	VARCHAR2(64),
	"ROAMING_COUNTRY_NAME_CALLING"	VARCHAR2(64),
	"DEBIT_AMOUNT"			VARCHAR2(20),
	"CURRENCY_IND"			VARCHAR2(3),
	"EXTERNAL_CUSTOMER_ID"	VARCHAR2(64),	-- Increased to 64
	"SERVICE_FILTER"	VARCHAR2(20),
	"IMEI"			VARCHAR2(24),	-- Increased to 24
	"OCS_SITE_ID"		VARCHAR2(20),
	"PRICING_ITEM_ID"	VARCHAR2(9),
	"PAYMENT_TYPE"		VARCHAR2(10),
        "ROAMING_ZONE"		VARCHAR2(10),	-- V.1.0
    	"ORIGINATING_CATEGORY"  VARCHAR2(10),
    	"DESTINATION_CATEGORY"	VARCHAR2(10),
    	"RERATE_INDICATOR" 	VARCHAR2(1),
    	"DISCOUNT_AMOUNT"       VARCHAR2(9),
    	"CD_USAGE"              VARCHAR2(1),
    	"REFUND_IND"            VARCHAR2(1),
    	"UNAPPLIED_ALLOWANCE"   VARCHAR2(20),	-- Increased to 20
    	"UNDEBIT_AMOUNT"	VARCHAR2(10),	-- Moved from Voive Attributes - 20210728
	"DURATION"		VARCHAR2(9),	-- Voice
	"RECIPIENT_NUMBER"	VARCHAR2(64),
	"CALLED_NUMBER"		VARCHAR2(64),
	"IMSI_CALLED_PARTY"	VARCHAR2(64),
	"CALL_DIRECTION"	VARCHAR2(1),
	"CALL_FORWARDING_FLAG"	VARCHAR2(2),
	"CALLED_PARTY_ROAMING_INFO"	VARCHAR2(256),
	"EVENT_CHARGING_TIME"	VARCHAR2(14),
	"TERMINATION_REASON"	VARCHAR2(10),
	"ACCESS_PREFIX"	VARCHAR2(20),
	"ACCESS_PREFIX_TYPE"	VARCHAR2(1),
	"REDIRECTING_NUMBER"	VARCHAR2(25),
	"LOCATION_AREA_CALLING"	VARCHAR2(10),
	"HOME_COUNTRY_CODE_CALLED"	 VARCHAR2(3),
	"HOME_AREA_CODE_CALLED"	VARCHAR2(10),
	"NETWORK_CODE_CALLED_PARTY"	 VARCHAR2(10),
	"ROAMING_COUNTRY_CODE_CALLED"	 VARCHAR2(3),
	"ROAMING_NETWORK_CODE_CALLED"	 VARCHAR2(10),
	"SPECIAL_NUMBER_IND"	 VARCHAR2(1),
	"IMS_IDENTIFIER"	 VARCHAR2(128),
	"HOME_COUNTRY_NAME_CALLED"	 VARCHAR2(64),
	"ROAM_COUNTRY_NAME_CALLED"	 VARCHAR2(64),
	"HOME_AREA_NAME_CALLED"	VARCHAR2(64),
--	"UNDEBIT_AMOUNT"	VARCHAR2(10),	-- Moved to Common Attributes - 20210728
	"FREE_DURATION_CONSUMED"	VARCHAR2(20),
	"MCC_VISITED"		VARCHAR2(32),
	"MNC_VISITED"		VARCHAR2(32),
	"LAC_VISITED"		VARCHAR2(32),
	"CELL_ID"		VARCHAR2(32),
	"VLR_NUMBER"		VARCHAR2(32),
	"ON_NET"		VARCHAR2(1),
	"DIALED_NUMBER"		VARCHAR2(100),	-- Increased to 100
	"ANI_INFO"		VARCHAR2(200),	-- Increased to 200
--	"REFUND_IND"		VARCHAR2(1),	-- Removed for V.1.0
	"SPECIAL_NUMBER_GROUP"	VARCHAR2(10),
    	"NETWORK_TYPE" 		VARCHAR2(1),	-- V.1.0
   	"RPP_STATE"		VARCHAR2(1),
    	"IDD_BAND"		VARCHAR2(1),
    	"SERVICE_CALL_DESC"	VARCHAR2(64)	
) 
SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE MZ_MOB_CDR_DATA
  partition by range(CREATED_DATE)
(
  PARTITION PMAXVALUE  VALUES LESS THAN (MAXVALUE) TABLESPACE  MZ_MOB_CDR_DATA);


-- Create new table CDR_INPUT_OCS_SMS_AMDOCS
--
CREATE TABLE "MZ_MOB_DATA_OWNER"."CDR_INPUT_OCS_SMS_AMDOCS" 
(
	"TRANSACTION_ID"	NUMBER NOT NULL, 
	"CREATED_DATE"		DATE DEFAULT sysdate NOT NULL, 
	"INPUT_FILENAME"	VARCHAR2(80),
	"A_NUMBER"		VARCHAR2(64),
	"B_NUMBER"		VARCHAR2(64),
	"EVENT_ID"		VARCHAR2(20),	-- Common
	"EVENT_SPLIT_REASON"	VARCHAR2(1),
	"EVENT_START_TIME"	VARCHAR2(14),
	"EVENT_END_TIME"	VARCHAR2(14),
	"EVENT_LOCAL_START_TIME"	VARCHAR2(14),
	"EVENT_LOCAL_END_TIME"	VARCHAR2(14),
	"OBJECT_TYPE"	VARCHAR2(1),
	"EXTERNAL_SUBSCRIBER_ID"	VARCHAR2(64),	-- Increased to 64
	"CUSTOMER_ID"		VARCHAR2(9),
	"SUBSCRIBER_ID"		VARCHAR2(9),
	"PRIMARY_RESOURCE_VALUE"	VARCHAR2(32),
	"BILL_CYCLE_IDENTIFIER"	VARCHAR2(8),
	"SERVICE_SUBTYPE"	VARCHAR2(10),
	"SESSION_ID"		VARCHAR2(128),
	"INTERNAL_RESULT_CODE"	VARCHAR2(10),
	"UOM"			VARCHAR2(1),
	"ACTUAL_USAGE"		VARCHAR2(20),	-- Increased to 20
	"ROUNDED_UNIT"		VARCHAR2(20),	-- Increased to 20
	"SERVICE_TYPE"		VARCHAR2(1),
	"CHARGE_AMOUNT"		VARCHAR2(10),
	"CALLING_NUMBER"	VARCHAR2(64),
	"IMSI_CALLING_PARTY"	VARCHAR2(64),
	"CALLING_PARTY_ROAMING_INFO"	VARCHAR2(256),
	"PRIMARY_OFFER_ID"	VARCHAR2(20),
	"CHARGED_NUMBER"	VARCHAR2(64),
	"ROAMING_IND"		VARCHAR2(1),
	"HOME_COUNTRY_CODE_CALLING"	VARCHAR2(3),
	"NETWORK_CODE_CALLING_PARTY"	VARCHAR2(10),
	"ROAMING_COUNTRY_CODE_CALLING"	VARCHAR2(3),
	"ROAMING_NETWORK_CODE_CALLING"	VARCHAR2(10),
	"IS_ONLINE"		VARCHAR2(1),
	"CYCLE_START_TIME"	VARCHAR2(14),
	"LAST_EFFECT_OFFER_ID"	VARCHAR2(20),	
	"CHARGE_CODE_INFO_CODE1"	VARCHAR2(64),
	"CHARGE_CODE_INFO_NAME1"	VARCHAR2(128),
	"CHARGE_CODE_INFO_AMOUNT1"	VARCHAR2(9),
	"CHARGE_CODE_INFO_CODE2"	VARCHAR2(64),
	"CHARGE_CODE_INFO_NAME2"	VARCHAR2(128),
	"CHARGE_CODE_INFO_AMOUNT2"	VARCHAR2(9),
	"CHARGE_CODE_INFO_CODE3"	VARCHAR2(64),
	"CHARGE_CODE_INFO_NAME3"	VARCHAR2(128),
	"CHARGE_CODE_INFO_AMOUNT3"	VARCHAR2(9),
	"SUMMARY_CHARGE_CODE_INFO"	VARCHAR2(64),	
	"SUMMARY_CHARGE_CODE_NAME"	VARCHAR2(128),
	"SUMMARY_CHARGE_AMOUNT"		VARCHAR2(9),
	"HOME_COUNTRY_NAME_CALLING"	VARCHAR2(64),
	"ROAMING_COUNTRY_NAME_CALLING"	VARCHAR2(64),
	"DEBIT_AMOUNT"			VARCHAR2(20),
	"CURRENCY_IND"			VARCHAR2(3),
	"EXTERNAL_CUSTOMER_ID"	VARCHAR2(64),	-- Increased to 64
	"SERVICE_FILTER"	VARCHAR2(20),
	"IMEI"			VARCHAR2(24),	-- Increased to 24
	"OCS_SITE_ID"		VARCHAR2(20),
	"PRICING_ITEM_ID"	VARCHAR2(9),
	"PAYMENT_TYPE"		VARCHAR2(10),
        "ROAMING_ZONE"		VARCHAR2(10),	-- V.1.0
    	"ORIGINATING_CATEGORY"  VARCHAR2(10),
    	"DESTINATION_CATEGORY"	VARCHAR2(10),
    	"RERATE_INDICATOR" 	VARCHAR2(1),
    	"DISCOUNT_AMOUNT"       VARCHAR2(9),
    	"CD_USAGE"              VARCHAR2(1),
    	"REFUND_IND"            VARCHAR2(1),
    	"UNAPPLIED_ALLOWANCE"   VARCHAR2(20),	-- Increased to 20
    	"UNDEBIT_AMOUNT"	VARCHAR2(10),	-- Newly added - 20210728
    	"RECIPIENT_NUMBER"	VARCHAR2(64),	-- SMS
    	"CALLED_NUMBER"		VARCHAR2(64),
    	"IMSI_CALLED_PARTY"           VARCHAR2(64),
    	"CALL_DIRECTION"              VARCHAR2(1),
    	"CALL_FORWARDING_FLAG"        VARCHAR2(2),
    	"CALLED_PARTY_ROAMING_INFO"   VARCHAR2(256),
    	"LOCATION_AREA_CALLING"       VARCHAR2(10),
    	"HOME_COUNTRY_CODE_CALLED"    VARCHAR2(3),
    	"HOME_AREA_CODE_CALLED"       VARCHAR2(10),
    	"NETWORK_CODE_CALLED_PARTY"   VARCHAR2(10),
    	"ROAMING_COUNTRY_CODE_CALLED" VARCHAR2(3),
    	"ROAMING_NETWORK_CODE_CALLED" VARCHAR2(10),
    	"SPECIAL_NUMBER_IND"          VARCHAR2(10),
    	"HOME_COUNTRYNAME_CALLED"     VARCHAR2(64),
    	"ROAM_COUNTRYNAME_CALLED"     VARCHAR2(64),
    	"HOME_AREA_NAME_CALLED"       VARCHAR2(64),
    	"FREE_OCCURRENCE_CONSUMED"    VARCHAR2(20),
    	"ON_NET"                      VARCHAR2(1),
    	"DIALED_NUMBER"               VARCHAR2(100),	-- Increased to 100
    	"SMS_ID"                      VARCHAR2(20),
    	"SMS_LENGTH"                  VARCHAR2(10),
        "SMSC_ADDRESS"                VARCHAR2(20),
--       "REFUND_IND"                  VARCHAR2(1),	-- Removed for V.1.0
        "MT_MSC_ADDRESS"              VARCHAR2(32),
        "MO_MSC_ADDRESS"              VARCHAR2(32),
        "SPECIAL_NUMBER_GROUP"        VARCHAR2(10),
        "RPP_STATE"                   VARCHAR2(1),	-- V.1.0
        "IDD_BAND"                    VARCHAR2(1),
        "SERVICE_CALL_DESC"           VARCHAR2(64)
) 
SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE MZ_MOB_CDR_DATA
  partition by range(CREATED_DATE)
(
  PARTITION PMAXVALUE  VALUES LESS THAN (MAXVALUE) TABLESPACE  MZ_MOB_CDR_DATA
);


-- Create new table CDR_INPUT_OCS_MMS_AMDOCS
--
CREATE TABLE "MZ_MOB_DATA_OWNER"."CDR_INPUT_OCS_MMS_AMDOCS" 
(
	"TRANSACTION_ID"	NUMBER NOT NULL, 
	"CREATED_DATE"		DATE DEFAULT sysdate NOT NULL, 
	"INPUT_FILENAME"	VARCHAR2(80),
	"A_NUMBER"		VARCHAR2(64),
	"B_NUMBER"		VARCHAR2(64),
	"EVENT_ID"		VARCHAR2(20),	-- Common
	"EVENT_SPLIT_REASON"	VARCHAR2(1),
	"EVENT_START_TIME"	VARCHAR2(14),
	"EVENT_END_TIME"	VARCHAR2(14),
	"EVENT_LOCAL_START_TIME"	VARCHAR2(14),
	"EVENT_LOCAL_END_TIME"	VARCHAR2(14),
	"OBJECT_TYPE"	VARCHAR2(1),
	"EXTERNAL_SUBSCRIBER_ID"	VARCHAR2(64),	-- Increased to 64
	"CUSTOMER_ID"		VARCHAR2(9),
	"SUBSCRIBER_ID"		VARCHAR2(9),
	"PRIMARY_RESOURCE_VALUE"	VARCHAR2(32),
	"BILL_CYCLE_IDENTIFIER"	VARCHAR2(8),
	"SERVICE_SUBTYPE"	VARCHAR2(10),
	"SESSION_ID"		VARCHAR2(128),
	"INTERNAL_RESULT_CODE"	VARCHAR2(10),
	"UOM"			VARCHAR2(1),
	"ACTUAL_USAGE"		VARCHAR2(20),	-- Increased to 20
	"ROUNDED_UNIT"		VARCHAR2(20),	-- Increased to 20
	"SERVICE_TYPE"		VARCHAR2(1),
	"CHARGE_AMOUNT"		VARCHAR2(10),
	"CALLING_NUMBER"	VARCHAR2(64),
	"IMSI_CALLING_PARTY"	VARCHAR2(64),
	"CALLING_PARTY_ROAMING_INFO"	VARCHAR2(256),
	"PRIMARY_OFFER_ID"	VARCHAR2(20),
	"CHARGED_NUMBER"	VARCHAR2(64),
	"ROAMING_IND"		VARCHAR2(1),
	"HOME_COUNTRY_CODE_CALLING"	VARCHAR2(3),
	"NETWORK_CODE_CALLING_PARTY"	VARCHAR2(10),
	"ROAMING_COUNTRY_CODE_CALLING"	VARCHAR2(3),
	"ROAMING_NETWORK_CODE_CALLING"	VARCHAR2(10),
	"IS_ONLINE"		VARCHAR2(1),
	"CYCLE_START_TIME"	VARCHAR2(14),
	"LAST_EFFECT_OFFER_ID"	VARCHAR2(20),	
	"CHARGE_CODE_INFO_CODE1"	VARCHAR2(64),
	"CHARGE_CODE_INFO_NAME1"	VARCHAR2(128),
	"CHARGE_CODE_INFO_AMOUNT1"	VARCHAR2(9),
	"CHARGE_CODE_INFO_CODE2"	VARCHAR2(64),
	"CHARGE_CODE_INFO_NAME2"	VARCHAR2(128),
	"CHARGE_CODE_INFO_AMOUNT2"	VARCHAR2(9),
	"CHARGE_CODE_INFO_CODE3"	VARCHAR2(64),
	"CHARGE_CODE_INFO_NAME3"	VARCHAR2(128),
	"CHARGE_CODE_INFO_AMOUNT3"	VARCHAR2(9),
	"SUMMARY_CHARGE_CODE_INFO"	VARCHAR2(64),	
	"SUMMARY_CHARGE_CODE_NAME"	VARCHAR2(128),
	"SUMMARY_CHARGE_AMOUNT"		VARCHAR2(9),
	"HOME_COUNTRY_NAME_CALLING"	VARCHAR2(64),
	"ROAMING_COUNTRY_NAME_CALLING"	VARCHAR2(64),
	"DEBIT_AMOUNT"			VARCHAR2(20),
	"CURRENCY_IND"			VARCHAR2(3),
	"EXTERNAL_CUSTOMER_ID"	VARCHAR2(64),	-- Increased to 64
	"SERVICE_FILTER"	VARCHAR2(20),
	"IMEI"			VARCHAR2(24),	-- Increased to 24
	"OCS_SITE_ID"		VARCHAR2(20),
	"PRICING_ITEM_ID"	VARCHAR2(9),
	"PAYMENT_TYPE"		VARCHAR2(10),
        "ROAMING_ZONE"		VARCHAR2(10),	-- V.1.0
    	"ORIGINATING_CATEGORY"  VARCHAR2(10),
    	"DESTINATION_CATEGORY"	VARCHAR2(10),
    	"RERATE_INDICATOR" 	VARCHAR2(1),
    	"DISCOUNT_AMOUNT"       VARCHAR2(9),
    	"CD_USAGE"              VARCHAR2(1),
    	"REFUND_IND"            VARCHAR2(1),
    	"UNAPPLIED_ALLOWANCE"   VARCHAR2(20),	-- Increased to 20
    	"UNDEBIT_AMOUNT"	VARCHAR2(10),	-- Newly added - 20210728    	
        "RECIPIENT_NUMBER"            VARCHAR2(64),	-- MMS
        "CALLED_NUMBER"               VARCHAR2(64),
        "IMSI_CALLED_PARTY"           VARCHAR2(64),
        "CALL_DIRECTION"              VARCHAR2(1),
        "CALL_FORWARDING_FLAG"        VARCHAR2(2),
        "CALLED_PARTY_ROAMING_INFO"   VARCHAR2(256),
        "LOCATION_AREA_CALLING"       VARCHAR2(10),
        "HOME_COUNTRY_CODE_CALLED"    VARCHAR2(3),
        "HOME_AREA_CODE_CALLED"       VARCHAR2(10),
        "NETWORK_CODE_CALLED_PARTY"   VARCHAR2(10),
        "ROAMING_COUNTRY_CODE_CALLED" VARCHAR2(3),
        "ROAMING_NETWORK_CODE_CALLED" VARCHAR2(10),
        "HOME_COUNTRYNAME_CALLED"     VARCHAR2(64),
        "ROAM_COUNTRYNAME_CALLED"     VARCHAR2(64),
        "HOME_AREA_NAME_CALLED"       VARCHAR2(64),
        "MNC_VISITED"                 VARCHAR2(32),
        "LAC_VISITED"                 VARCHAR2(32),
        "CELL_ID"                     VARCHAR2(32),
        "ON_NET"                      VARCHAR2(1),
        "DIALED_NUMBER"               VARCHAR2(100),	-- Increased to 100
        "MMS_ID"                      VARCHAR2(24),
        "MMS_LENGTH"                  VARCHAR2(10),
        "ORIGINAL_ADDRESS_TYPE"       VARCHAR2(10),
        "DEST_ADDRESS_TYPE"           VARCHAR2(10),
        "SPECIAL_NUMBER_GROUP"        VARCHAR2(10),
        "MCC_VISITED"		      VARCHAR2(32)	-- V.1.0
) 
SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE MZ_MOB_CDR_DATA
  partition by range(CREATED_DATE)
(
  PARTITION PMAXVALUE  VALUES LESS THAN (MAXVALUE) TABLESPACE  MZ_MOB_CDR_DATA
);


-- Create new table CDR_INPUT_OCS_GPRS_AMDOCS
--
CREATE TABLE "MZ_MOB_DATA_OWNER"."CDR_INPUT_OCS_GPRS_AMDOCS" 
(
	"TRANSACTION_ID"	NUMBER NOT NULL, 
	"CREATED_DATE"		DATE DEFAULT sysdate NOT NULL, 
	"INPUT_FILENAME"	VARCHAR2(80),
	"A_NUMBER"		VARCHAR2(64),
	"EVENT_ID"		VARCHAR2(20),	-- Common
	"EVENT_SPLIT_REASON"	VARCHAR2(1),
	"EVENT_START_TIME"	VARCHAR2(14),
	"EVENT_END_TIME"	VARCHAR2(14),
	"EVENT_LOCAL_START_TIME"	VARCHAR2(14),
	"EVENT_LOCAL_END_TIME"	VARCHAR2(14),
	"OBJECT_TYPE"	VARCHAR2(1),
	"EXTERNAL_SUBSCRIBER_ID"	VARCHAR2(64),	-- Increased to 64
	"CUSTOMER_ID"		VARCHAR2(9),
	"SUBSCRIBER_ID"		VARCHAR2(9),
	"PRIMARY_RESOURCE_VALUE"	VARCHAR2(32),
	"BILL_CYCLE_IDENTIFIER"	VARCHAR2(8),
	"SERVICE_SUBTYPE"	VARCHAR2(10),
	"SESSION_ID"		VARCHAR2(128),
	"INTERNAL_RESULT_CODE"	VARCHAR2(10),
	"UOM"			VARCHAR2(1),
	"ACTUAL_USAGE"		VARCHAR2(20),	-- Increased to 20
	"ROUNDED_UNIT"		VARCHAR2(20),	-- Increased to 20
	"SERVICE_TYPE"		VARCHAR2(1),
	"CHARGE_AMOUNT"		VARCHAR2(10),
	"CALLING_NUMBER"	VARCHAR2(64),
	"IMSI_CALLING_PARTY"	VARCHAR2(64),
	"CALLING_PARTY_ROAMING_INFO"	VARCHAR2(256),
	"PRIMARY_OFFER_ID"	VARCHAR2(20),
	"CHARGED_NUMBER"	VARCHAR2(64),
	"ROAMING_IND"		VARCHAR2(1),
	"HOME_COUNTRY_CODE_CALLING"	VARCHAR2(3),
	"NETWORK_CODE_CALLING_PARTY"	VARCHAR2(10),
	"ROAMING_COUNTRY_CODE_CALLING"	VARCHAR2(3),
	"ROAMING_NETWORK_CODE_CALLING"	VARCHAR2(10),
	"IS_ONLINE"		VARCHAR2(1),
	"CYCLE_START_TIME"	VARCHAR2(14),
	"LAST_EFFECT_OFFER_ID"	VARCHAR2(20),	
	"CHARGE_CODE_INFO_CODE1"	VARCHAR2(64),
	"CHARGE_CODE_INFO_NAME1"	VARCHAR2(128),
	"CHARGE_CODE_INFO_AMOUNT1"	VARCHAR2(9),
	"CHARGE_CODE_INFO_CODE2"	VARCHAR2(64),
	"CHARGE_CODE_INFO_NAME2"	VARCHAR2(128),
	"CHARGE_CODE_INFO_AMOUNT2"	VARCHAR2(9),
	"CHARGE_CODE_INFO_CODE3"	VARCHAR2(64),
	"CHARGE_CODE_INFO_NAME3"	VARCHAR2(128),
	"CHARGE_CODE_INFO_AMOUNT3"	VARCHAR2(9),
	"SUMMARY_CHARGE_CODE_INFO"	VARCHAR2(64),	
	"SUMMARY_CHARGE_CODE_NAME"	VARCHAR2(128),
	"SUMMARY_CHARGE_AMOUNT"		VARCHAR2(9),
	"HOME_COUNTRY_NAME_CALLING"	VARCHAR2(64),
	"ROAMING_COUNTRY_NAME_CALLING"	VARCHAR2(64),
	"DEBIT_AMOUNT"			VARCHAR2(20),
	"CURRENCY_IND"			VARCHAR2(3),
	"EXTERNAL_CUSTOMER_ID"	VARCHAR2(64),	-- Increased to 64
	"SERVICE_FILTER"	VARCHAR2(20),
	"IMEI"			VARCHAR2(24),	-- Increased to 24
	"OCS_SITE_ID"		VARCHAR2(20),
	"PRICING_ITEM_ID"	VARCHAR2(9),
	"PAYMENT_TYPE"		VARCHAR2(10),
        "ROAMING_ZONE"		VARCHAR2(10),	-- V.1.0
    	"ORIGINATING_CATEGORY"  VARCHAR2(10),
    	"DESTINATION_CATEGORY"	VARCHAR2(10),
    	"RERATE_INDICATOR" 	VARCHAR2(1),
    	"DISCOUNT_AMOUNT"       VARCHAR2(9),
    	"CD_USAGE"              VARCHAR2(1),
    	"REFUND_IND"            VARCHAR2(1),
    	"UNAPPLIED_ALLOWANCE"   VARCHAR2(20),	-- Increased to 20
    	"UNDEBIT_AMOUNT"	VARCHAR2(10),	-- Newly added - 20210728
	"RESULT_REASON"          VARCHAR2(64),	-- GPRS
	"CELL_ID_DATA"           VARCHAR2(20),
	"EVENT_CHARGING_TIME"    VARCHAR2(14),
	"FREE_VOLUME_CONSUMED"   VARCHAR2(20),
	"MCC_VISITED"            VARCHAR2(32),
	"MNC_VISITED"            VARCHAR2(32),
	"VLR_NUMBER"             VARCHAR2(32),
	"APN"                    VARCHAR2(30),	-- Increased to 30
	"ACCESS_NETWORK_ADDRESS" VARCHAR2(22),
	"GGSN_ADDRESS"           VARCHAR2(22),
	"SGSN_TIMESTAMP"         VARCHAR2(14),
	"TOTAL_USAGE"            VARCHAR2(20),
	"UPLINK"                 VARCHAR2(20),
	"DOWNLINK"               VARCHAR2(20),
	"ELAPSED_DURATION"       VARCHAR2(10),
	"QOS"                    VARCHAR2(40),	-- Increased to 40
	"NETWORK_CHARGING_ID"    VARCHAR2(10),
	"RATING_GROUP_ID"        VARCHAR2(10),
	"RAT_TYPE"               VARCHAR2(10),
	"ACCESS_TYPE_VALUE"      VARCHAR2(20),
	"RATING_GROUP_VALUE"     VARCHAR2(4),	-- Increased to 4
--	"REFUND_IND"             VARCHAR2(1),	-- Removed for V.1.0
	"LAC_VISITED"            VARCHAR2(32),	-- V.1.0
        "RPP_STATE"              VARCHAR2(1)
) 
SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE MZ_MOB_CDR_DATA
  partition by range(CREATED_DATE)
(
  PARTITION PMAXVALUE  VALUES LESS THAN (MAXVALUE) TABLESPACE  MZ_MOB_CDR_DATA
);


-- Create new table CDR_INPUT_OCS_NRC_AMDOCS
--
CREATE TABLE "MZ_MOB_DATA_OWNER"."CDR_INPUT_OCS_NRC_AMDOCS" 
(
	"TRANSACTION_ID"	NUMBER NOT NULL, 
	"CREATED_DATE"		DATE DEFAULT sysdate NOT NULL, 
	"INPUT_FILENAME"	VARCHAR2(80),
	"A_NUMBER"		VARCHAR2(64),
        "EVENT_ID"                 VARCHAR2(20),	-- NRC
        "EVENT_LOCAL_START_TIME"   VARCHAR2(14),
        "OBJECT_TYPE"              VARCHAR2(1),
        "EXTERNAL_SUBSCRIBER_ID"   VARCHAR2(64),	-- Increased to 64
        "CUSTOMER_ID"              VARCHAR2(9),
        "SUBSCRIBER_ID"            VARCHAR2(9),
        "SERVICE_TYPE"             VARCHAR2(2),		-- Increased to 2
        "CHARGE_AMOUNT"            VARCHAR2(10),
        "CHARGED_NUMBER"           VARCHAR2(64),
        "RENTAL_OFFERING_ID"       VARCHAR2(20),
        "CURRENCY_IND"             VARCHAR2(3),
        "EXTERNAL_CUSTOMER_ID"     VARCHAR2(64),	-- Increased to 64
        "SERVICE_FILTER"           VARCHAR2(20),
        "BILL_CYCLE_IDENTIFIER"    VARCHAR2(8),
        "OCS_SITE_ID"              VARCHAR2(20),
        "REFUND_IND"               VARCHAR2(1),
        "PAYMENT_TYPE"             VARCHAR2(10),
        "CHARGE_CODE"              VARCHAR2(10),	-- V.1.0
        "CHARGE_CODE_DESC"         VARCHAR2(128)
) 
SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE MZ_MOB_CDR_DATA
  partition by range(CREATED_DATE)
(
  PARTITION PMAXVALUE  VALUES LESS THAN (MAXVALUE) TABLESPACE  MZ_MOB_CDR_DATA
);


-- Create CDR_INPUT_PGW_NOKIA table
--
CREATE TABLE MZ_MOB_DATA_OWNER.CDR_INPUT_PGW_NOKIA 
(
	"TRANSACTION_ID" NUMBER NOT NULL, 
	"CREATED_DATE" DATE DEFAULT sysdate NOT NULL, 
	"INPUT_FILENAME" VARCHAR2(80 BYTE), 
	"SERVED_MSISDN" VARCHAR2(40 BYTE), 	
	"MSISDN" VARCHAR2(30 BYTE), 
	"IMSI" VARCHAR2(20 BYTE), 
	"IMEI" VARCHAR2(20 BYTE), 
	"RAT" NUMBER(*,0), 
	"RECORDOPENINGTIME" VARCHAR2(30 BYTE), 
	"REC_OPEN_TIME_UTC" DATE, 
	"MSTZ" VARCHAR2(10 BYTE), 
	"DURATION" NUMBER(15,0), 
	"CAUSE_REC_CLOSE" NUMBER(*,0), 
	"CHARGINGID" NUMBER(*,0), 
	"LOCAL_SEQ_NUM" NUMBER(*,0), 
	"SEQ_NUM" NUMBER(*,0), 
	"APN" VARCHAR2(80 BYTE), 
	"ULI_ORIGINAL" VARCHAR2(50 BYTE), 
	"MCC" VARCHAR2(5 BYTE), 
	"MNC" VARCHAR2(5 BYTE), 
	"LAC" VARCHAR2(10 BYTE), 
	"CI" VARCHAR2(10 BYTE), 
	"SAC" VARCHAR2(20 BYTE), 
	"RAC" VARCHAR2(5 BYTE), 
	"TAC" VARCHAR2(20 BYTE), 
	"ECI" VARCHAR2(20 BYTE),
	"SMENB" VARCHAR2(5 BYTE),			-- MAIN LEVEL SMENB FLAG
	"ENODEB_ID" VARCHAR2(50 BYTE),			-- MAIN LEVEL ENODEB ID 	
	"SERVING_NODE_TYPE" VARCHAR2(5 BYTE), 
	"STARTTIME" VARCHAR2(30 BYTE), 
	"STOPTIME" VARCHAR2(30 BYTE), 
	"IPADD" VARCHAR2(50 BYTE),			-- PDPPDN IP ADDRESS
	"UWAN_IPADD" VARCHAR2(50),			-- RAW UWAN DATA
	"UE_IP" VARCHAR2(50),				-- UWAN DATA IN IP NOTATION
	"INCOMP_CDR_IND_ACRLOST_START" VARCHAR2(1),	-- FAILOVER FIELDS
	"INCOMP_CDR_IND_ACRLOST_INTRM" NUMBER,
	"INCOMP_CDR_IND_ACRLOST_STOP" VARCHAR2(1),
	"SESSION_ID" VARCHAR2(200 BYTE),
	"PGW_ADDRESS" VARCHAR2(50 BYTE),
	"RECORD_CLOSURE_TIME" VARCHAR2(30 BYTE),
	"QCI" NUMBER(20,0),				-- MAIN QOS FIELDS
	"MAX_REQ_BW_UL" NUMBER(20,0),
	"MAX_REQ_BW_DL" NUMBER(20,0),
	"GUARANTEED_BR_UL" NUMBER(20,0),
	"GUARANTEED_BR_DL" NUMBER(20,0),
	"ARP" NUMBER(20,0),
	"APN_AGGR_MAX_BR_UL" NUMBER(20,0),
	"APN_AGGR_MAX_BR_DL" NUMBER(20,0),
	"EXT_MAX_REQ_BW_UL" NUMBER(20,0),
	"EXT_MAX_REQ_BW_DL" NUMBER(20,0),
	"EXT_APN_AM_BR_UL" NUMBER(20,0),
	"EXT_APN_AM_BR_DL" NUMBER(20,0),
	"RATING_GRP1" NUMBER(*,0),			-- START OF TEN DATA SERVICE CONTAINERS
	"FIRST_USAGE1" VARCHAR2(30 BYTE), 
	"LAST_USAGE1" VARCHAR2(30 BYTE), 
	"TIME_USAGE1" VARCHAR2(30 BYTE),
	"SVC_COND_CHANGE1" VARCHAR2(40 BYTE), 
	"SVCUPVOL1" NUMBER(20,0), 
	"SVCDOWNVOL1" NUMBER(20,0), 
	"RAT1" NUMBER(*,0), 
	"LOCAL_SEQ_NUM1" NUMBER(20,0), 
	"AF_CHARGING_ID_1" VARCHAR2(128),
	"UE_IP_1" VARCHAR2(50),
	"ULI_ORIG1" VARCHAR2(50 BYTE),			-- THESE ARE ULI FIELDS 
	"MCC1" VARCHAR2(5 BYTE), 
	"MNC1" VARCHAR2(5 BYTE), 
	"LAC1" VARCHAR2(10 BYTE), 
	"CI1" VARCHAR2(10 BYTE), 
	"SAC1" VARCHAR2(20 BYTE), 
	"RAC1" VARCHAR2(5 BYTE), 
	"TAC1" VARCHAR2(20 BYTE), 
	"ECI1" VARCHAR2(20 BYTE), 	
	"SMENB1" VARCHAR2(5 BYTE),
	"ENODEB_ID1" VARCHAR2(50 BYTE), 
	"RATING_GRP2" NUMBER(*,0), 
	"FIRST_USAGE2" VARCHAR2(30 BYTE), 
	"LAST_USAGE2" VARCHAR2(30 BYTE),
	"TIME_USAGE2" VARCHAR2(30 BYTE),
	"SVC_COND_CHANGE2" VARCHAR2(40 BYTE), 
	"SVCUPVOL2" NUMBER(20,0), 
	"SVCDOWNVOL2" NUMBER(20,0), 
	"RAT2" NUMBER(*,0), 
	"LOCAL_SEQ_NUM2" NUMBER(20,0), 
	"AF_CHARGING_ID_2" VARCHAR2(128),
	"UE_IP_2" VARCHAR2(50),
	"ULI_ORIG2" VARCHAR2(50 BYTE),			-- THESE ARE ULI FIELDS 
	"MCC2" VARCHAR2(5 BYTE), 
	"MNC2" VARCHAR2(5 BYTE), 
	"LAC2" VARCHAR2(10 BYTE), 
	"CI2" VARCHAR2(10 BYTE), 
	"SAC2" VARCHAR2(20 BYTE), 
	"RAC2" VARCHAR2(5 BYTE), 
	"TAC2" VARCHAR2(20 BYTE), 
	"ECI2" VARCHAR2(20 BYTE), 	
	"SMENB2" VARCHAR2(5 BYTE),
	"ENODEB_ID2" VARCHAR2(50 BYTE), 
	"RATING_GRP3" NUMBER(*,0), 
	"FIRST_USAGE3" VARCHAR2(30 BYTE), 
	"LAST_USAGE3" VARCHAR2(30 BYTE),
	"TIME_USAGE3" VARCHAR2(30 BYTE),
	"SVC_COND_CHANGE3" VARCHAR2(40 BYTE), 
	"SVCUPVOL3" NUMBER(20,0), 
	"SVCDOWNVOL3" NUMBER(20,0), 
	"RAT3" NUMBER(*,0), 
	"LOCAL_SEQ_NUM3" NUMBER(20,0), 
	"AF_CHARGING_ID_3" VARCHAR2(128),
	"UE_IP_3" VARCHAR2(50),
	"ULI_ORIG3" VARCHAR2(50 BYTE),			-- THESE ARE ULI FIELDS 
	"MCC3" VARCHAR2(5 BYTE), 
	"MNC3" VARCHAR2(5 BYTE), 
	"LAC3" VARCHAR2(10 BYTE), 
	"CI3" VARCHAR2(10 BYTE), 
	"SAC3" VARCHAR2(20 BYTE), 
	"RAC3" VARCHAR2(5 BYTE), 
	"TAC3" VARCHAR2(20 BYTE), 
	"ECI3" VARCHAR2(20 BYTE), 	
	"SMENB3" VARCHAR2(5 BYTE),
	"ENODEB_ID3" VARCHAR2(50 BYTE), 	
	"RATING_GRP4" NUMBER(*,0), 
	"FIRST_USAGE4" VARCHAR2(30 BYTE), 
	"LAST_USAGE4" VARCHAR2(30 BYTE),
	"TIME_USAGE4" VARCHAR2(30 BYTE),
	"SVC_COND_CHANGE4" VARCHAR2(40 BYTE), 
	"SVCUPVOL4" NUMBER(20,0), 
	"SVCDOWNVOL4" NUMBER(20,0), 
	"RAT4" NUMBER(*,0), 
	"LOCAL_SEQ_NUM4" NUMBER(20,0), 
	"AF_CHARGING_ID_4" VARCHAR2(128),
	"UE_IP_4" VARCHAR2(50),
	"ULI_ORIG4" VARCHAR2(50 BYTE),			-- THESE ARE ULI FIELDS  
	"MCC4" VARCHAR2(5 BYTE), 
	"MNC4" VARCHAR2(5 BYTE), 
	"LAC4" VARCHAR2(10 BYTE), 
	"CI4" VARCHAR2(10 BYTE), 
	"SAC4" VARCHAR2(20 BYTE), 
	"RAC4" VARCHAR2(5 BYTE), 
	"TAC4" VARCHAR2(20 BYTE), 
	"ECI4" VARCHAR2(20 BYTE), 	
	"SMENB4" VARCHAR2(5 BYTE),
	"ENODEB_ID4" VARCHAR2(50 BYTE), 	
	"RATING_GRP5" NUMBER(*,0), 
	"FIRST_USAGE5" VARCHAR2(30 BYTE), 
	"LAST_USAGE5" VARCHAR2(30 BYTE),
	"TIME_USAGE5" VARCHAR2(30 BYTE),
	"SVC_COND_CHANGE5" VARCHAR2(40 BYTE), 
	"SVCUPVOL5" NUMBER(20,0), 
	"SVCDOWNVOL5" NUMBER(20,0), 
	"RAT5" NUMBER(*,0), 
	"LOCAL_SEQ_NUM5" NUMBER(20,0), 
	"AF_CHARGING_ID_5" VARCHAR2(128),	
	"UE_IP_5" VARCHAR2(50),
	"ULI_ORIG5" VARCHAR2(50 BYTE),			-- THESE ARE ULI FIELDS 
	"MCC5" VARCHAR2(5 BYTE), 
	"MNC5" VARCHAR2(5 BYTE), 
	"LAC5" VARCHAR2(10 BYTE), 
	"CI5" VARCHAR2(10 BYTE), 
	"SAC5" VARCHAR2(20 BYTE), 
	"RAC5" VARCHAR2(5 BYTE), 
	"TAC5" VARCHAR2(20 BYTE), 
	"ECI5" VARCHAR2(20 BYTE), 	
	"SMENB5" VARCHAR2(5 BYTE),
	"ENODEB_ID5" VARCHAR2(50 BYTE), 	
	"RATING_GRP6" NUMBER(*,0), 
	"FIRST_USAGE6" VARCHAR2(30 BYTE), 
	"LAST_USAGE6" VARCHAR2(30 BYTE),
	"TIME_USAGE6" VARCHAR2(30 BYTE),
	"SVC_COND_CHANGE6" VARCHAR2(40 BYTE), 
	"SVCUPVOL6" NUMBER(20,0), 
	"SVCDOWNVOL6" NUMBER(20,0), 
	"RAT6" NUMBER(*,0), 
	"LOCAL_SEQ_NUM6" NUMBER(20,0), 
	"AF_CHARGING_ID_6" VARCHAR2(128),	
	"UE_IP_6" VARCHAR2(50),
	"ULI_ORIG6" VARCHAR2(50 BYTE),			-- THESE ARE ULI FIELDS 
	"MCC6" VARCHAR2(5 BYTE), 
	"MNC6" VARCHAR2(5 BYTE), 
	"LAC6" VARCHAR2(10 BYTE), 
	"CI6" VARCHAR2(10 BYTE), 
	"SAC6" VARCHAR2(20 BYTE), 
	"RAC6" VARCHAR2(5 BYTE), 
	"TAC6" VARCHAR2(20 BYTE), 
	"ECI6" VARCHAR2(20 BYTE), 	
	"SMENB6" VARCHAR2(5 BYTE),
	"ENODEB_ID6" VARCHAR2(50 BYTE), 	
	"RATING_GRP7" NUMBER(*,0), 
	"FIRST_USAGE7" VARCHAR2(30 BYTE), 
	"LAST_USAGE7" VARCHAR2(30 BYTE),
	"TIME_USAGE7" VARCHAR2(30 BYTE),
	"SVC_COND_CHANGE7" VARCHAR2(40 BYTE), 
	"SVCUPVOL7" NUMBER(20,0), 
	"SVCDOWNVOL7" NUMBER(20,0), 
	"RAT7" NUMBER(*,0), 
	"LOCAL_SEQ_NUM7" NUMBER(20,0), 
	"AF_CHARGING_ID_7" VARCHAR2(128),
	"UE_IP_7" VARCHAR2(50),
	"ULI_ORIG7" VARCHAR2(50 BYTE),			-- THESE ARE ULI FIELDS 
	"MCC7" VARCHAR2(5 BYTE), 
	"MNC7" VARCHAR2(5 BYTE), 
	"LAC7" VARCHAR2(10 BYTE), 
	"CI7" VARCHAR2(10 BYTE), 
	"SAC7" VARCHAR2(20 BYTE), 
	"RAC7" VARCHAR2(5 BYTE), 
	"TAC7" VARCHAR2(20 BYTE), 
	"ECI7" VARCHAR2(20 BYTE), 	
	"SMENB7" VARCHAR2(5 BYTE),
	"ENODEB_ID7" VARCHAR2(50 BYTE),	
	"RATING_GRP8" NUMBER(*,0), 
	"FIRST_USAGE8" VARCHAR2(30 BYTE), 
	"LAST_USAGE8" VARCHAR2(30 BYTE),
	"TIME_USAGE8" VARCHAR2(30 BYTE),
	"SVC_COND_CHANGE8" VARCHAR2(40 BYTE), 
	"SVCUPVOL8" NUMBER(20,0), 
	"SVCDOWNVOL8" NUMBER(20,0), 
	"RAT8" NUMBER(*,0), 
	"LOCAL_SEQ_NUM8" NUMBER(20,0), 
	"AF_CHARGING_ID_8" VARCHAR2(128),	
	"UE_IP_8" VARCHAR2(50),
	"ULI_ORIG8" VARCHAR2(50 BYTE),			-- THESE ARE ULI FIELDS 
	"MCC8" VARCHAR2(5 BYTE), 
	"MNC8" VARCHAR2(5 BYTE), 
	"LAC8" VARCHAR2(10 BYTE), 
	"CI8" VARCHAR2(10 BYTE), 
	"SAC8" VARCHAR2(20 BYTE), 
	"RAC8" VARCHAR2(5 BYTE), 
	"TAC8" VARCHAR2(20 BYTE), 
	"ECI8" VARCHAR2(20 BYTE), 	
	"SMENB8" VARCHAR2(5 BYTE),
	"ENODEB_ID8" VARCHAR2(50 BYTE),		
	"RATING_GRP9" NUMBER(*,0), 
	"FIRST_USAGE9" VARCHAR2(30 BYTE), 
	"LAST_USAGE9" VARCHAR2(30 BYTE),
	"TIME_USAGE9" VARCHAR2(30 BYTE),
	"SVC_COND_CHANGE9" VARCHAR2(40 BYTE), 
	"SVCUPVOL9" NUMBER(20,0), 
	"SVCDOWNVOL9" NUMBER(20,0), 
	"RAT9" NUMBER(*,0), 
	"LOCAL_SEQ_NUM9" NUMBER(20,0), 
	"AF_CHARGING_ID_9" VARCHAR2(128),	
	"UE_IP_9" VARCHAR2(50),
	"ULI_ORIG9" VARCHAR2(50 BYTE),			-- THESE ARE ULI FIELDS 
	"MCC9" VARCHAR2(5 BYTE), 
	"MNC9" VARCHAR2(5 BYTE), 
	"LAC9" VARCHAR2(10 BYTE), 
	"CI9" VARCHAR2(10 BYTE), 
	"SAC9" VARCHAR2(20 BYTE), 
	"RAC9" VARCHAR2(5 BYTE), 
	"TAC9" VARCHAR2(20 BYTE), 
	"ECI9" VARCHAR2(20 BYTE), 	
	"SMENB9" VARCHAR2(5 BYTE),
	"ENODEB_ID9" VARCHAR2(50 BYTE),	
	"RATING_GRP10" NUMBER(*,0), 
	"FIRST_USAGE10" VARCHAR2(30 BYTE), 
	"LAST_USAGE10" VARCHAR2(30 BYTE),
	"TIME_USAGE10" VARCHAR2(30 BYTE),
	"SVC_COND_CHANGE10" VARCHAR2(40 BYTE), 
	"SVCUPVOL10" NUMBER(20,0), 
	"SVCDOWNVOL10" NUMBER(20,0), 
	"RAT10" NUMBER(*,0), 
	"LOCAL_SEQ_NUM10" NUMBER(20,0),
	"AF_CHARGING_ID_10" VARCHAR2(128),
	"UE_IP_10" VARCHAR2(50),
	"ULI_ORIG10" VARCHAR2(50 BYTE),			-- THESE ARE ULI FIELDS 
	"MCC10" VARCHAR2(5 BYTE), 
	"MNC10" VARCHAR2(5 BYTE), 
	"LAC10" VARCHAR2(10 BYTE), 
	"CI10" VARCHAR2(10 BYTE), 
	"SAC10" VARCHAR2(20 BYTE), 
	"RAC10" VARCHAR2(5 BYTE), 
	"TAC10" VARCHAR2(20 BYTE), 
	"ECI10" VARCHAR2(20 BYTE), 	
	"SMENB10" VARCHAR2(5 BYTE),
	"ENODEB_ID10" VARCHAR2(50 BYTE)		
) 
SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE MZ_MOB_CDR_DATA
partition by range(CREATED_DATE)
(
  PARTITION PMAXVALUE  VALUES LESS THAN (MAXVALUE) TABLESPACE  MZ_MOB_CDR_DATA
);


-- Create the indexes in the CDR_INPUT_OCS_VOICE_AMDOCS table
--
CREATE INDEX CDR_INPUT_OCS_VOICE_A_IDX1 ON CDR_INPUT_OCS_VOICE_AMDOCS (CREATED_DATE) LOCAL;

CREATE INDEX CDR_INPUT_OCS_VOICE_A_IDX2 ON CDR_INPUT_OCS_VOICE_AMDOCS (TRANSACTION_ID) LOCAL;

CREATE INDEX CDR_INPUT_OCS_VOICE_A_IDX3 ON CDR_INPUT_OCS_VOICE_AMDOCS (A_NUMBER) LOCAL;

CREATE INDEX CDR_INPUT_OCS_VOICE_A_IDX4 ON CDR_INPUT_OCS_VOICE_AMDOCS (B_NUMBER) LOCAL;

CREATE INDEX CDR_INPUT_OCS_VOICE_A_IDX5 ON CDR_INPUT_OCS_VOICE_AMDOCS (IMSI_CALLING_PARTY) LOCAL;


-- Create the indexes in the CDR_INPUT_OCS_SMS_AMDOCS table
--
CREATE INDEX CDR_INPUT_OCS_SMS_A_IDX1 ON CDR_INPUT_OCS_SMS_AMDOCS (CREATED_DATE) LOCAL;

CREATE INDEX CDR_INPUT_OCS_SMS_A_IDX2 ON CDR_INPUT_OCS_SMS_AMDOCS (TRANSACTION_ID) LOCAL;

CREATE INDEX CDR_INPUT_OCS_SMS_A_IDX3 ON CDR_INPUT_OCS_SMS_AMDOCS (A_NUMBER) LOCAL;

CREATE INDEX CDR_INPUT_OCS_SMS_A_IDX4 ON CDR_INPUT_OCS_SMS_AMDOCS (B_NUMBER) LOCAL;


-- Create the indexes in the CDR_INPUT_OCS_MMS_AMDOCS table
--
CREATE INDEX CDR_INPUT_OCS_MMS_A_IDX1 ON CDR_INPUT_OCS_MMS_AMDOCS (CREATED_DATE) LOCAL;

CREATE INDEX CDR_INPUT_OCS_MMS_A_IDX2 ON CDR_INPUT_OCS_MMS_AMDOCS (TRANSACTION_ID) LOCAL;

CREATE INDEX CDR_INPUT_OCS_MMS_A_IDX3 ON CDR_INPUT_OCS_MMS_AMDOCS (A_NUMBER) LOCAL;

CREATE INDEX CDR_INPUT_OCS_MMS_A_IDX4 ON CDR_INPUT_OCS_MMS_AMDOCS (B_NUMBER) LOCAL;


-- Create the indexes in the CDR_INPUT_OCS_GPRS_AMDOCS table
--
CREATE INDEX CDR_INPUT_OCS_GPRS_A_IDX1 ON CDR_INPUT_OCS_GPRS_AMDOCS (CREATED_DATE) LOCAL;

CREATE INDEX CDR_INPUT_OCS_GPRS_A_IDX2 ON CDR_INPUT_OCS_GPRS_AMDOCS (TRANSACTION_ID) LOCAL;

CREATE INDEX CDR_INPUT_OCS_GPRS_A_IDX3 ON CDR_INPUT_OCS_GPRS_AMDOCS (A_NUMBER) LOCAL;


-- Create the indexes in the CDR_INPUT_OCS_NRC_AMDOCS table
--
CREATE INDEX CDR_INPUT_OCS_NRC_A_IDX1 ON CDR_INPUT_OCS_NRC_AMDOCS (CREATED_DATE) LOCAL;

CREATE INDEX CDR_INPUT_OCS_NRC_A_IDX2 ON CDR_INPUT_OCS_NRC_AMDOCS (TRANSACTION_ID) LOCAL;

CREATE INDEX CDR_INPUT_OCS_NRC_A_IDX3 ON CDR_INPUT_OCS_NRC_AMDOCS (A_NUMBER) LOCAL;


-- Create Indexes on CDR_INPUT_PGW_NOKIA
--
CREATE INDEX CDR_INPUT_PGW_N_IDX1 ON CDR_INPUT_PGW_NOKIA (CREATED_DATE) LOCAL;

CREATE INDEX CDR_INPUT_PGW_N_IDX2 ON CDR_INPUT_PGW_NOKIA (TRANSACTION_ID) LOCAL;

CREATE INDEX CDR_INPUT_PGW_N_IDX3 ON CDR_INPUT_PGW_NOKIA (MSISDN) LOCAL;