-- MZMOB-631 - Add further columns to the CDR_INPUT_TAP table
--
ALTER TABLE CDR_INPUT_TAP
  ADD (CHARGED_ITEM1		VARCHAR2(5),
       SERVING_BID		VARCHAR2(10),
       LOCATION_DESCRIPTION	VARCHAR2(150)
       );
