-- MZMOB-612 - Insert duplicate check values into the MZ_CONFIGURATION table for A-OCS
--
INSERT INTO "MZ_MOB_DATA_OWNER"."MZ_CONFIGURATION" (PARAMETER, PARAMETER_VALUE) VALUES ('AOCS_DUP_UDR_CHECK', '1');

INSERT INTO "MZ_MOB_DATA_OWNER"."MZ_CONFIGURATION" (PARAMETER, PARAMETER_VALUE) VALUES ('AOCS_DUP_BATCH_CHECK', '1');