-- MZMOB-682 - create lookup table DN_FREEPHONE_CODES_SMS for filtering numbers from SMS Kenan

create table MZ_MOB_DATA_OWNER.DN_FREEPHONE_CODES_SMS (
    SMS_CODE    VARCHAR2(32) NOT NULL,
    DESCRIPTION VARCHAR2(50)
);

-- Initial inserts. Update with later dbinc. once Olly/ Peter finalised the list.
INSERT INTO MZ_MOB_DATA_OWNER.DN_FREEPHONE_CODES_SMS (SMS_CODE, DESCRIPTION) VALUES ('999', 'Emergency');
INSERT INTO MZ_MOB_DATA_OWNER.DN_FREEPHONE_CODES_SMS (SMS_CODE, DESCRIPTION) VALUES ('112', 'Emergency');
INSERT INTO MZ_MOB_DATA_OWNER.DN_FREEPHONE_CODES_SMS (SMS_CODE, DESCRIPTION) VALUES ('116000', 'Missing child helpline');
INSERT INTO MZ_MOB_DATA_OWNER.DN_FREEPHONE_CODES_SMS (SMS_CODE, DESCRIPTION) VALUES ('18001111', 'Text relay');
INSERT INTO MZ_MOB_DATA_OWNER.DN_FREEPHONE_CODES_SMS (SMS_CODE, DESCRIPTION) VALUES ('85251', 'Shout helpline');
INSERT INTO MZ_MOB_DATA_OWNER.DN_FREEPHONE_CODES_SMS (SMS_CODE, DESCRIPTION) VALUES ('85252', 'Shout helpline');
INSERT INTO MZ_MOB_DATA_OWNER.DN_FREEPHONE_CODES_SMS (SMS_CODE, DESCRIPTION) VALUES ('85253', 'Shout helpline');
INSERT INTO MZ_MOB_DATA_OWNER.DN_FREEPHONE_CODES_SMS (SMS_CODE, DESCRIPTION) VALUES ('85254', 'Shout helpline');
INSERT INTO MZ_MOB_DATA_OWNER.DN_FREEPHONE_CODES_SMS (SMS_CODE, DESCRIPTION) VALUES ('85255', 'Shout helpline');
INSERT INTO MZ_MOB_DATA_OWNER.DN_FREEPHONE_CODES_SMS (SMS_CODE, DESCRIPTION) VALUES ('85256', 'Shout helpline');
INSERT INTO MZ_MOB_DATA_OWNER.DN_FREEPHONE_CODES_SMS (SMS_CODE, DESCRIPTION) VALUES ('85257', 'Shout helpline');
INSERT INTO MZ_MOB_DATA_OWNER.DN_FREEPHONE_CODES_SMS (SMS_CODE, DESCRIPTION) VALUES ('85258', 'Shout helpline');
INSERT INTO MZ_MOB_DATA_OWNER.DN_FREEPHONE_CODES_SMS (SMS_CODE, DESCRIPTION) VALUES ('85259', 'Shout helpline');