--MZMOB-690 - Widen three fields in the A-OCS DB tables

----Customer_ID
ALTER TABLE CDR_INPUT_OCS_VOICE_AMDOCS MODIFY CUSTOMER_ID VARCHAR2(20);
ALTER TABLE CDR_INPUT_OCS_GPRS_AMDOCS MODIFY CUSTOMER_ID VARCHAR2(20);
ALTER TABLE CDR_INPUT_OCS_SMS_AMDOCS MODIFY CUSTOMER_ID VARCHAR2(20);
ALTER TABLE CDR_INPUT_OCS_MMS_AMDOCS MODIFY CUSTOMER_ID VARCHAR2(20);
ALTER TABLE CDR_INPUT_OCS_NRC_AMDOCS MODIFY CUSTOMER_ID VARCHAR2(20);

----Subscriber_ID
ALTER TABLE CDR_INPUT_OCS_VOICE_AMDOCS MODIFY SUBSCRIBER_ID VARCHAR2(20);
ALTER TABLE CDR_INPUT_OCS_GPRS_AMDOCS MODIFY SUBSCRIBER_ID VARCHAR2(20);
ALTER TABLE CDR_INPUT_OCS_SMS_AMDOCS MODIFY SUBSCRIBER_ID VARCHAR2(20);
ALTER TABLE CDR_INPUT_OCS_MMS_AMDOCS MODIFY SUBSCRIBER_ID VARCHAR2(20);
ALTER TABLE CDR_INPUT_OCS_NRC_AMDOCS MODIFY SUBSCRIBER_ID VARCHAR2(20);

----Pricing_Item_ID (NRC Amdocs does not have Pricing_Item_ID)
ALTER TABLE CDR_INPUT_OCS_VOICE_AMDOCS MODIFY PRICING_ITEM_ID VARCHAR2(20);
ALTER TABLE CDR_INPUT_OCS_GPRS_AMDOCS MODIFY PRICING_ITEM_ID VARCHAR2(20);
ALTER TABLE CDR_INPUT_OCS_SMS_AMDOCS MODIFY PRICING_ITEM_ID VARCHAR2(20);
ALTER TABLE CDR_INPUT_OCS_MMS_AMDOCS MODIFY PRICING_ITEM_ID VARCHAR2(20);