-- INSERT INTO THE SERVICE TYPE TABLE
--
INSERT INTO SERVICE_TO_KENAN_MAPPING VALUES ('27','3','Voice Mail Callback','2000','031#');

-- UPDATE THE SERVICE TYPE TO THE CORRECT VALUE
--
UPDATE SERVICE_TO_KENAN_MAPPING 
   SET SERVICE_TYPE = '52'
 WHERE SERVICE_TYPE = '1';
