-- REMOVE THE EMERGENCY NUMBERS
--
DELETE FROM PREFIX_TO_KENAN_MAPPING
 WHERE DESCRIPTION LIKE 'Emergency%';


-- UPDATE THE NOMDIC NUMBER TO 55
--
UPDATE PREFIX_TO_KENAN_MAPPING
   SET PREFIX = '55'
 WHERE PREFIX = '5';


-- UPDATE ONE OF THE PREMIUM RATE 89* NUMBERS
--
UPDATE PREFIX_TO_KENAN_MAPPING
   SET PREFIX = '89'
 WHERE PREFIX = '892';
 

-- DELETE THE PREMIUM RATE 89* NUMBERS
--
DELETE FROM PREFIX_TO_KENAN_MAPPING
 WHERE PREFIX IN ('894', '895', '899');


-- UPDATE THE PREFIXES FOR THE FREEPHONE PUBLIC UTILTY 169 ROWS TO THE CORRECT PREFIX OF 196
--
UPDATE PREFIX_TO_KENAN_MAPPING
   SET prefix = prefix + 2700
 WHERE prefix LIKE '169%';


-- INSERT NEW CUSTOMER CARE NUMBERS FOR TIM
--
INSERT INTO PREFIX_TO_KENAN_MAPPING VALUES ('119','TIM Customer Service','2000','010#');

INSERT INTO PREFIX_TO_KENAN_MAPPING VALUES ('187','TIM Customer Service','2000','010#');

INSERT INTO PREFIX_TO_KENAN_MAPPING VALUES ('191','TIM Customer Service','2000','010#');


-- DELETE THE SKY CUSTOMER CARE 192 NUMBERS
--
DELETE FROM PREFIX_TO_KENAN_MAPPING
 WHERE PREFIX LIKE '192%';
 
 
-- INSERT NEW CUSTOMER CARE NUMBER FOR SKY
--
INSERT INTO PREFIX_TO_KENAN_MAPPING VALUES ('170','Sky Customer Service','2000','010#'); 


-- DELETE THE 700 NUMBER
--
DELETE FROM PREFIX_TO_KENAN_MAPPING
 WHERE PREFIX = '700';