-- REMOVE THE DO NOT DISTURB NUMBERS
--
DELETE FROM SERVICE_TO_KENAN_MAPPING
 WHERE SERVICE_TYPE = '39';


-- ADD THE DO NOT DISTURB PREFIXES INTO PREFIX_TO_KENAN_MAPPING
--
INSERT INTO PREFIX_TO_KENAN_MAPPING VALUES ('*70#','Do Not Disturb','2018','044#');

INSERT INTO PREFIX_TO_KENAN_MAPPING VALUES ('#70#','Do Not Disturb','2018','044#');

INSERT INTO PREFIX_TO_KENAN_MAPPING VALUES ('*#70#','Do Not Disturb','2018','044#');
