-- MZITA-79 - Adding in extra fields for supplementary services in the CDR_INPUT_IMS table
--
ALTER TABLE CDR_INPUT_IMS 
ADD
(
  SS_START_DATE_AND_TIME_1      TIMESTAMP(6),
  SS_END_DATE_AND_TIME_1        TIMESTAMP(6),
  SS_SERVICE_ID_1               VARCHAR2(64),
  SS_ASSOCIATED_NUMBER_2        VARCHAR2(128),
  SS_SERVICE_MODE_2             NUMBER,
  SS_SERVICE_TYPE_2             NUMBER,
  SS_SERVICE_ACTION_2           NUMBER,
  SS_START_DATE_AND_TIME_2      TIMESTAMP(6),
  SS_END_DATE_AND_TIME_2        TIMESTAMP(6),
  SS_SERVICE_ID_2               VARCHAR2(64),
  SS_ASSOCIATED_NUMBER_3        VARCHAR2(128),
  SS_SERVICE_MODE_3             NUMBER,
  SS_SERVICE_TYPE_3             NUMBER,
  SS_SERVICE_ACTION_3           NUMBER,
  SS_START_DATE_AND_TIME_3      TIMESTAMP(6),
  SS_END_DATE_AND_TIME_3        TIMESTAMP(6),
  SS_SERVICE_ID_3               VARCHAR2(64)
);
