CREATE TABLE CDR_INPUT_IMS
(
  TRANSACTION_ID                NUMBER	NOT NULL,
  CREATED_DATE                  DATE	DEFAULT sysdate	NOT NULL,
  INPUT_FILENAME                VARCHAR2(80),  
  RECORD_TYPE                   NUMBER,
  NODE_ADDRESS                  VARCHAR2(128),
  CALLING_PARTY                 VARCHAR2(128),
  CALLED_PARTY                  VARCHAR2(128),
  A_NUMBER                      VARCHAR2(30),
  B_NUMBER                      VARCHAR2(30),
  DELIVERY_START                TIMESTAMP(6),
  DELIVERY_END                  TIMESTAMP(6),
  RECORD_OPENING_TIME           TIMESTAMP(6),
  RECORD_CLOSURE_TIME           TIMESTAMP(6),
  DURATION                      NUMBER(22),
  ROLE_OF_NODE                  NUMBER,
  CAUSE_FOR_RECORD_CLOSING      NUMBER,
  LOCAL_REC_SEQ_NUMBER          VARCHAR2(10),
  RECORD_SEQ_NUMBER             NUMBER,
  SESSION_ID                    VARCHAR2(128),
  IMS_CHARGING_ID               VARCHAR2(128),
  INCOMP_CDR_IND_ACRLOST_START  VARCHAR2(1),
  INCOMP_CDR_IND_ACRLOST_INTRM  NUMBER,
  INCOMP_CDR_IND_ACRLOST_STOP   VARCHAR2(1),
  SIP_METHOD                    VARCHAR2(30),
  SRVC_REASON_RTN_CODE          VARCHAR2(10),
  ACCESS_NETWORK_INFORMATION    VARCHAR2(200),
  POS_IN_FILE			NUMBER,
  INCOMING_TRUNK_GRP_ID         VARCHAR2(30),
  OUTGOING_TRUNK_GRP_ID         VARCHAR2(30),
  INCOMING_TRUNK_GRP_NAME       VARCHAR2(50),
  OUTGOING_TRUNK_GRP_NAME       VARCHAR2(50), 
  SUPPLEMENTARY_SERVICE		VARCHAR2(256),
  SS_ASSOCIATED_NUMBER_1	VARCHAR2(128),
  SS_SERVICE_MODE_1		NUMBER,
  SS_SERVICE_TYPE_1		NUMBER,
  SS_SERVICE_ACTION_1		NUMBER
)
SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE MZ_ITA_CDR_DATA  
PARTITION BY RANGE(CREATED_DATE)
(
  PARTITION PMAXVALUE  VALUES LESS THAN (MAXVALUE) TABLESPACE  MZ_ITA_CDR_DATA);

CREATE INDEX CDR_INPUT_IMS_IDX1 ON CDR_INPUT_IMS(A_NUMBER) LOCAL;

CREATE INDEX CDR_INPUT_IMS_IDX2 ON CDR_INPUT_IMS(B_NUMBER) LOCAL;

CREATE INDEX CDR_INPUT_IMS_IDX3 ON CDR_INPUT_IMS(IMS_CHARGING_ID) LOCAL;

INSERT INTO MZ_CONFIGURATION VALUES ('IMS_DUP_BATCH_CHECK', 1);

INSERT INTO MZ_CONFIGURATION VALUES ('IMS_DUP_UDR_CHECK', 1);
