-- Add a table to enable Kenan freephone prefix filtering
--
CREATE TABLE DN_FREEPHONE_PREFIX_CODES
( FREEPHONE_PREFIX_CODE  VARCHAR2(15) NOT NULL
, FREEPHONE_PREFIX_DESC  VARCHAR2(200) NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;


CREATE UNIQUE INDEX DN_FREEPHONE_PREFIX_CODES_PK ON DN_FREEPHONE_PREFIX_CODES
(FREEPHONE_PREFIX_CODE);


ALTER TABLE DN_FREEPHONE_PREFIX_CODES 
ADD CONSTRAINT DN_FREEPHONE_PREFIX_CODES_PK 
PRIMARY KEY (FREEPHONE_PREFIX_CODE);


-- INSERT FREEPHONE PREFIX CODES
--
INSERT INTO DN_FREEPHONE_PREFIX_CODES (FREEPHONE_PREFIX_CODE,
FREEPHONE_PREFIX_DESC) VALUES (
'4011', 'Barring prefix'); 


-- DELETE "42" PREFIX - MZITA-199
--
DELETE FROM PREFIX_TO_KENAN_MAPPING
 WHERE PREFIX = '42';
