-- INSERT NEW VALUES INTO THE SKYIT_IBS_PRODUCT TABLE
--

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O','209800','FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O','209803','FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O','246800','FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O','246803','FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O','207800','FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O','207803','FREE'); 

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O','203800','FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O','203803','FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O','200800','FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O','200803','FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O','201800','FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O','201803','FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O','220800','FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O','220803','FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O','315800','FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O','315803','FREE');
