INSERT INTO MZ_FILTER_REASONS VALUES (0, 'No filtering');

INSERT INTO MZ_FILTER_REASONS VALUES (1, 'Duplicate UDR');

INSERT INTO MZ_FILTER_REASONS VALUES (2, 'Ineffective Call');

INSERT INTO MZ_FILTER_REASONS VALUES (3, 'Freephone 112');

INSERT INTO MZ_FILTER_REASONS VALUES (4, 'Freephone 113');

INSERT INTO MZ_FILTER_REASONS VALUES (5, 'Invalid Duration');

INSERT INTO MZ_FILTER_REASONS VALUES (6, 'Invalid Timestamp');

INSERT INTO MZ_FILTER_REASONS VALUES (7, 'Future Timestamp');

INSERT INTO MZ_FILTER_REASONS VALUES (8, 'Incomplete UDR');

INSERT INTO MZ_FILTER_REASONS VALUES (9, 'Long Call Segment');

INSERT INTO MZ_FILTER_REASONS VALUES (10, 'Event Activation');

INSERT INTO MZ_FILTER_REASONS VALUES (11, 'Event Deactivation');

INSERT INTO MZ_FILTER_REASONS VALUES (12, 'Event Cancel');

INSERT INTO MZ_FILTER_REASONS VALUES (13, 'Event Interrogation');

INSERT INTO MZ_FILTER_REASONS VALUES (14, 'Unrecognised CDR');

INSERT INTO MZ_FILTER_REASONS VALUES (15, 'Freephone Generic');

INSERT INTO MZ_FILTER_REASONS VALUES (16, 'Not Service Invocation');

INSERT INTO MZ_FILTER_REASONS VALUES (17, 'Not Required For Data Retention');
