INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '202800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '205800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '206800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '208800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '210800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '211800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '212800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '213800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '214800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '215800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '216800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '217800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '218800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '219800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '221800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '222800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '223800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '224800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '226800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '227800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '228800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '229800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '231800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '232800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '233800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '234800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '235800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '236800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '237800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '238800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '239800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '240800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '241800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '242800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '243800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '244800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '245800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '247800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '248800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '249800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '250800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '251800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '252800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '253800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '254800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '255800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '256800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '257800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '258800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '259800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '260800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '261800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '262800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '263800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '264800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '265800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '266800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '267800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '268800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '269800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '270800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '271800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '272800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '273800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '274800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '275800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '276800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '277800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '278800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '279800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '280800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '281800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '282800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '283800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '284800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '285800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '286800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '287800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '288800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '289800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '290800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '291800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '292800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '293800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '294800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '295800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '296800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '297800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '298800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '299800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '300800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '301800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '302800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '303800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '304800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '305800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '306800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '307800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '308800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '309800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '310800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '311800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '312800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '313800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '314800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '316800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '317800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '318800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '319800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '321800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '322800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '323800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '324800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '325800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '326800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '327800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '328800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '329800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '330800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '331800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '332800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '333800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '334800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '335800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '336800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '337800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '338800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '339800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '340800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '341800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '342800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '343800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '344800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '345800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '346800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '347800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '348800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '349800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '350800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '351800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '352800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '353800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '354800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '355800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '356800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '357800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '358800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '359800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '360800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '361800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '362800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '363800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '364800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '365800', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '202803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '205803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '206803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '208803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '210803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '211803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '212803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '213803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '214803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '215803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '216803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '217803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '218803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '219803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '221803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '222803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '223803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '224803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '226803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '227803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '228803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '229803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '231803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '232803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '233803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '234803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '235803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '236803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '237803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '238803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '239803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '240803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '241803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '242803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '243803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '244803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '245803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '247803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '248803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '249803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '250803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '251803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '252803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '253803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '254803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '255803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '256803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '257803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '258803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '259803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '260803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '261803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '262803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '263803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '264803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '265803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '266803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '267803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '268803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '269803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '270803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '271803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '272803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '273803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '274803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '275803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '276803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '277803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '278803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '279803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '280803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '281803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '282803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '283803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '284803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '285803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '286803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '287803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '288803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '289803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '290803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '291803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '292803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '293803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '294803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '295803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '296803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '297803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '298803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '299803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '300803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '301803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '302803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '303803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '304803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '305803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '306803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '307803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '308803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '309803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '310803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '311803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '312803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '313803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '314803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '316803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '317803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '318803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '319803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '321803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '322803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '323803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '324803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '325803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '326803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '327803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '328803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '329803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '330803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '331803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '332803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '333803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '334803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '335803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '336803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '337803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '338803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '339803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '340803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '341803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '342803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '343803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '344803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '345803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '346803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '347803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '348803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '349803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '350803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '351803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '352803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '353803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '354803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '355803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '356803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '357803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '358803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '359803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '360803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '361803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '362803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '363803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '364803', 'FREE');

INSERT INTO SKYIT_IBS_PRODUCT VALUES ('O', '365803', 'FREE');
