-- MZITA-240.A_NUM_TYPE / B_NUM_TYPE formatting rules for IBCF and PCSCF. 
INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('GEO','112'); 
INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('GEO','113'); 