-- MZITA-240.A_NUM_TYPE / B_NUM_TYPE formatting rules for IBCF and PCSCF. 
INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('CC-DI','146'); 
-- THIS REMOVE ENTRY WAS REQUESTED BY RICARDO
DELETE FROM SKYIT_DL_NUMBER_DETAIL_PREFIX WHERE ROUTE_TYPE = 'CC-DI' AND NUMB_PREFIX = '1920';