-- MZITA-255 - MZ - SKY new customer care number 141
--
INSERT INTO PREFIX_TO_KENAN_MAPPING VALUES ('141','Sky Customer Service','2000','010#'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('CCSKY','141');