-- Create the numbering detail prefix table
--
CREATE TABLE SKYIT_DL_NUMBER_DETAIL_PREFIX
(
  ROUTE_TYPE  varchar2(10) NOT NULL,
  NUMB_PREFIX varchar2(10) NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;

-- INSERT INTO THE SKYIT_DL_NUMBER_DETAIL_PREFIX TABLE
--
-- MOB -- 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','311'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','313'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','319'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','320'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','3211'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','3212'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','3213'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','3214');

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','3215'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','3216');
 
INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','323'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','324'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','327'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','328'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','329'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','330'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','331'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','333'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','334'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','335'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','336'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','337'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','338'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','339'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','340'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','342'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','343'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','344'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','345'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','346'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','347'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','348'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','349'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','3500'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','3501'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','3505'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','3510'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','3511'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','3512');
 
INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','3515'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','3516'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','3517'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','3518'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','3519'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','3533'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','3534'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','355'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','360'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','363'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','366'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','368'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','370'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','37'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','380'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','383'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','385'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','388'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','389'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','390'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','391'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','392'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('MOB','393'); 

-- NUE 
-- 112, 113, 114, 115, 118

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('NUE','112'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('NUE','113'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('NUE','114'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('NUE','115'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('NUE','118'); 

-- GEO (Emergency, Utility)

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('GEO','114'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('GEO','115'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('GEO','117'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('GEO','118'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('GEO','1500'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('GEO','1515'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('GEO','1518'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('GEO','1522'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('GEO','1525'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('GEO','1530'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('GEO','1533'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('GEO','1544'); 

-- GEO (Harmonised European numbers)

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('GEO','116000'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('GEO','116006'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('GEO','116111'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('GEO','116117'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('GEO','116123'); 

-- CCSKY (Customer care SKY)

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('CCSKY','170'); 

-- CC-DI
--X, XY, 119, 187, 191, 130, 133, 139, 145, 155,156,158,159, 180,190, 193, 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('CC-DI','192'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('CC-DI','1920'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('CC-DI','119'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('CC-DI','187'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('CC-DI','191'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('CC-DI','130'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('CC-DI','133'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('CC-DI','139'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('CC-DI','145'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('CC-DI','155'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('CC-DI','156'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('CC-DI','158'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('CC-DI','159'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('CC-DI','180'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('CC-DI','190'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('CC-DI','193'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('CC-DI','177'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('CC-DI','181'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('CC-DI','188'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('CC-DI','195'); 

-- (Directory enquiry (12XY))

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('CC-DI','1240'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('CC-DI','1248'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('CC-DI','1250'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('CC-DI','1254'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('CC-DI','1255'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('CC-DI','1256'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('CC-DI','1280'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('CC-DI','1288'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('CC-DI','1289'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('CC-DI','1290'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('CC-DI','1299'); 

-- OPE Personal numbers
-- 199*******, 178*****

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('OPE','199'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('OPE','178'); 

-- D4 Internal Network services
INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('D4','40'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('D4','41'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('D4','42'); 

-- OTHER Charity/Party donations 455XY 499XYZ

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('OTHER','455'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('OTHER','499'); 

-- NOM 
INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('NOM','55'); 

-- OPE (Freephone - Numeri Verdi)	800*****, 803***
INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('OPE','800'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('OPE','803'); 

-- OPE
-- (“Addebito ripartito”)	840*****, 841*****, 847*****, 848*****

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('OPE','840'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('OPE','841'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('OPE','847'); 

INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('OPE','848'); 

-- OPE (Premium Numbers)	89*******
INSERT INTO SKYIT_DL_NUMBER_DETAIL_PREFIX VALUES ('OPE','89'); 


