-- MZMOB-391 - Create new Index on BC_SUB_IDEN to match the BU_LOOKUP update process query clause
-- 
CREATE INDEX BC_SUB_IDEN_IDX4 ON BC_SUB_IDEN (PERIOD_END_DATE DESC, EFF_DATE ASC, EXP_DATE DESC, SUB_IDEN_TYPE ASC, SUB_IDENTITY ASC);
CREATE INDEX BC_SUB_IDEN_IDX5 ON BC_SUB_IDEN (PERIOD_END_DATE DESC);
CREATE INDEX BC_SUBSCRIBER_IDX3 ON BC_SUBSCRIBER (TP_SUB_KEY ASC);
