-- MZMOB-405 - Add new columns into CDR_INPUT_PGW and CDR_INPUT_TAP tables
--
ALTER TABLE CDR_INPUT_PGW
  ADD AF_CHARGING_ID_1 VARCHAR2(128);

ALTER TABLE CDR_INPUT_PGW
  ADD AF_CHARGING_ID_2 VARCHAR2(128);
  
ALTER TABLE CDR_INPUT_PGW
  ADD AF_CHARGING_ID_3 VARCHAR2(128);
  
ALTER TABLE CDR_INPUT_PGW
  ADD AF_CHARGING_ID_4 VARCHAR2(128);
  
ALTER TABLE CDR_INPUT_PGW
  ADD AF_CHARGING_ID_5 VARCHAR2(128);
  
ALTER TABLE CDR_INPUT_PGW
  ADD AF_CHARGING_ID_6 VARCHAR2(128);
  
ALTER TABLE CDR_INPUT_PGW
  ADD AF_CHARGING_ID_7 VARCHAR2(128);
  
ALTER TABLE CDR_INPUT_PGW
  ADD AF_CHARGING_ID_8 VARCHAR2(128);
  
ALTER TABLE CDR_INPUT_PGW
  ADD AF_CHARGING_ID_9 VARCHAR2(128);
  
ALTER TABLE CDR_INPUT_PGW
  ADD AF_CHARGING_ID_10 VARCHAR2(128);  

  
