--  Insert Initial Data set as defined in document
--  Huawei OCS Mediation Functions - Requirement Specifications v0.31 draft.doc
--  by Peter Ho
--  Created: 7th August 2018, MZMOB-430/461 [BK]
--
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('OAA00','ARETH','88255550','In Flight','882','Satellite numbers','Over the air','Thuraya','901','05','882161987651','882161987651',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('OAA00','ARETH','88255550','In Flight','882','Satellite numbers','Over the air','Thuraya','901','05','882161987661','882161987661',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('OAB00','NORAM','88255551','In Flight','882','Satellite numbers','Over the air','AeroMobile','901','14','88299100999','88299100999',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('OAB00','NORAM','88255551','In Flight','882','Satellite numbers','Over the air','AeroMobile','901','14','88299101999','88299101999',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('OAB00','NORAM','88255551','In Flight','882','Satellite numbers','Over the air','AeroMobile','901','14','88299102000','88299102000',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('OAB00','NORAM','88255551','In Flight','882','Satellite numbers','Over the air','AeroMobile','901','14','88299102001','88299102001',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('OAC00','CHEOA','88255552','In Flight','882','Satellite numbers','Over the air','OnAir','901','15','8829800201','8829800201',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('OAC00','CHEOA','88255552','In Flight','882','Satellite numbers','Over the air','OnAir','901','15','8829800204','8829800204',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('OAC00','CHEOA','88255552','In Flight','882','Satellite numbers','Over the air','OnAir','901','15','8829800301','8829800301',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('OAC00','CHEOA','88255552','In Flight','882','Satellite numbers','Over the air','OnAir','901','15','8829800304','8829800304',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('OSA00','NORMC','88266660','At Sea','882','Satellite numbers','Over the sea','MCP','901','12','882322000999','882322000999',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('OSA00','NORMC','88266660','At Sea','882','Satellite numbers','Over the sea','MCP','901','12','882322001999','882322001999',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('OSA00','NORMC','88266660','At Sea','882','Satellite numbers','Over the sea','MCP','901','12','882323001999','882323001999',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('OSB00','AAMOW','88266661','At Sea','354','Iceland','Over the sea','Siminn On-Waves Oceancell','274','08','3548900071','3548900071',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('OSB00','AAMOW','88266661','At Sea','354','Iceland','Over the sea','Siminn On-Waves Oceancell','274','08','3548900021','3548900021',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('OSB00','AAMOW','88266661','At Sea','354','Iceland','Over the sea','Siminn On-Waves Oceancell','274','08','3548900070','3548900070',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('OSC00','BMU01','88266662','At Sea','1360','USA','Over the sea','Telecom','901','18','13603399617','13603399617',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('OSC00','BMU01','88266662','At Sea','1360','USA','Over the sea','Telecom','901','18','13603399627','13603399627',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('OSC00','BMU01','88266662','At Sea','1360','USA','Over the sea','Telecom','901','18','13603399634','13603399634',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('OSC00','BMU01','88266662','At Sea','1360','USA','Over the sea','Telecom','901','18','13603399631','13603399631',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('OSC00','BMU01','88266662','At Sea','1360','USA','Over the sea','Telecom','901','18','13603399632','13603399632',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('OSC00','BMU01','88266662','At Sea','1360','USA','Over the sea','Telecom','901','18','13603399633','13603399633',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('OSC00','BMU01','88266662','At Sea','1360','USA','Over the sea','Telecom','901','18','13603399610','13603399610',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('OSD00','ITAGT','88266663','At Sea','39','Italy','Over the sea','Telecom Italia','901','26','393358817821','393358817821',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('OSE00','MLTMA','88266664','At Sea','356','Malta','Over the sea','Vodafone Malta Maritime','901','19','35699830928','35699830928',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('OSE00','MLTMA','88266664','At Sea','356','Malta','Over the sea','Vodafone Malta Maritime','901','19','35699830929','35699830929',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('FWA00','FRAF4','59600000','French West Indies','596','Martinique','French Guiana','Digicel Antilles Française Guyane','340','20','596696900137','596696900137',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('FWA00','FRAF4','59600000','French West Indies','596','Martinique','French West Indies','Digicel Antilles Française Guyane','340','20','596696900138','596696900138',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('FWA00','FRAF4','59600000','French West Indies','596','Martinique','Martinique','Digicel Antilles Française Guyane','340','20','596696900001','596696900001',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('FWA00','FRAF4','59600000','French West Indies','596','Martinique','Guadeloupe','Digicel Antilles Française Guyane','340','20','596696900003','596696900003',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('FWA00','FRAF4','59600000','French West Indies','596','Martinique','French Guiana','Digicel Antilles Française Guyane','340','20','596696900004','596696900004',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('FWA00','FRAF4','59600000','French West Indies','596','Martinique','Guadeloupe','Digicel Antilles Française Guyane','340','20','596696900160','596696900160',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('FWA00','FRAF4','59600000','French West Indies','596','Martinique','Martinique','Digicel Antilles Française Guyane','340','20','596696900260','596696900260',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('FWA00','FRAF4','59600000','French West Indies','596','Martinique','Martinique','Digicel Antilles Française Guyane','340','20','596696900360','596696900360',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('FTA00','FRARE','26200001','French Territories in the Indian Ocean','262','Reunion','Mayotte','SFR','647','10','262850221','262850221',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('FTA00','FRARE','26200001','French Territories in the Indian Ocean','262','Reunion','Mayotte','SFR','647','10','262850220','262850220',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('FTA00','FRARE','26200001','French Territories in the Indian Ocean','262','Reunion','Reunion','SFR','647','10','262850321','262850321',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('FTA00','FRARE','26200001','French Territories in the Indian Ocean','262','Reunion','Reunion','SFR','647','10','262850121','262850121',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('FTA00','FRARE','26200001','French Territories in the Indian Ocean','262','Reunion','Reunion','SFR','647','10','262850320','262850320',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('FTA00','FRARE','26200001','French Territories in the Indian Ocean','262','Reunion','Reunion','SFR','647','10','262850120','262850120',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('FWB00','GLP01','59600001','French West Indies','590','Guadeloupe','French Guiana','Orange Caraïbe','340','1','590690350000','590690350099',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('FWB00','GLP01','59600001','French West Indies','590','Guadeloupe','French West Indies','Orange Caraïbe','340','01','590690350000','590690350099',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('FWB00','GLP01','59600001','French West Indies','590','Guadeloupe','Guadeloupe','Orange Caraïbe','340','01','590690350000','590690350099',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('FWB00','GLP01','59600001','French West Indies','596','Martinique','Martinique','Orange Caraïbe','340','01','596696450000','596696450099',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('FWB00','GLP01','59600001','French West Indies','596','Martinique','Saint Barthelemy','Orange Caraïbe','340','01','596696450000','596696450099',sysdate,'Comfone', 'InitialTableLoad');
insert into MZ_MOB_DATA_OWNER.GSMA_NETWORK_EXCEPTIONS (ALIAS_TADIG, TADIG, DummyCountryCode, DummyCountry, CC, CountryFromOCS, NetworkCountry, NetworkName, MCC, MNC, VLR_Address_Range_From, VLR_Address_Range_To, EFF_DATE, PROVIDER, INPUT_FILENAME) values ('FWB00','GLP01','59600001','French West Indies','596','Martinique','Saint Martin','Orange Caraïbe','340','01','596696450000','596696450099',sysdate,'Comfone', 'InitialTableLoad');
