-- MZMOB-463 - Create an index on the TRANSACTION_ID in the CDR_INPUT_MMSC table
--
CREATE INDEX CDR_INPUT_MMSC_IDX3 ON CDR_INPUT_MMSC (TRANSACTION_ID) PARALLEL 16;

ALTER INDEX CDR_INPUT_MMSC_IDX3 NOPARALLEL;


-- MZMOB-463 - Create an index on the TRANSACTION_ID in the CDR_INPUT_OCS_MMS table
--
CREATE INDEX CDR_INPUT_OCS_MMS_IDX3 ON CDR_INPUT_OCS_MMS (TRANSACTION_ID) PARALLEL 16;

ALTER INDEX CDR_INPUT_OCS_MMS_IDX3 NOPARALLEL;


-- MZMOB-463 - Create an index on the TRANSACTION_ID in the CDR_INPUT_OCS_MON table
--
CREATE INDEX CDR_INPUT_OCS_MON_IDX2 ON CDR_INPUT_OCS_MON (TRANSACTION_ID) PARALLEL 16;

ALTER INDEX CDR_INPUT_OCS_MON_IDX2 NOPARALLEL;


-- MZMOB-463 - Create an index on the TRANSACTION_ID in the CDR_INPUT_SMSC table
--
CREATE INDEX CDR_INPUT_SMSC_IDX4 ON CDR_INPUT_SMSC (TRANSACTION_ID) LOCAL PARALLEL 16;

ALTER INDEX CDR_INPUT_SMSC_IDX4 NOPARALLEL;


-- MZMOB-463 - Create an index on the TRANSACTION_ID in the CDR_OUTPUT_KENAN_GPRS table
--
CREATE INDEX CDR_OUTPUT_KENAN_GPRS_IDX3 ON CDR_OUTPUT_KENAN_GPRS (TRANSACTION_ID) LOCAL PARALLEL 16;

ALTER INDEX CDR_OUTPUT_KENAN_GPRS_IDX3 NOPARALLEL;


-- MZMOB-463 - Create an index on the TRANSACTION_ID in the CDR_INPUT_PGW table
--
CREATE INDEX CDR_INPUT_PGW_IDX3 ON CDR_INPUT_PGW (TRANSACTION_ID) LOCAL PARALLEL 16;

ALTER INDEX CDR_INPUT_PGW_IDX3 NOPARALLEL;
