-- MZMOB-464 - Recreate indexes in the CDR_INPUT_SMSC table
--
DROP INDEX CDR_INPUT_SMSC_IDX1;
 
DROP INDEX CDR_INPUT_SMSC_IDX2;
 
CREATE INDEX CDR_INPUT_SMSC_IDX1 ON CDR_INPUT_SMSC (ORIGINAL_ADDRESS) LOCAL PARALLEL 16;
 
CREATE INDEX CDR_INPUT_SMSC_IDX2 ON CDR_INPUT_SMSC (DESTINATION_DELIVERY_ADDRESS) LOCAL PARALLEL 16;
 
ALTER INDEX CDR_INPUT_SMSC_IDX1 NOPARALLEL;
 
ALTER INDEX CDR_INPUT_SMSC_IDX2 NOPARALLEL;


-- MZMOB-464 - Recreate the indexes in the CDR_INPUT_PGW table
--
DROP INDEX CDR_INPUT_PGW_IDX1;

CREATE INDEX CDR_INPUT_PGW_IDX1 ON CDR_INPUT_PGW (MSISDN) LOCAL PARALLEL 16;

ALTER INDEX CDR_INPUT_PGW_IDX1 NOPARALLEL;
