-- Changes required for MZ 6.1 to MZ 6.3 upgrade
--
CREATE INDEX default_dupbatch_txn_idx ON DEFAULT_DUPBATCH(TXN);

ALTER TABLE CONFIGURATION_DATA ADD is_dirty number(1) DEFAULT 0 NOT NULL;

ALTER TABLE CONFIGURATION_FOLDER DROP CONSTRAINT fk_cf_owner;

ALTER TABLE CONFIGURATION_DATA DROP CONSTRAINT fk_cd_owner;
