-- MZMOB-568 Add enhanced filtering logic for TAP emergency numbers
INSERT INTO MZ_MOB_DATA_OWNER.DN_FREEPHONE_PREFIX_CODES_TAP (FREEPHONE_PREFIX_CODE, FREEPHONE_PREFIX_DESC) VALUES ('112', 'Emergency Services');
INSERT INTO MZ_MOB_DATA_OWNER.DN_FREEPHONE_PREFIX_CODES_TAP (FREEPHONE_PREFIX_CODE, FREEPHONE_PREFIX_DESC) VALUES ('999', 'Emergency Services');