--MZMOB-716 - INSERTION of new OFFERING_IDs into OCS_MON_OFFERING_LOOKUP table

INSERT INTO OCS_MON_OFFERING_LOOKUP (OFFERING_ID, DESCRIPTION, TIMEZONE) values ('13973','Roaming Charge For EU_EEA','Europe/EEA');
UPDATE OCS_MON_OFFERING_LOOKUP SET OFFERING_ID = '13974' WHERE DESCRIPTION = 'Roaming Charge For UAE';