-- 2023-12-28.AMG.MZMOB-875.[ROI - TAP] Open ROI TAP issues. Issue 1

delete from MZ_MOB_DATA_OWNER.DN_FREEPHONE_PREFIX_CODES_TAP_ROI where FREEPHONE_PREFIX_CODE  <> '00800';

INSERT INTO MZ_MOB_DATA_OWNER.DN_FREEPHONE_PREFIX_CODES_TAP_ROI (FREEPHONE_PREFIX_CODE, FREEPHONE_PREFIX_DESC) VALUES ('+800', 'Freephone Prefix');
INSERT INTO MZ_MOB_DATA_OWNER.DN_FREEPHONE_PREFIX_CODES_TAP_ROI (FREEPHONE_PREFIX_CODE, FREEPHONE_PREFIX_DESC) VALUES ('999', 'Emergency Services');
INSERT INTO MZ_MOB_DATA_OWNER.DN_FREEPHONE_PREFIX_CODES_TAP_ROI (FREEPHONE_PREFIX_CODE, FREEPHONE_PREFIX_DESC) VALUES ('112', 'Emergency Services');
INSERT INTO MZ_MOB_DATA_OWNER.DN_FREEPHONE_PREFIX_CODES_TAP_ROI (FREEPHONE_PREFIX_CODE, FREEPHONE_PREFIX_DESC) VALUES ('911', 'Emergency Services');


