-- MZMOB-875. [ROI - TAP] Open ROI TAP issues

-- Add the 'ZWEN1' TADIG filter from UK
create table MZ_MOB_DATA_OWNER.TAP_FILTER_NETWORK_TADIG_ROI (
    TADIG	VARCHAR2(5) NOT NULL
);

-- Initial inserts
INSERT INTO MZ_MOB_DATA_OWNER.TAP_FILTER_NETWORK_TADIG_ROI (TADIG) VALUES ('ZWEN1');