-- MZMOB-248 Deployment for Construction of DN_ENHANCED_BU_LOOKUP table
-- Author: B Knowles 
-- Date: 16th November 2016

-- Create DN_ENHANCED_BU_LOOKUP table
--

-- DROP TABLE DN_ENHANCED_BU_LOOKUP CASCADE CONSTRAINTS; commented out.. 2016-12-02. [amg]
CREATE TABLE DN_ENHANCED_BU_LOOKUP
(
	DIRECTORY_NUMBER  VARCHAR2(40) NOT NULL,
	UNIT_ID           NUMBER(8) NOT NULL,
	START_DATE        DATE,
	SKCI_FLAG         NUMBER(8),
	CEASE_DATE        DATE,
	CKCI_FLAG         NUMBER(8)
);


CREATE UNIQUE INDEX DN_ENHANCED_BU_LOOKUP_PK  ON DN_ENHANCED_BU_LOOKUP (DIRECTORY_NUMBER, UNIT_ID);
CREATE        INDEX DN_ENHANCED_BU_LOOKUP_FK1 ON DN_ENHANCED_BU_LOOKUP (UNIT_ID);
ALTER TABLE DN_ENHANCED_BU_LOOKUP ADD CONSTRAINT DN_ENHANCED_BU_LOOKUP_PK PRIMARY KEY (DIRECTORY_NUMBER, UNIT_ID);
ALTER TABLE DN_ENHANCED_BU_LOOKUP ADD CONSTRAINT DN_ENHANCED_BU_LOOKUP_FK1 FOREIGN KEY (UNIT_ID) REFERENCES BUSINESS_UNITS (UNIT_ID) ENABLE;

-- Update the BUSINESS_UNITS table and set the UNIT_ID to 12. 
-- Current value is 1 but overlaps with values used in the Landline
-- solution. 12 is the next availble value across both domains.
--

UPDATE BUSINESS_UNITS set UNIT_ID = 12 where UNIT_ID = 1;
