CREATE SEQUENCE LIC_LOG_ID
  START WITH 1
  MAXVALUE 999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE SEQUENCE SEQ_ARCHIVE_ENTRY_ID
  START WITH 1
  MAXVALUE 999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE SEQUENCE SEQ_CS_BUNDLE_ARCHIVE_ID
  START WITH 1
  MAXVALUE 999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE SEQUENCE SEQ_CS_BUNDLE_ID
  START WITH 1
  MAXVALUE 999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE SEQUENCE SEQ_ECS_GROUP
  START WITH 1
  MAXVALUE 999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE SEQUENCE SEQ_ECS_STAT
  START WITH 1
  MAXVALUE 999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE SEQUENCE SEQ_ECS_UDR
  START WITH 1
  MAXVALUE 999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE SEQUENCE SEQ_HOST_STAT
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE SEQUENCE SEQ_SYSTEM_LOG_ID
  START WITH 1
  MAXVALUE 999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE SEQUENCE SEQ_TXN_STATUS_ID
  START WITH 1
  MAXVALUE 999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

CREATE TABLE ULTRA_DATA
(
  TYPE   VARCHAR2(256 BYTE),
  VALUE  BLOB
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE ECS_STAT_ENTRY
(
  STAT_ID       NUMBER(6),
  ERROR_CODE    VARCHAR2(64 BYTE),
  COUNT_NEW     NUMBER(9),
  COUNT_RP      NUMBER(9),
  NEWEST_ENTRY  DATE,
  OLDEST_ENTRY  DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE ECS_STAT
(
  ID         NUMBER(6),
  STAT_DATE  DATE,
  DATATYPE   VARCHAR2(20 BYTE),
  COUNT_NEW  NUMBER(9),
  COUNT_RP   NUMBER(9)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE ECS_BATCH_ERROR
(
  TXN_ID        NUMBER(12),
  ERROR_CODE    VARCHAR2(64 BYTE),
  COMPLETE_MSG  VARCHAR2(256 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE ECS_UDR_ERROR
(
  ECS_UDR_ID    NUMBER(12),
  ERROR_CODE    VARCHAR2(64 BYTE),
  COMPLETE_MSG  VARCHAR2(256 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE ECS_MIM
(
  TXN_ID        NUMBER(12),
  WF_NODE_NAME  VARCHAR2(128 BYTE),
  DATATYPE      NUMBER(1),
  NAME          VARCHAR2(128 BYTE),
  VALUE         VARCHAR2(256 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE ECS_BATCH
(
  TXN_ID          NUMBER(12),
  STATE           NUMBER(1),
  WF_NAME         VARCHAR2(128 BYTE),
  WF_NODE_NAME    VARCHAR2(128 BYTE),
  MESSAGE         VARCHAR2(1024 BYTE),
  INSERT_TIME     DATE                          DEFAULT SYSDATE,
  SOURCE_NODE     VARCHAR2(128 BYTE),
  ERRORUDR        BLOB,
  ERROR_UDR_TYPE  VARCHAR2(256 BYTE),
  FILELENGTH      NUMBER(12),
  GROUP_ID        NUMBER(5)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE ECS_UDR
(
  ID            NUMBER(12),
  TXN_ID        NUMBER(12),
  STATE         NUMBER(1),
  WF_NAME       VARCHAR2(128 BYTE),
  WF_NODE_NAME  VARCHAR2(128 BYTE),
  INSERT_TIME   DATE                            DEFAULT SYSDATE,
  UDR_TYPE      VARCHAR2(256 BYTE),
  GROUP_ID      NUMBER(5),
  OFFSET        NUMBER(9),
  LENGTH        NUMBER(9)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE ECS_FILE
(
  TXN_ID    NUMBER(12),
  TXN_SAFE  NUMBER(1)                           DEFAULT 0,
  FILENAME  VARCHAR2(256 BYTE),
  DATATYPE  NUMBER(1)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE ECS_ERROR_CODE
(
  ERROR_CODE       VARCHAR2(64 BYTE),
  DESCRIPTION      VARCHAR2(256 BYTE),
  REPROCESS_GROUP  NUMBER(5),
  IS_SYSTEM_CODE   NUMBER(1)
)
LOGGING 
NOCOMPRESS 
CACHE
NOPARALLEL
MONITORING;


CREATE TABLE ECS_GROUP
(
  ID              NUMBER(5),
  GROUP_NAME      VARCHAR2(64 BYTE),
  COLLECTOR_WF    VARCHAR2(128 BYTE),
  COLLECTOR_NAME  VARCHAR2(128 BYTE),
  DATATYPE        NUMBER(1),
  UDR_TYPE        VARCHAR2(256 BYTE),
  STATE           NUMBER(1)
)
LOGGING 
NOCOMPRESS 
CACHE
NOPARALLEL
MONITORING;


CREATE TABLE DEFAULT_DUPBATCH
(
  ID           NUMBER,
  TIMESTAMP    DATE,
  CRC          NUMBER,
  LOGGED_MIMS  VARCHAR2(512 BYTE),
  TXN_SAFE     NUMBER(1)                        DEFAULT 0,
  PROFILE      VARCHAR2(64 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE DBAGENT_PENDING_TXN
(
  TXN_ID            NUMBER(12),
  SYSTEM_NAME       VARCHAR2(64 BYTE),
  WF_INSTANCE_NAME  VARCHAR2(128 BYTE),
  AGENT_ID          NUMBER(12),
  DB_TABLE_SCHEMA   VARCHAR2(128 BYTE),
  DB_TABLE_NAME     VARCHAR2(128 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE ARCHIVE_MIMS
(
  ENTRY_ID  NUMBER,
  NAME      VARCHAR2(256 BYTE),
  VALUE     VARCHAR2(256 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE ARCHIVE_ENTRIES
(
  ENTRY_ID          NUMBER,
  TXN_ID            NUMBER,
  PROFILE_ID        VARCHAR2(64 BYTE),
  PENDING_FILENAME  VARCHAR2(1024 BYTE),
  FINAL_FILENAME    VARCHAR2(1024 BYTE),
  COMPRESSION       NUMBER,
  TIMESTAMP         DATE,
  WF_INSTANCE_NAME  VARCHAR2(128 BYTE),
  WF_NODE_NAME      VARCHAR2(128 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE LIC_LOG
(
  ID        NUMBER(12),
  CONTENTS  BLOB
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE LIC_HEADER
(
  ID        NUMBER(12),
  CONTENTS  BLOB
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE WF_STAT
(
  HOST_STAT_ID      NUMBER(9),
  CLIENT_NAME       VARCHAR2(64 BYTE),
  WF_NAME           VARCHAR2(128 BYTE),
  DATA_COUNTER_AVR  NUMBER(19),
  DATA_COUNTER_MIN  NUMBER(19),
  DATA_COUNTER_MAX  NUMBER(19)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TASK_STAT
(
  HOST_STAT_ID  NUMBER(9),
  CLIENT_NAME   VARCHAR2(64 BYTE),
  TASK_NAME     VARCHAR2(64 BYTE),
  START_TIME    DATE,
  STOP_TIME     DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE PICO_CLIENT_STAT
(
  HOST_STAT_ID      NUMBER(9),
  CLIENT_NAME       VARCHAR2(64 BYTE),
  AVAILABLE_MEM     NUMBER(12),
  USED_MEM_AVR      NUMBER(12),
  USED_MEM_MIN      NUMBER(12),
  USED_MEM_MAX      NUMBER(12),
  GC_TIME_AVR       NUMBER(9),
  GC_TIME_MIN       NUMBER(9),
  GC_TIME_MAX       NUMBER(9),
  GC_COUNT_AVR      NUMBER(9),
  GC_COUNT_MIN      NUMBER(9),
  GC_COUNT_MAX      NUMBER(9),
  THREAD_COUNT_AVR  NUMBER(9),
  THREAD_COUNT_MIN  NUMBER(9),
  THREAD_COUNT_MAX  NUMBER(9)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE HOST_STAT
(
  ID                            NUMBER(9),
  STAT_DATE                     DATE,
  RESOLUTION                    VARCHAR2(12 BYTE),
  HOST_NAME                     VARCHAR2(64 BYTE),
  WAIT_PROC_AVR                 NUMBER(10),
  WAIT_PROC_MIN                 NUMBER(10),
  WAIT_PROC_MAX                 NUMBER(10),
  SLEEP_PROC_AVR                NUMBER(10),
  SLEEP_PROC_MIN                NUMBER(10),
  SLEEP_PROC_MAX                NUMBER(10),
  SWAP_PROC_AVR                 NUMBER(10),
  SWAP_PROC_MIN                 NUMBER(10),
  SWAP_PROC_MAX                 NUMBER(10),
  FROM_DISK_SWAP_PER_SEC_AVR    NUMBER(10),
  FROM_DISK_SWAP_PER_SEC_MIN    NUMBER(10),
  FROM_DISK_SWAP_PER_SEC_MAX    NUMBER(10),
  TO_DISK_SWAP_PER_SEC_AVR      NUMBER(10),
  TO_DISK_SWAP_PER_SEC_MIN      NUMBER(10),
  TO_DISK_SWAP_PER_SEC_MAX      NUMBER(10),
  CONTEXT_SWITCHES_PER_SEC_AVR  NUMBER(10),
  CONTEXT_SWITCHES_PER_SEC_MIN  NUMBER(10),
  CONTEXT_SWITCHES_PER_SEC_MAX  NUMBER(10),
  USER_TIME_CPU_AVR             NUMBER(3),
  USER_TIME_CPU_MIN             NUMBER(3),
  USER_TIME_CPU_MAX             NUMBER(3),
  SYS_TIME_CPU_AVR              NUMBER(3),
  SYS_TIME_CPU_MIN              NUMBER(3),
  SYS_TIME_CPU_MAX              NUMBER(3)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MZ_REFERENCE
(
  ORIG_OBJ_ID      VARCHAR2(256 BYTE),
  DEST_OBJ_ID      VARCHAR2(256 BYTE),
  DEST_MODIFIABLE  NUMBER(1)                    DEFAULT 1
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE USER_DEFINED_EVENT
(
  NAME  VARCHAR2(64 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TM_TASK
(
  NAME                 VARCHAR2(64 BYTE),
  EXECUTOR_CLASS_NAME  VARCHAR2(256 BYTE),
  EXECUTOR_CONFIG      CLOB,
  SCHEDULE             CLOB,
  STATUS               NUMBER(2),
  LAST_EXEC            DATE,
  EXEC_REPORT          VARCHAR2(2000 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TXN_STATUS
(
  ID      NUMBER(12),
  NAME    VARCHAR2(128 BYTE),
  STATUS  NUMBER(2)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE WF_TXN
(
  TXN_ID          NUMBER(12),
  INSTANCE_STATE  BLOB,
  INSTANCE_NAME   VARCHAR2(128 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE SYSTEM_LOG_NESTED
(
  SYSTEM_LOG_ID  NUMBER(12),
  NESTED_IDX     NUMBER(2),
  MESSAGE        VARCHAR2(4000 BYTE),
  STACKTRACE     VARCHAR2(3000 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE SYSTEM_LOG
(
  ID                  NUMBER(12),
  SEVERITY_TYPE       NUMBER(1),
  LOG_TYPE            NUMBER(1),
  WF_INSTANCE_NAME    VARCHAR2(128 BYTE),
  WF_NODE_NAME        VARCHAR2(128 BYTE),
  IP_ADDRESS          VARCHAR2(64 BYTE),
  PICO_NAME           VARCHAR2(64 BYTE),
  SHORT_MESSAGE       VARCHAR2(128 BYTE),
  MESSAGE             VARCHAR2(4000 BYTE),
  STACKTRACE          VARCHAR2(3000 BYTE),
  CREATION_TIME       DATE                      DEFAULT SYSDATE,
  LATEST_OCCURRENCE   DATE                      DEFAULT SYSDATE,
  OCCURRENCE_COUNTER  NUMBER(10)                DEFAULT 1,
  USER_NAME           VARCHAR2(64 BYTE),
  STACKTRACE_HASH     NUMBER(20)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MIM_GROUP
(
  NAME  VARCHAR2(128 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CS_BUNDLE_RESOURCE
(
  NAME        VARCHAR2(128 BYTE),
  ARCHIVE_ID  NUMBER(12)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CS_BUNDLE_INHERITANCE
(
  CLASSNAME       VARCHAR2(128 BYTE),
  SUPERCLASSNAME  VARCHAR2(128 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CS_BUNDLE_CLASS
(
  NAME        VARCHAR2(128 BYTE),
  ARCHIVE_ID  NUMBER(12)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CS_BUNDLE_ARCHIVE
(
  ID             NUMBER(12),
  BUNDLE_NAME    VARCHAR2(64 BYTE),
  CODE_LEVEL     NUMBER(2),
  CREATION_DATE  DATE                           DEFAULT SYSDATE,
  ORIG_FILENAME  VARCHAR2(128 BYTE),
  FILE_LENGTH    NUMBER(9),
  CONTENTS       BLOB
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CS_BUNDLE
(
  ID            NUMBER(12),
  PACKAGE_NAME  VARCHAR2(64 BYTE),
  NAME          VARCHAR2(64 BYTE),
  VERSION       VARCHAR2(20 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CS_PACKAGE
(
  NAME           VARCHAR2(64 BYTE),
  VERSION        VARCHAR2(20 BYTE),
  CUSTOMER       VARCHAR2(64 BYTE),
  CREATION_DATE  DATE                           DEFAULT SYSDATE,
  AUTHOR         VARCHAR2(64 BYTE),
  METADATA       VARCHAR2(128 BYTE),
  RUNTIME        NUMBER(1)                      DEFAULT 0
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CONFIGURATION_HISTORY
(
  CONFIG_KEY     VARCHAR2(64 BYTE),
  CONFIG_NAME    VARCHAR2(64 BYTE),
  CONFIG_TYPE    VARCHAR2(64 BYTE),
  FOLDER_NAME    VARCHAR2(64 BYTE),
  VERSION        NUMBER(5),
  OWNER          VARCHAR2(64 BYTE),
  MODIFIED_BY    VARCHAR2(64 BYTE),
  MODIFIED_DATE  DATE,
  IS_ENCRYPTED   NUMBER(1),
  COMMENTS       VARCHAR2(2000 BYTE),
  AUX_DATA       VARCHAR2(256 BYTE),
  DATA           CLOB
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CONFIGURATION_DATA
(
  CONFIG_KEY     VARCHAR2(64 BYTE),
  CONFIG_NAME    VARCHAR2(64 BYTE),
  CONFIG_TYPE    VARCHAR2(64 BYTE),
  FOLDER_NAME    VARCHAR2(64 BYTE),
  VERSION        NUMBER(5),
  OWNER          VARCHAR2(64 BYTE),
  MODIFIED_BY    VARCHAR2(64 BYTE),
  MODIFIED_DATE  DATE,
  ACCESS_GROUPS  VARCHAR2(256 BYTE),
  IS_VALID       NUMBER(1)                      DEFAULT 1,
  IS_ENCRYPTED   NUMBER(1),
  AUX_DATA       VARCHAR2(256 BYTE),
  DATA           CLOB
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CONFIGURATION_FOLDER
(
  FOLDER_NAME  VARCHAR2(64 BYTE),
  OWNER        VARCHAR2(64 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE USER_GROUP
(
  USERNAME    VARCHAR2(64 BYTE),
  GROUP_NAME  VARCHAR2(64 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE APPLICATION_DATA
(
  APP_TYPE      VARCHAR2(64 BYTE),
  PERM_NAME     VARCHAR2(128 BYTE),
  ACCESS_GROUP  VARCHAR2(64 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE PASSWORD_HISTORY
(
  USERNAME       VARCHAR2(64 BYTE),
  PASSWORD       VARCHAR2(128 BYTE),
  CREATION_DATE  DATE                           DEFAULT SYSDATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MZ_USER
(
  USERNAME          VARCHAR2(64 BYTE),
  FULLNAME          VARCHAR2(128 BYTE),
  PASSWORD          VARCHAR2(128 BYTE),
  EMAIL             VARCHAR2(128 BYTE),
  DEFAULT_GROUP     VARCHAR2(64 BYTE),
  IS_DISABLED       NUMBER(1)                   DEFAULT 0,
  METADATA          BLOB,
  FAILED_LOGINS     NUMBER(1)                   DEFAULT 0,
  PASSWORD_CHANGED  DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE ACCESS_GROUP
(
  GROUP_NAME   VARCHAR2(64 BYTE),
  DESCRIPTION  VARCHAR2(128 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE PICO_INSTANCES
(
  IPADDRESS  VARCHAR2(128 BYTE),
  NAME       VARCHAR2(64 BYTE),
  TYPE       VARCHAR2(64 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE PICO_HOSTS
(
  IPADDRESS  VARCHAR2(128 BYTE),
  DISABLED   NUMBER(1)                          DEFAULT 0
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;



CREATE INDEX ARCHIVE_MAINTAIN_IDX ON ARCHIVE_ENTRIES
(TXN_ID, PROFILE_ID, TIMESTAMP, ENTRY_ID)
LOGGING
NOPARALLEL
COMPRESS 2;


CREATE INDEX ARCHIVE_MIM_ENTRY_IDX ON ARCHIVE_MIMS
(ENTRY_ID)
LOGGING
NOPARALLEL;


CREATE INDEX ARCHIVE_TXN_IDX ON ARCHIVE_ENTRIES
(TXN_ID)
LOGGING
NOPARALLEL
COMPRESS 1;


CREATE INDEX CLIENT_STAT_HOSTID_IDX ON PICO_CLIENT_STAT
(HOST_STAT_ID)
LOGGING
NOPARALLEL;


CREATE INDEX CLIENT_STAT_NAME_IDX ON PICO_CLIENT_STAT
(CLIENT_NAME)
LOGGING
NOPARALLEL
COMPRESS 1;


CREATE UNIQUE INDEX CONFIGURATION_DATA_U_IDX ON CONFIGURATION_DATA
(CONFIG_TYPE, CONFIG_NAME, FOLDER_NAME)
LOGGING
NOPARALLEL;


CREATE INDEX CS_BUNDLE_CLASS_IDX ON CS_BUNDLE_CLASS
(ARCHIVE_ID, NAME)
LOGGING
NOPARALLEL;


CREATE INDEX CS_BUNDLE_INHERITANCE_IDX ON CS_BUNDLE_INHERITANCE
(SUPERCLASSNAME, CLASSNAME)
LOGGING
NOPARALLEL;


CREATE INDEX CS_BUNDLE_RESOURCE_IDX ON CS_BUNDLE_RESOURCE
(ARCHIVE_ID, NAME)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX CS_BUNDLE_U_IDX ON CS_BUNDLE
(ID)
LOGGING
NOPARALLEL;


CREATE INDEX DEFAULT_DUPBATCH_CRC_IDX ON DEFAULT_DUPBATCH
(CRC)
LOGGING
NOPARALLEL;


CREATE INDEX DEFAULT_DUPBATCH_TIME_IDX ON DEFAULT_DUPBATCH
(PROFILE, TIMESTAMP)
LOGGING
NOPARALLEL;


CREATE INDEX ECS1_BATCH_IDX ON ECS_BATCH
(WF_NAME, WF_NODE_NAME)
LOGGING
NOPARALLEL;


CREATE INDEX ECS_BATCH_ERROR1_IDX ON ECS_BATCH_ERROR
(TXN_ID)
LOGGING
NOPARALLEL;


CREATE INDEX ECS_BATCH_ERROR2_IDX ON ECS_BATCH_ERROR
(ERROR_CODE, COMPLETE_MSG)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX ECS_GROUP_IDX ON ECS_GROUP
(GROUP_NAME)
LOGGING
NOPARALLEL;


CREATE INDEX ECS_STAT_ENTRY1_IDX ON ECS_STAT_ENTRY
(ERROR_CODE)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX ECS_STAT_U_IDX ON ECS_STAT
(STAT_DATE, DATATYPE)
LOGGING
NOPARALLEL;


CREATE INDEX ECS_UDR_ERROR1_IDX ON ECS_UDR_ERROR
(ECS_UDR_ID)
LOGGING
NOPARALLEL;


CREATE INDEX ECS_UDR_ERROR2_IDX ON ECS_UDR_ERROR
(ERROR_CODE, COMPLETE_MSG)
LOGGING
NOPARALLEL;


CREATE INDEX ECS_UDR_TIME_IDX ON ECS_UDR
(INSERT_TIME)
LOGGING
NOPARALLEL;


CREATE INDEX ECS_UDR_TXN_IDX ON ECS_UDR
(TXN_ID)
LOGGING
NOPARALLEL;


CREATE INDEX ECS_UDR_WF_IDX ON ECS_UDR
(TXN_ID, WF_NODE_NAME)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX HOST_STAT_U_IDX ON HOST_STAT
(HOST_NAME, RESOLUTION, STAT_DATE)
LOGGING
NOPARALLEL
COMPRESS 2;


CREATE UNIQUE INDEX PICO_INSTANCES_U_IDX ON PICO_INSTANCES
(IPADDRESS, NAME, TYPE)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_ARCHIVE_ENTRIES ON ARCHIVE_ENTRIES
(ENTRY_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_CS_BUNDLE ON CS_BUNDLE
(NAME)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_CS_BUNDLE_ARCHIVE ON CS_BUNDLE_ARCHIVE
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_CS_BUNDLE_CLASS_NAME ON CS_BUNDLE_CLASS
(NAME)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_CS_PACKAGE ON CS_PACKAGE
(NAME)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_DEFAULT_DUPBATCH ON DEFAULT_DUPBATCH
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_ECS_BATCH ON ECS_BATCH
(TXN_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_ECS_ERROR_CODE ON ECS_ERROR_CODE
(ERROR_CODE)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_ECS_FILE ON ECS_FILE
(TXN_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_ECS_GROUP ON ECS_GROUP
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_ECS_MIM ON ECS_MIM
(TXN_ID, WF_NODE_NAME, NAME)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_ECS_STAT ON ECS_STAT
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_ECS_UDR ON ECS_UDR
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_HOST_STAT ON HOST_STAT
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_MZ_USER ON MZ_USER
(USERNAME)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_REFERENCE ON MZ_REFERENCE
(ORIG_OBJ_ID, DEST_OBJ_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_SYSTEM_LOG ON SYSTEM_LOG
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_TXN_STATUS ON TXN_STATUS
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_ULTRA_DATA ON ULTRA_DATA
(TYPE)
LOGGING
NOPARALLEL;


CREATE INDEX REFERENCE_U_IDX ON MZ_REFERENCE
(DEST_OBJ_ID)
LOGGING
NOPARALLEL;


CREATE INDEX SYSTEM_L_IDX ON SYSTEM_LOG
(CREATION_TIME, WF_INSTANCE_NAME, WF_NODE_NAME)
LOGGING
NOPARALLEL;


CREATE INDEX SYSTEM_L_NESTED_IDX ON SYSTEM_LOG_NESTED
(SYSTEM_LOG_ID)
LOGGING
NOPARALLEL;


CREATE INDEX SYSTEM_L_USERIDX ON SYSTEM_LOG
(USER_NAME)
LOGGING
NOPARALLEL
COMPRESS 1;


CREATE INDEX TASK_STAT_HOSTID_IDX ON TASK_STAT
(HOST_STAT_ID)
LOGGING
NOPARALLEL;


CREATE INDEX WF_STAT_HOSTID_IDX ON WF_STAT
(HOST_STAT_ID)
LOGGING
NOPARALLEL;


CREATE INDEX WF_STAT_NAME_IDX ON WF_STAT
(WF_NAME)
LOGGING
NOPARALLEL
COMPRESS 1;


CREATE INDEX WF_TXN_WF_IDX ON WF_TXN
(INSTANCE_NAME)
LOGGING
NOPARALLEL;


ALTER TABLE ECS_BATCH ADD (
  CONSTRAINT PK_ECS_BATCH
 PRIMARY KEY
 (TXN_ID));

ALTER TABLE ECS_MIM ADD (
  CONSTRAINT PK_ECS_MIM
 PRIMARY KEY
 (TXN_ID, WF_NODE_NAME, NAME));

ALTER TABLE HOST_STAT ADD (
  CONSTRAINT PK_HOST_STAT
 PRIMARY KEY
 (ID));

ALTER TABLE ARCHIVE_ENTRIES ADD (
  CONSTRAINT PK_ARCHIVE_ENTRIES
 PRIMARY KEY
 (ENTRY_ID));

ALTER TABLE DEFAULT_DUPBATCH ADD (
  CONSTRAINT PK_DEFAULT_DUPBATCH
 PRIMARY KEY
 (ID));

ALTER TABLE ECS_GROUP ADD (
  CONSTRAINT PK_ECS_GROUP
 PRIMARY KEY
 (ID));

ALTER TABLE ECS_ERROR_CODE ADD (
  CONSTRAINT PK_ECS_ERROR_CODE
 PRIMARY KEY
 (ERROR_CODE));

ALTER TABLE ECS_FILE ADD (
  CONSTRAINT PK_ECS_FILE
 PRIMARY KEY
 (TXN_ID));

ALTER TABLE ECS_UDR ADD (
  CONSTRAINT PK_ECS_UDR
 PRIMARY KEY
 (ID));

ALTER TABLE ECS_STAT ADD (
  CONSTRAINT PK_ECS_STAT
 PRIMARY KEY
 (ID));

ALTER TABLE ULTRA_DATA ADD (
  CONSTRAINT PK_ULTRA_DATA
 PRIMARY KEY
 (TYPE));

ALTER TABLE PICO_HOSTS ADD (
  PRIMARY KEY
 (IPADDRESS));

ALTER TABLE ACCESS_GROUP ADD (
  PRIMARY KEY
 (GROUP_NAME));

ALTER TABLE MZ_USER ADD (
  CONSTRAINT PK_MZ_USER
 PRIMARY KEY
 (USERNAME));

ALTER TABLE PASSWORD_HISTORY ADD (
  PRIMARY KEY
 (USERNAME, PASSWORD));

ALTER TABLE APPLICATION_DATA ADD (
  PRIMARY KEY
 (APP_TYPE, PERM_NAME, ACCESS_GROUP));

ALTER TABLE USER_GROUP ADD (
  PRIMARY KEY
 (USERNAME, GROUP_NAME));

ALTER TABLE CONFIGURATION_FOLDER ADD (
  PRIMARY KEY
 (FOLDER_NAME));

ALTER TABLE CONFIGURATION_DATA ADD (
  PRIMARY KEY
 (CONFIG_KEY));

ALTER TABLE CONFIGURATION_HISTORY ADD (
  PRIMARY KEY
 (CONFIG_KEY, VERSION));

ALTER TABLE CS_PACKAGE ADD (
  CONSTRAINT PK_CS_PACKAGE
 PRIMARY KEY
 (NAME));

ALTER TABLE CS_BUNDLE ADD (
  CONSTRAINT PK_CS_BUNDLE
 PRIMARY KEY
 (NAME));

ALTER TABLE CS_BUNDLE_ARCHIVE ADD (
  CONSTRAINT PK_CS_BUNDLE_ARCHIVE
 PRIMARY KEY
 (ID));

ALTER TABLE CS_BUNDLE_CLASS ADD (
  CONSTRAINT PK_CS_BUNDLE_CLASS_NAME
 PRIMARY KEY
 (NAME));

ALTER TABLE SYSTEM_LOG ADD (
  CONSTRAINT PK_SYSTEM_LOG
 PRIMARY KEY
 (ID));

ALTER TABLE TXN_STATUS ADD (
  CONSTRAINT PK_TXN_STATUS
 PRIMARY KEY
 (ID),
  UNIQUE (NAME));

ALTER TABLE TM_TASK ADD (
  PRIMARY KEY
 (NAME));

ALTER TABLE USER_DEFINED_EVENT ADD (
  PRIMARY KEY
 (NAME));

ALTER TABLE MZ_REFERENCE ADD (
  CONSTRAINT PK_REFERENCE
 PRIMARY KEY
 (ORIG_OBJ_ID, DEST_OBJ_ID));

ALTER TABLE ECS_BATCH ADD (
  CONSTRAINT FK_ECS_BATCH_TXN 
 FOREIGN KEY (TXN_ID) 
 REFERENCES ECS_FILE (TXN_ID),
  FOREIGN KEY (GROUP_ID) 
 REFERENCES ECS_GROUP (ID));

ALTER TABLE ECS_MIM ADD (
  CONSTRAINT FK_ECS_MIM_TXN 
 FOREIGN KEY (TXN_ID) 
 REFERENCES ECS_FILE (TXN_ID)
    ON DELETE CASCADE);

ALTER TABLE ECS_ERROR_CODE ADD (
  FOREIGN KEY (REPROCESS_GROUP) 
 REFERENCES ECS_GROUP (ID));

ALTER TABLE ECS_UDR ADD (
  CONSTRAINT FK_ECS_UDR_TXN 
 FOREIGN KEY (TXN_ID) 
 REFERENCES ECS_FILE (TXN_ID),
  FOREIGN KEY (GROUP_ID) 
 REFERENCES ECS_GROUP (ID));

ALTER TABLE MZ_USER ADD (
  CONSTRAINT FK_USER_DEFAULT_GROUP 
 FOREIGN KEY (DEFAULT_GROUP) 
 REFERENCES ACCESS_GROUP (GROUP_NAME));

ALTER TABLE PASSWORD_HISTORY ADD (
  CONSTRAINT FK_CS_MZ_USER_NAME 
 FOREIGN KEY (USERNAME) 
 REFERENCES MZ_USER (USERNAME)
    ON DELETE CASCADE);

ALTER TABLE APPLICATION_DATA ADD (
  CONSTRAINT FK_APP_ACCESS_GROUP 
 FOREIGN KEY (ACCESS_GROUP) 
 REFERENCES ACCESS_GROUP (GROUP_NAME));

ALTER TABLE USER_GROUP ADD (
  CONSTRAINT FK_USER_GROUP_USERNAME 
 FOREIGN KEY (USERNAME) 
 REFERENCES MZ_USER (USERNAME),
  CONSTRAINT FK_USER_GROUP_GROUPNAME 
 FOREIGN KEY (GROUP_NAME) 
 REFERENCES ACCESS_GROUP (GROUP_NAME));

ALTER TABLE CONFIGURATION_FOLDER ADD (
  CONSTRAINT FK_CF_OWNER 
 FOREIGN KEY (OWNER) 
 REFERENCES MZ_USER (USERNAME));

ALTER TABLE CONFIGURATION_DATA ADD (
  CONSTRAINT FK_CONFIG_DATA_FOLDER_NAME 
 FOREIGN KEY (FOLDER_NAME) 
 REFERENCES CONFIGURATION_FOLDER (FOLDER_NAME),
  CONSTRAINT FK_CD_OWNER 
 FOREIGN KEY (OWNER) 
 REFERENCES MZ_USER (USERNAME));

ALTER TABLE CS_BUNDLE ADD (
  CONSTRAINT FK_CS_BUNDLE_PACKAGE_ID 
 FOREIGN KEY (PACKAGE_NAME) 
 REFERENCES CS_PACKAGE (NAME)
    ON DELETE CASCADE);

ALTER TABLE CS_BUNDLE_ARCHIVE ADD (
  CONSTRAINT FK_CS_BUNDLE_BUNDLE_NAME 
 FOREIGN KEY (BUNDLE_NAME) 
 REFERENCES CS_BUNDLE (NAME)
    ON DELETE CASCADE);

ALTER TABLE CS_BUNDLE_CLASS ADD (
  CONSTRAINT FK_CS_BUNDLE_CLASS_ARCHIVE_ID 
 FOREIGN KEY (ARCHIVE_ID) 
 REFERENCES CS_BUNDLE_ARCHIVE (ID)
    ON DELETE CASCADE);

ALTER TABLE CS_BUNDLE_RESOURCE ADD (
  CONSTRAINT FK_CS_BUNDLE_RESOURCE_A_ID 
 FOREIGN KEY (ARCHIVE_ID) 
 REFERENCES CS_BUNDLE_ARCHIVE (ID)
    ON DELETE CASCADE);

ALTER TABLE PICO_CLIENT_STAT ADD (
  CONSTRAINT FK_PICO_STAT_HOST_ID 
 FOREIGN KEY (HOST_STAT_ID) 
 REFERENCES HOST_STAT (ID)
    ON DELETE CASCADE);

ALTER TABLE TASK_STAT ADD (
  CONSTRAINT FK_TASK_STAT_HOST_ID 
 FOREIGN KEY (HOST_STAT_ID) 
 REFERENCES HOST_STAT (ID)
    ON DELETE CASCADE);

ALTER TABLE WF_STAT ADD (
  CONSTRAINT FK_WF_STAT_HOST_ID 
 FOREIGN KEY (HOST_STAT_ID) 
 REFERENCES HOST_STAT (ID)
    ON DELETE CASCADE);

ALTER TABLE ARCHIVE_MIMS ADD (
  CONSTRAINT ARCHIVE_MIMS_ID_FK 
 FOREIGN KEY (ENTRY_ID) 
 REFERENCES ARCHIVE_ENTRIES (ENTRY_ID)
    ON DELETE CASCADE);

ALTER TABLE ECS_UDR_ERROR ADD (
  FOREIGN KEY (ECS_UDR_ID) 
 REFERENCES ECS_UDR (ID)
    ON DELETE CASCADE,
  FOREIGN KEY (ERROR_CODE) 
 REFERENCES ECS_ERROR_CODE (ERROR_CODE));

ALTER TABLE ECS_BATCH_ERROR ADD (
  FOREIGN KEY (TXN_ID) 
 REFERENCES ECS_BATCH (TXN_ID)
    ON DELETE CASCADE,
  FOREIGN KEY (ERROR_CODE) 
 REFERENCES ECS_ERROR_CODE (ERROR_CODE));

ALTER TABLE ECS_STAT_ENTRY ADD (
  CONSTRAINT FK_ECS_STAT_ID 
 FOREIGN KEY (STAT_ID) 
 REFERENCES ECS_STAT (ID)
    ON DELETE CASCADE);

ALTER TABLE PICO_INSTANCES ADD (
  CONSTRAINT FK_PI_IPADDRESS 
 FOREIGN KEY (IPADDRESS) 
 REFERENCES PICO_HOSTS (IPADDRESS)
    ON DELETE CASCADE);

ALTER TABLE CS_BUNDLE_INHERITANCE ADD (
  CONSTRAINT FK_CS_BUNDLE_CLASS_NAME 
 FOREIGN KEY (CLASSNAME) 
 REFERENCES CS_BUNDLE_CLASS (NAME)
    ON DELETE CASCADE);

ALTER TABLE SYSTEM_LOG_NESTED ADD (
  CONSTRAINT FK_SLN_SYSTEM_LOG_ID 
 FOREIGN KEY (SYSTEM_LOG_ID) 
 REFERENCES SYSTEM_LOG (ID));


--BEGIN_PLSQL
CREATE OR REPLACE TRIGGER trg_cs_bundle_archive_id
  BEFORE INSERT ON cs_bundle_archive
  REFERENCING NEW AS NEW FOR EACH ROW
BEGIN
        SELECT seq_cs_bundle_archive_id.NEXTVAL INTO :NEW.id FROM DUAL;
END;
/
--END_PLSQL

--BEGIN_PLSQL
CREATE OR REPLACE TRIGGER trg_system_log_id BEFORE INSERT ON system_log
REFERENCING OLD AS OLD NEW AS NEW FOR EACH ROW
DECLARE ind Integer;
BEGIN
	SELECT seq_system_log_id.NEXTVAL INTO ind FROM DUAL;
        :NEW.id := ind;
END;
/
--END_PLSQL

--BEGIN_PLSQL
CREATE OR REPLACE TRIGGER trg_cs_bundle_id
  BEFORE INSERT ON cs_bundle
  REFERENCING NEW AS NEW FOR EACH ROW
BEGIN
        SELECT seq_cs_bundle_id.NEXTVAL INTO :NEW.id FROM DUAL;
END;
/
--END_PLSQL

--BEGIN_PLSQL
CREATE OR REPLACE TRIGGER trg_txn_status_id
       BEFORE INSERT ON txn_status
REFERENCING OLD AS OLD NEW AS NEW FOR EACH ROW
DECLARE ind Integer;
BEGIN

        SELECT  seq_txn_status_id.NEXTVAL INTO ind FROM DUAL;
        :NEW.id := ind;

END;
/
--END_PLSQL

--BEGIN_PLSQL
CREATE OR REPLACE TRIGGER trg_host_stat
       BEFORE INSERT ON host_stat
REFERENCING OLD AS OLD NEW AS NEW FOR EACH ROW
DECLARE ind Integer;
 BEGIN
        SELECT  seq_host_stat.NEXTVAL INTO ind FROM DUAL;
        :NEW.id := ind;
END;
/
--END_PLSQL

--BEGIN_PLSQL
CREATE OR REPLACE TRIGGER lic_log_id
  BEFORE INSERT ON lic_log
  REFERENCING NEW AS NEW FOR EACH ROW
BEGIN
        SELECT lic_log_id.NEXTVAL INTO :NEW.id FROM DUAL;
END;
/
--END_PLSQL

--BEGIN_PLSQL
CREATE OR REPLACE TRIGGER trg_archive_entry_id
       BEFORE INSERT ON archive_entries
REFERENCING OLD AS OLD NEW AS NEW FOR EACH ROW
DECLARE ind Integer;
 BEGIN
        SELECT  seq_archive_entry_id.NEXTVAL INTO ind FROM DUAL;
        :NEW.entry_id := ind;
END;
/
--END_PLSQL

--BEGIN_PLSQL
CREATE OR REPLACE TRIGGER trg_ecs_group
       BEFORE INSERT ON ecs_group
REFERENCING OLD AS OLD NEW AS NEW FOR EACH ROW
DECLARE ind Integer;
 BEGIN
        SELECT  seq_ecs_group.NEXTVAL INTO ind FROM DUAL;
        :NEW.id := ind;
END;
/
--END_PLSQL

--BEGIN_PLSQL
CREATE OR REPLACE TRIGGER trg_ecs_udr
       BEFORE INSERT ON ecs_udr
REFERENCING OLD AS OLD NEW AS NEW FOR EACH ROW
DECLARE ind Integer;
 BEGIN
        SELECT  seq_ecs_udr.NEXTVAL INTO ind FROM DUAL;
        :NEW.id := ind;
END;
/
--END_PLSQL

--BEGIN_PLSQL
CREATE OR REPLACE TRIGGER trg_ecs_stat
       BEFORE INSERT ON ecs_stat
REFERENCING OLD AS OLD NEW AS NEW FOR EACH ROW
DECLARE ind Integer;
 BEGIN
        SELECT  seq_ecs_stat.NEXTVAL INTO ind FROM DUAL;
        :NEW.id := ind;
END;
/
--END_PLSQL

ALTER TABLE ULTRA_DATA
MODIFY(VALUE  NOT NULL);


ALTER TABLE ECS_STAT
MODIFY(STAT_DATE  NOT NULL);


ALTER TABLE ECS_STAT
MODIFY(DATATYPE  NOT NULL);


ALTER TABLE ECS_FILE
MODIFY(TXN_SAFE  NOT NULL);


ALTER TABLE ECS_FILE
MODIFY(FILENAME  NOT NULL);


ALTER TABLE ECS_FILE
MODIFY(DATATYPE  NOT NULL);


ALTER TABLE ECS_GROUP
MODIFY(GROUP_NAME  NOT NULL);


ALTER TABLE ECS_GROUP
MODIFY(DATATYPE  NOT NULL);


ALTER TABLE ECS_GROUP
MODIFY(STATE  NOT NULL);


ALTER TABLE DEFAULT_DUPBATCH
MODIFY(TIMESTAMP  NOT NULL);


ALTER TABLE DEFAULT_DUPBATCH
MODIFY(CRC  NOT NULL);


ALTER TABLE DEFAULT_DUPBATCH
MODIFY(TXN_SAFE  NOT NULL);


ALTER TABLE DEFAULT_DUPBATCH
MODIFY(PROFILE  NOT NULL);


ALTER TABLE DBAGENT_PENDING_TXN
MODIFY(TXN_ID  NOT NULL);


ALTER TABLE DBAGENT_PENDING_TXN
MODIFY(SYSTEM_NAME  NOT NULL);


ALTER TABLE DBAGENT_PENDING_TXN
MODIFY(WF_INSTANCE_NAME  NOT NULL);


ALTER TABLE DBAGENT_PENDING_TXN
MODIFY(AGENT_ID  NOT NULL);


ALTER TABLE DBAGENT_PENDING_TXN
MODIFY(DB_TABLE_SCHEMA  NOT NULL);


ALTER TABLE DBAGENT_PENDING_TXN
MODIFY(DB_TABLE_NAME  NOT NULL);


ALTER TABLE ARCHIVE_ENTRIES
MODIFY(TXN_ID  NOT NULL);


ALTER TABLE ARCHIVE_ENTRIES
MODIFY(PROFILE_ID  NOT NULL);


ALTER TABLE ARCHIVE_ENTRIES
MODIFY(COMPRESSION  NOT NULL);


ALTER TABLE ARCHIVE_ENTRIES
MODIFY(TIMESTAMP  NOT NULL);


ALTER TABLE LIC_LOG
MODIFY(ID  NOT NULL);


ALTER TABLE LIC_LOG
MODIFY(CONTENTS  NOT NULL);


ALTER TABLE LIC_HEADER
MODIFY(ID  NOT NULL);


ALTER TABLE LIC_HEADER
MODIFY(CONTENTS  NOT NULL);


ALTER TABLE HOST_STAT
MODIFY(STAT_DATE  NOT NULL);


ALTER TABLE HOST_STAT
MODIFY(RESOLUTION  NOT NULL);


ALTER TABLE HOST_STAT
MODIFY(HOST_NAME  NOT NULL);


ALTER TABLE HOST_STAT
MODIFY(WAIT_PROC_AVR  NOT NULL);


ALTER TABLE HOST_STAT
MODIFY(WAIT_PROC_MIN  NOT NULL);


ALTER TABLE HOST_STAT
MODIFY(WAIT_PROC_MAX  NOT NULL);


ALTER TABLE HOST_STAT
MODIFY(SLEEP_PROC_AVR  NOT NULL);


ALTER TABLE HOST_STAT
MODIFY(SLEEP_PROC_MIN  NOT NULL);


ALTER TABLE HOST_STAT
MODIFY(SLEEP_PROC_MAX  NOT NULL);


ALTER TABLE HOST_STAT
MODIFY(SWAP_PROC_AVR  NOT NULL);


ALTER TABLE HOST_STAT
MODIFY(SWAP_PROC_MIN  NOT NULL);


ALTER TABLE HOST_STAT
MODIFY(SWAP_PROC_MAX  NOT NULL);


ALTER TABLE HOST_STAT
MODIFY(FROM_DISK_SWAP_PER_SEC_AVR  NOT NULL);


ALTER TABLE HOST_STAT
MODIFY(FROM_DISK_SWAP_PER_SEC_MIN  NOT NULL);


ALTER TABLE HOST_STAT
MODIFY(FROM_DISK_SWAP_PER_SEC_MAX  NOT NULL);


ALTER TABLE HOST_STAT
MODIFY(TO_DISK_SWAP_PER_SEC_AVR  NOT NULL);


ALTER TABLE HOST_STAT
MODIFY(TO_DISK_SWAP_PER_SEC_MIN  NOT NULL);


ALTER TABLE HOST_STAT
MODIFY(TO_DISK_SWAP_PER_SEC_MAX  NOT NULL);


ALTER TABLE HOST_STAT
MODIFY(CONTEXT_SWITCHES_PER_SEC_AVR  NOT NULL);


ALTER TABLE HOST_STAT
MODIFY(CONTEXT_SWITCHES_PER_SEC_MIN  NOT NULL);


ALTER TABLE HOST_STAT
MODIFY(CONTEXT_SWITCHES_PER_SEC_MAX  NOT NULL);


ALTER TABLE HOST_STAT
MODIFY(USER_TIME_CPU_AVR  NOT NULL);


ALTER TABLE HOST_STAT
MODIFY(USER_TIME_CPU_MIN  NOT NULL);


ALTER TABLE HOST_STAT
MODIFY(USER_TIME_CPU_MAX  NOT NULL);


ALTER TABLE HOST_STAT
MODIFY(SYS_TIME_CPU_AVR  NOT NULL);


ALTER TABLE HOST_STAT
MODIFY(SYS_TIME_CPU_MIN  NOT NULL);


ALTER TABLE HOST_STAT
MODIFY(SYS_TIME_CPU_MAX  NOT NULL);


ALTER TABLE MZ_REFERENCE
MODIFY(DEST_MODIFIABLE  NOT NULL);


ALTER TABLE TM_TASK
MODIFY(STATUS  NOT NULL);


ALTER TABLE TXN_STATUS
MODIFY(NAME  NOT NULL);


ALTER TABLE TXN_STATUS
MODIFY(STATUS  NOT NULL);


ALTER TABLE WF_TXN
MODIFY(TXN_ID  NOT NULL);


ALTER TABLE WF_TXN
MODIFY(INSTANCE_STATE  NOT NULL);


ALTER TABLE WF_TXN
MODIFY(INSTANCE_NAME  NOT NULL);


ALTER TABLE SYSTEM_LOG
MODIFY(SEVERITY_TYPE  NOT NULL);


ALTER TABLE SYSTEM_LOG
MODIFY(LOG_TYPE  NOT NULL);


ALTER TABLE SYSTEM_LOG
MODIFY(SHORT_MESSAGE  NOT NULL);


ALTER TABLE SYSTEM_LOG
MODIFY(MESSAGE  NOT NULL);


ALTER TABLE SYSTEM_LOG
MODIFY(CREATION_TIME  NOT NULL);


ALTER TABLE SYSTEM_LOG
MODIFY(LATEST_OCCURRENCE  NOT NULL);


ALTER TABLE SYSTEM_LOG
MODIFY(OCCURRENCE_COUNTER  NOT NULL);


ALTER TABLE MIM_GROUP
MODIFY(NAME  NOT NULL);


ALTER TABLE CS_PACKAGE
MODIFY(VERSION  NOT NULL);


ALTER TABLE CS_PACKAGE
MODIFY(CUSTOMER  NOT NULL);


ALTER TABLE CS_PACKAGE
MODIFY(CREATION_DATE  NOT NULL);


ALTER TABLE CS_PACKAGE
MODIFY(RUNTIME  NOT NULL);


ALTER TABLE CONFIGURATION_HISTORY
MODIFY(CONFIG_NAME  NOT NULL);


ALTER TABLE CONFIGURATION_HISTORY
MODIFY(CONFIG_TYPE  NOT NULL);


ALTER TABLE CONFIGURATION_HISTORY
MODIFY(FOLDER_NAME  NOT NULL);


ALTER TABLE CONFIGURATION_HISTORY
MODIFY(OWNER  NOT NULL);


ALTER TABLE CONFIGURATION_HISTORY
MODIFY(MODIFIED_BY  NOT NULL);


ALTER TABLE CONFIGURATION_HISTORY
MODIFY(MODIFIED_DATE  NOT NULL);


ALTER TABLE CONFIGURATION_HISTORY
MODIFY(IS_ENCRYPTED  NOT NULL);


ALTER TABLE ECS_STAT_ENTRY
MODIFY(STAT_ID  NOT NULL);


ALTER TABLE ECS_STAT_ENTRY
MODIFY(ERROR_CODE  NOT NULL);


ALTER TABLE ECS_STAT_ENTRY
MODIFY(COUNT_NEW  NOT NULL);


ALTER TABLE ECS_STAT_ENTRY
MODIFY(COUNT_RP  NOT NULL);


ALTER TABLE ECS_STAT_ENTRY
MODIFY(NEWEST_ENTRY  NOT NULL);


ALTER TABLE ECS_STAT_ENTRY
MODIFY(OLDEST_ENTRY  NOT NULL);


ALTER TABLE ECS_MIM
MODIFY(DATATYPE  NOT NULL);


ALTER TABLE ECS_BATCH
MODIFY(STATE  NOT NULL);


ALTER TABLE ECS_BATCH
MODIFY(WF_NAME  NOT NULL);


ALTER TABLE ECS_BATCH
MODIFY(WF_NODE_NAME  NOT NULL);


ALTER TABLE ECS_BATCH
MODIFY(INSERT_TIME  NOT NULL);


ALTER TABLE ECS_BATCH
MODIFY(FILELENGTH  NOT NULL);


ALTER TABLE ECS_UDR
MODIFY(TXN_ID  NOT NULL);


ALTER TABLE ECS_UDR
MODIFY(STATE  NOT NULL);


ALTER TABLE ECS_UDR
MODIFY(WF_NAME  NOT NULL);


ALTER TABLE ECS_UDR
MODIFY(WF_NODE_NAME  NOT NULL);


ALTER TABLE ECS_UDR
MODIFY(INSERT_TIME  NOT NULL);


ALTER TABLE ECS_UDR
MODIFY(UDR_TYPE  NOT NULL);


ALTER TABLE ECS_UDR
MODIFY(OFFSET  NOT NULL);


ALTER TABLE ECS_UDR
MODIFY(LENGTH  NOT NULL);


ALTER TABLE ECS_ERROR_CODE
MODIFY(IS_SYSTEM_CODE  NOT NULL);


ALTER TABLE WF_STAT
MODIFY(HOST_STAT_ID  NOT NULL);


ALTER TABLE WF_STAT
MODIFY(CLIENT_NAME  NOT NULL);


ALTER TABLE WF_STAT
MODIFY(WF_NAME  NOT NULL);


ALTER TABLE WF_STAT
MODIFY(DATA_COUNTER_AVR  NOT NULL);


ALTER TABLE WF_STAT
MODIFY(DATA_COUNTER_MIN  NOT NULL);


ALTER TABLE WF_STAT
MODIFY(DATA_COUNTER_MAX  NOT NULL);


ALTER TABLE TASK_STAT
MODIFY(HOST_STAT_ID  NOT NULL);


ALTER TABLE TASK_STAT
MODIFY(CLIENT_NAME  NOT NULL);


ALTER TABLE TASK_STAT
MODIFY(TASK_NAME  NOT NULL);


ALTER TABLE TASK_STAT
MODIFY(START_TIME  NOT NULL);


ALTER TABLE TASK_STAT
MODIFY(STOP_TIME  NOT NULL);


ALTER TABLE PICO_CLIENT_STAT
MODIFY(HOST_STAT_ID  NOT NULL);


ALTER TABLE PICO_CLIENT_STAT
MODIFY(CLIENT_NAME  NOT NULL);


ALTER TABLE PICO_CLIENT_STAT
MODIFY(AVAILABLE_MEM  NOT NULL);


ALTER TABLE PICO_CLIENT_STAT
MODIFY(USED_MEM_AVR  NOT NULL);


ALTER TABLE PICO_CLIENT_STAT
MODIFY(USED_MEM_MIN  NOT NULL);


ALTER TABLE PICO_CLIENT_STAT
MODIFY(USED_MEM_MAX  NOT NULL);


ALTER TABLE PICO_CLIENT_STAT
MODIFY(GC_TIME_AVR  NOT NULL);


ALTER TABLE PICO_CLIENT_STAT
MODIFY(GC_TIME_MIN  NOT NULL);


ALTER TABLE PICO_CLIENT_STAT
MODIFY(GC_TIME_MAX  NOT NULL);


ALTER TABLE PICO_CLIENT_STAT
MODIFY(GC_COUNT_AVR  NOT NULL);


ALTER TABLE PICO_CLIENT_STAT
MODIFY(GC_COUNT_MIN  NOT NULL);


ALTER TABLE PICO_CLIENT_STAT
MODIFY(GC_COUNT_MAX  NOT NULL);


ALTER TABLE PICO_CLIENT_STAT
MODIFY(THREAD_COUNT_AVR  NOT NULL);


ALTER TABLE PICO_CLIENT_STAT
MODIFY(THREAD_COUNT_MIN  NOT NULL);


ALTER TABLE PICO_CLIENT_STAT
MODIFY(THREAD_COUNT_MAX  NOT NULL);


ALTER TABLE SYSTEM_LOG_NESTED
MODIFY(SYSTEM_LOG_ID  NOT NULL);


ALTER TABLE SYSTEM_LOG_NESTED
MODIFY(NESTED_IDX  NOT NULL);


ALTER TABLE SYSTEM_LOG_NESTED
MODIFY(MESSAGE  NOT NULL);


ALTER TABLE CS_BUNDLE
MODIFY(ID  NOT NULL);


ALTER TABLE CS_BUNDLE
MODIFY(PACKAGE_NAME  NOT NULL);


ALTER TABLE CS_BUNDLE
MODIFY(VERSION  NOT NULL);


ALTER TABLE MZ_USER
MODIFY(FULLNAME  NOT NULL);


ALTER TABLE MZ_USER
MODIFY(PASSWORD  NOT NULL);


ALTER TABLE MZ_USER
MODIFY(EMAIL  NOT NULL);


ALTER TABLE MZ_USER
MODIFY(IS_DISABLED  NOT NULL);


ALTER TABLE PICO_INSTANCES
MODIFY(IPADDRESS  NOT NULL);


ALTER TABLE PICO_INSTANCES
MODIFY(NAME  NOT NULL);


ALTER TABLE PICO_INSTANCES
MODIFY(TYPE  NOT NULL);


ALTER TABLE ECS_BATCH_ERROR
MODIFY(TXN_ID  NOT NULL);


ALTER TABLE ECS_BATCH_ERROR
MODIFY(ERROR_CODE  NOT NULL);


ALTER TABLE ECS_UDR_ERROR
MODIFY(ECS_UDR_ID  NOT NULL);


ALTER TABLE ECS_UDR_ERROR
MODIFY(ERROR_CODE  NOT NULL);


ALTER TABLE CS_BUNDLE_ARCHIVE
MODIFY(BUNDLE_NAME  NOT NULL);


ALTER TABLE CS_BUNDLE_ARCHIVE
MODIFY(CODE_LEVEL  NOT NULL);


ALTER TABLE CS_BUNDLE_ARCHIVE
MODIFY(CREATION_DATE  NOT NULL);


ALTER TABLE CS_BUNDLE_ARCHIVE
MODIFY(ORIG_FILENAME  NOT NULL);


ALTER TABLE CS_BUNDLE_ARCHIVE
MODIFY(FILE_LENGTH  NOT NULL);


ALTER TABLE CS_BUNDLE_ARCHIVE
MODIFY(CONTENTS  NOT NULL);


ALTER TABLE CONFIGURATION_FOLDER
MODIFY(OWNER  NOT NULL);


ALTER TABLE PASSWORD_HISTORY
MODIFY(CREATION_DATE  NOT NULL);


ALTER TABLE CS_BUNDLE_RESOURCE
MODIFY(ARCHIVE_ID  NOT NULL);


ALTER TABLE CS_BUNDLE_CLASS
MODIFY(ARCHIVE_ID  NOT NULL);


ALTER TABLE CONFIGURATION_DATA
MODIFY(CONFIG_NAME  NOT NULL);


ALTER TABLE CONFIGURATION_DATA
MODIFY(CONFIG_TYPE  NOT NULL);


ALTER TABLE CONFIGURATION_DATA
MODIFY(FOLDER_NAME  NOT NULL);


ALTER TABLE CONFIGURATION_DATA
MODIFY(VERSION  NOT NULL);


ALTER TABLE CONFIGURATION_DATA
MODIFY(OWNER  NOT NULL);


ALTER TABLE CONFIGURATION_DATA
MODIFY(MODIFIED_BY  NOT NULL);


ALTER TABLE CONFIGURATION_DATA
MODIFY(MODIFIED_DATE  NOT NULL);


ALTER TABLE CONFIGURATION_DATA
MODIFY(ACCESS_GROUPS  NOT NULL);


ALTER TABLE CONFIGURATION_DATA
MODIFY(IS_VALID  NOT NULL);


ALTER TABLE CONFIGURATION_DATA
MODIFY(IS_ENCRYPTED  NOT NULL);


ALTER TABLE CS_BUNDLE_INHERITANCE
MODIFY(CLASSNAME  NOT NULL);


ALTER TABLE CS_BUNDLE_INHERITANCE
MODIFY(SUPERCLASSNAME  NOT NULL);

INSERT INTO access_group (group_name, description) VALUES
  ('Administrator', 'Full privileged group');

INSERT INTO access_group (group_name, description) VALUES
  ('All', 'Group where all users are automatically members');

INSERT INTO mz_user (username, fullname, email, password, default_group, is_disabled, metadata, password_changed) VALUES
('mzadmin', 'MZ Administrator', 'mzadmin',
 '32993803465104903760650474495088870400774373023', 'Administrator', 0, empty_blob(), CURRENT_TIMESTAMP);

INSERT INTO user_group (username, group_name) VALUES ('mzadmin','Administrator');

INSERT INTO configuration_folder(folder_name, owner) VALUES ('Default', 'mzadmin');

INSERT INTO mz_reference(orig_obj_id, dest_obj_id) VALUES ('Folder:Default', 'User:mzadmin');

