-- Create tables
--
CREATE TABLE MZ_CONFIGURATION
(
  PARAMETER        VARCHAR2(32 BYTE),
  PARAMETER_VALUE  NUMBER(15)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;


-- Create indexes
--
CREATE UNIQUE INDEX MZ_CONFIGURATION_PK
ON MZ_CONFIGURATION (PARAMETER);


-- Add contraints
--
ALTER TABLE MZ_CONFIGURATION
ADD CONSTRAINT MZ_CONFIGURATION_PK
PRIMARY KEY (PARAMETER);


-- Add rows to MZ_CONFIGURATION
--
INSERT INTO MZ_CONFIGURATION VALUES ('RTR_DUP_BATCH_CHECK', 1);

INSERT INTO MZ_CONFIGURATION VALUES ('RTR_DUP_UDR_CHECK', 1);