-- Create a parameters table to store salt value for Datalake
--
CREATE TABLE SKYIT_PARAMETERS
(
  PARAMETER        VARCHAR2(32 BYTE),
  PARAMETER_VALUE  VARCHAR2(32 BYTE),
  DESCRIPTION      VARCHAR2(128 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;

-- INSERT INTO THE SKYIT_PARAMETERS TABLE
--
INSERT INTO SKYIT_PARAMETERS VALUES ('SALT_VALUE','61AA205584203BBE32DBB613978716B7','Defining the SALT value to be added when we need to deliver a hashed value'); 