-- Update the SALT value
--
UPDATE SKYIT_PARAMETERS 
   SET PARAMETER_VALUE = '33FA0178'
 WHERE PARAMETER = 'SALT_VALUE'; 
 
 
-- Widen the SDSI field from 50 to 80
--
ALTER TABLE CUMULATIVE_RADIUS MODIFY SDSI VARCHAR2(80);
