-- ADD SESS_FPTS TO CUMULATIVE_RADIUS TABLE
--
ALTER TABLE CUMULATIVE_RADIUS
ADD SESS_FPTS VARCHAR2(26);


-- ADD SESS_FPTS TO CDR_INPUT_RTR TABLE
--
ALTER TABLE CDR_INPUT_RTR
ADD SESS_FPTS NUMBER(10);
