-- MZITA-227 - Change datatype in CDR_INPUT_RTR and CUMULATIVE_RADIUS tables
--


-- RENAME THE EXISTING TABLES
--
RENAME CDR_INPUT_RTR TO CDR_INPUT_RTR_OLD;

RENAME CUMULATIVE_RADIUS TO CUMULATIVE_RADIUS_OLD;


-- DROP THE CDR_INPUT_RTR INDEX
--
DROP INDEX CDR_INPUT_RTR_IDX1;


-- DROP THE CUMULATIVE_RADIUS INDEX
--
DROP INDEX CUMULATIVE_RADIUS_IDX1;


-- RE-CREATE THE CDR_INPUT_RTR TABLE WITH NEW DATATYPES
--
CREATE TABLE CDR_INPUT_RTR
(	
	TRANSACTION_ID NUMBER(22), 
	CREATED_DATE DATE DEFAULT SYSDATE NOT NULL, 
	INPUT_FILENAME VARCHAR2(80), 
	RTR_TYPE VARCHAR2(50), 
	USERNAME VARCHAR2(50), 
	UNIQSESS VARCHAR2(16), 
	SESSIONAGE NUMBER(10),
	UPDATETIME NUMBER(10),
	IN_OCTETS VARCHAR2(15), 
	IN_GIGA_OCTETS VARCHAR2(15), 
	OUT_OCTETS VARCHAR2(15), 
	OUT_GIGA_OCTETS VARCHAR2(15), 
	ALL_STATES NUMBER(6),
	NAS_TX_SPEED NUMBER(10), 
	NAS_RX_SPEED NUMBER(10), 
	CONNECT_INFO VARCHAR2(50), 
	DISCONNECT_CAUSE VARCHAR2(50), 
	CLASS VARCHAR2(250), 
	IN_PACKETS NUMBER(10), 
	OUT_PACKETS NUMBER(10), 
	NAS_IP VARCHAR2(40), 
	NAS_PORT VARCHAR2(50), 
	CLIENT_IP VARCHAR2(50), 
	PSID VARCHAR2(50), 
	ACCT_SESSION_ID VARCHAR2(50), 
	MULTISESS VARCHAR2(50), 
	START_TIME NUMBER(10), 
	V6PREFIX NUMBER(10), 
	V6IPHIGH64 VARCHAR2(50), 
	V6IPLOW64 VARCHAR2(50), 
	MAPT_IPV4ADDR VARCHAR2(50), 
	MAPT_IPV6PREFIX VARCHAR2(50), 
	MAPT_PSID_OFFSET NUMBER(10), 
	MAPT_PSID_LEN NUMBER(10), 
	MAPT_PSID NUMBER(10), 
	SESS_FPTS NUMBER(10)
)	
  SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE MZ_ITA_CDR_DATA
partition by range(CREATED_DATE)
(
  PARTITION PMAXVALUE  VALUES LESS THAN (MAXVALUE) TABLESPACE  MZ_ITA_CDR_DATA
);	
	
	
-- RE-CREATE CUMULATIVE_RADIUS TABLE WITH NEW DATATYPES
--
CREATE TABLE CUMULATIVE_RADIUS
(
	TRANSACTION_ID NUMBER NOT NULL, 
	RTR_TYPE VARCHAR2(50), 
	USERNAME VARCHAR2(50), 
	UNIQSESS VARCHAR2(16), 
	SESSIONAGE NUMBER(10), 
	UPDATETIME VARCHAR2(26), 
	IN_OCTETS VARCHAR2(50), 
	OUT_OCTETS VARCHAR2(50), 
	ALL_STATES NUMBER(6), 
	NAS_TX_SPEED NUMBER(10), 
	NAS_RX_SPEED NUMBER(10), 
	CONNECT_INFO VARCHAR2(50), 
	DISCONNECT_CAUSE VARCHAR2(50), 
	CLASS VARCHAR2(250), 
	CLIENT_IP VARCHAR2(50), 
	PSID VARCHAR2(50), 
	ACCT_SESSION_ID VARCHAR2(50), 
	START_TIME VARCHAR2(26), 
	V6PREFIX NUMBER(10), 
	V6IP VARCHAR2(50), 
	MAPT_IPV4ADDR VARCHAR2(50), 
	MAPT_IPV6PREFIX VARCHAR2(50), 
	MAPT_PSID_OFFSET NUMBER(10), 
	MAPT_PSID_LEN NUMBER(10), 
	MAPT_PSID NUMBER(10), 
	SDSI VARCHAR2(80), 
	PROCESSED_TIME VARCHAR2(26), 
	START_STOP_UPDATED_TIME VARCHAR2(26), 
	SESS_FPTS VARCHAR2(26)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;


-- COPY BACK IN THE DATA FROM CDR_INPUT_RTR_OLD
--
INSERT /*+ APPEND */ INTO CDR_INPUT_RTR (
  TRANSACTION_ID
, CREATED_DATE
, INPUT_FILENAME
, RTR_TYPE
, USERNAME
, UNIQSESS
, SESSIONAGE
, UPDATETIME
, IN_OCTETS
, IN_GIGA_OCTETS
, OUT_OCTETS
, OUT_GIGA_OCTETS
, ALL_STATES
, NAS_TX_SPEED
, NAS_RX_SPEED
, CONNECT_INFO
, DISCONNECT_CAUSE
, CLASS 
, IN_PACKETS
, OUT_PACKETS
, NAS_IP
, NAS_PORT
, CLIENT_IP
, PSID
, ACCT_SESSION_ID
, MULTISESS
, START_TIME
, V6PREFIX
, V6IPHIGH64
, V6IPLOW64
, MAPT_IPV4ADDR
, MAPT_IPV6PREFIX
, MAPT_PSID_OFFSET
, MAPT_PSID_LEN
, MAPT_PSID 
, SESS_FPTS
)
SELECT
  TRANSACTION_ID
, CREATED_DATE
, INPUT_FILENAME
, RTR_TYPE
, USERNAME
, UNIQSESS
, SESSIONAGE
, UPDATETIME
, TO_CHAR(IN_OCTETS)
, TO_CHAR(IN_GIGA_OCTETS)
, TO_CHAR(OUT_OCTETS)
, TO_CHAR(OUT_GIGA_OCTETS)
, ALL_STATES
, NAS_TX_SPEED
, NAS_RX_SPEED
, CONNECT_INFO
, DISCONNECT_CAUSE
, CLASS 
, IN_PACKETS
, OUT_PACKETS
, NAS_IP
, NAS_PORT
, CLIENT_IP
, PSID
, ACCT_SESSION_ID
, MULTISESS
, START_TIME
, V6PREFIX
, TO_CHAR(V6IPHIGH64)
, TO_CHAR(V6IPLOW64)
, MAPT_IPV4ADDR
, MAPT_IPV6PREFIX
, MAPT_PSID_OFFSET
, MAPT_PSID_LEN
, MAPT_PSID 
, SESS_FPTS
FROM CDR_INPUT_RTR_OLD;


-- COPY BACK IN THE DATA FROM CUMULATIVE_RADIUS_OLD
--
INSERT /*+ APPEND */ INTO CUMULATIVE_RADIUS (
  TRANSACTION_ID 
, RTR_TYPE 
, USERNAME 
, UNIQSESS 
, SESSIONAGE 
, UPDATETIME
, IN_OCTETS
, OUT_OCTETS
, ALL_STATES
, NAS_TX_SPEED
, NAS_RX_SPEED
, CONNECT_INFO
, DISCONNECT_CAUSE
, CLASS  
, CLIENT_IP
, PSID 
, ACCT_SESSION_ID 
, START_TIME 
, V6PREFIX 
, V6IP  
, MAPT_IPV4ADDR 
, MAPT_IPV6PREFIX
, MAPT_PSID_OFFSET
, MAPT_PSID_LEN
, MAPT_PSID
, SDSI
, PROCESSED_TIME
, START_STOP_UPDATED_TIME
, SESS_FPTS
)
SELECT
  TRANSACTION_ID 
, RTR_TYPE 
, USERNAME 
, UNIQSESS 
, SESSIONAGE 
, UPDATETIME
, TO_CHAR(IN_OCTETS)
, TO_CHAR(OUT_OCTETS)
, ALL_STATES
, NAS_TX_SPEED
, NAS_RX_SPEED
, CONNECT_INFO
, DISCONNECT_CAUSE
, CLASS  
, CLIENT_IP
, PSID 
, ACCT_SESSION_ID 
, START_TIME 
, V6PREFIX 
, V6IP  
, MAPT_IPV4ADDR 
, MAPT_IPV6PREFIX
, MAPT_PSID_OFFSET
, MAPT_PSID_LEN
, MAPT_PSID
, SDSI
, PROCESSED_TIME
, START_STOP_UPDATED_TIME
, SESS_FPTS
FROM CUMULATIVE_RADIUS_OLD;


-- RE_CREATE INDEX ON CDR_INPUT_RTR TABLE
--
CREATE INDEX CDR_INPUT_RTR_IDX1
  ON CDR_INPUT_RTR (UNIQSESS, INPUT_FILENAME, UPDATETIME) LOCAL;


-- RE-CREATE INDEX ON CUMULATIVE_RADIUS TABLE
--
CREATE INDEX CUMULATIVE_RADIUS_IDX1
  ON CUMULATIVE_RADIUS (UNIQSESS, SDSI);
