-- MED-651. Alter the BI and FMS Oracle DB sequences to cycle due to small max values

ALTER SEQUENCE MZ_CDR_OWNER.IMS_NOKIA_ROI_FRAUD_OUTPUT_SEQ CYCLE;

ALTER SEQUENCE MZ_CDR_OWNER.IMS_NOKIA_ROI_BI_FULL_OUTPUT_SEQ CYCLE;
