CREATE ROLE dar_readonly;
CREATE ROLE dar_update;
CREATE ROLE dar_execute;

CREATE USER dar_owner
IDENTIFIED BY dar_owner
DEFAULT TABLESPACE dar_data
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON dar_data;

GRANT CREATE SESSION TO dar_owner;
GRANT CREATE PROCEDURE TO dar_owner;
GRANT CREATE TABLE TO dar_owner;
GRANT CREATE VIEW TO dar_owner;
GRANT UNLIMITED TABLESPACE TO dar_owner;
GRANT GRANT ANY OBJECT PRIVILEGE TO dar_owner;
GRANT CREATE ANY EDITION TO dar_owner;

CREATE USER dar_user
IDENTIFIED BY dar
DEFAULT TABLESPACE dar_data
TEMPORARY TABLESPACE temp
QUOTA 0 ON dar_data;

GRANT CREATE SESSION TO dar_user;

GRANT dar_readonly TO dar_user;
GRANT dar_update TO dar_user;
