-- MZMOB-297 - Remove UNIT_ID of 1 and adjust UNIT_NAME for UNIT_ID 12 to 'SKYTMO'
--
DELETE FROM BUSINESS_UNITS
 WHERE UNIT_ID = 1;

UPDATE BUSINESS_UNITS
   SET UNIT_NAME = 'SKYTMO'
 WHERE UNIT_ID = '12';