-- Add indexes to all the MZ audit tables to enhance DB performance
--
CREATE INDEX IDX_AUD_I_TXN ON MZ_AUDIT_INPUT
(TXN_ID)
LOGGING
NOPARALLEL;

CREATE INDEX IDX_AUD_F_TXN ON MZ_AUDIT_FILTERED
(TXN_ID)
LOGGING
NOPARALLEL;

CREATE INDEX IDX_AUD_O_TXN ON MZ_AUDIT_OUTPUT
(TXN_ID)
LOGGING
NOPARALLEL;

CREATE INDEX IDX_AUD_FEAT_TXN ON MZ_AUDIT_FEATURES
(TXN_ID)
LOGGING
NOPARALLEL;

CREATE INDEX IDX_AUD_STAT_TXN ON MZ_AUDIT_STATISTICS
(TXN_ID)
LOGGING
NOPARALLEL;
