-- MZMOB-216 - Insert MZ duplicate configuration for FMS NRTRDE
--
INSERT INTO MZ_CONFIGURATION (PARAMETER, PARAMETER_VALUE) 
VALUES ('NRTRDE_DUP_BATCH_CHECK', 1);

-- MZMOB-234 - Insert 116 freephone numbers into the Mediation freephone table
--
INSERT INTO DN_FREEPHONE_PREFIX_CODES ( FREEPHONE_PREFIX_CODE,
FREEPHONE_PREFIX_DESC ) VALUES ( 
'116000', 'Hotline for missing children'); 

INSERT INTO DN_FREEPHONE_PREFIX_CODES ( FREEPHONE_PREFIX_CODE,
FREEPHONE_PREFIX_DESC ) VALUES ( 
'116111', 'Child helpline'); 

INSERT INTO DN_FREEPHONE_PREFIX_CODES ( FREEPHONE_PREFIX_CODE,
FREEPHONE_PREFIX_DESC ) VALUES ( 
'116123', 'Emotional support helpline'); 
