
-- Create new table CDR_INPUT_OCS_VOICE_AMDOCS_ROI
--
CREATE TABLE "MZ_MOB_DATA_OWNER"."CDR_INPUT_OCS_VOICE_AMDOCS_ROI" 
(
  TRANSACTION_ID                NUMBER          NOT NULL,
  CREATED_DATE                  DATE            DEFAULT sysdate               NOT NULL,
  INPUT_FILENAME                VARCHAR2(80 BYTE),
  A_NUMBER                      VARCHAR2(64 BYTE),
  B_NUMBER                      VARCHAR2(64 BYTE),
  EVENT_ID                      VARCHAR2(20 BYTE),
  EVENT_SPLIT_REASON            VARCHAR2(1 BYTE),
  EVENT_START_TIME              VARCHAR2(14 BYTE),
  EVENT_END_TIME                VARCHAR2(14 BYTE),
  EVENT_LOCAL_START_TIME        VARCHAR2(14 BYTE),
  EVENT_LOCAL_END_TIME          VARCHAR2(14 BYTE),
  OBJECT_TYPE                   VARCHAR2(1 BYTE),
  EXTERNAL_SUBSCRIBER_ID        VARCHAR2(64 BYTE),
  CUSTOMER_ID                   VARCHAR2(20 BYTE),
  SUBSCRIBER_ID                 VARCHAR2(20 BYTE),
  PRIMARY_RESOURCE_VALUE        VARCHAR2(32 BYTE),
  BILL_CYCLE_IDENTIFIER         VARCHAR2(8 BYTE),
  SERVICE_SUBTYPE               VARCHAR2(10 BYTE),
  SESSION_ID                    VARCHAR2(128 BYTE),
  INTERNAL_RESULT_CODE          VARCHAR2(10 BYTE),
  UOM                           VARCHAR2(1 BYTE),
  ACTUAL_USAGE                  VARCHAR2(20 BYTE),
  ROUNDED_UNIT                  VARCHAR2(20 BYTE),
  SERVICE_TYPE                  VARCHAR2(1 BYTE),
  CHARGE_AMOUNT                 VARCHAR2(10 BYTE),
  CALLING_NUMBER                VARCHAR2(64 BYTE),
  IMSI_CALLING_PARTY            VARCHAR2(64 BYTE),
  CALLING_PARTY_ROAMING_INFO    VARCHAR2(256 BYTE),
  PRIMARY_OFFER_ID              VARCHAR2(20 BYTE),
  CHARGED_NUMBER                VARCHAR2(64 BYTE),
  ROAMING_IND                   VARCHAR2(1 BYTE),
  HOME_COUNTRY_CODE_CALLING     VARCHAR2(3 BYTE),
  NETWORK_CODE_CALLING_PARTY    VARCHAR2(10 BYTE),
  ROAMING_COUNTRY_CODE_CALLING  VARCHAR2(3 BYTE),
  ROAMING_NETWORK_CODE_CALLING  VARCHAR2(10 BYTE),
  IS_ONLINE                     VARCHAR2(1 BYTE),
  CYCLE_START_TIME              VARCHAR2(14 BYTE),
  LAST_EFFECT_OFFER_ID          VARCHAR2(20 BYTE),
  CHARGE_CODE_INFO_CODE1        VARCHAR2(64 BYTE),
  CHARGE_CODE_INFO_NAME1        VARCHAR2(128 BYTE),
  CHARGE_CODE_INFO_AMOUNT1      VARCHAR2(9 BYTE),
  CHARGE_CODE_INFO_CODE2        VARCHAR2(64 BYTE),
  CHARGE_CODE_INFO_NAME2        VARCHAR2(128 BYTE),
  CHARGE_CODE_INFO_AMOUNT2      VARCHAR2(9 BYTE),
  CHARGE_CODE_INFO_CODE3        VARCHAR2(64 BYTE),
  CHARGE_CODE_INFO_NAME3        VARCHAR2(128 BYTE),
  CHARGE_CODE_INFO_AMOUNT3      VARCHAR2(9 BYTE),
  SUMMARY_CHARGE_CODE_INFO      VARCHAR2(64 BYTE),
  SUMMARY_CHARGE_CODE_NAME      VARCHAR2(128 BYTE),
  SUMMARY_CHARGE_AMOUNT         VARCHAR2(9 BYTE),
  HOME_COUNTRY_NAME_CALLING     VARCHAR2(64 BYTE),
  ROAMING_COUNTRY_NAME_CALLING  VARCHAR2(64 BYTE),
  DEBIT_AMOUNT                  VARCHAR2(20 BYTE),
  CURRENCY_IND                  VARCHAR2(3 BYTE),
  EXTERNAL_CUSTOMER_ID          VARCHAR2(64 BYTE),
  SERVICE_FILTER                VARCHAR2(20 BYTE),
  IMEI                          VARCHAR2(24 BYTE),
  OCS_SITE_ID                   VARCHAR2(20 BYTE),
  PRICING_ITEM_ID               VARCHAR2(20 BYTE),
  PAYMENT_TYPE                  VARCHAR2(10 BYTE),
  ROAMING_ZONE                  VARCHAR2(10 BYTE),
  ORIGINATING_CATEGORY          VARCHAR2(10 BYTE),
  DESTINATION_CATEGORY          VARCHAR2(10 BYTE),
  RERATE_INDICATOR              VARCHAR2(1 BYTE),
  DISCOUNT_AMOUNT               VARCHAR2(9 BYTE),
  CD_USAGE                      VARCHAR2(1 BYTE),
  REFUND_IND                    VARCHAR2(1 BYTE),
  UNAPPLIED_ALLOWANCE           VARCHAR2(20 BYTE),
  UNDEBIT_AMOUNT                VARCHAR2(10 BYTE),
  DURATION                      VARCHAR2(9 BYTE),
  RECIPIENT_NUMBER              VARCHAR2(64 BYTE),
  CALLED_NUMBER                 VARCHAR2(64 BYTE),
  IMSI_CALLED_PARTY             VARCHAR2(64 BYTE),
  CALL_DIRECTION                VARCHAR2(1 BYTE),
  CALL_FORWARDING_FLAG          VARCHAR2(2 BYTE),
  CALLED_PARTY_ROAMING_INFO     VARCHAR2(256 BYTE),
  EVENT_CHARGING_TIME           VARCHAR2(14 BYTE),
  TERMINATION_REASON            VARCHAR2(10 BYTE),
  ACCESS_PREFIX                 VARCHAR2(20 BYTE),
  ACCESS_PREFIX_TYPE            VARCHAR2(1 BYTE),
  REDIRECTING_NUMBER            VARCHAR2(25 BYTE),
  LOCATION_AREA_CALLING         VARCHAR2(10 BYTE),
  HOME_COUNTRY_CODE_CALLED      VARCHAR2(3 BYTE),
  HOME_AREA_CODE_CALLED         VARCHAR2(10 BYTE),
  NETWORK_CODE_CALLED_PARTY     VARCHAR2(10 BYTE),
  ROAMING_COUNTRY_CODE_CALLED   VARCHAR2(3 BYTE),
  ROAMING_NETWORK_CODE_CALLED   VARCHAR2(10 BYTE),
  SPECIAL_NUMBER_IND            VARCHAR2(1 BYTE),
  IMS_IDENTIFIER                VARCHAR2(128 BYTE),
  HOME_COUNTRY_NAME_CALLED      VARCHAR2(64 BYTE),
  ROAM_COUNTRY_NAME_CALLED      VARCHAR2(64 BYTE),
  HOME_AREA_NAME_CALLED         VARCHAR2(64 BYTE),
  FREE_DURATION_CONSUMED        VARCHAR2(20 BYTE),
  MCC_VISITED                   VARCHAR2(32 BYTE),
  MNC_VISITED                   VARCHAR2(32 BYTE),
  LAC_VISITED                   VARCHAR2(32 BYTE),
  CELL_ID                       VARCHAR2(32 BYTE),
  VLR_NUMBER                    VARCHAR2(32 BYTE),
  ON_NET                        VARCHAR2(1 BYTE),
  DIALED_NUMBER                 VARCHAR2(100 BYTE),
  ANI_INFO                      VARCHAR2(200 BYTE),
  SPECIAL_NUMBER_GROUP          VARCHAR2(10 BYTE),
  NETWORK_TYPE                  VARCHAR2(1 BYTE),
  RPP_STATE                     VARCHAR2(1 BYTE),
  IDD_BAND                      VARCHAR2(1 BYTE),
  SERVICE_CALL_DESC             VARCHAR2(64 BYTE)
)
SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE MZ_MOB_CDR_DATA
  partition by range(CREATED_DATE)
(
  PARTITION PMAXVALUE  VALUES LESS THAN (MAXVALUE) TABLESPACE  MZ_MOB_CDR_DATA);


-- Create new table CDR_INPUT_OCS_SMS_AMDOCS_ROI
--
CREATE TABLE "MZ_MOB_DATA_OWNER"."CDR_INPUT_OCS_SMS_AMDOCS_ROI" 
(
  TRANSACTION_ID                NUMBER          NOT NULL,
  CREATED_DATE                  DATE            DEFAULT sysdate               NOT NULL,
  INPUT_FILENAME                VARCHAR2(80 BYTE),
  A_NUMBER                      VARCHAR2(64 BYTE),
  B_NUMBER                      VARCHAR2(64 BYTE),
  EVENT_ID                      VARCHAR2(20 BYTE),
  EVENT_SPLIT_REASON            VARCHAR2(1 BYTE),
  EVENT_START_TIME              VARCHAR2(14 BYTE),
  EVENT_END_TIME                VARCHAR2(14 BYTE),
  EVENT_LOCAL_START_TIME        VARCHAR2(14 BYTE),
  EVENT_LOCAL_END_TIME          VARCHAR2(14 BYTE),
  OBJECT_TYPE                   VARCHAR2(1 BYTE),
  EXTERNAL_SUBSCRIBER_ID        VARCHAR2(64 BYTE),
  CUSTOMER_ID                   VARCHAR2(20 BYTE),
  SUBSCRIBER_ID                 VARCHAR2(20 BYTE),
  PRIMARY_RESOURCE_VALUE        VARCHAR2(32 BYTE),
  BILL_CYCLE_IDENTIFIER         VARCHAR2(8 BYTE),
  SERVICE_SUBTYPE               VARCHAR2(10 BYTE),
  SESSION_ID                    VARCHAR2(128 BYTE),
  INTERNAL_RESULT_CODE          VARCHAR2(10 BYTE),
  UOM                           VARCHAR2(1 BYTE),
  ACTUAL_USAGE                  VARCHAR2(20 BYTE),
  ROUNDED_UNIT                  VARCHAR2(20 BYTE),
  SERVICE_TYPE                  VARCHAR2(1 BYTE),
  CHARGE_AMOUNT                 VARCHAR2(10 BYTE),
  CALLING_NUMBER                VARCHAR2(64 BYTE),
  IMSI_CALLING_PARTY            VARCHAR2(64 BYTE),
  CALLING_PARTY_ROAMING_INFO    VARCHAR2(256 BYTE),
  PRIMARY_OFFER_ID              VARCHAR2(20 BYTE),
  CHARGED_NUMBER                VARCHAR2(64 BYTE),
  ROAMING_IND                   VARCHAR2(1 BYTE),
  HOME_COUNTRY_CODE_CALLING     VARCHAR2(3 BYTE),
  NETWORK_CODE_CALLING_PARTY    VARCHAR2(10 BYTE),
  ROAMING_COUNTRY_CODE_CALLING  VARCHAR2(3 BYTE),
  ROAMING_NETWORK_CODE_CALLING  VARCHAR2(10 BYTE),
  IS_ONLINE                     VARCHAR2(1 BYTE),
  CYCLE_START_TIME              VARCHAR2(14 BYTE),
  LAST_EFFECT_OFFER_ID          VARCHAR2(20 BYTE),
  CHARGE_CODE_INFO_CODE1        VARCHAR2(64 BYTE),
  CHARGE_CODE_INFO_NAME1        VARCHAR2(128 BYTE),
  CHARGE_CODE_INFO_AMOUNT1      VARCHAR2(9 BYTE),
  CHARGE_CODE_INFO_CODE2        VARCHAR2(64 BYTE),
  CHARGE_CODE_INFO_NAME2        VARCHAR2(128 BYTE),
  CHARGE_CODE_INFO_AMOUNT2      VARCHAR2(9 BYTE),
  CHARGE_CODE_INFO_CODE3        VARCHAR2(64 BYTE),
  CHARGE_CODE_INFO_NAME3        VARCHAR2(128 BYTE),
  CHARGE_CODE_INFO_AMOUNT3      VARCHAR2(9 BYTE),
  SUMMARY_CHARGE_CODE_INFO      VARCHAR2(64 BYTE),
  SUMMARY_CHARGE_CODE_NAME      VARCHAR2(128 BYTE),
  SUMMARY_CHARGE_AMOUNT         VARCHAR2(9 BYTE),
  HOME_COUNTRY_NAME_CALLING     VARCHAR2(64 BYTE),
  ROAMING_COUNTRY_NAME_CALLING  VARCHAR2(64 BYTE),
  DEBIT_AMOUNT                  VARCHAR2(20 BYTE),
  CURRENCY_IND                  VARCHAR2(3 BYTE),
  EXTERNAL_CUSTOMER_ID          VARCHAR2(64 BYTE),
  SERVICE_FILTER                VARCHAR2(20 BYTE),
  IMEI                          VARCHAR2(24 BYTE),
  OCS_SITE_ID                   VARCHAR2(20 BYTE),
  PRICING_ITEM_ID               VARCHAR2(20 BYTE),
  PAYMENT_TYPE                  VARCHAR2(10 BYTE),
  ROAMING_ZONE                  VARCHAR2(10 BYTE),
  ORIGINATING_CATEGORY          VARCHAR2(10 BYTE),
  DESTINATION_CATEGORY          VARCHAR2(10 BYTE),
  RERATE_INDICATOR              VARCHAR2(1 BYTE),
  DISCOUNT_AMOUNT               VARCHAR2(9 BYTE),
  CD_USAGE                      VARCHAR2(1 BYTE),
  REFUND_IND                    VARCHAR2(1 BYTE),
  UNAPPLIED_ALLOWANCE           VARCHAR2(20 BYTE),
  UNDEBIT_AMOUNT                VARCHAR2(10 BYTE),
  RECIPIENT_NUMBER              VARCHAR2(64 BYTE),
  CALLED_NUMBER                 VARCHAR2(64 BYTE),
  IMSI_CALLED_PARTY             VARCHAR2(64 BYTE),
  CALL_DIRECTION                VARCHAR2(1 BYTE),
  CALL_FORWARDING_FLAG          VARCHAR2(2 BYTE),
  CALLED_PARTY_ROAMING_INFO     VARCHAR2(256 BYTE),
  LOCATION_AREA_CALLING         VARCHAR2(10 BYTE),
  HOME_COUNTRY_CODE_CALLED      VARCHAR2(3 BYTE),
  HOME_AREA_CODE_CALLED         VARCHAR2(10 BYTE),
  NETWORK_CODE_CALLED_PARTY     VARCHAR2(10 BYTE),
  ROAMING_COUNTRY_CODE_CALLED   VARCHAR2(3 BYTE),
  ROAMING_NETWORK_CODE_CALLED   VARCHAR2(10 BYTE),
  SPECIAL_NUMBER_IND            VARCHAR2(10 BYTE),
  HOME_COUNTRYNAME_CALLED       VARCHAR2(64 BYTE),
  ROAM_COUNTRYNAME_CALLED       VARCHAR2(64 BYTE),
  HOME_AREA_NAME_CALLED         VARCHAR2(64 BYTE),
  FREE_OCCURRENCE_CONSUMED      VARCHAR2(20 BYTE),
  ON_NET                        VARCHAR2(1 BYTE),
  DIALED_NUMBER                 VARCHAR2(100 BYTE),
  SMS_ID                        VARCHAR2(32 BYTE),
  SMS_LENGTH                    VARCHAR2(10 BYTE),
  SMSC_ADDRESS                  VARCHAR2(20 BYTE),
  MT_MSC_ADDRESS                VARCHAR2(32 BYTE),
  MO_MSC_ADDRESS                VARCHAR2(32 BYTE),
  SPECIAL_NUMBER_GROUP          VARCHAR2(10 BYTE),
  RPP_STATE                     VARCHAR2(1 BYTE),
  IDD_BAND                      VARCHAR2(1 BYTE),
  SERVICE_CALL_DESC             VARCHAR2(64 BYTE)
)
SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE MZ_MOB_CDR_DATA
  partition by range(CREATED_DATE)
(
  PARTITION PMAXVALUE  VALUES LESS THAN (MAXVALUE) TABLESPACE  MZ_MOB_CDR_DATA
);


-- Create new table CDR_INPUT_OCS_GPRS_AMDOCS_ROI
--
CREATE TABLE "MZ_MOB_DATA_OWNER"."CDR_INPUT_OCS_GPRS_AMDOCS_ROI" 
(
 TRANSACTION_ID                NUMBER          NOT NULL,
  CREATED_DATE                  DATE            DEFAULT sysdate               NOT NULL,
  INPUT_FILENAME                VARCHAR2(80 BYTE),
  A_NUMBER                      VARCHAR2(64 BYTE),
  EVENT_ID                      VARCHAR2(20 BYTE),
  EVENT_SPLIT_REASON            VARCHAR2(1 BYTE),
  EVENT_START_TIME              VARCHAR2(14 BYTE),
  EVENT_END_TIME                VARCHAR2(14 BYTE),
  EVENT_LOCAL_START_TIME        VARCHAR2(14 BYTE),
  EVENT_LOCAL_END_TIME          VARCHAR2(14 BYTE),
  OBJECT_TYPE                   VARCHAR2(1 BYTE),
  EXTERNAL_SUBSCRIBER_ID        VARCHAR2(64 BYTE),
  CUSTOMER_ID                   VARCHAR2(20 BYTE),
  SUBSCRIBER_ID                 VARCHAR2(20 BYTE),
  PRIMARY_RESOURCE_VALUE        VARCHAR2(32 BYTE),
  BILL_CYCLE_IDENTIFIER         VARCHAR2(8 BYTE),
  SERVICE_SUBTYPE               VARCHAR2(10 BYTE),
  SESSION_ID                    VARCHAR2(128 BYTE),
  INTERNAL_RESULT_CODE          VARCHAR2(10 BYTE),
  UOM                           VARCHAR2(1 BYTE),
  ACTUAL_USAGE                  VARCHAR2(20 BYTE),
  ROUNDED_UNIT                  VARCHAR2(20 BYTE),
  SERVICE_TYPE                  VARCHAR2(1 BYTE),
  CHARGE_AMOUNT                 VARCHAR2(10 BYTE),
  CALLING_NUMBER                VARCHAR2(64 BYTE),
  IMSI_CALLING_PARTY            VARCHAR2(64 BYTE),
  CALLING_PARTY_ROAMING_INFO    VARCHAR2(256 BYTE),
  PRIMARY_OFFER_ID              VARCHAR2(20 BYTE),
  CHARGED_NUMBER                VARCHAR2(64 BYTE),
  ROAMING_IND                   VARCHAR2(1 BYTE),
  HOME_COUNTRY_CODE_CALLING     VARCHAR2(3 BYTE),
  NETWORK_CODE_CALLING_PARTY    VARCHAR2(10 BYTE),
  ROAMING_COUNTRY_CODE_CALLING  VARCHAR2(3 BYTE),
  ROAMING_NETWORK_CODE_CALLING  VARCHAR2(10 BYTE),
  IS_ONLINE                     VARCHAR2(1 BYTE),
  CYCLE_START_TIME              VARCHAR2(14 BYTE),
  LAST_EFFECT_OFFER_ID          VARCHAR2(20 BYTE),
  CHARGE_CODE_INFO_CODE1        VARCHAR2(64 BYTE),
  CHARGE_CODE_INFO_NAME1        VARCHAR2(128 BYTE),
  CHARGE_CODE_INFO_AMOUNT1      VARCHAR2(9 BYTE),
  CHARGE_CODE_INFO_CODE2        VARCHAR2(64 BYTE),
  CHARGE_CODE_INFO_NAME2        VARCHAR2(128 BYTE),
  CHARGE_CODE_INFO_AMOUNT2      VARCHAR2(9 BYTE),
  CHARGE_CODE_INFO_CODE3        VARCHAR2(64 BYTE),
  CHARGE_CODE_INFO_NAME3        VARCHAR2(128 BYTE),
  CHARGE_CODE_INFO_AMOUNT3      VARCHAR2(9 BYTE),
  SUMMARY_CHARGE_CODE_INFO      VARCHAR2(64 BYTE),
  SUMMARY_CHARGE_CODE_NAME      VARCHAR2(128 BYTE),
  SUMMARY_CHARGE_AMOUNT         VARCHAR2(9 BYTE),
  HOME_COUNTRY_NAME_CALLING     VARCHAR2(64 BYTE),
  ROAMING_COUNTRY_NAME_CALLING  VARCHAR2(64 BYTE),
  DEBIT_AMOUNT                  VARCHAR2(20 BYTE),
  CURRENCY_IND                  VARCHAR2(3 BYTE),
  EXTERNAL_CUSTOMER_ID          VARCHAR2(64 BYTE),
  SERVICE_FILTER                VARCHAR2(20 BYTE),
  IMEI                          VARCHAR2(24 BYTE),
  OCS_SITE_ID                   VARCHAR2(20 BYTE),
  PRICING_ITEM_ID               VARCHAR2(20 BYTE),
  PAYMENT_TYPE                  VARCHAR2(10 BYTE),
  ROAMING_ZONE                  VARCHAR2(10 BYTE),
  ORIGINATING_CATEGORY          VARCHAR2(10 BYTE),
  DESTINATION_CATEGORY          VARCHAR2(10 BYTE),
  RERATE_INDICATOR              VARCHAR2(1 BYTE),
  DISCOUNT_AMOUNT               VARCHAR2(9 BYTE),
  CD_USAGE                      VARCHAR2(1 BYTE),
  REFUND_IND                    VARCHAR2(1 BYTE),
  UNAPPLIED_ALLOWANCE           VARCHAR2(20 BYTE),
  UNDEBIT_AMOUNT                VARCHAR2(10 BYTE),
  RESULT_REASON                 VARCHAR2(64 BYTE),
  CELL_ID_DATA                  VARCHAR2(20 BYTE),
  EVENT_CHARGING_TIME           VARCHAR2(14 BYTE),
  FREE_VOLUME_CONSUMED          VARCHAR2(20 BYTE),
  MCC_VISITED                   VARCHAR2(32 BYTE),
  MNC_VISITED                   VARCHAR2(32 BYTE),
  VLR_NUMBER                    VARCHAR2(32 BYTE),
  APN                           VARCHAR2(30 BYTE),
  ACCESS_NETWORK_ADDRESS        VARCHAR2(22 BYTE),
  GGSN_ADDRESS                  VARCHAR2(22 BYTE),
  SGSN_TIMESTAMP                VARCHAR2(14 BYTE),
  TOTAL_USAGE                   VARCHAR2(20 BYTE),
  UPLINK                        VARCHAR2(20 BYTE),
  DOWNLINK                      VARCHAR2(20 BYTE),
  ELAPSED_DURATION              VARCHAR2(10 BYTE),
  QOS                           VARCHAR2(40 BYTE),
  NETWORK_CHARGING_ID           VARCHAR2(10 BYTE),
  RATING_GROUP_ID               VARCHAR2(10 BYTE),
  RAT_TYPE                      VARCHAR2(10 BYTE),
  ACCESS_TYPE_VALUE             VARCHAR2(20 BYTE),
  RATING_GROUP_VALUE            VARCHAR2(4 BYTE),
  LAC_VISITED                   VARCHAR2(32 BYTE),
  RPP_STATE                     VARCHAR2(1 BYTE)
)
SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE MZ_MOB_CDR_DATA
  partition by range(CREATED_DATE)
(
  PARTITION PMAXVALUE  VALUES LESS THAN (MAXVALUE) TABLESPACE  MZ_MOB_CDR_DATA
);



-- Create the indexes in the CDR_INPUT_OCS_VOICE_AMDOCS_ROI table
--
CREATE INDEX CDR_INPUT_OCS_VOICE_ROI_A_IDX1 ON CDR_INPUT_OCS_VOICE_AMDOCS_ROI (CREATED_DATE) LOCAL;

CREATE INDEX CDR_INPUT_OCS_VOICE_ROI_A_IDX2 ON CDR_INPUT_OCS_VOICE_AMDOCS_ROI (TRANSACTION_ID) LOCAL;

CREATE INDEX CDR_INPUT_OCS_VOICE_ROI_A_IDX3 ON CDR_INPUT_OCS_VOICE_AMDOCS_ROI (A_NUMBER) LOCAL;

CREATE INDEX CDR_INPUT_OCS_VOICE_ROI_A_IDX4 ON CDR_INPUT_OCS_VOICE_AMDOCS_ROI (B_NUMBER) LOCAL;

CREATE INDEX CDR_INPUT_OCS_VOICE_ROI_A_IDX5 ON CDR_INPUT_OCS_VOICE_AMDOCS_ROI (IMSI_CALLING_PARTY) LOCAL;


-- Create the indexes in the CDR_INPUT_OCS_SMS_AMDOCS_ROI table
--
CREATE INDEX CDR_INPUT_OCS_SMS_ROI_A_IDX1 ON CDR_INPUT_OCS_SMS_AMDOCS_ROI (CREATED_DATE) LOCAL;

CREATE INDEX CDR_INPUT_OCS_SMS_ROI_A_IDX2 ON CDR_INPUT_OCS_SMS_AMDOCS_ROI (TRANSACTION_ID) LOCAL;

CREATE INDEX CDR_INPUT_OCS_SMS_ROI_A_IDX3 ON CDR_INPUT_OCS_SMS_AMDOCS_ROI (A_NUMBER) LOCAL;

CREATE INDEX CDR_INPUT_OCS_SMS_ROI_A_IDX4 ON CDR_INPUT_OCS_SMS_AMDOCS_ROI (B_NUMBER) LOCAL;




-- Create the indexes in the CDR_INPUT_OCS_GPRS_AMDOCS_ROI table
--
CREATE INDEX CDR_INPUT_OCS_GPRS_ROI_A_IDX1 ON CDR_INPUT_OCS_GPRS_AMDOCS_ROI (CREATED_DATE) LOCAL;

CREATE INDEX CDR_INPUT_OCS_GPRS_ROI_A_IDX2 ON CDR_INPUT_OCS_GPRS_AMDOCS_ROI (TRANSACTION_ID) LOCAL;

CREATE INDEX CDR_INPUT_OCS_GPRS_ROI_A_IDX3 ON CDR_INPUT_OCS_GPRS_AMDOCS_ROI (A_NUMBER) LOCAL;
