-- MZMOB-778 SMSC-IBS Incoming/Outgoing path for SMSoLTE CDRs should populate MCCMNC instead of 'LTE'

-- INSERT SKY SMSC LTE GT NUMBERS for SMSC SINCH
--
INSERT INTO SKY_SMSC_LTE_GT ( GT, ROLE_OF_NODE,
DESCRIPTION ) VALUES (
'447488203', 0, 'ENGLO IP-SM-GW(VoLTE Roaming)'); 

INSERT INTO SKY_SMSC_LTE_GT ( GT, ROLE_OF_NODE,
DESCRIPTION ) VALUES (
'447488204', 0, 'MIMNC IP-SM-GW(VoLTE Roaming)'); 

INSERT INTO SKY_SMSC_LTE_GT ( GT, ROLE_OF_NODE,
DESCRIPTION ) VALUES (
'447488205', 0, 'ENBGK IP-SM-GW(VoLTE Roaming)'); 

INSERT INTO SKY_SMSC_LTE_GT ( GT, ROLE_OF_NODE,
DESCRIPTION ) VALUES (
'447488206', 0, 'ENLCS IP-SM-GW(VoLTE Roaming)'); 
