CREATE TABLE CDR_OUTPUT_KENAN_GPRS_ROI
(
  TRANSACTION_ID       NUMBER                   NOT NULL,
  CREATED_DATE         DATE                     DEFAULT sysdate               NOT NULL,
  INPUT_FILENAME       VARCHAR2(100 BYTE),
  RECORD_TYPE          VARCHAR2(10 BYTE),
  TYPE_ID_USG          VARCHAR2(10 BYTE),
  TRANS_DT             VARCHAR2(20 BYTE),
  POINT_ORIGIN         VARCHAR2(30 BYTE),
  PRIMARY_UNITS        VARCHAR2(30 BYTE),
  PROVIDER_ID          VARCHAR2(10 BYTE),
  EXT_TRACKING_ID      VARCHAR2(40 BYTE),
  AMOUNT               VARCHAR2(20 BYTE),
  UNITS_CURRENCY_CODE  VARCHAR2(10 BYTE),
  VISIT_COUNTRY_CODE   VARCHAR2(60 BYTE),
  OCS_CHARGE_CODE_ID   VARCHAR2(30 BYTE),
  EXTERNAL_ID          VARCHAR2(80 BYTE),
  EXTERNAL_ID_TYPE     VARCHAR2(10 BYTE),
  CUSTOMER_TAG         VARCHAR2(30 BYTE)
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
partition by range(CREATED_DATE)
(
  PARTITION PMAXVALUE  VALUES LESS THAN (MAXVALUE) TABLESPACE  MZ_MOB_CDR_DATA);

CREATE INDEX CDR_OUTPUT_KENAN_GPRS_ROI_IDX1 ON CDR_OUTPUT_KENAN_GPRS_ROI (INPUT_FILENAME) LOCAL;

CREATE INDEX CDR_OUTPUT_KENAN_GPRS_ROI_IDX2 ON CDR_OUTPUT_KENAN_GPRS_ROI (CREATED_DATE) LOCAL;

CREATE INDEX CDR_OUTPUT_KENAN_GPRS_ROI_IDX3 ON CDR_OUTPUT_KENAN_GPRS_ROI (TRANSACTION_ID) LOCAL PARALLEL 16;

ALTER INDEX CDR_OUTPUT_KENAN_GPRS_ROI_IDX3 NOPARALLEL;