-- MZMOB-810 ROI Kerry AOCS mediation functions implementation

create table MZ_MOB_DATA_OWNER.DN_FREEPHONE_CODES_SMS_ROI (
    SMS_CODE    VARCHAR2(32) NOT NULL,
    DESCRIPTION VARCHAR2(50)
);

-- Initial inserts
INSERT INTO MZ_MOB_DATA_OWNER.DN_FREEPHONE_CODES_SMS_ROI (SMS_CODE, DESCRIPTION) VALUES ('112', 'Emergency');
INSERT INTO MZ_MOB_DATA_OWNER.DN_FREEPHONE_CODES_SMS_ROI (SMS_CODE, DESCRIPTION) VALUES ('50', 'Free Text');
