CREATE TABLE DN_FREEPHONE_PREFIX_CODES_ROI
( FREEPHONE_PREFIX_CODE  VARCHAR2(15) NOT NULL
, FREEPHONE_PREFIX_DESC  VARCHAR2(200) NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;

CREATE UNIQUE INDEX DN_FREEPHONE_PREFIX_CODES_ROI_PK ON DN_FREEPHONE_PREFIX_CODES_ROI
(FREEPHONE_PREFIX_CODE);

ALTER TABLE DN_FREEPHONE_PREFIX_CODES_ROI 
ADD CONSTRAINT DN_FREEPHONE_PREFIX_CODES_ROI_PK 
PRIMARY KEY (FREEPHONE_PREFIX_CODE);


-- Insert rows
--
-- INSERT FREEPHONE PREFIX CODES_ROI
--
INSERT INTO DN_FREEPHONE_PREFIX_CODES_ROI ( FREEPHONE_PREFIX_CODE,
FREEPHONE_PREFIX_DESC ) VALUES ( 
'3531800', 'Freephone prefix'); 

INSERT INTO DN_FREEPHONE_PREFIX_CODES_ROI ( FREEPHONE_PREFIX_CODE,
FREEPHONE_PREFIX_DESC ) VALUES ( 
'1800', 'Freephone prefix'); 

INSERT INTO DN_FREEPHONE_PREFIX_CODES_ROI ( FREEPHONE_PREFIX_CODE,
FREEPHONE_PREFIX_DESC ) VALUES ( 
'0800', 'Freephone prefix'); 
INSERT INTO DN_FREEPHONE_PREFIX_CODES_ROI ( FREEPHONE_PREFIX_CODE,
FREEPHONE_PREFIX_DESC ) VALUES ( 
'00800', 'International Freephone prefix'); 

INSERT INTO DN_FREEPHONE_PREFIX_CODES_ROI ( FREEPHONE_PREFIX_CODE,
FREEPHONE_PREFIX_DESC ) VALUES ( 
'1979', 'Sky Customer Care number'); 

INSERT INTO DN_FREEPHONE_PREFIX_CODES_ROI ( FREEPHONE_PREFIX_CODE,
FREEPHONE_PREFIX_DESC ) VALUES ( 
'116000', 'Hotlines For Missing Children');

INSERT INTO DN_FREEPHONE_PREFIX_CODES_ROI ( FREEPHONE_PREFIX_CODE,
FREEPHONE_PREFIX_DESC ) VALUES ( 
'116006', 'Helpline For Victims Of Crime');

INSERT INTO DN_FREEPHONE_PREFIX_CODES_ROI ( FREEPHONE_PREFIX_CODE,
FREEPHONE_PREFIX_DESC ) VALUES ( 
'116111', 'Child Helplines');

INSERT INTO DN_FREEPHONE_PREFIX_CODES_ROI ( FREEPHONE_PREFIX_CODE,
FREEPHONE_PREFIX_DESC ) VALUES ( 
'116117', 'Non-Emergency Medical On Call Service');

INSERT INTO DN_FREEPHONE_PREFIX_CODES_ROI ( FREEPHONE_PREFIX_CODE,
FREEPHONE_PREFIX_DESC ) VALUES ( 
'116123', 'Emotional Support Helplines ');


INSERT INTO DN_FREEPHONE_PREFIX_CODES_ROI ( FREEPHONE_PREFIX_CODE,
FREEPHONE_PREFIX_DESC ) VALUES ( 
'196', 'Telemessaging Services'); 

INSERT INTO DN_FREEPHONE_PREFIX_CODES_ROI ( FREEPHONE_PREFIX_CODE,
FREEPHONE_PREFIX_DESC ) VALUES ( 
'999', 'Emergency Services');

INSERT INTO DN_FREEPHONE_PREFIX_CODES_ROI ( FREEPHONE_PREFIX_CODE,
FREEPHONE_PREFIX_DESC ) VALUES ( 
'911', 'Emergency Services'); 

INSERT INTO DN_FREEPHONE_PREFIX_CODES_ROI ( FREEPHONE_PREFIX_CODE,
FREEPHONE_PREFIX_DESC ) VALUES ( 
'112', 'Emergency Services');
