-- MZMOB-818 - Handle SMSC shortcodes for IBS in Sinch SMSC ROI
--
CREATE TABLE SKY_SHORTCODE_ACCOUNT_ROI
(
  SHORTCODE_ACCOUNT	VARCHAR2(30 BYTE),
  DESCRIPTION	VARCHAR2(40 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;


-- INSERT SHORTCODE ACCOUNTS
--
INSERT INTO SKY_SHORTCODE_ACCOUNT_ROI ( SHORTCODE_ACCOUNT,
DESCRIPTION ) VALUES (
'OTA_ROI', 'Sky SMSC Shortcode Account');

INSERT INTO SKY_SHORTCODE_ACCOUNT_ROI ( SHORTCODE_ACCOUNT,
DESCRIPTION ) VALUES (
'VMS_ROI', 'Sky SMSC Shortcode Account');

INSERT INTO SKY_SHORTCODE_ACCOUNT_ROI ( SHORTCODE_ACCOUNT,
DESCRIPTION ) VALUES (
'VVG_ROI', 'Sky SMSC Shortcode Account');

INSERT INTO SKY_SHORTCODE_ACCOUNT_ROI ( SHORTCODE_ACCOUNT,
DESCRIPTION ) VALUES (
'CEL_WSMS_ROI', 'Sky SMSC Shortcode Account');

INSERT INTO SKY_SHORTCODE_ACCOUNT_ROI ( SHORTCODE_ACCOUNT,
DESCRIPTION ) VALUES (
'CEL_WSMS_BACKUP_ROI', 'Sky SMSC Shortcode Account');