-- MZMOB-312 Build
--
-- Create the IGOR package and procedures
--
CREATE INDEX BC_ACCT_IDX1 ON BC_ACCT (ACCT_ID ASC);
CREATE INDEX BC_ACCT_IDX2 ON BC_ACCT (CUST_ID ASC);
CREATE INDEX BC_SUB_DEF_ACCT_IDX1 ON BC_SUB_DEF_ACCT (DFT_ACCT_ID ASC);
CREATE INDEX BC_SUB_DEF_ACCT_IDX2 ON BC_SUB_DEF_ACCT (SUB_ID ASC);
CREATE INDEX BC_SUB_IDEN_IDX1 ON BC_SUB_IDEN (SUB_ID ASC);
CREATE INDEX BC_SUB_IDEN_IDX2 ON BC_SUB_IDEN (CUST_ID ASC);
CREATE INDEX BC_SUB_IDEN_IDX3 ON BC_SUB_IDEN (PRIMARY_FLAG ASC);
CREATE INDEX BC_SUBSCRIBER_IDX1 ON BC_SUBSCRIBER (SUB_ID ASC);
CREATE INDEX BC_SUBSCRIBER_IDX2 ON BC_SUBSCRIBER (CUST_ID ASC);
CREATE INDEX PE_FREE_UNIT_IDX1 ON PE_FREE_UNIT (FREE_UNIT_OWNER_ID ASC);
CREATE INDEX PE_FREE_UNIT_IDX2 ON PE_FREE_UNIT (CUST_ID ASC);
