-- MZMOB-774 . Comfone DCH Mediation Functions for Ireland Mobile
-- CDR_INPUT_TAP for ROI
--
  CREATE TABLE MZ_MOB_DATA_OWNER.CDR_INPUT_TAP_ROI
   (	 TRANSACTION_ID        NUMBER                  NOT NULL,
  CREATED_DATE          DATE                    DEFAULT sysdate               NOT NULL,
  INPUT_FILENAME        VARCHAR2(50 BYTE),
  SOURCE_TADIG          VARCHAR2(10 BYTE),
  POS_IN_FILE           NUMBER,
  CALL_EVENT_TYPE       VARCHAR2(5 BYTE),
  CHARGEABLE_IMSI       VARCHAR2(30 BYTE),
  CHARGEABLE_MSISDN     VARCHAR2(30 BYTE),
  CHARGEABLE_IMEI       VARCHAR2(30 BYTE),
  CALLED_NUMBER         VARCHAR2(30 BYTE),
  DIALLED_DIGITS        VARCHAR2(30 BYTE),
  CALLING_NUMBER        VARCHAR2(30 BYTE),
  THIRD_PTY_NUMBER      VARCHAR2(30 BYTE),
  SMS_NUMBER            VARCHAR2(30 BYTE),
  A_NUMBER              VARCHAR2(30 BYTE),
  B_NUMBER              VARCHAR2(30 BYTE),
  START_TIME            VARCHAR2(30 BYTE),
  DURATION              VARCHAR2(30 BYTE),
  CAUSE_FOR_TERM        VARCHAR2(30 BYTE),
  CALL_REFERENCE        VARCHAR2(30 BYTE),
  REC_ENT_TYPE1         VARCHAR2(30 BYTE),
  REC_ENT_ID1           VARCHAR2(100 BYTE),
  REC_ENT_TYPE2         VARCHAR2(30 BYTE),
  REC_ENT_ID2           VARCHAR2(100 BYTE),
  REC_ENT_TYPE3         VARCHAR2(30 BYTE),
  REC_ENT_ID3           VARCHAR2(100 BYTE),
  LAC                   VARCHAR2(30 BYTE),
  CI                    VARCHAR2(30 BYTE),
  SERVING_NETWORK       VARCHAR2(30 BYTE),
  CHARGE                VARCHAR2(30 BYTE),
  SERVICE_CODE          VARCHAR2(30 BYTE),
  CAMEL_SERVICE_KEY     VARCHAR2(30 BYTE),
  CAMEL_DESTINATION     VARCHAR2(30 BYTE),
  SS_CODE               VARCHAR2(30 BYTE),
  SS_ACTION             VARCHAR2(30 BYTE),
  SS_PARAMS             VARCHAR2(30 BYTE),
  CHARGED_PTY_STATUS    VARCHAR2(30 BYTE),
  NON_CHARGED_NUMBER    VARCHAR2(30 BYTE),
  ORIG_NETWORK          VARCHAR2(30 BYTE),
  DEST_NETWORK          VARCHAR2(30 BYTE),
  PDP_ADDRESS           VARCHAR2(100 BYTE),
  APN_NI                VARCHAR2(30 BYTE),
  APN_OI                VARCHAR2(30 BYTE),
  CHARGING_ID           VARCHAR2(30 BYTE),
  DATA_VOL_IN           VARCHAR2(30 BYTE),
  DATA_VOL_OUT          VARCHAR2(30 BYTE),
  MODIFIED_IMSI         VARCHAR2(30 BYTE),
  REC_ENT_TYPE4         VARCHAR2(30 BYTE),
  REC_ENT_ID4           VARCHAR2(100 BYTE),
  CHARGED_ITEM1         VARCHAR2(5 BYTE),
  SERVING_BID           VARCHAR2(10 BYTE),
  LOCATION_DESCRIPTION  VARCHAR2(150 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE MZ_MOB_CDR_DATA
partition by range(CREATED_DATE)
(
  PARTITION PMAXVALUE  VALUES LESS THAN (MAXVALUE) TABLESPACE  MZ_MOB_CDR_DATA);
  
CREATE INDEX CDR_INPUT_TAP_ROI_IDX1 ON CDR_INPUT_TAP_ROI (A_NUMBER);
 
CREATE INDEX CDR_INPUT_TAP_ROI_IDX2 ON CDR_INPUT_TAP_ROI (B_NUMBER) ;
CREATE INDEX CDR_INPUT_TAP_ROI_IDX3 ON CDR_INPUT_TAP_ROI (CREATED_DATE);
CREATE INDEX CDR_INPUT_TAP_ROI_IDX4 ON CDR_INPUT_TAP_ROI (TRANSACTION_ID) ;
 
 -- Added Business Unit for ROIMOB

INSERT INTO BUSINESS_UNITS (UNIT_ID, UNIT_NAME) VALUES (17, 'ROIMOB');