-- MZMOB-790. Nokia IMS Mediation Functions for Ireland Mobile
-- Ireland's MPC lookup.

CREATE TABLE MZ_MOB_DATA_OWNER.MPC_LOOKUP_ROI 
( 
  MPC_PREFIX_NUMBER  VARCHAR2(15) NOT NULL,
  STATUS VARCHAR2(40) NOT NULL,
  COMMS_PROVIDER VARCHAR2(80) NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;

-- create index
CREATE UNIQUE INDEX MPC_LOOKUP_ROI_PK ON MPC_LOOKUP_ROI
(MPC_PREFIX_NUMBER);

-- Add contraints
--

ALTER TABLE MPC_LOOKUP_ROI
ADD CONSTRAINT MPC_LOOKUP_ROI_PK 
PRIMARY KEY (MPC_PREFIX_NUMBER );

-- Inserting rows
INSERT INTO MZ_MOB_DATA_OWNER.MPC_LOOKUP_ROI ( MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER ) 
VALUES ('17670','Allocated','Office of the Government Chief Informaion Officer');

INSERT INTO MZ_MOB_DATA_OWNER.MPC_LOOKUP_ROI ( MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER ) 
VALUES ('17671','Allocated','Sky Ireland');

INSERT INTO MZ_MOB_DATA_OWNER.MPC_LOOKUP_ROI ( MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER ) 
VALUES ('17680','Allocated','Virgin Media Ireland Ltd');

INSERT INTO MZ_MOB_DATA_OWNER.MPC_LOOKUP_ROI ( MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER ) 
VALUES ('17681','Allocated','Carphone Warehouse Irealand Mobile Limited');

INSERT INTO MZ_MOB_DATA_OWNER.MPC_LOOKUP_ROI ( MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER ) 
VALUES ('17682','Allocated','Lycamobile Ireland Ltd');

INSERT INTO MZ_MOB_DATA_OWNER.MPC_LOOKUP_ROI ( MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER ) 
VALUES ('17683','Allocated','Three Ireland (Hutchinson) Ltd');

INSERT INTO MZ_MOB_DATA_OWNER.MPC_LOOKUP_ROI ( MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER ) 
VALUES ('17684','Allocated','Liffey Telecom Ltd');

INSERT INTO MZ_MOB_DATA_OWNER.MPC_LOOKUP_ROI ( MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER ) 
VALUES ('17685','Allocated','Meteor');

INSERT INTO MZ_MOB_DATA_OWNER.MPC_LOOKUP_ROI ( MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER ) 
VALUES ('17686','Allocated','Three Ireland Services (Hutchinson) Ltd');

INSERT INTO MZ_MOB_DATA_OWNER.MPC_LOOKUP_ROI ( MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER ) 
VALUES ('17687','Allocated','Vodafone Ireland');
