-- MZMOB-775. Nokia PGW Mediation Functions ROI

CREATE TABLE "MZ_MOB_DATA_OWNER"."PGW_APN_ROI" 
(
	"TYPE"	VARCHAR2(20) NOT NULL,
	"APN"	VARCHAR2(32) NOT NULL,
	"DESCRIPTION"  VARCHAR2(32) NOT NULL
	 );

-- MZMOB-775. Nokia PGW Mediation Functions ROI

INSERT INTO MZ_MOB_DATA_OWNER.PGW_APN_ROI (TYPE, APN, DESCRIPTION) VALUES ('VOLTE', 'imspreprod','TB1 Test');
INSERT INTO MZ_MOB_DATA_OWNER.PGW_APN_ROI (TYPE, APN,DESCRIPTION)  VALUES ('VOLTE', 'imsdev', 'TB2 Test');
INSERT INTO MZ_MOB_DATA_OWNER.PGW_APN_ROI (TYPE, APN,DESCRIPTION)  VALUES ('VOLTE', 'imsenglo', 'ENGLO Trial');
INSERT INTO MZ_MOB_DATA_OWNER.PGW_APN_ROI (TYPE, APN,DESCRIPTION)  VALUES ('VOLTE',	'imsenbgk',	'ENBGK Trial');
INSERT INTO MZ_MOB_DATA_OWNER.PGW_APN_ROI (TYPE, APN,DESCRIPTION)  VALUES ('VOLTE',	'imsenlcs',	'ENLCS Trial');
INSERT INTO MZ_MOB_DATA_OWNER.PGW_APN_ROI (TYPE, APN,DESCRIPTION)  VALUES ('VOLTE', 'imsmimnc', 'MIMNC Trial');
INSERT INTO MZ_MOB_DATA_OWNER.PGW_APN_ROI (TYPE, APN,DESCRIPTION)  VALUES ('VOLTE', 'ims', 'Production');