
-- MZMOB-392 - Ensure ALL corporate OCS CDRs are suppressed from the Kenan retail feeds
-- A new table is needed to store the main_offering_id and businness unit

CREATE TABLE OCS_MAIN_OFFERING_ID_LOOKUP 
(
 MAIN_OFFERING_ID VARCHAR2(20) NOT NULL,
 UNIT_ID    NUMBER                             NOT NULL)
 
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;

CREATE INDEX OCS_MAIN_OFF_ID_LOOKUP_IDX1 ON OCS_MAIN_OFFERING_ID_LOOKUP(MAIN_OFFERING_ID);
CREATE INDEX OCS_MAIN_OFF_ID_LOOKUP_FK1  ON OCS_MAIN_OFFERING_ID_LOOKUP(UNIT_ID);

ALTER TABLE MZ_MOB_DATA_OWNER.OCS_MAIN_OFFERING_ID_LOOKUP ADD (
  CONSTRAINT  OCS_MAIN_OFF_ID_LOOKUP_FK1 
  FOREIGN KEY (UNIT_ID) 
  REFERENCES MZ_MOB_DATA_OWNER.BUSINESS_UNITS (UNIT_ID)
  ENABLE VALIDATE);





