-- MZMOB-414 - INSERT THREE NEW SHORTCODE ACCOUNTS
--
INSERT INTO SKY_SHORTCODE_ACCOUNT ( SHORTCODE_ACCOUNT,
DESCRIPTION ) VALUES (
'MM5', 'Sky SMSC Shortcode Account'); 

INSERT INTO SKY_SHORTCODE_ACCOUNT ( SHORTCODE_ACCOUNT,
DESCRIPTION ) VALUES (
'MMSC_ENGLO', 'Sky SMSC Shortcode Account'); 

INSERT INTO SKY_SHORTCODE_ACCOUNT ( SHORTCODE_ACCOUNT,
DESCRIPTION ) VALUES (
'MMSC_MIMNC', 'Sky SMSC Shortcode Account'); 