-- MZMOB-413 - Mediation changes for CV635 readiness - handle LastEffectOffering field [amg]
--
ALTER TABLE CDR_INPUT_OCS_VOICE MODIFY LAST_EFFECT_OFFERING VARCHAR2(30);
ALTER TABLE CDR_INPUT_OCS_MMS MODIFY LAST_EFFECT_OFFERING VARCHAR2(30);
ALTER TABLE CDR_INPUT_OCS_SMS MODIFY LAST_EFFECT_OFFERING VARCHAR2(30);
