-- MZMOB-402 - Create a Sky SMSC SMSoWiFi GT lookup table
--
CREATE TABLE SKY_SMSC_WIFI_GT
(
  GT	VARCHAR2(25 BYTE),
  ROLE_OF_NODE	NUMBER,
  DESCRIPTION	VARCHAR2(40 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;


-- INSERT SKY SMSC WIFI GT NUMBERS
--
INSERT INTO SKY_SMSC_WIFI_GT ( GT, ROLE_OF_NODE,
DESCRIPTION ) VALUES (
'447488200002', 0, 'DR MO GT'); 

INSERT INTO SKY_SMSC_WIFI_GT ( GT, ROLE_OF_NODE,
DESCRIPTION ) VALUES (
'447488200007', 0, 'ENGLO MO GT'); 

INSERT INTO SKY_SMSC_WIFI_GT ( GT, ROLE_OF_NODE,
DESCRIPTION ) VALUES (
'447488200011', 0, 'MIMNC MO GT'); 

INSERT INTO SKY_SMSC_WIFI_GT ( GT, ROLE_OF_NODE,
DESCRIPTION ) VALUES (
'447488200016', 0, 'LAB MO GT'); 

INSERT INTO SKY_SMSC_WIFI_GT ( GT, ROLE_OF_NODE,
DESCRIPTION ) VALUES (
'447488200001', 1, 'DEFAULT MT GT');