-- INSERTING NEW FREEPHONE PREFIX CODES

INSERT INTO DN_FREEPHONE_PREFIX_CODES ( FREEPHONE_PREFIX_CODE,
FREEPHONE_PREFIX_DESC ) VALUES ( 
'759', 'Voicemail');
INSERT INTO DN_FREEPHONE_PREFIX_CODES ( FREEPHONE_PREFIX_CODE,
FREEPHONE_PREFIX_DESC ) VALUES ( 
'07488222000', 'Voicemail');
INSERT INTO DN_FREEPHONE_PREFIX_CODES ( FREEPHONE_PREFIX_CODE,
FREEPHONE_PREFIX_DESC ) VALUES ( 
'111', 'NHS');

-- DELETING FIXED LINE FREEPHONE PREFIX CODES

DELETE FROM DN_FREEPHONE_PREFIX_CODES WHERE FREEPHONE_PREFIX_CODE IN ('1571', '1572', '1577','1578', '17070');

-- INSERTING NEW FILTER REASONS

INSERT INTO MZ_FILTER_REASONS ( FILTER_REASON_ID,
DESCRIPTION ) VALUES ( 
51, 'Freephone 759');
INSERT INTO MZ_FILTER_REASONS ( FILTER_REASON_ID,
DESCRIPTION ) VALUES ( 
52, 'Freephone 07488222000');
