-- MED-215 - Drop unnecessary filtered DB tables
--
DROP TABLE CDR_FILTERED_BTW_DEDS CASCADE CONSTRAINTS;

DROP TABLE CDR_FILTERED_WCLI_DEDS CASCADE CONSTRAINTS;

DROP TABLE CDR_FILTERED_WLR_DEDS CASCADE CONSTRAINTS;

DROP TABLE CDR_FILTERED_WCLI_DEDS_ARCH CASCADE CONSTRAINTS;

DROP TABLE CDR_FILTERED_WLR_DEDS_ARCH CASCADE CONSTRAINTS;