-- MZMOB-987.ROI - eSimGo for mediation delivery

CREATE TABLE DN_MSISDN_RANGE_ESIMGO_ROI 
( 
  RANGE_START VARCHAR2(20) NOT NULL,
  RANGE_END VARCHAR2(20) NOT NULL,
  UNIT_NAME VARCHAR2(20) NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;

INSERT INTO  DN_MSISDN_RANGE_ESIMGO_ROI (RANGE_START, RANGE_END, UNIT_NAME) 
VALUES ('353000000000', '353019999999', 'ESIMGO');

Insert into MZ_MOB_DATA_OWNER.MZ_FILTER_REASONS (FILTER_REASON_ID, DESCRIPTION)
 Values (69, 'Not ESimGo CDR');  
   
INSERT INTO BUSINESS_UNITS (UNIT_ID, UNIT_NAME) VALUES (22, 'ESIMGO');