-- MZMOB-964 UK - eSimGo for mediation delivery

CREATE TABLE DN_MSISDN_RANGE_ESIMGO_UK 
( 
  RANGE_START VARCHAR2(20) NOT NULL,
  RANGE_END VARCHAR2(20) NOT NULL,
  UNIT_NAME VARCHAR2(20) NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;

INSERT INTO  DN_MSISDN_RANGE_ESIMGO_UK (RANGE_START, RANGE_END, UNIT_NAME) 
VALUES ('440100000000', '440119999999', 'ESIMGO');
