CREATE TABLE MZ_AUDIT_NAPAPI_RESPONSE (
    TRANSACTION_ID     NUMBER NOT NULL,
    CREATED_DATE       DATE DEFAULT SYSDATE  NOT NULL,
    REQUEST            VARCHAR2(1000),
    RESPONSE_STATUS    VARCHAR2(10),
    RESPONSE_MESAGE    VARCHAR2(100)
    
);


CREATE TABLE MZ_AUDIT_NAPAPI_REQUEST (
    TRANSACTION_ID     NUMBER  NOT NULL,
    CREATED_DATE       DATE DEFAULT SYSDATE  NOT NULL,
    INPUT_ACTION       VARCHAR2(20),
    INPUT_DATESTAMP    VARCHAR2(30), 
    INPUT_LOB          VARCHAR2(30),
    INPUT_NEWNUMBER    VARCHAR2(40),
    INPUT_OLDNUMBER    VARCHAR2(40),
    INPUT_SEQUENCENUM  VARCHAR2(20), 
    INPUT_SOURCENAP    VARCHAR2(20),
    STATUS             VARCHAR2(20),
    LOG_MESSAGE        VARCHAR2(400),
    WF_NAME            VARCHAR2(100)
    
);
