DROP TABLE MZ_AUDIT_NAPAPI_RESPONSE;
DROP TABLE MZ_AUDIT_NAPAPI_REQUEST;

CREATE TABLE MZ_AUDIT_NAPAPI_RESPONSE (
	TRANSACTION_ID     NUMBER,
	UUID			   VARCHAR2(50),
    CREATED_DATE       DATE DEFAULT SYSDATE,
    REQUEST            VARCHAR2(1000),
    RESPONSE_STATUS    VARCHAR2(10),
    RESPONSE_MESSAGE   VARCHAR2(100)
    
);


CREATE TABLE MZ_AUDIT_NAPAPI_REQUEST (
	TRANSACTION_ID     NUMBER,
	UUID			   VARCHAR2(50),
    CREATED_DATE       DATE DEFAULT SYSDATE,
    INPUT_ACTION       VARCHAR2(20),
    INPUT_DATESTAMP    VARCHAR2(30), 
    INPUT_LOB          VARCHAR2(30),
    INPUT_NEWNUMBER    VARCHAR2(40),
    INPUT_OLDNUMBER    VARCHAR2(40),
    INPUT_SEQUENCENUM  VARCHAR2(50), 
    INPUT_SOURCENAP    VARCHAR2(40),
    STATUS             VARCHAR2(20),
    LOG_MESSAGE        VARCHAR2(400)
    
);

