-- MED-525 - NIC PREFIX TABLE
--
CREATE TABLE MZ_CDR_OWNER.NIC_PREFIX_CODES 
( NIC_PREFIX VARCHAR2(6) NOT NULL,
  NIC_PREFIX_DESC VARCHAR2(50) NOT NULL);
  
 
Insert into NIC_PREFIX_CODES (NIC_PREFIX,NIC_PREFIX_DESC) values ('104','IBCF');
Insert into NIC_PREFIX_CODES (NIC_PREFIX,NIC_PREFIX_DESC) values ('105','IBCF');
Insert into NIC_PREFIX_CODES (NIC_PREFIX,NIC_PREFIX_DESC) values ('106','IBCF');
Insert into NIC_PREFIX_CODES (NIC_PREFIX,NIC_PREFIX_DESC) values ('107','IBCF');
Insert into NIC_PREFIX_CODES (NIC_PREFIX,NIC_PREFIX_DESC) values ('108','IBCF');
Insert into NIC_PREFIX_CODES (NIC_PREFIX,NIC_PREFIX_DESC) values ('109','IBCF');
Insert into NIC_PREFIX_CODES (NIC_PREFIX,NIC_PREFIX_DESC) values ('110','IBCF');
  