-- CREATE TABLE MPC_LOOKUP - MZMOB-273 - Create an IBCF feed to IBS [amg]

-- DROP TABLE MPC_LOOKUP  CASCADE CONSTRAINTS; -- Removing this command for the release [amg]
CREATE TABLE MPC_LOOKUP 
( 
  ALLOCATION_DATE DATE NOT NULL,
  MPC_PREFIX_NUMBER  VARCHAR2(15) NOT NULL,
  STATUS VARCHAR2(40) NOT NULL,
  COMMS_PROVIDER VARCHAR2(40) NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;

-- create index
CREATE UNIQUE INDEX MPC_LOOKUP_PK ON MPC_LOOKUP
(MPC_PREFIX_NUMBER);

-- Add contraints
--

ALTER TABLE MPC_LOOKUP  
ADD CONSTRAINT MPC_LOOKUP_PK 
PRIMARY KEY (MPC_PREFIX_NUMBER );


-- Insert rows
--
-- INSERT MPC_LOOKUP 
--

INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  ) 
VALUES ( to_date('10-Jun-08','DD-MM-YY'),'7603','Allocated','24 Seven Communications Ltd');

INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  ) 
VALUES (  to_date('14-Aug-06','DD-MM-YY'),'7604','Allocated','Jersey Telecom'); 

INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  ) 
VALUES (  to_date('23-Apr-10','DD-MM-YY'),'7605','Allocated','Cloud9 Communications Limited'); 

INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  )
 VALUES (  to_date('23-Jul-10','DD-MM-YY'), '7606','Allocated','Stour Marine Limited'); 
 
INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  ) 
VALUES (  to_date('13-Nov-06','DD-MM-YY'), '7607','Allocated','Jersey Airtel  Limited'); 

INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  ) 
VALUES (  to_date(' 21-Jan-15','DD-MM-YY'),'7608','Allocated','TalkTalk Communications Limited'); 

INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  ) 
VALUES (  to_date(' 19-Apr-07','DD-MM-YY'),'7609','Allocated','Mundio Mobile Limited'); 

INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  ) 
VALUES (  to_date(' 28-Feb-07','DD-MM-YY'),'7610','Allocated','HAY SYSTEMS LIMITED'); 

INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  ) 
VALUES (  to_date('11-May-07','DD-MM-YY'),'7611','Allocated','TalkTalkCommunicationsLimited'); 

INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  ) 
VALUES (  to_date('06-Nov-13','DD-MM-YY'),'7612','Allocated','BTOnePhoneLimited'); 

INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  ) 
VALUES ( to_date('03-Aug-07','DD-MM-YY'),'7613','Allocated','IcronNetworkLimited'); 

INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  ) 
VALUES ( to_date('27-Nov-07','DD-MM-YY'),'7614','Allocated','MagratheaTelecommunicationsLimited'); 

INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  )
VALUES ( to_date('05-Jun-08','DD-MM-YY'),'7615','Allocated','JT(Guernsey)Limited'); 
 
INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  ) 
VALUES ( to_date('11-Jul-08','DD-MM-YY'),'7616','Allocated','Sure(Guernsey)Limited'); 

INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  ) 
VALUES ( to_date('14-Jul-08','DD-MM-YY'),'7617','Allocated','Sure(Jersey)Limited'); 

INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  ) 
VALUES ( to_date('14-Jul-08','DD-MM-YY'),'7618','Allocated','Sure(IsleofMan)Limited'); 

INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  ) 
VALUES (to_date('16-Jul-08','DD-MM-YY'),'7619','Allocated','GuernseyAirtelLimited'); 

INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  ) 
VALUES ( to_date('10-Oct-08','DD-MM-YY'),'7620','Allocated','ManxTelecom'); 

INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  ) 
VALUES ( to_date('28-Oct-08','DD-MM-YY'),'7621','Allocated','TruphoneLtd'); 

INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  ) 
VALUES ( to_date('30-Dec-08','DD-MM-YY'),'7622','Allocated','TeleWarePLC');

INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  ) 
VALUES ( to_date('18-Mar-15','DD-MM-YY'),'7630','Allocated','SkyUKLimited'); 

INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  ) 
VALUES ( to_date('11-Jan-16','DD-MM-YY'),'7631','Allocated','VirginMobileTelecomsLimited'); 

INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  ) 
VALUES ( to_date('01-Feb-16','DD-MM-YY'),'7632','Allocated','AMSUKLTD'); 

INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  )
 VALUES ( to_date('11-Apr-16','DD-MM-YY'),'7633','Allocated','HomeOffice'); 
 
INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  ) 
VALUES ( to_date('03-Oct-13','DD-MM-YY'),'7682','Allocated','VodafoneLtd(C&W)'); 

INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  ) 
VALUES ( to_date('10-Aug-09','DD-MM-YY'),'7683','Allocated','LycamobileUKLimited'); 

INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  ) 
VALUES ( to_date('27-May-10','DD-MM-YY'),'7684','Allocated','TeleenaUKLimited'); 

INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  ) 
VALUES ( to_date('11-Nov-10','DD-MM-YY'),'7685','Allocated','ManxTelecom'); 

INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  ) 
VALUES ( to_date('16-Nov-10','DD-MM-YY'),'7686','Allocated','aqlWholesaleLimited'); 

INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  ) 
VALUES ( to_date('27-Jul-11','DD-MM-YY'),'7688','Allocated','TismiBV'); 

INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  ) 
VALUES ( to_date('26-Oct-11','DD-MM-YY'),'7689','Allocated','NationwideTelephoneAssistanceLtd'); 

INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  ) 
VALUES ( to_date('05-Apr-12','DD-MM-YY'),'7690','Allocated','SwiftnetLtd'); 

INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  )
VALUES ( to_date('02-Feb-15','DD-MM-YY'),'7691','Allocated','GammaTelecomHoldingsLtd'); 
 
INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  ) 
VALUES (to_date('15-Apr-13','DD-MM-YY'),'7692','Allocated','VoxboneSA'); 

INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  ) 
VALUES ( to_date('06-May-14','DD-MM-YY'),'7694','Allocated','ResilientPlc'); 

INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  ) 
VALUES (to_date('25-Feb-15','DD-MM-YY'),'7695','Allocated','TGLServices(UK)Ltd'); 

INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  ) 
VALUES (to_date('01-Jan-94','DD-MM-YY'),'7991','Allocated','TelefonicaUKLimited'); 

INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  ) 
VALUES (to_date('01-Jan-94','DD-MM-YY'),'7992','Allocated','EELimited(TM)'); 

INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  ) 
VALUES (to_date('01-Jan-94','DD-MM-YY'),'7993','Allocated','Orange'); 

INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  ) 
VALUES (to_date('01-Jan-94','DD-MM-YY'),'7994','Allocated','VodafoneUkLtd'); 

INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  ) 
VALUES ( to_date('23-Apr-13','DD-MM-YY'),'7995','Allocated','VirginMobileTelecomsLimited'); 

INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  ) 
VALUES (to_date('01-Jan-94','DD-MM-YY'),'7996','Allocated','Hutchison3GUKLtd'); 

INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  ) 
VALUES ( to_date('17-Aug-05','DD-MM-YY'),'7997','Allocated','BT'); 

INSERT INTO MPC_LOOKUP ( ALLOCATION_DATE, MPC_PREFIX_NUMBER, STATUS, COMMS_PROVIDER  ) 
VALUES (to_date('21-Jun-13','DD-MM-YY'),'7998','Allocated','LimitlessMobileLtd'); 








