--MZMOB-873. [ROI-AOCS] Kerry - AOCS Mediation Functions for ROI. new Issues & Observations

-- Insert rows
--
-- INSERT FREEPHONE PREFIX CODES_ROI
--
INSERT INTO DN_FREEPHONE_PREFIX_CODES_ROI ( FREEPHONE_PREFIX_CODE,
FREEPHONE_PREFIX_DESC ) VALUES ( 
'0896555000', 'Voicemail ROI roaming normalised'); 

INSERT INTO DN_FREEPHONE_PREFIX_CODES_ROI ( FREEPHONE_PREFIX_CODE,
FREEPHONE_PREFIX_DESC ) VALUES ( 
'01800', 'Freephone prefix arriving as 3531800xxxxxxx'); 
