-- MZMOB-385 - Add new columns into CDR_INPUT_MMSC
--
ALTER TABLE CDR_INPUT_MMSC
  ADD SENDER_SGSN_IP_ADDR VARCHAR2(50);

ALTER TABLE CDR_INPUT_MMSC
  ADD RECEIVER_SGSN_IP_ADDR VARCHAR2(50);
  
ALTER TABLE CDR_INPUT_MMSC
  ADD SENDER_IMSI VARCHAR2(20);
  
ALTER TABLE CDR_INPUT_MMSC
  ADD RECEIVER_IMSI VARCHAR2(20);
  
ALTER TABLE CDR_INPUT_MMSC
  ADD USER_AGENT VARCHAR2(150);

ALTER TABLE CDR_INPUT_MMSC
  ADD APN_NAME VARCHAR2(300);

ALTER TABLE CDR_INPUT_MMSC
  ADD SGSN_IP VARCHAR2(50);
  
ALTER TABLE CDR_INPUT_MMSC
  ADD SGSN_IP_DECODED VARCHAR2(50);
  
ALTER TABLE CDR_INPUT_MMSC
  ADD IMEI VARCHAR2(256);
  
ALTER TABLE CDR_INPUT_MMSC
  ADD AREA VARCHAR2(300);
  
ALTER TABLE CDR_INPUT_MMSC
  ADD LAC VARCHAR2(10);
  
ALTER TABLE CDR_INPUT_MMSC
  ADD CI VARCHAR2(10);
  
ALTER TABLE CDR_INPUT_MMSC
  ADD SAC VARCHAR2(20);
  
ALTER TABLE CDR_INPUT_MMSC
  ADD RAC VARCHAR2(20);
  
ALTER TABLE CDR_INPUT_MMSC
  ADD TAC VARCHAR2(20);
  
ALTER TABLE CDR_INPUT_MMSC
  ADD ECI VARCHAR2(20);
  
ALTER TABLE CDR_INPUT_MMSC
  ADD SENDER_DOMAIN VARCHAR2(200);
  
ALTER TABLE CDR_INPUT_MMSC
  ADD RECEIVER_DOMAIN VARCHAR2(200);