-- MZMOB-882. Mediation work for Sky Mobile Business SIMO. Added Business Unit for SKYBMO 

INSERT INTO MZ_CONFIGURATION (PARAMETER, PARAMETER_VALUE) VALUES ('BOCS_DUP_UDR_CHECK', 1);
INSERT INTO MZ_CONFIGURATION (PARAMETER, PARAMETER_VALUE) VALUES ('BOCS_DUP_BATCH_CHECK', 1);