-- MZMOB-893. [ROI N-PGW] IBS Aggregation - Field Length Adjustments

-- Modify the existing TOTAL_USAGE fields length to 20 for all the mz_audit tables
ALTER TABLE MZ_MOB_DATA_OWNER.MZ_AUDIT_INPUT MODIFY TOTAL_USAGE NUMBER(20,2);
ALTER TABLE MZ_MOB_DATA_OWNER.MZ_AUDIT_OUTPUT MODIFY TOTAL_USAGE NUMBER(20,2);
ALTER TABLE MZ_MOB_DATA_OWNER.MZ_AUDIT_FILTERED MODIFY TOTAL_USAGE NUMBER(20,2);
ALTER TABLE MZ_MOB_DATA_OWNER.MZ_AUDIT_STATISTICS MODIFY TOTAL_USAGE NUMBER(20,2);