 CREATE TABLE CDR_INPUT_IMS_NOKIA
 (
   TRANSACTION_ID                NUMBER	NOT NULL,
   CREATED_DATE                  DATE	DEFAULT sysdate	NOT NULL,
   INPUT_FILENAME                VARCHAR2(80),  
   RECORD_TYPE                   NUMBER,
   NODE_ADDRESS                  VARCHAR2(128),
   CALLING_PARTY                 VARCHAR2(128),
   CALLED_PARTY                  VARCHAR2(128),
   REQUESTED_PARTY               VARCHAR2(128),
   A_NUMBER                      VARCHAR2(30),
   B_NUMBER                      VARCHAR2(30),
   DELIVERY_START                TIMESTAMP(6),
   DELIVERY_END                  TIMESTAMP(6),
   RECORD_OPENING_TIME           TIMESTAMP(6),
   RECORD_CLOSURE_TIME           TIMESTAMP(6),
   DURATION                      NUMBER(22),
   ROLE_OF_NODE                  NUMBER,
   CAUSE_FOR_RECORD_CLOSING      NUMBER,
   LOCAL_REC_SEQ_NUMBER          VARCHAR2(10),
   RECORD_SEQ_NUMBER             NUMBER,
   SESSION_ID                    VARCHAR2(128),
   IMS_CHARGING_ID               VARCHAR2(256),
   INCOMP_CDR_IND_ACRLOST_START  VARCHAR2(1),
   INCOMP_CDR_IND_ACRLOST_INTRM  NUMBER,
   INCOMP_CDR_IND_ACRLOST_STOP   VARCHAR2(1),
   SIP_METHOD                    VARCHAR2(30),
   SRVC_REASON_RTN_CODE          VARCHAR2(10),
   ACCESS_NETWORK_INFORMATION    VARCHAR2(200),
   POS_IN_FILE			 NUMBER,
   INCOMING_TRUNK_GRP_ID         VARCHAR2(30),
   OUTGOING_TRUNK_GRP_ID         VARCHAR2(30),
   INCOMING_TRUNK_GRP_NAME       VARCHAR2(50),
   OUTGOING_TRUNK_GRP_NAME       VARCHAR2(50), 
   SUPPLEMENTARY_SERVICE	 VARCHAR2(256),
   SS_ASSOCIATED_NUMBER_1	 VARCHAR2(128),
   SS_SERVICE_MODE_1		 NUMBER,
   SS_SERVICE_TYPE_1		 NUMBER,
   SS_SERVICE_ACTION_1		 NUMBER,
   SS_START_DATE_AND_TIME_1      TIMESTAMP(6),
   SS_END_DATE_AND_TIME_1        TIMESTAMP(6),
   SS_SERVICE_ID_1               VARCHAR2(64),
   SS_ASSOCIATED_NUMBER_2        VARCHAR2(128),
   SS_SERVICE_MODE_2             NUMBER,
   SS_SERVICE_TYPE_2             NUMBER,
   SS_SERVICE_ACTION_2           NUMBER,
   SS_START_DATE_AND_TIME_2      TIMESTAMP(6),
   SS_END_DATE_AND_TIME_2        TIMESTAMP(6),
   SS_SERVICE_ID_2               VARCHAR2(64),
   SS_ASSOCIATED_NUMBER_3        VARCHAR2(128),
   SS_SERVICE_MODE_3             NUMBER,
   SS_SERVICE_TYPE_3             NUMBER,
   SS_SERVICE_ACTION_3           NUMBER,
   SS_START_DATE_AND_TIME_3      TIMESTAMP(6),
   SS_END_DATE_AND_TIME_3        TIMESTAMP(6),
   SS_SERVICE_ID_3               VARCHAR2(64),
   SS_ASSOCIATED_NUMBER_4        VARCHAR2(128),
   SS_SERVICE_MODE_4             NUMBER,
   SS_SERVICE_TYPE_4             NUMBER,
   SS_SERVICE_ACTION_4           NUMBER,
   SS_START_DATE_AND_TIME_4      TIMESTAMP(6),
   SS_END_DATE_AND_TIME_4        TIMESTAMP(6),
   SS_SERVICE_ID_4               VARCHAR2(64),
   SS_ASSOCIATED_NUMBER_5        VARCHAR2(128),
   SS_SERVICE_MODE_5             NUMBER,
   SS_SERVICE_TYPE_5             NUMBER,
   SS_SERVICE_ACTION_5           NUMBER,
   SS_START_DATE_AND_TIME_5      TIMESTAMP(6),
   SS_END_DATE_AND_TIME_5        TIMESTAMP(6),
   SS_SERVICE_ID_5               VARCHAR2(64)   
 )
 SEGMENT CREATION IMMEDIATE
   PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
   TABLESPACE MZ_CDR_DATA  
 PARTITION BY RANGE(CREATED_DATE)
 (
   PARTITION PMAXVALUE  VALUES LESS THAN (MAXVALUE) TABLESPACE  MZ_CDR_DATA
 );
 
 
 -- Create Indexes
 --
 CREATE INDEX CDR_INPUT_IMS_IDX1 ON CDR_INPUT_IMS_NOKIA (A_NUMBER) LOCAL;
 
 CREATE INDEX CDR_INPUT_IMS_IDX2 ON CDR_INPUT_IMS_NOKIA (B_NUMBER) LOCAL;
 
 CREATE INDEX CDR_INPUT_IMS_IDX3 ON CDR_INPUT_IMS_NOKIA (IMS_CHARGING_ID) LOCAL;
 

