-- CDR_OUTPUT_IMS_NOKIA_ECS
--
CREATE TABLE CDR_OUTPUT_IMS_NOKIA_ECS
(
  FILE_CONTROL_ID         NUMBER                NOT NULL,
  FILE_REC_ID             NUMBER                NOT NULL,
  CREATED_DATE            DATE                  NOT NULL,
  TRANSACTION_ID          NUMBER                NOT NULL,
  CALLING_NUMBER          VARCHAR2(30 BYTE),
  CALLED_NUMBER           VARCHAR2(30 BYTE),
  SWITCH_ID               VARCHAR2(20 BYTE),
  SESSION_NUMBER          VARCHAR2(20 BYTE),
  SEQUENCE_NUMBER         VARCHAR2(20 BYTE),
  IN_TRUNK                VARCHAR2(100 BYTE),
  OUT_TRUNK               VARCHAR2(100 BYTE),
  CDR_TIMESTAMP           TIMESTAMP(6),
  CDR_DURATION_MS         NUMBER(22),
  ERROR_CODE              VARCHAR2(30 BYTE),
  TIMESTAMP_IN            TIMESTAMP(6),
  TIMESTAMP_REPROCESSING  TIMESTAMP(6),
  ORIG_FNAME_TIMESTAMP    VARCHAR2(20 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

-- Create CDR_OUTPUT_IMS_NOKIA_ECS Indexes
--
CREATE INDEX IDX_O_IMS_N_ECS_CALLED_NUMBER ON CDR_OUTPUT_IMS_NOKIA_ECS 
(CALLED_NUMBER);

CREATE INDEX IDX_O_IMS_N_ECS_CALLING_NUMBER ON CDR_OUTPUT_IMS_NOKIA_ECS
(CALLING_NUMBER);

CREATE INDEX IDX_O_IMS_N_ECS_IDX1 ON CDR_OUTPUT_IMS_NOKIA_ECS
(SWITCH_ID, SESSION_NUMBER, SEQUENCE_NUMBER);