-- Upgrade script for MZ5.1FR4 to MZ5.1 FR5. MZO-449
-- 
CREATE TABLE ECS_CONFIG (
 	TYPE	VARCHAR2(64)   NOT NULL,
 	NAME	VARCHAR2(64)   NOT NULL,
	DATA	CLOB           NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE ECS_CONFIG ADD (
   CONSTRAINT PK_ECS_SAVED_FILTERS
  PRIMARY KEY
  (NAME));


-- Add new column to table ECS_UDR     
--
ALTER TABLE ECS_UDR ADD (
   TAG             VARCHAR2(256),
   SEARCH_FIELD_1  VARCHAR2(256),
   SEARCH_FIELD_2  VARCHAR2(256),
   SEARCH_FIELD_3  VARCHAR2(256),
   SEARCH_FIELD_4  VARCHAR2(256),
   SEARCH_FIELD_5  VARCHAR2(256),
   SEARCH_FIELD_6  VARCHAR2(256),
   SEARCH_FIELD_7  VARCHAR2(256),
   SEARCH_FIELD_8  VARCHAR2(256),
   SEARCH_FIELD_9  VARCHAR2(256),
   SEARCH_FIELD_10 VARCHAR2(256));


GRANT SELECT, UPDATE, INSERT, DELETE ON ECS_CONFIG TO MZ5_ADMIN;

GRANT SELECT, UPDATE, INSERT, DELETE ON ECS_CONFIG TO MZ5_READONLY;

GRANT SELECT, UPDATE, INSERT, DELETE ON ECS_CONFIG TO MZ5_ROLE;

CREATE SYNONYM MZ5_ADMIN.ECS_CONFIG FOR MZ5_OWNER.ECS_CONFIG;
