CREATE TABLE MZ_R66_AUDIT
(
  TXN_ID    NUMBER(15),
  WF_NAME VARCHAR2(100 BYTE),
  TIMESTAMP_FWD  DATE,
  INPUT_FILE_NAME VARCHAR2(100 BYTE),
  FILE_TIMESTAMP DATE,
  ACTUAL_RECORD_COUNT NUMBER(15),
  COUNT_ADDS  NUMBER(15),
  COUNT_DELS NUMBER(15),
  COUNT_GOOD_ADDS NUMBER(15),
  COUNT_GOOD_DELS NUMBER(15),
  OUTPUT_FILE_NAME VARCHAR2(100)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;