-- Create TADIG lookup tables
--
CREATE TABLE GSMA_TADIG
(
  INPUT_FILENAME 	VARCHAR2(50 BYTE),
  TADIG		 	VARCHAR2(10 BYTE),
  MCC		 	VARCHAR2(10 BYTE),
  MNC		 	VARCHAR2(10 BYTE),
  MGT_CC         	VARCHAR2(15 BYTE), 
  MGT_NC         	VARCHAR2(15 BYTE),
  OPERATOR_NAME	 	VARCHAR2(80 BYTE),
  COUNTRY        	VARCHAR2(50 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;


CREATE TABLE GSMA_CC_NDC_MAP2TADIG
(
  INPUT_FILENAME 	VARCHAR2(50 BYTE),
  CC		 	VARCHAR2(20 BYTE), 
  NDC		 	VARCHAR2(20 BYTE),
  TADIG 	 	VARCHAR2(10 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;


CREATE TABLE GSMA_GT_NODE
(
  INPUT_FILENAME 	VARCHAR2(50 BYTE),
  GT_START		VARCHAR2(20 BYTE),
  GT_STOP		VARCHAR2(20 BYTE),
  IP_ADDRESS            VARCHAR2(40 BYTE),  
  IP_START		VARCHAR2(20 BYTE),
  IP_STOP		VARCHAR2(20 BYTE),  
  LOCATION		VARCHAR2(100 BYTE),    
  TADIG			VARCHAR2(10 BYTE),
  MODIFIED_TADIG	VARCHAR2(10 BYTE),
  EFFECTIVE_DATE	DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;


CREATE TABLE GSMA_GT_RANGES
(
  INPUT_FILENAME 	VARCHAR2(50 BYTE),
  GT_START		VARCHAR2(20 BYTE),
  GT_STOP		VARCHAR2(20 BYTE),
  TADIG			VARCHAR2(10 BYTE),
  EFFECTIVE_DATE	DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;


CREATE TABLE GSMA_IP_RANGES
(
  INPUT_FILENAME 	VARCHAR2(50 BYTE),
  IP_ADDRESS_OR_RANGE   VARCHAR2(40 BYTE),
  IP_START		VARCHAR2(20 BYTE),
  IP_STOP		VARCHAR2(20 BYTE),
  TADIG			VARCHAR2(10 BYTE),
  EFFECTIVE_DATE	DATE 
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;


-- Create Indexes
--
CREATE INDEX IDX_TADIG_T ON GSMA_TADIG
(TADIG)
LOGGING
NOPARALLEL;


CREATE INDEX IDX_INPUT_FILENAME_GTN ON GSMA_GT_NODE
(INPUT_FILENAME)
LOGGING
NOPARALLEL;


CREATE INDEX IDX_GT_START_GTN ON GSMA_GT_NODE
(GT_START)
LOGGING
NOPARALLEL;


CREATE INDEX IDX_GT_STOP_GTN ON GSMA_GT_NODE
(GT_STOP)
LOGGING
NOPARALLEL;


CREATE INDEX IDX_IP_START_GTN ON GSMA_GT_NODE
(IP_START)
LOGGING
NOPARALLEL;


CREATE INDEX IDX_IP_STOP_GTN ON GSMA_GT_NODE
(IP_STOP)
LOGGING
NOPARALLEL;


CREATE INDEX IDX_GT_START_GTR ON GSMA_GT_RANGES
(GT_START)
LOGGING
NOPARALLEL;


CREATE INDEX IDX_GT_STOP_GTR ON GSMA_GT_RANGES
(GT_STOP)
LOGGING
NOPARALLEL;


CREATE INDEX IDX_IP_START_IPR ON GSMA_IP_RANGES
(IP_START)
LOGGING
NOPARALLEL;


CREATE INDEX IDX_IP_STOP_IPR ON GSMA_IP_RANGES
(IP_STOP)
LOGGING
NOPARALLEL;
