-- Create Indexes - MZMOB-174
--
CREATE INDEX IDX_INPUT_FILENAME_GCNM ON GSMA_CC_NDC_MAP2TADIG
(INPUT_FILENAME)
LOGGING
NOPARALLEL;


CREATE INDEX IDX_CC_GCNM ON GSMA_CC_NDC_MAP2TADIG
(CC)
LOGGING
NOPARALLEL;


CREATE INDEX IDX_NDC_GCNM ON GSMA_CC_NDC_MAP2TADIG
(NDC)
LOGGING
NOPARALLEL;


CREATE INDEX IDX_TADIG_GCNM ON GSMA_CC_NDC_MAP2TADIG
(TADIG)
LOGGING
NOPARALLEL;


CREATE INDEX IDX_INPUT_FILENAME_GTR ON GSMA_GT_RANGES
(INPUT_FILENAME)
LOGGING
NOPARALLEL;


CREATE INDEX IDX_INPUT_FILENAME_IPR ON GSMA_IP_RANGES
(INPUT_FILENAME)
LOGGING
NOPARALLEL;
