INSERT INTO DN_FREEPHONE_PREFIX_CODES ( FREEPHONE_PREFIX_CODE,
FREEPHONE_PREFIX_DESC ) VALUES ( 
'195', 'Special Assistance Directory Enquiries'); 

INSERT INTO DN_FREEPHONE_PREFIX_CODES ( FREEPHONE_PREFIX_CODE,
FREEPHONE_PREFIX_DESC ) VALUES ( 
'17070', 'Line Test Number'); 

INSERT INTO DN_FREEPHONE_PREFIX_CODES ( FREEPHONE_PREFIX_CODE,
FREEPHONE_PREFIX_DESC ) VALUES ( 
'155', 'International Operator');

INSERT INTO DN_FREEPHONE_PREFIX_CODES ( FREEPHONE_PREFIX_CODE,
FREEPHONE_PREFIX_DESC ) VALUES ( 
'198', 'Special Assistance Operator');

INSERT INTO DN_FREEPHONE_PREFIX_CODES ( FREEPHONE_PREFIX_CODE,
FREEPHONE_PREFIX_DESC ) VALUES ( 
'116006', 'Helpline for victims of crime');

INSERT INTO DN_FREEPHONE_PREFIX_CODES ( FREEPHONE_PREFIX_CODE,
FREEPHONE_PREFIX_DESC ) VALUES ( 
'116117', 'Non-emergency medical on-call service');

INSERT INTO DN_FREEPHONE_PREFIX_CODES ( FREEPHONE_PREFIX_CODE,
FREEPHONE_PREFIX_DESC ) VALUES ( 
'105', 'Electricity Helpline');
