CREATE SEQUENCE CDR_FILTERED_BTW_DEDS_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 1000
  NOORDER;


CREATE SEQUENCE CDR_INPUT_BTW_DEDS_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 1000
  NOORDER;


CREATE SEQUENCE CDR_OUTPUT_BTW_DEDS_THUS_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 1000
  NOORDER;


CREATE SEQUENCE SEQ_NUMBER
  START WITH 0
  MAXVALUE 99999
  MINVALUE 0
  CYCLE
  NOCACHE
  NOORDER;


CREATE SEQUENCE SNS_PARTITION_CTL_ID_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE SEQUENCE SNS_PARTITION_ERROR_LOG_ID_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

CREATE TABLE CDR_FILE_CONTROL
(
  FILE_CONTROL_ID       NUMBER(8)         NOT NULL
, FILE_TYPE             VARCHAR2(40 BYTE) NOT NULL
, VERSION               VARCHAR2(40 BYTE) NOT NULL
, EFFECTIVE_START_DATE  DATE              DEFAULT SYSDATE NOT NULL
, EFFECTIVE_END_DATE    DATE
, TABLE_NAME            VARCHAR2(30 BYTE) NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;


CREATE TABLE MZ_FILTER_RULES
(
  WF_NAME     VARCHAR2(60 BYTE),
  FIELD_NAME  VARCHAR2(32 BYTE),
  OPERATOR    VARCHAR2(32 BYTE),
  VALUE       VARCHAR2(32 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;


CREATE TABLE MZ_CONFIGURATION
(
  PARAMETER        VARCHAR2(32 BYTE),
  PARAMETER_VALUE  NUMBER(15)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;


CREATE TABLE MZ_AUDIT_STATISTICS
(
  TXN_ID             NUMBER(15),
  WF_NAME            VARCHAR2(100 BYTE),
  INPUT_FILE_NAME    VARCHAR2(100 BYTE),
  TIMESTAMP_FWD      DATE,
  CDR_COUNT          NUMBER(15),
  TOTAL_WSALE_PRICE  NUMBER(15),
  TOTAL_DURATION     NUMBER(15),
  OUTPUT_FILE_NAME   VARCHAR2(100 BYTE),
  FILE_TIMESTAMP     DATE,
  STATISTICS         VARCHAR2(32 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;


CREATE TABLE MZ_AUDIT_REPROCESSING
(
  TXN_ID           NUMBER(15),
  WF_NAME          VARCHAR2(60 BYTE),
  FILE_NAME        VARCHAR2(100 BYTE),
  TIMESTAMP        DATE,
  INPUT_CDRS       NUMBER(15),
  OUTPUT_CDRS      NUMBER(15),
  INPUT_BATCHES    NUMBER(15),
  OUTPUT_BATCHES   NUMBER(15),
  FILE_VALID_FLAG  NUMBER(15),
  OUTPUT_ID        NUMBER(15)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;


CREATE TABLE MZ_AUDIT_OUTPUT
(
  TXN_ID             NUMBER(15),
  WF_NAME            VARCHAR2(100 BYTE),
  INPUT_FILE_NAME    VARCHAR2(100 BYTE),
  OUTPUT_ID          VARCHAR2(8 BYTE),
  CDR_COUNT          NUMBER(15),
  TOTAL_WSALE_PRICE  NUMBER(15),
  TIMESTAMP_FWD      DATE,
  TOTAL_DURATION     NUMBER(15),
  OUTPUT_FILE_NAME   VARCHAR2(100 BYTE),
  FILE_TIMESTAMP     DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;


CREATE TABLE MZ_AUDIT_INPUT
(
  TXN_ID             NUMBER(15),
  WF_NAME            VARCHAR2(100 BYTE),
  FILE_NAME          VARCHAR2(100 BYTE),
  TIMESTAMP_COLL     DATE,
  FILE_SIZE          NUMBER(15),
  CDR_COUNT          NUMBER(15),
  FIRST_CDR_DATE     DATE,
  LAST_CDR_DATE      DATE,
  TOTAL_WSALE_PRICE  NUMBER(15),
  FILE_VALID_FLAG    NUMBER(15),
  TIMESTAMP_FWD      DATE,
  TOTAL_DURATION     NUMBER(15),
  FILE_TIMESTAMP     DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;


CREATE TABLE MZ_AUDIT_FILTERED
(
  TXN_ID             NUMBER(15),
  WF_NAME            VARCHAR2(100 BYTE),
  INPUT_FILE_NAME    VARCHAR2(100 BYTE),
  OUTPUT_ID          VARCHAR2(8 BYTE),
  CDR_COUNT          NUMBER(15),
  TOTAL_WSALE_PRICE  NUMBER(15),
  TIMESTAMP_FWD      DATE,
  TOTAL_DURATION     NUMBER(15),
  OUTPUT_FILE_NAME   VARCHAR2(100 BYTE),
  FILE_TIMESTAMP     DATE,
  FILTER_REASON_ID   NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;


CREATE TABLE CDR_OUTPUT_BTW_DEDS_THUS
(
  FILE_CONTROL_ID         NUMBER NOT NULL,
  FILE_REC_ID             NUMBER NOT NULL,
  CREATED_DATE            DATE   DEFAULT SYSDATE NOT NULL,
  TRANSACTION_ID          NUMBER(15) NOT NULL,
  CALLING_NUMBER          VARCHAR2(30 BYTE),
  CALLED_NUMBER           VARCHAR2(30 BYTE),
  CLI                     VARCHAR2(28 BYTE),
  CALL_START_DATE         VARCHAR2(6 BYTE),
  CALL_START_TIME         VARCHAR2(6 BYTE),
  CALL_DURATION           NUMBER(8),
  THUS_ACCOUNT_NUMBER     VARCHAR2(12 BYTE),
  CARRIER_COST            VARCHAR2(18 BYTE),
  THUS_COST               VARCHAR2(12 BYTE),
  THUS_CALL_AREA_NAME     VARCHAR2(25 BYTE),
  THUS_RATE_PERIOD        VARCHAR2(5 BYTE),
  THUS_CALL_TYPE          VARCHAR2(6 BYTE),
  LONG_DURATION_FLAG      VARCHAR2(1 BYTE),
  SAD_CALL_FLAG           VARCHAR2(1 BYTE),
  DIALLED_NUMBER          VARCHAR2(28 BYTE),
  COST_CODE_NAME          VARCHAR2(28 BYTE),
  SOURCE_FILE_IDENTIFIER  VARCHAR2(100 BYTE),
  EVENT_SOURCE            VARCHAR2(30 BYTE)
)
PARTITION BY RANGE (CREATED_DATE)
(  
  PARTITION O_BTW_DEDS_THUS_MAXVALUE VALUES LESS THAN (MAXVALUE)
    LOGGING
    COMPRESS
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CDR_INPUT_BTW_DEDS
(
  FILE_CONTROL_ID        NUMBER     NOT NULL,
  FILE_REC_ID            NUMBER     NOT NULL,
  CREATED_DATE           DATE       DEFAULT SYSDATE NOT NULL,
  TRANSACTION_ID         NUMBER(15) NOT NULL,
  CALLING_NUMBER         VARCHAR2(30 BYTE),
  CALLED_NUMBER          VARCHAR2(30 BYTE),
  TAG                    VARCHAR2(20 BYTE),
  CALLING_LINE_IDENTITY  VARCHAR2(20 BYTE),
  EVENT_TYPE             VARCHAR2(20 BYTE),
  DATE_AND_TIME_FIELDS   VARCHAR2(30 BYTE),
  RESERVED_FOR_BT_1      VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_2      VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_3      VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_4      VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_5      VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_6      VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_7      VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_8      VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_9      VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_10     VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_11     VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_12     VARCHAR2(20 BYTE),
  SPID                   VARCHAR2(15 BYTE),
  PBX_SUFFIX             VARCHAR2(20 BYTE),
  DURATION_OF_CALL       VARCHAR2(100 BYTE),
  RESERVED_FOR_BT_13     VARCHAR2(20 BYTE),
  LINK_FIELD             VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_14     VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_15     VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_16     VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_17     VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_18     VARCHAR2(100 BYTE),
  RERATE_INDICATOR       VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_19     VARCHAR2(20 BYTE),
  ACCOUNT_NUMBER         VARCHAR2(20 BYTE),
  RECORD_STATUS          VARCHAR2(20 BYTE),
  WHOLESALE_PRICE        VARCHAR2(20 BYTE),
  PHONEBOOK_CODE         VARCHAR2(100 BYTE),
  RESERVED_FOR_BT_20     VARCHAR2(20 BYTE),
  SERVICE_TYPE           VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_21     VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_22     VARCHAR2(20 BYTE)
)
PARTITION BY RANGE (CREATED_DATE)
(   
  PARTITION I_BTW_DEDS_MAXVALUE VALUES LESS THAN (MAXVALUE)
    LOGGING
    COMPRESS
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;


CREATE TABLE CDR_FILTERED_BTW_DEDS
(
  FILE_CONTROL_ID  NUMBER NOT NULL,
  FILE_REC_ID      NUMBER NOT NULL,
  CREATED_DATE     DATE                         DEFAULT SYSDATE NOT NULL,
  TRANSACTION_ID   NUMBER(15) NOT NULL,
  CALLING_NUMBER   VARCHAR2(30 BYTE),
  CALLED_NUMBER    VARCHAR2(30 BYTE)
)
PARTITION BY RANGE (CREATED_DATE)
(  
  PARTITION F_BTW_DEDS_MAXVALUE VALUES LESS THAN (MAXVALUE)
    LOGGING
    COMPRESS
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;


CREATE TABLE MZ_FILTER_REASONS
(
  FILTER_REASON_ID  NUMBER,
  DESCRIPTION       VARCHAR2(100 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;


CREATE UNIQUE INDEX CDR_FILE_CONTROL_PK ON CDR_FILE_CONTROL
(FILE_CONTROL_ID)
LOGGING
NOPARALLEL;


CREATE INDEX IDX_F_CALLED_NUMBER ON CDR_FILTERED_BTW_DEDS
(CALLED_NUMBER)
  LOCAL (  
  PARTITION F_BTW_DEDS_MAXVALUE
    LOGGING
    NOCOMPRESS
)
NOPARALLEL;


CREATE INDEX IDX_F_CALLING_NUMBER ON CDR_FILTERED_BTW_DEDS
(CALLING_NUMBER)
  LOCAL (   
  PARTITION F_BTW_DEDS_MAXVALUE
    LOGGING
    NOCOMPRESS
)
NOPARALLEL;


CREATE INDEX IDX_I_CALLED_NUMBER ON CDR_INPUT_BTW_DEDS
(CALLED_NUMBER)
  LOCAL (  
  PARTITION I_BTW_DEDS_MAXVALUE
    LOGGING
    NOCOMPRESS
)
NOPARALLEL;


CREATE INDEX IDX_I_CALLING_NUMBER ON CDR_INPUT_BTW_DEDS
(CALLING_NUMBER)
  LOCAL (  
  PARTITION I_BTW_DEDS_MAXVALUE
    LOGGING
    NOCOMPRESS
)
NOPARALLEL;


CREATE INDEX IDX_O_CALLED_NUMBER ON CDR_OUTPUT_BTW_DEDS_THUS
(CALLED_NUMBER)
  LOCAL (  
  PARTITION O_BTW_DEDS_THUS_MAXVALUE
    LOGGING
    NOCOMPRESS
)
NOPARALLEL;


CREATE INDEX IDX_O_CALLING_NUMBER ON CDR_OUTPUT_BTW_DEDS_THUS
(CALLING_NUMBER)
  LOCAL (  
  PARTITION O_BTW_DEDS_THUS_MAXVALUE
    LOGGING
    NOCOMPRESS
)
NOPARALLEL;


ALTER TABLE CDR_FILE_CONTROL ADD (
  CONSTRAINT CDR_FILE_CONTROL_PK
 PRIMARY KEY
 (FILE_CONTROL_ID));


Insert into MZ_CDR_OWNER.CDR_FILE_CONTROL
   (FILE_CONTROL_ID, FILE_TYPE, VERSION, EFFECTIVE_START_DATE, EFFECTIVE_END_DATE, TABLE_NAME)
 Values
   (1, 'BTW_DEDS', '1', TO_DATE('01/01/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('12/31/2099 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'CDR_INPUT_BTW_DEDS');
Insert into MZ_CDR_OWNER.CDR_FILE_CONTROL
   (FILE_CONTROL_ID, FILE_TYPE, VERSION, EFFECTIVE_START_DATE, EFFECTIVE_END_DATE, TABLE_NAME)
 Values
   (2, 'BTW_DEDS', '1', TO_DATE('01/01/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('12/31/2099 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'CDR_FILTERED_BTW_DEDS');
Insert into MZ_CDR_OWNER.CDR_FILE_CONTROL
   (FILE_CONTROL_ID, FILE_TYPE, VERSION, EFFECTIVE_START_DATE, EFFECTIVE_END_DATE, TABLE_NAME)
 Values
   (3, 'BTW_DEDS', '1', TO_DATE('01/01/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('12/31/2099 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'CDR_OUTPUT_BTW_DEDS_THUS');

Insert into MZ_CDR_OWNER.MZ_CONFIGURATION
   (PARAMETER, PARAMETER_VALUE)
 Values
   ('WCLI_DEDS_DUP_CHECK', 1);
Insert into MZ_CDR_OWNER.MZ_CONFIGURATION
   (PARAMETER, PARAMETER_VALUE)
 Values
   ('WCLI_DEDS_LONG_DUR_CALL_LIMIT', 1800000000);

Insert into MZ_CDR_OWNER.MZ_FILTER_REASONS
   (FILTER_REASON_ID, DESCRIPTION)
 Values
   (0, 'No filtering.');
Insert into MZ_CDR_OWNER.MZ_FILTER_REASONS
   (FILTER_REASON_ID, DESCRIPTION)
 Values
   (1, 'Call duration not a number.');
Insert into MZ_CDR_OWNER.MZ_FILTER_REASONS
   (FILTER_REASON_ID, DESCRIPTION)
 Values
   (2, 'Event type not correct.');
Insert into MZ_CDR_OWNER.MZ_FILTER_REASONS
   (FILTER_REASON_ID, DESCRIPTION)
 Values
   (3, 'Carrier Cost not a number.');
Insert into MZ_CDR_OWNER.MZ_FILTER_REASONS
   (FILTER_REASON_ID, DESCRIPTION)
 Values
   (4, 'Invalid record status');
Insert into MZ_CDR_OWNER.MZ_FILTER_REASONS
   (FILTER_REASON_ID, DESCRIPTION)
 Values
   (5, 'Re-rated call');
Insert into MZ_CDR_OWNER.MZ_FILTER_REASONS
   (FILTER_REASON_ID, DESCRIPTION)
 Values
   (6, 'Duplicate CDR');
Insert into MZ_CDR_OWNER.MZ_FILTER_REASONS
   (FILTER_REASON_ID, DESCRIPTION)
 Values
   (7, 'Out of date call');
Insert into MZ_CDR_OWNER.MZ_FILTER_REASONS
   (FILTER_REASON_ID, DESCRIPTION)
 Values
   (8, 'Incomplete Thus Skytalk session');
Insert into MZ_CDR_OWNER.MZ_FILTER_REASONS
   (FILTER_REASON_ID, DESCRIPTION)
 Values
   (9, 'Invalid Date field.');
Insert into MZ_CDR_OWNER.MZ_FILTER_REASONS
   (FILTER_REASON_ID, DESCRIPTION)
 Values
   (10, 'Invalid SPID field.');
Insert into MZ_CDR_OWNER.MZ_FILTER_REASONS
   (FILTER_REASON_ID, DESCRIPTION)
 Values
   (11, 'Invalid Facility Description field');
Insert into MZ_CDR_OWNER.MZ_FILTER_REASONS
   (FILTER_REASON_ID, DESCRIPTION)
 Values
   (12, 'Invalid PPNQ field.');
Insert into MZ_CDR_OWNER.MZ_FILTER_REASONS
   (FILTER_REASON_ID, DESCRIPTION)
 Values
   (13, 'Bad Operator Description field.');
Insert into MZ_CDR_OWNER.MZ_FILTER_REASONS
   (FILTER_REASON_ID, DESCRIPTION)
 Values
   (14, 'The Calling Line Identity is emty');
Insert into MZ_CDR_OWNER.MZ_FILTER_REASONS
   (FILTER_REASON_ID, DESCRIPTION)
 Values
   (15, 'The Called Number is emty.');
Insert into MZ_CDR_OWNER.MZ_FILTER_REASONS
   (FILTER_REASON_ID, DESCRIPTION)
 Values
   (16, 'Message Size is null (zero).');
Insert into MZ_CDR_OWNER.MZ_FILTER_REASONS
   (FILTER_REASON_ID, DESCRIPTION)
 Values
   (17, 'Invalid Time gap in session.');
Insert into MZ_CDR_OWNER.MZ_FILTER_REASONS
   (FILTER_REASON_ID, DESCRIPTION)
 Values
   (18, 'Session Timed Out.');
Insert into MZ_CDR_OWNER.MZ_FILTER_REASONS
   (FILTER_REASON_ID, DESCRIPTION)
 Values
   (19, 'Summary filter file.');
Insert into MZ_CDR_OWNER.MZ_FILTER_REASONS
   (FILTER_REASON_ID, DESCRIPTION)
 Values
   (20, 'Invalid Rerate Indicator');
Insert into MZ_CDR_OWNER.MZ_FILTER_REASONS
   (FILTER_REASON_ID, DESCRIPTION)
 Values
   (21, 'Proportion text not a int');
Insert into MZ_CDR_OWNER.MZ_FILTER_REASONS
   (FILTER_REASON_ID, DESCRIPTION)
 Values
   (22, 'Output filtering rules');
Insert into MZ_CDR_OWNER.MZ_FILTER_REASONS
   (FILTER_REASON_ID, DESCRIPTION)
 Values
   (23, 'Event type 326');
Insert into MZ_CDR_OWNER.MZ_FILTER_REASONS
   (FILTER_REASON_ID, DESCRIPTION)
 Values
   (24, 'Undecodable batch');
Insert into MZ_CDR_OWNER.MZ_FILTER_REASONS
   (FILTER_REASON_ID, DESCRIPTION)
 Values
   (25, 'Segmented CDRs');
Insert into MZ_CDR_OWNER.MZ_FILTER_REASONS
   (FILTER_REASON_ID, DESCRIPTION)
 Values
   (26, 'Re-introduced Segmented CDRs');
Insert into MZ_CDR_OWNER.MZ_FILTER_REASONS
   (FILTER_REASON_ID, DESCRIPTION)
 Values
   (27, 'Long Duration Calls');
Insert into MZ_CDR_OWNER.MZ_FILTER_REASONS
   (FILTER_REASON_ID, DESCRIPTION)
 Values
   (28, 'Record type 327 - cannot derive usage_type');
Insert into MZ_CDR_OWNER.MZ_FILTER_REASONS
   (FILTER_REASON_ID, DESCRIPTION)
 Values
   (29, 'Record type 312. Cannot derive usage_type');
Insert into MZ_CDR_OWNER.MZ_FILTER_REASONS
   (FILTER_REASON_ID, DESCRIPTION)
 Values
   (30, 'Record type 313. Cannot derive usage_type');

