CREATE TABLE CDR_INPUT_CS2K
(
  FILE_CONTROL_ID          NUMBER     NOT NULL,
  FILE_REC_ID              NUMBER     NOT NULL,
  CREATED_DATE             DATE       DEFAULT SYSDATE NOT NULL,
  TRANSACTION_ID           NUMBER(15) NOT NULL,
  CALLING_NUMBER           VARCHAR2(30 BYTE),
  SESSION_ID               VARCHAR2(20 BYTE),
  CALLED_NUMBER            VARCHAR2(30 BYTE),
  CALL_TYPE_CODE           VARCHAR2(3 BYTE), 
  SENSOR_TYPE              VARCHAR2(3 BYTE), 
  SENSOR_IDENTIFICATION    VARCHAR2(7 BYTE), 
  RECORDING_OFFICE_TYPE    VARCHAR2(3 BYTE), 
  RECORDING_OFFICE_ID      VARCHAR2(7 BYTE), 
  CALL_DATE                VARCHAR2(5 BYTE), 
  TIMING_INDICATOR         VARCHAR2(5 BYTE), 
  STUDY_INDICATOR          VARCHAR2(7 BYTE), 
  CALLED_PARTY_OFF_HOOK    VARCHAR2(1 BYTE), 
  SERVICE_OBSERVED_TRAFF   VARCHAR2(1 BYTE), 
  OPERATOR_ACTION          VARCHAR2(1 BYTE), 
  SERVICE_FEATURE          VARCHAR2(3 BYTE), 
  CONNECT_TIME             VARCHAR2(7 BYTE), 
  ELAPSED_TIME             VARCHAR2(9 BYTE), 
  ORIGINATING_OPEN_DIGITS  VARCHAR2(30 BYTE), 
  TERMINATING_OPEN_DIGITS  VARCHAR2(30 BYTE), 
  ORIGINATING_CHARGE_INFO  VARCHAR2(4 BYTE), 
  DOMESTIC_INTERNATIONAL_IND  VARCHAR2(1 BYTE), 
  COMPLETION_INDICATOR        VARCHAR2(3 BYTE), 
  M22_PRESENT_DATE            VARCHAR2(5 BYTE), 
  M22_PRESENT_TIME            VARCHAR2(7 BYTE), 
  M42_CALL_RECORD_SEQUENCE    VARCHAR2(7 BYTE), 
  M70_BEARER_CAPABILITIES     VARCHAR2(3 BYTE), 
  M70_NETWORK_INTERWORKING    VARCHAR2(1 BYTE), 
  M70_SIGNALING_OR_SUPPL_SCU  VARCHAR2(15 BYTE), 
  M70_RELEASE_CAUSE_INDICATOR VARCHAR2(5 BYTE), 
  M71_BEARER_CAPABILITIES     VARCHAR2(3 BYTE), 
  M71_NETWORK_INTERWORKING    VARCHAR2(1 BYTE), 
  M71_RELEASE_CAUSE_INDICATOR VARCHAR2(5 BYTE), 
  M104_INCOMING_TRUNK_ID      VARCHAR2(9 BYTE), 
  M104_OUTGOING_TRUNK_ID      VARCHAR2(9 BYTE), 
  M504_DATE_BEFORE_CHANGE     VARCHAR2(5 BYTE), 
  M504_TIME_BEFORE_CHANGE     VARCHAR2(7 BYTE), 
  M504_DATE_AFTER_CHANGE      VARCHAR2(5 BYTE), 
  M504_TIME_AFTER_CHANGE      VARCHAR2(7 BYTE), 
  M509_ORIGINATING_FEATURE_CODES  VARCHAR2(3 BYTE), 
  M509_TERMINATING_FEATURE_CODES  VARCHAR2(3 BYTE), 
  M611_CONTEXT_80024              VARCHAR2(16 BYTE), 
  M611_CONTEXT_80050              VARCHAR2(16 BYTE), 
  M612_CONTEXT_80011              VARCHAR2(32 BYTE) 
)
PARTITION BY RANGE (CREATED_DATE)
(   
  PARTITION I_CS2K_MAXVALUE VALUES LESS THAN (MAXVALUE)
    LOGGING
    COMPRESS
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

Insert into MZ_FILTER_REASONS (FILTER_REASON_ID,DESCRIPTION) values (39, 'NANP Structure');

Insert into MZ_FILTER_REASONS (FILTER_REASON_ID,DESCRIPTION) values (35,'Inefective call');
Insert into MZ_FILTER_REASONS (FILTER_REASON_ID,DESCRIPTION) values (38,'Unknown business unit');
Insert into MZ_FILTER_REASONS (FILTER_REASON_ID,DESCRIPTION) values (37,'On-Net call');
Insert into MZ_FILTER_REASONS (FILTER_REASON_ID,DESCRIPTION) values (36,'Invalid UDR');
