CREATE TABLE CDR_INPUT_OMP
(
  FILE_CONTROL_ID          NUMBER     NOT NULL,
  FILE_REC_ID              NUMBER     NOT NULL,
  CREATED_DATE             DATE       DEFAULT SYSDATE NOT NULL,
  TRANSACTION_ID           NUMBER(15) NOT NULL,
  CALLING_NUMBER       	   VARCHAR2(20 BYTE),
  CALLED_NUMBER		   VARCHAR2(20 BYTE),
  BILL_RECORD_TYPE	   VARCHAR2(2 BYTE), 
  CALL_DATE                VARCHAR2(8 BYTE),
  CALL_START_TIME	   VARCHAR2(6 BYTE),
  ACTUAL_DURATION	   VARCHAR2(6 BYTE),
  CHARGED_DURATION	   VARCHAR2(6 BYTE),
  PRICE			   VARCHAR2(10 BYTE),
  XFC			   VARCHAR2(1 BYTE),
  ALM			   VARCHAR2(1 BYTE),
  CCB			   VARCHAR2(1 BYTE),
  AO			   VARCHAR2(1 BYTE),
  INEFF			   VARCHAR2(1 BYTE),
  PROPORTION_TEXT	   VARCHAR2(3 BYTE)
)
PARTITION BY RANGE (CREATED_DATE)
(   
  PARTITION I_OMP_MAXVALUE VALUES LESS THAN (MAXVALUE)
    LOGGING
    COMPRESS
);

CREATE INDEX IDX_OMP_CALLED_NUMBER ON CDR_INPUT_OMP
(CALLED_NUMBER)
  LOCAL (
  PARTITION I_OMP_MAXVALUE
    LOGGING
    NOCOMPRESS
)
NOPARALLEL;


CREATE INDEX IDX_OMP_CALLING_NUMBER ON CDR_INPUT_OMP
(CALLING_NUMBER)
  LOCAL (
  PARTITION I_OMP_MAXVALUE
    LOGGING
    NOCOMPRESS
)
NOPARALLEL;

insert into MZ_CONFIGURATION (PARAMETER,PARAMETER_VALUE) values ('OMP_DUPBATCH_CHECK',1);
insert into MZ_CONFIGURATION (PARAMETER,PARAMETER_VALUE) values ('OMP_DUPUDR_CHECK',1);
insert into MZ_FILTER_REASONS (FILTER_REASON_ID,DESCRIPTION) values (54,'OMP Record Type 27');
insert into MZ_FILTER_REASONS (FILTER_REASON_ID,DESCRIPTION) values (55,'OMP Record Type 28');
insert into MZ_FILTER_REASONS (FILTER_REASON_ID,DESCRIPTION) values (56,'OMP ChargecardCallRecord');
insert into MZ_FILTER_REASONS (FILTER_REASON_ID,DESCRIPTION) values (57,'OMP ChargecardDetailsRecord');
insert into MZ_FILTER_REASONS (FILTER_REASON_ID,DESCRIPTION) values (58,'OMP No Feature In Record');
insert into MZ_FILTER_REASONS (FILTER_REASON_ID,DESCRIPTION) values (59,'OMP Ineffective');

CREATE TABLE IDA_PREFIX_PRIMARY 
  ( PREFIX          VARCHAR2 (8) NOT NULL
  , DIGITS_STRIPPED VARCHAR2 (3) 
  , DESCRIPTION     VARCHAR2 (200)
   );

CREATE TABLE IDA_PREFIX_SECONDARY 
  ( PREFIX          VARCHAR2 (8)
  , DIGITS_STRIPPED VARCHAR2 (3)
  , DESCRIPTION     VARCHAR2 (200)
   );

CREATE TABLE CDR_OUTPUT_CS2K_ECS 
   ( FILE_CONTROL_ID        NUMBER    NOT NULL
   , FILE_REC_ID            NUMBER    NOT NULL
   , CREATED_DATE           DATE      DEFAULT sysdate NOT NULL
   , TRANSACTION_ID         NUMBER    NOT NULL 
   , CALLING_NUMBER         VARCHAR2  (30) 
   , CALLED_NUMBER          VARCHAR2  (30)
   , SWITCH_NUMBER          VARCHAR2  (2)
   , SESSION_NUMBER         VARCHAR2  (12)
   , SEQUENCE_NUMBER        VARCHAR2  (10)
   , IN_TRUNK               VARCHAR2  (10)
   , OUT_TRUNK              VARCHAR2  (10)
   , CDR_DATE               VARCHAR2  (8)
   , CDR_START_TIME         VARCHAR2  (8)
   , CDR_DURATION           VARCHAR2  (10)
   , ERROR_CODE             VARCHAR2  (30)
   , TIMESTAMP_IN           TIMESTAMP (6)
   , TIMESTAMP_REPROCESSING TIMESTAMP (6)
)
PARTITION BY RANGE (CREATED_DATE)
(  
  PARTITION O_CS2K_ECS_MAXVALUE VALUES LESS THAN (MAXVALUE)
    LOGGING
    COMPRESS
);

CREATE INDEX IDX_O_CS2K_ECS_CALLED_NUMBER ON CDR_OUTPUT_CS2K_ECS
(CALLED_NUMBER)
  LOCAL (  
  PARTITION O_CS2K_ECS_MAXVALUE
    LOGGING
    NOCOMPRESS
);


CREATE INDEX IDX_O_CS2K_ECS_CALLING_NUMBER ON CDR_OUTPUT_CS2K_ECS
(CALLING_NUMBER)
  LOCAL (  
  PARTITION O_CS2K_ECS_MAXVALUE
    LOGGING
    NOCOMPRESS
);
