-- CREATE INDEX ON CDR_OUTPUT_CS2K_ECS
--
CREATE INDEX MZ_CDR_OWNER.IDX_O_CS2K_ECS_COMPOSITE ON MZ_CDR_OWNER.CDR_OUTPUT_CS2K_ECS
(SWITCH_NUMBER, SESSION_NUMBER, SEQUENCE_NUMBER)
  PCTFREE    10
  INITRANS   2
  MAXTRANS   255
LOCAL (  
  PARTITION O_CS2K_ECS_MAXVALUE
    LOGGING
    NOCOMPRESS
    TABLESPACE MZ_CDR_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                BUFFER_POOL      DEFAULT
               )
)
NOPARALLEL;


-- CREATE TABLE DN_SHORTCODE_SUFFIX_CODES
--
CREATE TABLE MZ_CDR_OWNER.DN_SHORTCODE_SUFFIX_CODES
(
  SHORTCODE    VARCHAR2(10 BYTE)                NOT NULL,
  DESCRIPTION  VARCHAR2(200 BYTE)
)
TABLESPACE MZ_CDR_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

 
-- CREATE INDEX ON DN_SHORTCODE_SUFFIX_CODES
--
CREATE UNIQUE INDEX MZ_CDR_OWNER.DN_SHORTCODE_SUFFIX_CODES_PK ON MZ_CDR_OWNER.DN_SHORTCODE_SUFFIX_CODES
(SHORTCODE)
LOGGING
TABLESPACE MZ_CDR_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


-- CREATE SYNONYM
--
CREATE SYNONYM MZ_CDR_USER.DN_SHORTCODE_SUFFIX_CODES FOR MZ_CDR_OWNER.DN_SHORTCODE_SUFFIX_CODES;


-- ADD CONSTRAINT TO DN_SHORTCODE_SUFFIX_CODES
--
ALTER TABLE MZ_CDR_OWNER.DN_SHORTCODE_SUFFIX_CODES ADD (
  CONSTRAINT DN_SHORTCODE_SUFFIX_CODES
 PRIMARY KEY
 (SHORTCODE));


-- GRANT SELECT TO THE TABLE FOR MZ_CDR_READONLY
--
GRANT SELECT ON MZ_CDR_OWNER.DN_SHORTCODE_SUFFIX_CODES TO MZ_CDR_READONLY;


-- INSERT DATA INTO THE DN_SHORTCODE_SUFFIX_CODES TABLE
--
INSERT INTO DN_SHORTCODE_SUFFIX_CODES ( SHORTCODE, DESCRIPTION ) VALUES ( 
'10034', 'Operator'); 
INSERT INTO DN_SHORTCODE_SUFFIX_CODES ( SHORTCODE, DESCRIPTION ) VALUES ( 
'11234', 'ES'); 
INSERT INTO DN_SHORTCODE_SUFFIX_CODES ( SHORTCODE, DESCRIPTION ) VALUES ( 
'12334', 'Speaking Clock'); 
INSERT INTO DN_SHORTCODE_SUFFIX_CODES ( SHORTCODE, DESCRIPTION ) VALUES ( 
'19534', 'Operator'); 
INSERT INTO DN_SHORTCODE_SUFFIX_CODES ( SHORTCODE, DESCRIPTION ) VALUES ( 
'19834', 'Operator'); 
INSERT INTO DN_SHORTCODE_SUFFIX_CODES ( SHORTCODE, DESCRIPTION ) VALUES ( 
'99934', 'ES');


-- INSERT NEW FILTER REASONS
--
INSERT INTO MZ_FILTER_REASONS ( FILTER_REASON_ID, DESCRIPTION ) VALUES ( 
60, 'Arbor Blank Terminating Number'); 
INSERT INTO MZ_FILTER_REASONS ( FILTER_REASON_ID, DESCRIPTION ) VALUES ( 
61, 'Unknown BU Ineffective Call'); 
INSERT INTO MZ_FILTER_REASONS ( FILTER_REASON_ID, DESCRIPTION ) VALUES ( 
62, 'EC0417_Invalid_Duration'); 
INSERT INTO MZ_FILTER_REASONS ( FILTER_REASON_ID, DESCRIPTION ) VALUES (
63, 'Invalid Re-rate Record Status');
INSERT INTO MZ_FILTER_REASONS ( FILTER_REASON_ID, DESCRIPTION ) VALUES (
64, 'Record type 326 - cannot derive usage_type');


-- INSERT NEW FREEPHONE PREFIX CODES
--
INSERT INTO DN_FREEPHONE_PREFIX_CODES ( FREEPHONE_PREFIX_CODE,
FREEPHONE_PREFIX_DESC ) VALUES ('155', 'International Operator prefix');
INSERT INTO DN_FREEPHONE_PREFIX_CODES ( FREEPHONE_PREFIX_CODE,
FREEPHONE_PREFIX_DESC ) VALUES ('198', 'Special Assistance Operator prefix');
