-- CREATE THE IMS OUTPUT ECS TABLE
--
CREATE TABLE CDR_OUTPUT_IMS_ECS 
   ( FILE_CONTROL_ID        NUMBER    NOT NULL
   , FILE_REC_ID            NUMBER    NOT NULL
   , CREATED_DATE           DATE      DEFAULT sysdate NOT NULL
   , TRANSACTION_ID         NUMBER    NOT NULL 
   , CALLING_NUMBER         VARCHAR2  (30) 
   , CALLED_NUMBER          VARCHAR2  (30)
   , SWITCH_ID              VARCHAR2  (20)
   , SESSION_NUMBER         VARCHAR2  (12)
   , SEQUENCE_NUMBER        VARCHAR2  (10)
   , IN_TRUNK               VARCHAR2  (10)
   , OUT_TRUNK              VARCHAR2  (10)
   , CDR_TIMESTAMP          TIMESTAMP (6)
   , CDR_DURATION_MS        NUMBER    (22)
   , ERROR_CODE             VARCHAR2  (30)
   , TIMESTAMP_IN           TIMESTAMP (6)
   , TIMESTAMP_REPROCESSING TIMESTAMP (6)
   , ORIG_FNAME_TIMESTAMP   VARCHAR2  (18)
)
PARTITION BY RANGE (CREATED_DATE)
(  
  PARTITION O_IMS_ECS_MAXVALUE VALUES LESS THAN (MAXVALUE)
    LOGGING
    COMPRESS
);

CREATE INDEX IDX_O_IMS_ECS_CALLED_NUMBER ON CDR_OUTPUT_IMS_ECS
(CALLED_NUMBER)
  LOCAL (  
  PARTITION O_IMS_ECS_MAXVALUE
    LOGGING
    NOCOMPRESS
);


CREATE INDEX IDX_O_IMS_ECS_CALLING_NUMBER ON CDR_OUTPUT_IMS_ECS
(CALLING_NUMBER)
  LOCAL (  
  PARTITION O_IMS_ECS_MAXVALUE
    LOGGING
    NOCOMPRESS
);

CREATE INDEX IDX_O_IMS_ECS_IDX1 ON CDR_OUTPUT_IMS_ECS
(SWITCH_ID, SESSION_NUMBER, SEQUENCE_NUMBER)
COMPUTE STATISTICS TABLESPACE MZ_CDR_DATA
LOCAL (  
  PARTITION O_IMS_ECS_MAXVALUE
    LOGGING
    NOCOMPRESS
);



-- INSERT NEW PARAMETERS FOR IMS DUPLICATE CHECKING
--
INSERT INTO MZ_CONFIGURATION VALUES (
'IMS_DUP_BATCH_CHECK', 0);
INSERT INTO MZ_CONFIGURATION VALUES (
'IMS_DUP_UDR_CHECK', 0);


-- INSERT NEW FILTER REASON
--
INSERT INTO MZ_FILTER_REASONS ( FILTER_REASON_ID, DESCRIPTION ) VALUES ( 
66, 'IMS Terminating Role CDRs dropped');


-- INSERT NEW FREEPHONE PREFIX CODES
--
INSERT INTO DN_FREEPHONE_PREFIX_CODES VALUES (
'111', 'Department Of Health prefix');
INSERT INTO DN_FREEPHONE_PREFIX_CODES VALUES (
'195', 'Special Assistance Directory Enquiries prefix');


-- INSERT NEW BUSINESS_UNIT FOR EASYNET ENTERPRISE AND THE LIFECYCLE BILLING FEED
--
INSERT INTO BUSINESS_UNITS VALUES (
5, 'ESYENT');
