CREATE TABLE CDR_INPUT_IMS 
   ( FILE_CONTROL_ID              NUMBER    NOT NULL
   , FILE_REC_ID                  NUMBER    NOT NULL
   , CREATED_DATE                 DATE      DEFAULT sysdate NOT NULL
   , TRANSACTION_ID               NUMBER    NOT NULL 
   , RECORD_TYPE                  NUMBER
   , SWITCH_ID                    VARCHAR2  (20)
   , ORIG_FNAME_TIMESTAMP         VARCHAR2  (18)
   , CALLING_PARTY                VARCHAR2  (128)
   , CALLED_PARTY                 VARCHAR2  (128)
   , A_NUMBER                     VARCHAR2  (30)
   , B_NUMBER                     VARCHAR2  (30)
   , INDEXING_TIMESTAMP           TIMESTAMP (6)
   , DURATION                     NUMBER    (22)
   , DURATION_MS                  NUMBER    (22)
   , ACCOUNTING_REC_TYPE          NUMBER
   , SESSION_ID                   VARCHAR2  (14)
   , ROLE_OF_NODE                 NUMBER
   , SERVICE_IDENTIFIER           NUMBER
   , RECORD_CLOSED_REASON         NUMBER
   , LOCAL_REC_SEQ_NUMBER         VARCHAR2  (10)
   , RECORD_SEQ_NUMBER            NUMBER
   , IMS_CHARGING_ID              VARCHAR2  (128)
   , INCOMP_CDR_IND_ACRLOST_START VARCHAR2  (1)
   , INCOMP_CDR_IND_ACRLOST_INTRM NUMBER
   , INCOMP_CDR_IND_ACRLOST_STOP  VARCHAR2  (1)
   , SIP_METHOD                   VARCHAR2  (30)
   , SRVC_REASON_RTN_CODE         VARCHAR2  (10)
   , INCOMING_TRUNK_GRP_ID        VARCHAR2  (10)
   , OUTGOING_TRUNK_GRP_ID        VARCHAR2  (10)
)
PARTITION BY RANGE (CREATED_DATE)
(  
  PARTITION O_IMS_MAXVALUE VALUES LESS THAN (MAXVALUE)
    NOLOGGING
    COMPRESS
);

CREATE INDEX IDX_C_IMS_A_NUMBER ON CDR_INPUT_IMS
(A_NUMBER)
  LOCAL (  
  PARTITION O_IMS_MAXVALUE
    NOLOGGING
    NOCOMPRESS
);


CREATE INDEX IDX_C_IMS_B_NUMBER ON CDR_INPUT_IMS
(B_NUMBER)
  LOCAL (  
  PARTITION O_IMS_MAXVALUE
    NOLOGGING
    NOCOMPRESS
);
