-- CREATE A NEW SEQUENCE FOR THE IMS FRAUD FEED
--
CREATE SEQUENCE MZ_CDR_OWNER.FRAUD_IMS_OUTPUT_SEQ
  MINVALUE 1 
  MAXVALUE 999999999999999999999999999 
  INCREMENT BY 1 
  START WITH 1 
  NOCACHE  
  NOORDER  
  NOCYCLE;
  
CREATE SYNONYM MZ_CDR_USER.FRAUD_IMS_OUTPUT_SEQ FOR MZ_CDR_OWNER.FRAUD_IMS_OUTPUT_SEQ;

GRANT SELECT ON  MZ_CDR_OWNER.FRAUD_IMS_OUTPUT_SEQ TO MZ_CDR_UPDATE;  