-- RENAME THE EXISTING SEQUENCE TO A TEMPORARY SEQUENCE NAME
--
RENAME FRAUD_IMS_OUTPUT_SEQ TO TMP_SEQ;


-- CREATE A NEW SEQUENCE FOR THE IMS FMS FEED
--
CREATE SEQUENCE MZ_CDR_OWNER.FRAUD_IMS_OUTPUT_SEQ
  MINVALUE 1 
  MAXVALUE 999999999999999999999999999 
  INCREMENT BY 1 
  START WITH 1 
  NOCACHE  
  NOORDER  
  NOCYCLE;


-- RENAME TEMPORARY SEQUENCE NAME TO THE BI FULL FEED ACTUAL NAME
--
RENAME TMP_SEQ TO BI_FULL_IMS_OUTPUT_SEQ;


CREATE SYNONYM MZ_CDR_USER.BI_FULL_IMS_OUTPUT_SEQ FOR MZ_CDR_OWNER.BI_FULL_IMS_OUTPUT_SEQ;


GRANT SELECT ON MZ_CDR_OWNER.FRAUD_IMS_OUTPUT_SEQ TO MZ_CDR_UPDATE;


-- INSERT NEW FILTER REASON
--
INSERT INTO MZ_FILTER_REASONS ( FILTER_REASON_ID, DESCRIPTION ) VALUES (
67, 'Filtered for FMS');