CREATE SEQUENCE CDR_FILTERED_PICNIC_THUS_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 1000
  NOORDER;

CREATE SEQUENCE CDR_FILTERED_SKYTALK_THUS_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 1000
  NOORDER;

CREATE SEQUENCE CDR_FILTERED_WCLI_DEDS_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 1000
  NOORDER;

CREATE SEQUENCE CDR_FILTERED_WLR_DEDS_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 1000
  NOORDER;

CREATE SEQUENCE CDR_INPUT_PICNIC_THUS_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 1000
  NOORDER;

CREATE SEQUENCE CDR_INPUT_SKYTALK_THUS_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 1000
  NOORDER;

CREATE SEQUENCE CDR_INPUT_WCLI_DEDS_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 1000
  NOORDER;

CREATE SEQUENCE CDR_INPUT_WLR_DEDS_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 1000
  NOORDER;

CREATE SEQUENCE CDR_OUTPUT_PICNIC_ARBOR_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 1000
  NOORDER;

CREATE SEQUENCE CDR_OUTPUT_SKYTALK_ARBOR_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 1000
  NOORDER;

CREATE SEQUENCE CDR_OUTPUT_WCLI_DEDS_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 1000
  NOORDER;

CREATE SEQUENCE CDR_OUTPUT_WLR_DEDS_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 1000
  NOORDER;

CREATE TABLE CDR_OUTPUT_WLR_DEDS
(
  FILE_CONTROL_ID   NUMBER                      NOT NULL,
  FILE_REC_ID       NUMBER                      NOT NULL,
  CREATED_DATE      DATE                        DEFAULT SYSDATE               NOT NULL,
  TRANSACTION_ID    NUMBER(15)                  NOT NULL,
  CALLING_NUMBER    VARCHAR2(30 BYTE),
  CALLED_NUMBER     VARCHAR2(30 BYTE),
  RECORD_TYPE       VARCHAR2(10 BYTE),
  USAGE_TYPE        VARCHAR2(5 BYTE),
  TIME_ZONE         VARCHAR2(5 BYTE),
  ORIGIN            VARCHAR2(30 BYTE),
  TARGET            VARCHAR2(30 BYTE),
  EXTERNAL_ID_TYPE  VARCHAR2(2 BYTE),
  EXTERNAL_ID       VARCHAR2(47 BYTE),
  TRANS_DATE_TIME   VARCHAR2(14 BYTE),
  PRIMARY_VALUE     VARCHAR2(10 BYTE),
  COMPLETION_CODE   VARCHAR2(3 BYTE),
  BILL_CLASS_ID     VARCHAR2(3 BYTE),
  PROPORTION_TEXT   VARCHAR2(3 BYTE),
  WHOLESALE_PRICE   VARCHAR2(8 BYTE)
)
PARTITION BY RANGE (CREATED_DATE)
(
  PARTITION O_WLR_DEDS_MAXVALUE VALUES LESS THAN (MAXVALUE)
    LOGGING
    COMPRESS
)
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;

CREATE TABLE CDR_OUTPUT_SKYTALK_ARBOR
(
  FILE_CONTROL_ID   NUMBER                      NOT NULL,
  FILE_REC_ID       NUMBER                      NOT NULL,
  CREATED_DATE      DATE                        DEFAULT SYSDATE               NOT NULL,
  TRANSACTION_ID    NUMBER(15)                  NOT NULL,
  CALLING_NUMBER    VARCHAR2(30 BYTE),
  CALLED_NUMBER     VARCHAR2(30 BYTE),
  RECORD_TYPE       VARCHAR2(10 BYTE),
  USAGE_TYPE        VARCHAR2(5 BYTE),
  TIME_ZONE         VARCHAR2(5 BYTE),
  ORIGIN            VARCHAR2(30 BYTE),
  TARGET            VARCHAR2(30 BYTE),
  EXTERNAL_ID_TYPE  VARCHAR2(2 BYTE),
  EXTERNAL_ID       VARCHAR2(47 BYTE),
  TRANS_DATE_TIME   VARCHAR2(14 BYTE),
  PRIMARY_VALUE     VARCHAR2(10 BYTE),
  COMPLETION_CODE   VARCHAR2(3 BYTE),
  BILL_CLASS_ID     VARCHAR2(3 BYTE),
  PROPORTION_TEXT   VARCHAR2(3 BYTE),
  WHOLESALE_PRICE   VARCHAR2(8 BYTE)
)
PARTITION BY RANGE (CREATED_DATE)
(
  PARTITION O_SKYTALK_ARBOR_MAXVALUE VALUES LESS THAN (MAXVALUE)
    LOGGING
    COMPRESS
)
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;

CREATE TABLE CDR_OUTPUT_PICNIC_ARBOR
(
  FILE_CONTROL_ID   NUMBER                      NOT NULL,
  FILE_REC_ID       NUMBER                      NOT NULL,
  CREATED_DATE      DATE                        DEFAULT SYSDATE               NOT NULL,
  TRANSACTION_ID    NUMBER(15)                  NOT NULL,
  CALLING_NUMBER    VARCHAR2(30 BYTE),
  CALLED_NUMBER     VARCHAR2(30 BYTE),
  RECORD_TYPE       VARCHAR2(10 BYTE),
  USAGE_TYPE        VARCHAR2(5 BYTE),
  TIME_ZONE         VARCHAR2(5 BYTE),
  ORIGIN            VARCHAR2(30 BYTE),
  TARGET            VARCHAR2(30 BYTE),
  EXTERNAL_ID_TYPE  VARCHAR2(2 BYTE),
  EXTERNAL_ID       VARCHAR2(47 BYTE),
  TRANS_DATE_TIME   VARCHAR2(14 BYTE),
  PRIMARY_VALUE     VARCHAR2(10 BYTE),
  COMPLETION_CODE   VARCHAR2(3 BYTE),
  BILL_CLASS_ID     VARCHAR2(3 BYTE),
  PROPORTION_TEXT   VARCHAR2(3 BYTE),
  WHOLESALE_PRICE   VARCHAR2(8 BYTE)
)
PARTITION BY RANGE (CREATED_DATE)
(
  PARTITION O_PICNIC_ARBOR_MAXVALUE VALUES LESS THAN (MAXVALUE)
    LOGGING
    COMPRESS
)
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;


CREATE TABLE CDR_INPUT_PICNIC_THUS
(
  FILE_CONTROL_ID          NUMBER               NOT NULL,
  FILE_REC_ID              NUMBER               NOT NULL,
  CREATED_DATE             DATE                 DEFAULT SYSDATE               NOT NULL,
  TRANSACTION_ID           NUMBER(15)           NOT NULL,
  CALLING_NUMBER           VARCHAR2(30 BYTE),
  CALLED_NUMBER            VARCHAR2(30 BYTE),
  CLI                      VARCHAR2(30 BYTE),
  CALL_START_DATE          VARCHAR2(6 BYTE),
  CALL_START_TIME          VARCHAR2(6 BYTE),
  CALL_DURATION            NUMBER(8),
  THUS_ACCOUNT_NUMBER      VARCHAR2(12 BYTE),
  CARRIER_COST             NUMBER(18),
  THUS_COST                VARCHAR2(12 BYTE),
  THUS_CALL_AREA_NAME      VARCHAR2(25 BYTE),
  THUS_RATE_PERIOD         VARCHAR2(5 BYTE),
  THUS_CALL_TYPE           VARCHAR2(6 BYTE),
  LONG_CALL_DURATION_FLAG  NUMBER(1),
  SAD_CALL_FLAG            NUMBER(1)
)
PARTITION BY RANGE (CREATED_DATE)
(
  PARTITION I_PICNIC_THUS_MAXVALUE VALUES LESS THAN (MAXVALUE)
    LOGGING
    COMPRESS
)
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;

CREATE TABLE CDR_FILTERED_WLR_DEDS
(
  FILE_CONTROL_ID  NUMBER                       NOT NULL,
  FILE_REC_ID      NUMBER                       NOT NULL,
  CREATED_DATE     DATE                         DEFAULT SYSDATE               NOT NULL,
  TRANSACTION_ID   NUMBER(15)                   NOT NULL,
  CALLING_NUMBER   VARCHAR2(30 BYTE),
  CALLED_NUMBER    VARCHAR2(30 BYTE)
)
PARTITION BY RANGE (CREATED_DATE)
(
  PARTITION F_WLR_DEDS_MAXVALUE VALUES LESS THAN (MAXVALUE)
    LOGGING
    COMPRESS
)
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;

CREATE TABLE CDR_FILTERED_SKYTALK_THUS
(
  FILE_CONTROL_ID  NUMBER                       NOT NULL,
  FILE_REC_ID      NUMBER                       NOT NULL,
  CREATED_DATE     DATE                         DEFAULT SYSDATE               NOT NULL,
  TRANSACTION_ID   NUMBER(15)                   NOT NULL,
  CALLING_NUMBER   VARCHAR2(30 BYTE),
  CALLED_NUMBER    VARCHAR2(30 BYTE)
)
PARTITION BY RANGE (CREATED_DATE)
(
  PARTITION F_SKYTALK_THUS_MAXVALUE VALUES LESS THAN (MAXVALUE)
    LOGGING
    COMPRESS
)
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;

CREATE TABLE CDR_FILTERED_PICNIC_THUS
(
  FILE_CONTROL_ID  NUMBER                       NOT NULL,
  FILE_REC_ID      NUMBER                       NOT NULL,
  CREATED_DATE     DATE                         DEFAULT SYSDATE               NOT NULL,
  TRANSACTION_ID   NUMBER(15)                   NOT NULL,
  CALLING_NUMBER   VARCHAR2(30 BYTE),
  CALLED_NUMBER    VARCHAR2(30 BYTE)
)
PARTITION BY RANGE (CREATED_DATE)
(
  PARTITION F_PICNIC_THUS_MAXVALUE VALUES LESS THAN (MAXVALUE)
    LOGGING
    COMPRESS
)
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;

ALTER TABLE CDR_OUTPUT_BTW_DEDS_THUS
MODIFY(CLI VARCHAR2(30 BYTE));


ALTER TABLE MZ_AUDIT_STATISTICS
MODIFY(TOTAL_DURATION NUMBER(17,2));


ALTER TABLE MZ_AUDIT_OUTPUT
MODIFY(TOTAL_DURATION NUMBER(17,2));


ALTER TABLE MZ_AUDIT_INPUT
MODIFY(TOTAL_DURATION NUMBER(17,2));


ALTER TABLE MZ_AUDIT_FILTERED
MODIFY(TOTAL_DURATION NUMBER(17,2));


CREATE TABLE CDR_OUTPUT_WCLI_DEDS
(
  FILE_CONTROL_ID   NUMBER                      NOT NULL,
  FILE_REC_ID       NUMBER                      NOT NULL,
  CREATED_DATE      DATE                        DEFAULT SYSDATE               NOT NULL,
  TRANSACTION_ID    NUMBER(15)                  NOT NULL,
  CALLING_NUMBER    VARCHAR2(30 BYTE),
  CALLED_NUMBER     VARCHAR2(30 BYTE),
  RECORD_TYPE       VARCHAR2(10 BYTE),
  USAGE_TYPE        VARCHAR2(5 BYTE),
  TIME_ZONE         VARCHAR2(5 BYTE),
  ORIGIN            VARCHAR2(30 BYTE),
  TARGET            VARCHAR2(30 BYTE),
  EXTERNAL_ID_TYPE  VARCHAR2(2 BYTE),
  EXTERNAL_ID       VARCHAR2(47 BYTE),
  TRANS_DATE_TIME   VARCHAR2(14 BYTE),
  PRIMARY_VALUE     VARCHAR2(10 BYTE),
  COMPLETION_CODE   VARCHAR2(3 BYTE),
  BILL_CLASS_ID     VARCHAR2(3 BYTE),
  PROPORTION_TEXT   VARCHAR2(3 BYTE),
  WHOLESALE_PRICE   VARCHAR2(8 BYTE)
)
PARTITION BY RANGE (CREATED_DATE)
(  
  PARTITION O_WCLI_DEDS_MAXVALUE VALUES LESS THAN (MAXVALUE)
    LOGGING
    NOCOMPRESS
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;

CREATE TABLE CDR_FILTERED_WCLI_DEDS
(
  FILE_CONTROL_ID  NUMBER                       NOT NULL,
  FILE_REC_ID      NUMBER                       NOT NULL,
  CREATED_DATE     DATE                         DEFAULT SYSDATE               NOT NULL,
  TRANSACTION_ID   NUMBER(15)                   NOT NULL,
  CALLING_NUMBER   VARCHAR2(30 BYTE),
  CALLED_NUMBER    VARCHAR2(30 BYTE)
)
PARTITION BY RANGE (CREATED_DATE)
(   
  PARTITION F_WCLI_DEDS_MAXVALUE VALUES LESS THAN (MAXVALUE)
    LOGGING
    NOCOMPRESS
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;

CREATE TABLE CDR_INPUT_WCLI_DEDS
(
  FILE_CONTROL_ID        NUMBER                 NOT NULL,
  FILE_REC_ID            NUMBER                 NOT NULL,
  CREATED_DATE           DATE                   DEFAULT SYSDATE               NOT NULL,
  TRANSACTION_ID         NUMBER(15)             NOT NULL,
  CALLING_NUMBER         VARCHAR2(30 BYTE),
  CALLED_NUMBER          VARCHAR2(30 BYTE),
  TAG                    VARCHAR2(20 BYTE),
  CALLING_LINE_IDENTITY  VARCHAR2(30 BYTE),
  EVENT_TYPE             VARCHAR2(20 BYTE),
  DATE_AND_TIME_FIELDS   VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_1      VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_2      VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_3      VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_4      VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_5      VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_6      VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_7      VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_8      VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_9      VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_10     VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_11     VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_12     VARCHAR2(20 BYTE),
  SPID                   VARCHAR2(15 BYTE),
  PBX_SUFFIX             VARCHAR2(20 BYTE),
  DURATION_OF_CALL       VARCHAR2(40 BYTE),
  RESERVED_FOR_BT_13     VARCHAR2(20 BYTE),
  LINK_FIELD             VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_14     VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_15     VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_16     VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_17     VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_18     VARCHAR2(100 BYTE),
  RERATE_INDICATOR       VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_19     VARCHAR2(20 BYTE),
  ACCOUNT_NUMBER         VARCHAR2(20 BYTE),
  RECORD_STATUS          VARCHAR2(20 BYTE),
  WHOLESALE_PRICE        VARCHAR2(20 BYTE),
  PHONEBOOK_CODE         VARCHAR2(100 BYTE),
  RESERVED_FOR_BT_20     VARCHAR2(20 BYTE),
  SERVICE_TYPE           VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_21     VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_22     VARCHAR2(20 BYTE)
)
PARTITION BY RANGE (CREATED_DATE)
(  
  PARTITION I_WCLI_DEDS_MAXVALUE VALUES LESS THAN (MAXVALUE)
    LOGGING
    NOCOMPRESS
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;

CREATE TABLE CDR_INPUT_WLR_DEDS
(
  FILE_CONTROL_ID        NUMBER                 NOT NULL,
  FILE_REC_ID            NUMBER                 NOT NULL,
  CREATED_DATE           DATE                   DEFAULT SYSDATE               NOT NULL,
  TRANSACTION_ID         NUMBER(15)             NOT NULL,
  CALLING_NUMBER         VARCHAR2(30 BYTE),
  CALLED_NUMBER          VARCHAR2(30 BYTE),
  TAG                    VARCHAR2(20 BYTE),
  CALLING_LINE_IDENTITY  VARCHAR2(30 BYTE),
  EVENT_TYPE             VARCHAR2(20 BYTE),
  DATE_AND_TIME_FIELDS   VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_1      VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_2      VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_3      VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_4      VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_5      VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_6      VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_7      VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_8      VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_9      VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_10     VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_11     VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_12     VARCHAR2(20 BYTE),
  SPID                   VARCHAR2(15 BYTE),
  PBX_SUFFIX             VARCHAR2(20 BYTE),
  DURATION_OF_CALL       VARCHAR2(40 BYTE),
  RESERVED_FOR_BT_13     VARCHAR2(20 BYTE),
  LINK_FIELD             VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_14     VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_15     VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_16     VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_17     VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_18     VARCHAR2(100 BYTE),
  RERATE_INDICATOR       VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_19     VARCHAR2(20 BYTE),
  ACCOUNT_NUMBER         VARCHAR2(20 BYTE),
  RECORD_STATUS          VARCHAR2(20 BYTE),
  WHOLESALE_PRICE        VARCHAR2(20 BYTE),
  PHONEBOOK_CODE         VARCHAR2(100 BYTE),
  RESERVED_FOR_BT_20     VARCHAR2(20 BYTE),
  SERVICE_TYPE           VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_21     VARCHAR2(20 BYTE),
  RESERVED_FOR_BT_22     VARCHAR2(20 BYTE)
)
PARTITION BY RANGE (CREATED_DATE)
(  
  PARTITION I_WLR_DEDS_MAXVALUE VALUES LESS THAN (MAXVALUE)
    LOGGING
    NOCOMPRESS
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;

CREATE TABLE CDR_INPUT_SKYTALK_THUS
(
  FILE_CONTROL_ID          NUMBER               NOT NULL,
  FILE_REC_ID              NUMBER               NOT NULL,
  CREATED_DATE             DATE                 DEFAULT SYSDATE               NOT NULL,
  TRANSACTION_ID           NUMBER(15)           NOT NULL,
  CALLING_NUMBER           VARCHAR2(30 BYTE),
  CALLED_NUMBER            VARCHAR2(30 BYTE),
  CLI                      VARCHAR2(30 BYTE),
  CALL_START_DATE          VARCHAR2(6 BYTE),
  CALL_START_TIME          VARCHAR2(6 BYTE),
  CALL_DURATION            NUMBER(8),
  THUS_ACCOUNT_NUMBER      VARCHAR2(12 BYTE),
  CARRIER_COST             NUMBER(18),
  THUS_COST                VARCHAR2(12 BYTE),
  THUS_CALL_AREA_NAME      VARCHAR2(25 BYTE),
  THUS_RATE_PERIOD         VARCHAR2(5 BYTE),
  THUS_CALL_TYPE           VARCHAR2(6 BYTE),
  LONG_CALL_DURATION_FLAG  NUMBER(1),
  SAD_CALL_FLAG            NUMBER(1)
)
PARTITION BY RANGE (CREATED_DATE)
(  
  PARTITION I_SKYTALK_THUS_MAXVALUE VALUES LESS THAN (MAXVALUE)
    LOGGING
    NOCOMPRESS
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;



CREATE INDEX IDX_F_WCD_CALLED_NUMBER ON CDR_FILTERED_WCLI_DEDS
(CALLED_NUMBER)
  LOCAL (
  PARTITION F_WCLI_DEDS_MAXVALUE
    LOGGING
    NOCOMPRESS
)
NOPARALLEL;


CREATE INDEX IDX_F_WCD_CALLING_NUMBER ON CDR_FILTERED_WCLI_DEDS
(CALLING_NUMBER)
  LOCAL (
  PARTITION F_WCLI_DEDS_MAXVALUE
    LOGGING
    NOCOMPRESS
)
NOPARALLEL;


CREATE INDEX IDX_F_PT_CALLED_NUMBER ON CDR_FILTERED_PICNIC_THUS
(CALLED_NUMBER)
  LOCAL (
  PARTITION F_PICNIC_THUS_MAXVALUE
    LOGGING
    NOCOMPRESS
)
NOPARALLEL;


CREATE INDEX IDX_F_PT_CALLING_NUMBER ON CDR_FILTERED_PICNIC_THUS
(CALLING_NUMBER)
  LOCAL (
  PARTITION F_PICNIC_THUS_MAXVALUE
    LOGGING
    NOCOMPRESS
)
NOPARALLEL;


CREATE INDEX IDX_F_ST_CALLED_NUMBER ON CDR_FILTERED_SKYTALK_THUS
(CALLED_NUMBER)
  LOCAL (
  PARTITION F_SKYTALK_THUS_MAXVALUE
    LOGGING
    NOCOMPRESS
)
NOPARALLEL;


CREATE INDEX IDX_F_ST_CALLING_NUMBER ON CDR_FILTERED_SKYTALK_THUS
(CALLING_NUMBER)
  LOCAL (
  PARTITION F_SKYTALK_THUS_MAXVALUE
    LOGGING
    NOCOMPRESS
)
NOPARALLEL;


CREATE INDEX IDX_F_WLD_CALLED_NUMBER ON CDR_FILTERED_WLR_DEDS
(CALLED_NUMBER)
  LOCAL (
  PARTITION F_WLR_DEDS_MAXVALUE
    LOGGING
    NOCOMPRESS
)
NOPARALLEL;


CREATE INDEX IDX_F_WLD_CALLING_NUMBER ON CDR_FILTERED_WLR_DEDS
(CALLING_NUMBER)
  LOCAL (
  PARTITION F_WLR_DEDS_MAXVALUE
    LOGGING
    NOCOMPRESS
)
NOPARALLEL;





CREATE INDEX IDX_I_WCD_CALLED_NUMBER ON CDR_INPUT_WCLI_DEDS
(CALLED_NUMBER)
  LOCAL (
  PARTITION I_WCLI_DEDS_MAXVALUE
    LOGGING
    NOCOMPRESS
)
NOPARALLEL;


CREATE INDEX IDX_I_WCD_CALLING_NUMBER ON CDR_INPUT_WCLI_DEDS
(CALLING_NUMBER)
  LOCAL (
  PARTITION I_WCLI_DEDS_MAXVALUE
    LOGGING
    NOCOMPRESS
)
NOPARALLEL;

CREATE INDEX IDX_I_PT_CALLED_NUMBER ON CDR_INPUT_PICNIC_THUS
(CALLED_NUMBER)
  LOCAL (
  PARTITION I_PICNIC_THUS_MAXVALUE
    LOGGING
    NOCOMPRESS
)
NOPARALLEL;


CREATE INDEX IDX_I_PT_CALLING_NUMBER ON CDR_INPUT_PICNIC_THUS
(CALLING_NUMBER)
  LOCAL (
  PARTITION I_PICNIC_THUS_MAXVALUE
    LOGGING
    NOCOMPRESS
)
NOPARALLEL;


CREATE INDEX IDX_I_ST_CALLED_NUMBER ON CDR_INPUT_SKYTALK_THUS
(CALLED_NUMBER)
  LOCAL (
  PARTITION I_SKYTALK_THUS_MAXVALUE
    LOGGING
    NOCOMPRESS
)
NOPARALLEL;


CREATE INDEX IDX_I_ST_CALLING_NUMBER ON CDR_INPUT_SKYTALK_THUS
(CALLING_NUMBER)
  LOCAL (
  PARTITION I_SKYTALK_THUS_MAXVALUE
    LOGGING
    NOCOMPRESS
)
NOPARALLEL;


CREATE INDEX IDX_I_WLD_CALLED_NUMBER ON CDR_INPUT_WLR_DEDS
(CALLED_NUMBER)
  LOCAL (
  PARTITION I_WLR_DEDS_MAXVALUE
    LOGGING
    NOCOMPRESS
)
NOPARALLEL;


CREATE INDEX IDX_I_WLD_CALLING_NUMBER ON CDR_INPUT_WLR_DEDS
(CALLING_NUMBER)
  LOCAL (
  PARTITION I_WLR_DEDS_MAXVALUE
    LOGGING
    NOCOMPRESS
)
NOPARALLEL;






CREATE INDEX IDX_O_WCD_CALLED_NUMBER ON CDR_OUTPUT_WCLI_DEDS
(CALLED_NUMBER)
  LOCAL (
  PARTITION O_WCLI_DEDS_MAXVALUE
    LOGGING
    NOCOMPRESS
)
NOPARALLEL;


CREATE INDEX IDX_O_WCD_CALLING_NUMBER ON CDR_OUTPUT_WCLI_DEDS
(CALLING_NUMBER)
  LOCAL (
  PARTITION O_WCLI_DEDS_MAXVALUE
    LOGGING
    NOCOMPRESS
)
NOPARALLEL;


CREATE INDEX IDX_O_PA_CALLED_NUMBER ON CDR_OUTPUT_PICNIC_ARBOR
(CALLED_NUMBER)
  LOCAL (
  PARTITION O_PICNIC_ARBOR_MAXVALUE
    LOGGING
    NOCOMPRESS
)
NOPARALLEL;


CREATE INDEX IDX_O_PA_CALLING_NUMBER ON CDR_OUTPUT_PICNIC_ARBOR
(CALLING_NUMBER)
  LOCAL (
  PARTITION O_PICNIC_ARBOR_MAXVALUE
    LOGGING
    NOCOMPRESS
)
NOPARALLEL;


CREATE INDEX IDX_O_SA_CALLED_NUMBER ON CDR_OUTPUT_SKYTALK_ARBOR
(CALLED_NUMBER)
  LOCAL (
  PARTITION O_SKYTALK_ARBOR_MAXVALUE
    LOGGING
    NOCOMPRESS
)
NOPARALLEL;


CREATE INDEX IDX_O_SA_CALLING_NUMBER ON CDR_OUTPUT_SKYTALK_ARBOR
(CALLING_NUMBER)
  LOCAL (
  PARTITION O_SKYTALK_ARBOR_MAXVALUE
    LOGGING
    NOCOMPRESS
)
NOPARALLEL;


CREATE INDEX IDX_O_WLD_CALLED_NUMBER ON CDR_OUTPUT_WLR_DEDS
(CALLED_NUMBER)
  LOCAL (
  PARTITION O_WLR_DEDS_MAXVALUE
    LOGGING
    NOCOMPRESS
)
NOPARALLEL;


CREATE INDEX IDX_O_WLD_CALLING_NUMBER ON CDR_OUTPUT_WLR_DEDS
(CALLING_NUMBER)
  LOCAL (
  PARTITION O_WLR_DEDS_MAXVALUE
    LOGGING
    NOCOMPRESS
)
NOPARALLEL;

Insert into MZ_CDR_OWNER.MZ_FILTER_REASONS
   (FILTER_REASON_ID, DESCRIPTION)
 Values
   (31, 'Duplicate Batch');
Insert into MZ_CDR_OWNER.MZ_FILTER_REASONS
   (FILTER_REASON_ID, DESCRIPTION)
 Values
   (32, 'Fraud File');
Insert into MZ_CDR_OWNER.MZ_FILTER_REASONS
   (FILTER_REASON_ID, DESCRIPTION)
 Values
   (33, 'Tariff File');

Insert into MZ_CDR_OWNER.MZ_CONFIGURATION
   (PARAMETER, PARAMETER_VALUE)
 Values
   ('THUS_PIC_LONG_DUR_CALL_LIMIT', 1800000000);
Insert into MZ_CDR_OWNER.MZ_CONFIGURATION
   (PARAMETER, PARAMETER_VALUE)
 Values
   ('THUS_PICNIC_DUP_CHECK', 1);
Insert into MZ_CDR_OWNER.MZ_CONFIGURATION
   (PARAMETER, PARAMETER_VALUE)
 Values
   ('THUS_SKY_LONG_DUR_CALL_LIMIT', 1800000000);
Insert into MZ_CDR_OWNER.MZ_CONFIGURATION
   (PARAMETER, PARAMETER_VALUE)
 Values
   ('THUS_SKYTALK_DUP_CHECK', 1);
Insert into MZ_CDR_OWNER.MZ_CONFIGURATION
   (PARAMETER, PARAMETER_VALUE)
 Values
   ('WLR_DEDS_DUP_CHECK', 1);
Insert into MZ_CDR_OWNER.MZ_CONFIGURATION
   (PARAMETER, PARAMETER_VALUE)
 Values
   ('WLR_DEDS_LONG_DUR_CALL_LIMIT', 1800000000);

Insert into MZ_CDR_OWNER.CDR_FILE_CONTROL
   (FILE_CONTROL_ID, FILE_TYPE, VERSION, EFFECTIVE_START_DATE, EFFECTIVE_END_DATE, TABLE_NAME)
 Values
   (4, 'WLR_DEDS', '1', TO_DATE('01/01/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('12/31/2099 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'CDR_INPUT_WLR_DEDS');
Insert into MZ_CDR_OWNER.CDR_FILE_CONTROL
   (FILE_CONTROL_ID, FILE_TYPE, VERSION, EFFECTIVE_START_DATE, EFFECTIVE_END_DATE, TABLE_NAME)
 Values
   (5, 'SKYTALK', '1', TO_DATE('01/01/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('12/31/2099 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'CDR_INPUT_SKYTALK_THUS');
Insert into MZ_CDR_OWNER.CDR_FILE_CONTROL
   (FILE_CONTROL_ID, FILE_TYPE, VERSION, EFFECTIVE_START_DATE, EFFECTIVE_END_DATE, TABLE_NAME)
 Values
   (6, 'SKYTALK', '1', TO_DATE('01/01/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('12/31/2099 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'CDR_FILTERED_SKYTALK_THUS');
Insert into MZ_CDR_OWNER.CDR_FILE_CONTROL
   (FILE_CONTROL_ID, FILE_TYPE, VERSION, EFFECTIVE_START_DATE, EFFECTIVE_END_DATE, TABLE_NAME)
 Values
   (7, 'SKYTALK', '1', TO_DATE('01/01/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('12/31/2099 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'CDR_OUTPUT_SKYTALK_ARBOR');
Insert into MZ_CDR_OWNER.CDR_FILE_CONTROL
   (FILE_CONTROL_ID, FILE_TYPE, VERSION, EFFECTIVE_START_DATE, EFFECTIVE_END_DATE, TABLE_NAME)
 Values
   (8, 'WLR_DEDS', '1', TO_DATE('01/01/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('12/31/2099 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'CDR_FILTERED_WLR_DEDS');
Insert into MZ_CDR_OWNER.CDR_FILE_CONTROL
   (FILE_CONTROL_ID, FILE_TYPE, VERSION, EFFECTIVE_START_DATE, EFFECTIVE_END_DATE, TABLE_NAME)
 Values
   (9, 'WLR_DEDS', '1', TO_DATE('01/01/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('12/31/2099 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'CDR_OUTPUT_WLR_DEDS');
Insert into MZ_CDR_OWNER.CDR_FILE_CONTROL
   (FILE_CONTROL_ID, FILE_TYPE, VERSION, EFFECTIVE_START_DATE, EFFECTIVE_END_DATE, TABLE_NAME)
 Values
   (10, 'WCLI_DEDS', '1', TO_DATE('01/01/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('12/31/2099 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'CDR_FILTERED_WCLI_DEDS');
Insert into MZ_CDR_OWNER.CDR_FILE_CONTROL
   (FILE_CONTROL_ID, FILE_TYPE, VERSION, EFFECTIVE_START_DATE, EFFECTIVE_END_DATE, TABLE_NAME)
 Values
   (11, 'WCLI_DEDS', '1', TO_DATE('01/01/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('12/31/2099 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'CDR_INPUT_WCLI_DEDS');
Insert into MZ_CDR_OWNER.CDR_FILE_CONTROL
   (FILE_CONTROL_ID, FILE_TYPE, VERSION, EFFECTIVE_START_DATE, EFFECTIVE_END_DATE, TABLE_NAME)
 Values
   (12, 'WCLI_DEDS', '1', TO_DATE('01/01/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('12/31/2099 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'CDR_OUTPUT_WCLI_DEDS');
Insert into MZ_CDR_OWNER.CDR_FILE_CONTROL
   (FILE_CONTROL_ID, FILE_TYPE, VERSION, EFFECTIVE_START_DATE, EFFECTIVE_END_DATE, TABLE_NAME)
 Values
   (13, 'PICNIC', '1', TO_DATE('01/01/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('12/31/2099 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'CDR_INPUT_PICNIC_THUS');
Insert into MZ_CDR_OWNER.CDR_FILE_CONTROL
   (FILE_CONTROL_ID, FILE_TYPE, VERSION, EFFECTIVE_START_DATE, EFFECTIVE_END_DATE, TABLE_NAME)
 Values
   (14, 'PICNIC', '1', TO_DATE('01/01/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('12/31/2099 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'CDR_FILTERED_PICNIC_THUS');
Insert into MZ_CDR_OWNER.CDR_FILE_CONTROL
   (FILE_CONTROL_ID, FILE_TYPE, VERSION, EFFECTIVE_START_DATE, EFFECTIVE_END_DATE, TABLE_NAME)
 Values
   (15, 'PICNIC', '1', TO_DATE('01/01/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('12/31/2099 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'CDR_OUTPUT_PICNIC_ARBOR');
COMMIT;

