-- CREATE A NEW SEQUENCE FOR THE FRAUD OMP FEED
--
CREATE SEQUENCE MZ_CDR_OWNER.FRAUD_OMP_OUTPUT_SEQ
  MINVALUE 1 
  MAXVALUE 99999
  INCREMENT BY 1 
  START WITH 1 
  NOCACHE
  NOORDER
  CYCLE;

CREATE SYNONYM MZ_CDR_USER.FRAUD_OMP_OUTPUT_SEQ FOR MZ_CDR_OWNER.FRAUD_OMP_OUTPUT_SEQ;

GRANT SELECT ON MZ_CDR_OWNER.FRAUD_OMP_OUTPUT_SEQ TO MZ_CDR_UPDATE;


-- CREATE A NEW SEQUENCE FOR THE BI WCLI FEED
--
CREATE SEQUENCE MZ_CDR_OWNER.BI_WCLI_OUTPUT_SEQ
  MINVALUE 1 
  MAXVALUE 99999
  INCREMENT BY 1 
  START WITH 1 
  NOCACHE  
  NOORDER  
  CYCLE;

CREATE SYNONYM MZ_CDR_USER.BI_WCLI_OUTPUT_SEQ FOR MZ_CDR_OWNER.BI_WCLI_OUTPUT_SEQ;

GRANT SELECT ON MZ_CDR_OWNER.BI_WCLI_OUTPUT_SEQ TO MZ_CDR_UPDATE;


-- CREATE A NEW SEQUENCE FOR THE BI WLR FEED
--
CREATE SEQUENCE MZ_CDR_OWNER.BI_WLR_OUTPUT_SEQ
  MINVALUE 1 
  MAXVALUE 99999
  INCREMENT BY 1
  START WITH 1 
  NOCACHE  
  NOORDER  
  CYCLE;

CREATE SYNONYM MZ_CDR_USER.BI_WLR_OUTPUT_SEQ FOR MZ_CDR_OWNER.BI_WLR_OUTPUT_SEQ;

GRANT SELECT ON MZ_CDR_OWNER.BI_WLR_OUTPUT_SEQ TO MZ_CDR_UPDATE;