-- CREATE THE WLR3 INPUT TABLE
--
CREATE TABLE CDR_INPUT_WLR3
(
  FILE_CONTROL_ID          NUMBER               NOT NULL,
  FILE_REC_ID              NUMBER               NOT NULL,
  CREATED_DATE             DATE                 DEFAULT SYSDATE               NOT NULL,
  TRANSACTION_ID           NUMBER(15)           NOT NULL,
  CALLING_NUMBER           VARCHAR2(30 BYTE),
  CALLED_NUMBER            VARCHAR2(30 BYTE),
  TAG                      VARCHAR2(20 BYTE),
  CALLING_LINE_IDENTITY    VARCHAR2(30 BYTE),
  EVENT_TYPE               VARCHAR2(20 BYTE),
  DATE_AND_TIME_FIELDS     VARCHAR2(20 BYTE),
  SPID                     VARCHAR2(15 BYTE),
  PBX_SUFFIX               VARCHAR2(20 BYTE),
  DURATION_OF_CALL         VARCHAR2(40 BYTE),
  RERATE_INDICATOR         VARCHAR2(20 BYTE),
  ACCOUNT_NUMBER           VARCHAR2(20 BYTE),
  RECORD_STATUS            VARCHAR2(20 BYTE),
  WHOLESALE_PRICE          VARCHAR2(20 BYTE),
  DESCRIPTION              VARCHAR2(100 BYTE),
  SERVICE_TYPE             VARCHAR2(20 BYTE),
  PPNQ                     VARCHAR2(20 BYTE),
  REVERSE_CHARGE           VARCHAR2(20 BYTE),
  DATETIME_RECEIVED_MSG    VARCHAR2(30 BYTE),
  DIRECTION_TYPE_SMS       VARCHAR2(20 BYTE),
  DESTINATION_CODE         VARCHAR2(20 BYTE),
  MESSAGE_SIZE             VARCHAR2(20 BYTE),
  MESSAGE_TYPE             VARCHAR2(20 BYTE),
  TARIFF                   VARCHAR2(20 BYTE),
  DUR_INCOMING_FIXED_LINE  VARCHAR2(20 BYTE),
  CHARGEBAND               VARCHAR2(20 BYTE),
  PROPORTION_TEXT          VARCHAR2(20 BYTE)
)
TABLESPACE MZ_CDR_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
PARTITION BY RANGE (CREATED_DATE) 
SUBPARTITION BY HASH (TRANSACTION_ID)
SUBPARTITION TEMPLATE
  (SUBPARTITION H1,
   SUBPARTITION H2,
   SUBPARTITION H3,
   SUBPARTITION H4
  )
(  
  PARTITION I_WLR3_MAXVALUE VALUES LESS THAN (MAXVALUE)
    LOGGING
    NOCOMPRESS
    TABLESPACE I_WLR3_MAXVALUE
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                BUFFER_POOL      DEFAULT
               )
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;

CREATE INDEX IDX_I_WLR3_CALLED_NUMBER ON CDR_INPUT_WLR3
(CALLED_NUMBER)
  INITRANS   2
  MAXTRANS   255
LOCAL (  
  PARTITION I_WLR3_MAXVALUE
    LOGGING
    NOCOMPRESS
    TABLESPACE I_WLR3_MAXVALUE
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                BUFFER_POOL      DEFAULT
               )
)
NOPARALLEL;

CREATE INDEX IDX_I_WLR3_CALLING_NUMBER ON CDR_INPUT_WLR3
(CALLING_NUMBER)
  INITRANS   2
  MAXTRANS   255
LOCAL (  
  PARTITION I_WLR3_MAXVALUE
    LOGGING
    NOCOMPRESS
    TABLESPACE I_WLR3_MAXVALUE
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                BUFFER_POOL      DEFAULT
               )
)
NOPARALLEL;

CREATE SYNONYM MZ_CDR_USER.CDR_INPUT_WLR3 FOR CDR_INPUT_WLR3;

GRANT SELECT ON  CDR_INPUT_WLR3 TO MZ_CDR_READONLY;

GRANT DELETE, INSERT, UPDATE ON  CDR_INPUT_WLR3 TO MZ_CDR_UPDATE;

-- INSERT NEW FILTER REASONS
--
INSERT INTO MZ_FILTER_REASONS  VALUES (68, 'Record Type 354 - cannot derive usage_type');
INSERT INTO MZ_FILTER_REASONS  VALUES (69, 'Record Type 351/352 - cannot derive usage_type');
INSERT INTO MZ_FILTER_REASONS  VALUES (70, 'Record Type 353/355 - cannot derive usage_type');
INSERT INTO MZ_FILTER_REASONS  VALUES (71, 'EC0434_Invalid_Duration');

