-- RENAME THE EXISTING FRAUD SEQUENCE TO A TEMPORARY SEQUENCE NAME
--
RENAME FRAUD_OUTPUT_SEQ TO TMP_SEQ;


-- CREATE A NEW SEQUENCE FOR THE CS2K FMA FEED
--
CREATE SEQUENCE MZ_CDR_OWNER.FRAUD_CS2K_OUTPUT_SEQ
  MINVALUE 1
  MAXVALUE 99999
  INCREMENT BY 1
  START WITH 1
  NOCACHE
  NOORDER
  CYCLE;


-- RENAME TEMPORARY SEQUENCE NAME TO THE BI FULL FEED ACTUAL NAME
--
RENAME TMP_SEQ TO BI_FULL_CS2K_OUTPUT_SEQ;


CREATE SYNONYM MZ_CDR_USER.BI_FULL_CS2K_OUTPUT_SEQ FOR MZ_CDR_OWNER.BI_FULL_CS2K_OUTPUT_SEQ;

CREATE SYNONYM MZ_CDR_USER.FRAUD_CS2K_OUTPUT_SEQ FOR MZ_CDR_OWNER.FRAUD_CS2K_OUTPUT_SEQ;


GRANT SELECT ON MZ_CDR_OWNER.BI_FULL_CS2K_OUTPUT_SEQ TO MZ_CDR_UPDATE;

GRANT SELECT ON MZ_CDR_OWNER.FRAUD_CS2K_OUTPUT_SEQ TO MZ_CDR_UPDATE;
