-- Create indesxes on the audit tables to increase UM Reporting workflow speed
--
CREATE INDEX MZ_CDR_OWNER.IDX_AUD_I_FN ON MZ_CDR_OWNER.MZ_AUDIT_INPUT(FILE_NAME)
LOGGING
TABLESPACE MZ_CDR_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX MZ_CDR_OWNER.IDX_AUD_O_OFN ON MZ_CDR_OWNER.MZ_AUDIT_OUTPUT(OUTPUT_FILE_NAME)
LOGGING
TABLESPACE MZ_CDR_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX MZ_CDR_OWNER.IDX_AUD_F_IFN ON MZ_CDR_OWNER.MZ_AUDIT_FILTERED(INPUT_FILE_NAME)
LOGGING
TABLESPACE MZ_CDR_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX MZ_CDR_OWNER.IDX_AUD_FEAT_IFX ON MZ_CDR_OWNER.MZ_AUDIT_FEATURES(INPUT_FILE_NAME)
LOGGING
TABLESPACE MZ_CDR_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX MZ_CDR_OWNER.IDX_AUD_REP_FN ON MZ_CDR_OWNER.MZ_AUDIT_REPROCESSING(FILE_NAME)
LOGGING
TABLESPACE MZ_CDR_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX MZ_CDR_OWNER.IDX_AUDIT_S_IFN ON MZ_CDR_OWNER.MZ_AUDIT_STATISTICS(INPUT_FILE_NAME)
LOGGING
TABLESPACE MZ_CDR_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;
