CREATE TABLE MZ_CDR_OWNER.DN_ENHANCED_LOAD
(
  DIRECTORY_NUMBER  VARCHAR2(40 BYTE),
  UNIT_ID           NUMBER,
  START_DATE        DATE,
  SKCI_FLAG         NUMBER,
  CEASE_DATE        DATE,
  CKCI_FLAG         NUMBER
)
TABLESPACE MZ_CDR_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE TABLE MZ_CDR_OWNER.DN_ENHANCED_LOAD_PROV
(
  DIRECTORY_NUMBER  VARCHAR2(40 BYTE),
  UNIT_ID           NUMBER,
  START_DATE        DATE,
  SKCI_FLAG         NUMBER,
  CEASE_DATE        DATE,
  CKCI_FLAG         NUMBER
)
TABLESPACE MZ_CDR_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE TABLE MZ_CDR_OWNER.DN_ENHANCED_LOAD_CEASE
(
  DIRECTORY_NUMBER  VARCHAR2(40 BYTE),
  UNIT_ID           NUMBER,
  START_DATE        DATE,
  SKCI_FLAG         NUMBER,
  CEASE_DATE        DATE,
  CKCI_FLAG         NUMBER
)
TABLESPACE MZ_CDR_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE TABLE MZ_CDR_OWNER.DN_ENHANCED_BU_LOOKUP
(
  DIRECTORY_NUMBER  VARCHAR2(40 BYTE),
  UNIT_ID           NUMBER,
  START_DATE        DATE,
  SKCI_FLAG         NUMBER,
  CEASE_DATE        DATE,
  CKCI_FLAG         NUMBER
)
TABLESPACE MZ_CDR_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX MZ_CDR_OWNER.DN_ENHANCED_BU_LOOKUP_FK1 ON MZ_CDR_OWNER.DN_ENHANCED_BU_LOOKUP
(UNIT_ID)
LOGGING
TABLESPACE MZ_CDR_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX MZ_CDR_OWNER.DN_ENHANCED_BU_LOOKUP_PK ON MZ_CDR_OWNER.DN_ENHANCED_BU_LOOKUP
(DIRECTORY_NUMBER)
LOGGING
TABLESPACE MZ_CDR_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE MZ_CDR_OWNER.DN_ENHANCED_BU_LOOKUP ADD (
  PRIMARY KEY
 (DIRECTORY_NUMBER));

ALTER TABLE MZ_CDR_OWNER.DN_ENHANCED_BU_LOOKUP ADD (
  CONSTRAINT DN_ENHANCED_BU_LOOKUP_FK1 
 FOREIGN KEY (UNIT_ID) 
 REFERENCES MZ_CDR_OWNER.BUSINESS_UNITS (UNIT_ID));

grant select on MZ_CDR_OWNER.DN_ENHANCED_BU_LOOKUP to mz_cdr_readonly ;