-- Create a new CDR input table for project Harp - MZO-359
--
CREATE TABLE CDR_INPUT_ROI_BTI
(
	FILE_CONTROL_ID NUMBER(22) NOT NULL,
	FILE_REC_ID NUMBER(22) NOT NULL,
	CREATED_DATE DATE DEFAULT SYSDATE NOT NULL,
	TRANSACTION_ID NUMBER(22) NOT NULL,
	FILENAME_INFO VARCHAR2(20 BYTE),
	LINE_NO NUMBER(22),
	CLI VARCHAR2(30 BYTE),
	DIALLED VARCHAR2(52 BYTE),
	CALL_START_TIME VARCHAR2(18 BYTE),
	CALL_DURATION VARCHAR2(15 BYTE),
	WHOLESALE VARCHAR2(20 BYTE),
	WCC VARCHAR2(15 BYTE)
)
TABLESPACE MZ_CDR_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
PARTITION BY RANGE (CREATED_DATE)
(  
  PARTITION PMAXVALUE VALUES LESS THAN (MAXVALUE)
    LOGGING
    NOCOMPRESS
    TABLESPACE MZ_CDR_DATA
    PCTFREE    0
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                BUFFER_POOL      DEFAULT
               )
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;


-- Create two indexes on the new CDR input table
--
CREATE INDEX IDX_I_ROI_CLI ON CDR_INPUT_ROI_BTI(CLI) LOCAL NOPARALLEL;
CREATE INDEX IDX_I_ROI_DIALLED ON CDR_INPUT_ROI_BTI(DIALLED) LOCAL NOPARALLEL;


-- Create three new filter reasons
--
INSERT INTO MZ_CDR_OWNER.MZ_FILTER_REASONS VALUES (74, 'Field Oversize');
INSERT INTO MZ_CDR_OWNER.MZ_FILTER_REASONS VALUES (75, 'Invalid Duration');
INSERT INTO MZ_CDR_OWNER.MZ_FILTER_REASONS VALUES (76, 'Filtered Freephone');
