-- Create BTI duplication check flags for MZO-359
--
INSERT INTO MZ_CDR_OWNER.MZ_CONFIGURATION VALUES ('ROIBTI_DUP_BATCH_CHECK', 1);
INSERT INTO MZ_CDR_OWNER.MZ_CONFIGURATION VALUES ('BTI_1_DUP_UDR_CHECK', 1);
INSERT INTO MZ_CDR_OWNER.MZ_CONFIGURATION VALUES ('BTI_3_DUP_UDR_CHECK', 1);
INSERT INTO MZ_CDR_OWNER.MZ_CONFIGURATION VALUES ('BTI_7_DUP_UDR_CHECK', 1);