CREATE UNIQUE INDEX MZ_CONFIGURATION_PK
ON MZ_CONFIGURATION ( PARAMETER );

ALTER TABLE MZ_CONFIGURATION
ADD CONSTRAINT MZ_CONFIGURATION_PK
PRIMARY KEY ( PARAMETER );

INSERT INTO mz_configuration (parameter,parameter_value) VALUES ('CS2K_DUP_CHECK', 0);
INSERT INTO mz_configuration (parameter,parameter_value) VALUES ('CS2K_LONG_DUR_CALL_LIMIT', 21600);

CREATE TABLE MZ_CDR_OWNER.MZ_AUDIT_FEATURES 
( TXN_ID             NUMBER
, WF_NAME            VARCHAR2(220 CHAR)
, INPUT_FILE_NAME    VARCHAR2(100 CHAR)
, TIMESTAMP_FWD      DATE
, FEATURE_NAME       VARCHAR2(20 BYTE)
, CDR_COUNT          NUMBER
, TOTAL_WSALE_PRICE  NUMBER
, TOTAL_DURATION     NUMBER
, OUTPUT_FILE_NAME   VARCHAR2(100 CHAR)
, FILE_TIMESTAMP     DATE
);
