CREATE TABLE DN_RANGE_HOLDERS
( RANGE_START  VARCHAR2(20)  NOT NULL
, RANGE_END  VARCHAR2(15)  NOT NULL
, CUPID     VARCHAR2(6) NOT NULL
);

CREATE UNIQUE INDEX DN_RANGE_HOLDERS_PK ON DN_RANGE_HOLDERS (RANGE_START, RANGE_END);

ALTER TABLE DN_RANGE_HOLDERS ADD CONSTRAINT DN_RANGE_HOLDERS_PK PRIMARY KEY (RANGE_START, RANGE_END);

CREATE SEQUENCE  MZ_CDR_OWNER.IBS_OUTPUT_SEQ;
