CREATE SEQUENCE FRAUD_OUTPUT_SEQ;

CREATE TABLE DN_PORTABILITY_PREFIX_CODES
( PORTABILITY_PREFIX_CODE  VARCHAR2(6) NOT NULL
, PORTABILITY_PREFIX_DESC  VARCHAR2(200) NOT NULL
);

CREATE UNIQUE INDEX DN_PORTABILITY_PREFIX_CODES_PK ON DN_PORTABILITY_PREFIX_CODES(PORTABILITY_PREFIX_CODE);

ALTER TABLE DN_PORTABILITY_PREFIX_CODES ADD CONSTRAINT DN_PORTABILITY_PREFIX_CODES_PK PRIMARY KEY(PORTABILITY_PREFIX_CODE);

insert into DN_PORTABILITY_PREFIX_CODES (PORTABILITY_PREFIX_CODE, PORTABILITY_PREFIX_DESC)
values ('548500', 'Sky NPPC code');

insert into DN_PORTABILITY_PREFIX_CODES (PORTABILITY_PREFIX_CODE, PORTABILITY_PREFIX_DESC)
values ('548550', 'Sky NPPC code');

insert into DN_RANGE_HOLDERS (RANGE_START, RANGE_END, CUPID)
values ('0000000001','09999999999', '001');

insert into BUSINESS_UNITS (UNIT_ID,UNIT_NAME)
values (0,'TRANST');
