CREATE TABLE DN_FREEPHONE_PREFIX_CODES
( FREEPHONE_PREFIX_CODE  VARCHAR2(15) NOT NULL
, FREEPHONE_PREFIX_DESC  VARCHAR2(200) NOT NULL
);
 
CREATE UNIQUE INDEX DN_FREEPHONE_PREFIX_CODES_PK ON DN_FREEPHONE_PREFIX_CODES(FREEPHONE_PREFIX_CODE);
 
ALTER TABLE DN_FREEPHONE_PREFIX_CODES ADD CONSTRAINT DN_FREEPHONE_PREFIX_CODES_PK PRIMARY KEY(FREEPHONE_PREFIX_CODE);

-- INSERT FREEPHONE PREFIX CODES
--
INSERT INTO DN_FREEPHONE_PREFIX_CODES ( FREEPHONE_PREFIX_CODE,
FREEPHONE_PREFIX_DESC ) VALUES ( 
'0800', 'Freephone prefix'); 
INSERT INTO DN_FREEPHONE_PREFIX_CODES ( FREEPHONE_PREFIX_CODE,
FREEPHONE_PREFIX_DESC ) VALUES ( 
'0500', 'Freephone prefix'); 
INSERT INTO DN_FREEPHONE_PREFIX_CODES ( FREEPHONE_PREFIX_CODE,
FREEPHONE_PREFIX_DESC ) VALUES ( 
'100', 'Operator prefix'); 
INSERT INTO DN_FREEPHONE_PREFIX_CODES ( FREEPHONE_PREFIX_CODE,
FREEPHONE_PREFIX_DESC ) VALUES ( 
'0808', 'Freephone prefix'); 
INSERT INTO DN_FREEPHONE_PREFIX_CODES ( FREEPHONE_PREFIX_CODE,
FREEPHONE_PREFIX_DESC ) VALUES ( 
'1571', 'VoiceMail'); 
INSERT INTO DN_FREEPHONE_PREFIX_CODES ( FREEPHONE_PREFIX_CODE,
FREEPHONE_PREFIX_DESC ) VALUES ( 
'17070', 'Line Test Number'); 
INSERT INTO DN_FREEPHONE_PREFIX_CODES ( FREEPHONE_PREFIX_CODE,
FREEPHONE_PREFIX_DESC ) VALUES ( 
'1572', 'Voicemail'); 
INSERT INTO DN_FREEPHONE_PREFIX_CODES ( FREEPHONE_PREFIX_CODE,
FREEPHONE_PREFIX_DESC ) VALUES ( 
'1577', 'Voicemail'); 
INSERT INTO DN_FREEPHONE_PREFIX_CODES ( FREEPHONE_PREFIX_CODE,
FREEPHONE_PREFIX_DESC ) VALUES ( 
'1578', 'Voicemail'); 
INSERT INTO DN_FREEPHONE_PREFIX_CODES ( FREEPHONE_PREFIX_CODE,
FREEPHONE_PREFIX_DESC ) VALUES ( 
'999', 'Emergency Services'); 
INSERT INTO DN_FREEPHONE_PREFIX_CODES ( FREEPHONE_PREFIX_CODE,
FREEPHONE_PREFIX_DESC ) VALUES ( 
'112', 'Emergency Services'); 
