-- SQL to run for MZ App upgrade from 6 to 7
--

--BEGIN_PLSQL
DECLARE V_CONSTRAINT_NAME VARCHAR(64);
BEGIN
SELECT CONSTRAINT_NAME INTO V_CONSTRAINT_NAME FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'ECS_UDR' AND CONSTRAINT_TYPE = 'R' AND R_CONSTRAINT_NAME = 'PK_ECS_GROUP';
EXECUTE IMMEDIATE 'ALTER TABLE ECS_UDR DROP CONSTRAINT ' || V_CONSTRAINT_NAME;
SELECT CONSTRAINT_NAME INTO V_CONSTRAINT_NAME FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'ECS_BATCH' AND CONSTRAINT_TYPE = 'R' AND R_CONSTRAINT_NAME = 'PK_ECS_GROUP';
EXECUTE IMMEDIATE 'ALTER TABLE ECS_BATCH DROP CONSTRAINT ' || V_CONSTRAINT_NAME;
SELECT CONSTRAINT_NAME INTO V_CONSTRAINT_NAME FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'ECS_UDR_ERROR' AND CONSTRAINT_TYPE = 'R' AND R_CONSTRAINT_NAME = 'PK_ECS_ERROR_CODE';
EXECUTE IMMEDIATE 'ALTER TABLE ECS_UDR_ERROR DROP CONSTRAINT ' || V_CONSTRAINT_NAME;
SELECT CONSTRAINT_NAME INTO V_CONSTRAINT_NAME FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'ECS_BATCH_ERROR' AND CONSTRAINT_TYPE = 'R' AND R_CONSTRAINT_NAME = 'PK_ECS_ERROR_CODE';
EXECUTE IMMEDIATE 'ALTER TABLE ECS_BATCH_ERROR DROP CONSTRAINT ' || V_CONSTRAINT_NAME;
SELECT CONSTRAINT_NAME INTO V_CONSTRAINT_NAME FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'ECS_ERROR_CODE' AND CONSTRAINT_TYPE = 'R' AND R_CONSTRAINT_NAME = 'PK_ECS_GROUP';
EXECUTE IMMEDIATE 'ALTER TABLE ECS_ERROR_CODE DROP CONSTRAINT ' || V_CONSTRAINT_NAME;
END;
--END_PLSQL