-- MZMOB-545 - Enhancements to TAPIN Mediation Filtering

CREATE TABLE MZ_MOB_DATA_OWNER.DN_FREEPHONE_PREFIX_CODES_TAP (
	FREEPHONE_PREFIX_CODE VARCHAR(20),
	FREEPHONE_PREFIX_DESC VARCHAR(100)
	);
	
INSERT INTO MZ_MOB_DATA_OWNER.DN_FREEPHONE_PREFIX_CODES_TAP (FREEPHONE_PREFIX_CODE, FREEPHONE_PREFIX_DESC) VALUES (44800, 'Freephone Prefix');
INSERT INTO MZ_MOB_DATA_OWNER.DN_FREEPHONE_PREFIX_CODES_TAP (FREEPHONE_PREFIX_CODE, FREEPHONE_PREFIX_DESC) VALUES (44808, 'Freephone Prefix');
INSERT INTO MZ_MOB_DATA_OWNER.DN_FREEPHONE_PREFIX_CODES_TAP (FREEPHONE_PREFIX_CODE, FREEPHONE_PREFIX_DESC) VALUES (44150, 'Freephone CS');
INSERT INTO MZ_MOB_DATA_OWNER.DN_FREEPHONE_PREFIX_CODES_TAP (FREEPHONE_PREFIX_CODE, FREEPHONE_PREFIX_DESC) VALUES (441312783778, 'Freephone CS');
INSERT INTO MZ_MOB_DATA_OWNER.DN_FREEPHONE_PREFIX_CODES_TAP (FREEPHONE_PREFIX_CODE, FREEPHONE_PREFIX_DESC) VALUES (443442414141, 'Freephone CS');
INSERT INTO MZ_MOB_DATA_OWNER.DN_FREEPHONE_PREFIX_CODES_TAP (FREEPHONE_PREFIX_CODE, FREEPHONE_PREFIX_DESC) VALUES (447488222000, 'Voicemail');


CREATE TABLE MZ_MOB_DATA_OWNER.MSRN_RANGES_SKY (
	RANGE_START VARCHAR(20),
	RANGE_END VARCHAR(20),
	TADIG VARCHAR(20)
	);
	
INSERT INTO MZ_MOB_DATA_OWNER.MSRN_RANGES_SKY (RANGE_START, RANGE_END, TADIG) VALUES (447488210000, 447488221999, 'GBRKY');
