-- MZMOB-545 CRR-355 - TAPIN Filtering Enhancements

DELETE FROM MZ_MOB_DATA_OWNER.DN_FREEPHONE_PREFIX_CODES_TAP
WHERE FREEPHONE_PREFIX_CODE = 44150;

INSERT INTO MZ_MOB_DATA_OWNER.DN_FREEPHONE_PREFIX_CODES_TAP (FREEPHONE_PREFIX_CODE, FREEPHONE_PREFIX_DESC) VALUES ('150', 'Freephone CS');
