-- MZMOB-738. Insert GTs for roaming SMSoLTE

--
INSERT INTO SKY_SMSC_LTE_GT_ROI ( GT, ROLE_OF_NODE,
DESCRIPTION ) VALUES (
'353896503', 0, 'ENGLO IP-SM-GW(VoLTE Roaming)'); 

INSERT INTO SKY_SMSC_LTE_GT_ROI ( GT, ROLE_OF_NODE,
DESCRIPTION ) VALUES (
'353896504', 0, 'MIMNC IP-SM-GW(VoLTE Roaming)'); 

INSERT INTO SKY_SMSC_LTE_GT_ROI ( GT, ROLE_OF_NODE,
DESCRIPTION ) VALUES (
'353896505', 0, 'ENBGK IP-SM-GW(VoLTE Roaming)'); 

INSERT INTO SKY_SMSC_LTE_GT_ROI ( GT, ROLE_OF_NODE,
DESCRIPTION ) VALUES (
'353896506', 0, 'ENLCS IP-SM-GW(VoLTE Roaming)'); 
