-- MED-642. Nokia IMS DB Write is failing due to LOCAL_REC_SEQ_NUMBER being too large.

ALTER TABLE CDR_INPUT_IMS_NOKIA MODIFY LOCAL_REC_SEQ_NUMBER VARCHAR2(15);

ALTER TABLE CDR_INPUT_IMS_NOKIA_ROI MODIFY LOCAL_REC_SEQ_NUMBER VARCHAR2(15);