-- MZMOB-136 - Widen the OBJ_ID fields as a fix-on-fail
--
ALTER TABLE CDR_INPUT_OCS_VOICE MODIFY OBJ_ID VARCHAR2(80);
ALTER TABLE CDR_INPUT_OCS_GPRS MODIFY OBJ_ID VARCHAR2(80);
ALTER TABLE CDR_INPUT_OCS_MMS MODIFY OBJ_ID VARCHAR2(80);
ALTER TABLE CDR_INPUT_OCS_SMS MODIFY OBJ_ID VARCHAR2(80);