-- MZMOB-448 - Recreate the indexes in the CDR_INPUT_TAP and CDR_INPUT_OCS_VOICE table
--
DROP INDEX CDR_INPUT_TAP_IDX1;
 
DROP INDEX CDR_INPUT_TAP_IDX2;
 
CREATE INDEX CDR_INPUT_TAP_IDX1 ON CDR_INPUT_TAP (A_NUMBER) LOCAL PARALLEL 16;
 
CREATE INDEX CDR_INPUT_TAP_IDX2 ON CDR_INPUT_TAP (B_NUMBER) LOCAL PARALLEL 16;
 
ALTER INDEX CDR_INPUT_TAP_IDX1 NOPARALLEL;
 
ALTER INDEX CDR_INPUT_TAP_IDX2 NOPARALLEL;


-- Recreate the indexes in the CDR_INPUT_OCS_VOICE table
--
DROP INDEX CDR_INPUT_OCS_VOICE_IDX1;

DROP INDEX CDR_INPUT_OCS_VOICE_IDX2;

CREATE INDEX CDR_INPUT_OCS_VOICE_IDX1 ON CDR_INPUT_OCS_VOICE (A_NUMBER) LOCAL PARALLEL 16;

CREATE INDEX CDR_INPUT_OCS_VOICE_IDX2 ON CDR_INPUT_OCS_VOICE (B_NUMBER) LOCAL PARALLEL 16;

ALTER INDEX CDR_INPUT_OCS_VOICE_IDX1 NOPARALLEL;

ALTER INDEX CDR_INPUT_OCS_VOICE_IDX2 NOPARALLEL;