-- MZMOB-437 - Add local index to CALLING_PARTY_IMSI to improve search performance
--
CREATE INDEX CDR_INPUT_OCS_VOICE_IDX4 ON CDR_INPUT_OCS_VOICE (CALLING_PARTY_IMSI) LOCAL PARALLEL 16;

ALTER INDEX CDR_INPUT_OCS_VOICE_IDX4 NOPARALLEL;