-- MZMOB-513 - SQL Script to create partitions on CDR_INPUT_OCS_MMS
--

-- Rename table to keep a copy of existing data
--
RENAME CDR_INPUT_OCS_MMS TO CDR_INPUT_OCS_MMS_OLD;


-- Create the new partitioned table
--
CREATE TABLE CDR_INPUT_OCS_MMS
(
  TRANSACTION_ID                NUMBER          NOT NULL,
  CREATED_DATE                  DATE            DEFAULT sysdate               NOT NULL,
  INPUT_FILENAME                VARCHAR2(80 BYTE),
  CDR_ID                        VARCHAR2(20 BYTE),
  CDR_SUB_ID                    VARCHAR2(20 BYTE),
  CDR_TYPE                      VARCHAR2(1 BYTE),
  SPLIT_CDR_REASON              VARCHAR2(1 BYTE),
  CDR_BATCH_ID                  VARCHAR2(20 BYTE),
  SRC_REC_LINE_NO               VARCHAR2(10 BYTE),
  SRC_CDR_ID                    VARCHAR2(20 BYTE),
  SRC_CDR_NO                    VARCHAR2(20 BYTE),
  STATUS                        VARCHAR2(1 BYTE),
  RE_RATING_TIMES               VARCHAR2(3 BYTE),
  CREATE_DATE                   VARCHAR2(14 BYTE),
  START_DATE                    VARCHAR2(14 BYTE),
  END_DATE                      VARCHAR2(14 BYTE),
  CUST_LOCAL_START_DATE         VARCHAR2(14 BYTE),
  CUST_LOCAL_END_DATE           VARCHAR2(14 BYTE),
  STD_EVT_TYPE_ID               VARCHAR2(10 BYTE),
  EVT_SOURCE_CAT                VARCHAR2(1 BYTE),
  OBJ_TYPE                      VARCHAR2(1 BYTE),
  OBJ_ID                        VARCHAR2(80 BYTE),
  OWNER_CUST_ID                 VARCHAR2(20 BYTE),
  DEFAULT_ACCT_ID               VARCHAR2(20 BYTE),
  PRI_IDENTITY                  VARCHAR2(64 BYTE),
  BILL_CYCLE_ID                 VARCHAR2(20 BYTE),
  SERVICE_CATEG                 VARCHAR2(10 BYTE),
  USAGE_SERVICE_TYPE            VARCHAR2(10 BYTE),
  SESSION_ID                    VARCHAR2(128 BYTE),
  RESULT_CODE                   VARCHAR2(10 BYTE),
  RESULT_REASON                 VARCHAR2(256 BYTE),
  BE_ID                         VARCHAR2(10 BYTE),
  HOT_SEQ                       VARCHAR2(10 BYTE),
  CP_ID                         VARCHAR2(10 BYTE),
  RECIPIENT_NUMBER              VARCHAR2(128 BYTE),
  USAGE_MEASURE_ID              VARCHAR2(10 BYTE),
  ACTUAL_USAGE                  VARCHAR2(20 BYTE),
  RATE_USAGE                    VARCHAR2(20 BYTE),
  SERVICE_UNIT_TYPE             VARCHAR2(10 BYTE),
  DEBIT_AMOUNT                  VARCHAR2(20 BYTE),
  TOTAL_TAX                     VARCHAR2(20 BYTE),
  CALLING_PARTY_NUMBER          VARCHAR2(64 BYTE),
  CALLED_PARTY_NUMBER           VARCHAR2(128 BYTE),
  A_NUMBER                      VARCHAR2(64 BYTE),
  B_NUMBER                      VARCHAR2(128 BYTE),
  CALLING_PARTY_IMSI            VARCHAR2(64 BYTE),
  CALLED_PARTY_IMSI             VARCHAR2(64 BYTE),
  DIALED_NUMBER                 VARCHAR2(128 BYTE),
  SERVICE_FLOW                  VARCHAR2(1 BYTE),
  CALLING_ROAM_INFO             VARCHAR2(256 BYTE),
  CALLING_CELL_ID               VARCHAR2(60 BYTE),
  CALLED_ROAM_INFO              VARCHAR2(256 BYTE),
  CALLED_CELL_ID                VARCHAR2(60 BYTE),
  TIMESTAMP_OF_SSP              VARCHAR2(14 BYTE),
  TIMEZONE_OF_SSP               VARCHAR2(10 BYTE),
  CHARGING_TIME                 VARCHAR2(14 BYTE),
  SEND_RESULT                   VARCHAR2(10 BYTE),
  MMS_ID                        VARCHAR2(24 BYTE),
  IMEI                          VARCHAR2(24 BYTE),
  MMS_LENGTH                    VARCHAR2(10 BYTE),
  REFUND_INDICATOR              VARCHAR2(20 BYTE),
  BRAND_ID                      VARCHAR2(20 BYTE),
  MAIN_OFFERING_ID              VARCHAR2(20 BYTE),
  CHARGING_PARTY_NUMBER         VARCHAR2(64 BYTE),
  CHARGE_PARTY_INDICATOR        VARCHAR2(1 BYTE),
  PAY_TYPE                      VARCHAR2(1 BYTE),
  CHARGING_TYPE                 VARCHAR2(1 BYTE),
  ON_NET_INDICATOR              VARCHAR2(1 BYTE),
  ROAM_STATE                    VARCHAR2(1 BYTE),
  CALLING_HOME_COUNTRY_CODE     VARCHAR2(10 BYTE),
  CALLING_HOME_AREA_NUMBER      VARCHAR2(10 BYTE),
  CALLING_HOME_NETWORK_CODE     VARCHAR2(10 BYTE),
  CALLING_ROAM_COUNTRY_CODE     VARCHAR2(10 BYTE),
  CALLING_ROAM_AREA_NUMBER      VARCHAR2(10 BYTE),
  CALLING_ROAM_NETWORK_CODE     VARCHAR2(10 BYTE),
  CALLED_HOME_COUNTRY_CODE      VARCHAR2(10 BYTE),
  CALLED_HOME_AREA_NUMBER       VARCHAR2(10 BYTE),
  CALLED_HOME_NETWORK_CODE      VARCHAR2(10 BYTE),
  CALLED_ROAM_COUNTRY_CODE      VARCHAR2(10 BYTE),
  CALLED_ROAM_AREA_NUMBER       VARCHAR2(10 BYTE),
  CALLED_ROAM_NETWORK_CODE      VARCHAR2(10 BYTE),
  SERVICE_TYPE                  VARCHAR2(128 BYTE),
  SPECIAL_NUMBER_INDICATOR      VARCHAR2(10 BYTE),
  NP_FLAG                       VARCHAR2(1 BYTE),
  NP_PREFIX                     VARCHAR2(6 BYTE),
  CALLING_CUG_NO                VARCHAR2(20 BYTE),
  CALLED_CUG_NO                 VARCHAR2(20 BYTE),
  OPPOSE_NUMBER_TYPE            VARCHAR2(10 BYTE),
  CALLING_NETWORK_TYPE          VARCHAR2(10 BYTE),
  CALLED_NETWORK_TYPE           VARCHAR2(10 BYTE),
  CALLING_VPN_TOP_GROUP_NUMBER  VARCHAR2(64 BYTE),
  CALLING_VPN_GROUP_NUMBER      VARCHAR2(64 BYTE),
  CALLING_VPN_SHORT_NUMBER      VARCHAR2(10 BYTE),
  CALLED_VPN_TOP_GROUP_NUMBER   VARCHAR2(64 BYTE),
  CALLED_VPN_GROUP_NUMBER       VARCHAR2(64 BYTE),
  CALLED_VPN_SHORT_NUMBER       VARCHAR2(10 BYTE),
  GROUP_CALL_TYPE               VARCHAR2(10 BYTE),
  ONLINE_CHARGING_FLAG          VARCHAR2(1 BYTE),
  START_TIME_OF_BILL_CYCLE      VARCHAR2(14 BYTE),
  LAST_EFFECT_OFFERING          VARCHAR2(30 BYTE),
  ORIG_ADDRESS_TYPE             VARCHAR2(10 BYTE),
  DEST_ADDRESS_TYPE             VARCHAR2(10 BYTE),
  MESSAGE_TYPE                  VARCHAR2(10 BYTE),
  VASP_ID                       VARCHAR2(20 BYTE),
  VAS_ID                        VARCHAR2(20 BYTE),
  SERVICE_ID                    VARCHAR2(20 BYTE),
  DT_DISCOUNT                   VARCHAR2(10 BYTE),
  OPPOSE_MAIN_OFFERING_ID       VARCHAR2(20 BYTE),
  USER_STATE                    VARCHAR2(10 BYTE),
  GROUP_PAY_FLAG                VARCHAR2(10 BYTE),
  ROAMING_ZONE_ID               VARCHAR2(20 BYTE),
  PRIMARY_OFFER_CHG_AMT         VARCHAR2(20 BYTE),
  CHARGE_CODE_INFO              VARCHAR2(256 BYTE),
  CALLING_HOME_COUNTRY          VARCHAR2(64 BYTE),
  CALLING_ROAM_COUNTRY          VARCHAR2(64 BYTE),
  CALLED_HOME_COUNTRY           VARCHAR2(64 BYTE),
  CALLED_ROAM_COUNTRY           VARCHAR2(64 BYTE),
  CALLED_HOME_AREA              VARCHAR2(64 BYTE)
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
partition by range(CREATED_DATE)
(
  PARTITION PMAXVALUE  VALUES LESS THAN (MAXVALUE) TABLESPACE  MZ_MOB_CDR_DATA);


-- Drop the existing indexes
--
DROP INDEX CDR_INPUT_OCS_MMS_IDX1;

DROP INDEX CDR_INPUT_OCS_MMS_IDX2;

DROP INDEX CDR_INPUT_OCS_MMS_IDX3;


-- Insert 31 days of data from the old table to the new table
--
INSERT /*+ append */ INTO CDR_INPUT_OCS_MMS (SELECT * FROM CDR_INPUT_OCS_MMS_OLD WHERE CREATED_DATE >= SYSDATE - 31);


-- Recreate the indexes on the partitioned table
--
CREATE INDEX CDR_INPUT_OCS_MMS_IDX1 ON CDR_INPUT_OCS_MMS (A_NUMBER) LOCAL;

CREATE INDEX CDR_INPUT_OCS_MMS_IDX2 ON CDR_INPUT_OCS_MMS (B_NUMBER) LOCAL;

CREATE INDEX CDR_INPUT_OCS_MMS_IDX3 ON CDR_INPUT_OCS_MMS (TRANSACTION_ID) LOCAL;


-- Create partition local index on created_date
--
CREATE INDEX CDR_INPUT_OCS_MMS_IDX4 ON CDR_INPUT_OCS_MMS (CREATED_DATE) LOCAL;


--
--
-- MZMOB-513 - SQL Script to create partitions on CDR_INPUT_OCS_MON
--

-- Rename table to keep a copy of existing data
--
RENAME CDR_INPUT_OCS_MON TO CDR_INPUT_OCS_MON_OLD;


-- Create the new partitioned table
--
CREATE TABLE CDR_INPUT_OCS_MON
(
  TRANSACTION_ID                NUMBER          NOT NULL,
  CREATED_DATE                  DATE            DEFAULT sysdate               NOT NULL,
  INPUT_FILENAME                VARCHAR2(80 BYTE),
  CDR_ID                        VARCHAR2(20 BYTE),
  CDR_SUB_ID                    VARCHAR2(20 BYTE),
  CDR_TYPE                      VARCHAR2(1 BYTE),
  SPLIT_CDR_REASON              VARCHAR2(1 BYTE),
  CDR_BATCH_ID                  VARCHAR2(20 BYTE),
  SRC_REC_LINE_NO               VARCHAR2(10 BYTE),
  SRC_CDR_ID                    VARCHAR2(20 BYTE),
  SRC_CDR_NO                    VARCHAR2(20 BYTE),
  STATUS                        VARCHAR2(1 BYTE),
  RE_RATING_TIMES               VARCHAR2(3 BYTE),
  CREATE_DATE                   VARCHAR2(14 BYTE),
  START_DATE                    VARCHAR2(14 BYTE),
  END_DATE                      VARCHAR2(14 BYTE),
  DURATION                      VARCHAR2(20 BYTE),
  CUST_LOCAL_START_DATE         VARCHAR2(14 BYTE),
  CUST_LOCAL_END_DATE           VARCHAR2(14 BYTE),
  STD_EVT_TYPE_ID               VARCHAR2(10 BYTE),
  EVT_SOURCE_CAT                VARCHAR2(1 BYTE),
  OBJ_TYPE                      VARCHAR2(1 BYTE),
  OBJ_ID                        VARCHAR2(64 BYTE),
  OWNER_CUST_ID                 VARCHAR2(20 BYTE),
  DEFAULT_ACCT_ID               VARCHAR2(20 BYTE),
  PRI_IDENTITY                  VARCHAR2(64 BYTE),
  BILL_CYCLE_ID                 VARCHAR2(20 BYTE),
  SERVICE_CATEG                 VARCHAR2(10 BYTE),
  USAGE_SERVICE_TYPE            VARCHAR2(10 BYTE),
  SESSION_ID                    VARCHAR2(128 BYTE),
  RESULT_CODE                   VARCHAR2(10 BYTE),
  RESULT_REASON                 VARCHAR2(256 BYTE),
  BE_ID                         VARCHAR2(10 BYTE),
  HOT_SEQ                       VARCHAR2(10 BYTE),
  CP_ID                         VARCHAR2(10 BYTE),
  RECIPIENT_NUMBER              VARCHAR2(64 BYTE),
  USAGE_MEASURE_ID              VARCHAR2(10 BYTE),
  ACTUAL_USAGE                  VARCHAR2(20 BYTE),
  RATE_USAGE                    VARCHAR2(20 BYTE),
  SERVICE_UNIT_TYPE             VARCHAR2(10 BYTE),
  DEBIT_AMOUNT                  VARCHAR2(20 BYTE),
  BRAND_ID                      VARCHAR2(20 BYTE),
  MAIN_OFFERING_ID              VARCHAR2(20 BYTE),
  PAY_TYPE                      VARCHAR2(1 BYTE),
  CHARGING_PARTY_NUMBER         VARCHAR2(64 BYTE),
  A_NUMBER                      VARCHAR2(64 BYTE),
  CHARGING_PARTY_TYPE           VARCHAR2(1 BYTE),
  CYCLE_BEGIN_TIME              VARCHAR2(14 BYTE),
  CYCLE_END_TIME                VARCHAR2(14 BYTE),
  CYCLE_LENGTH                  VARCHAR2(10 BYTE),
  ELAPSE_CYCLES                 VARCHAR2(10 BYTE),
  INNER_CYCLE_BEGIN_TIME        VARCHAR2(14 BYTE),
  INNER_CYCLE_END_TIME          VARCHAR2(14 BYTE),
  PRODUCT_ID                    VARCHAR2(20 BYTE),
  OFFERING_ID                   VARCHAR2(20 BYTE),
  OFFERING_INST_ID              VARCHAR2(20 BYTE),
  ORDER_STATUS                  VARCHAR2(1 BYTE),
  PRORATE_FLAG                  VARCHAR2(1 BYTE),
  START_TIME_OF_BILL_CYCLE      VARCHAR2(14 BYTE),
  CHARGE_PARTY_INDICATOR        VARCHAR2(1 BYTE),
  POS_RENT_MODE                 VARCHAR2(1 BYTE),
  TRIGGER_MODE                  VARCHAR2(1 BYTE),
  EXECUTE_FLAG                  VARCHAR2(1 BYTE),
  PRODUCT_CODE                  VARCHAR2(64 BYTE),
  MAIN_BALANCE_INFO             VARCHAR2(255 BYTE),
  CHG_BALANCE_INFO              VARCHAR2(255 BYTE),
  CHG_FREE_UNIT_INFO            VARCHAR2(255 BYTE),
  USER_STATE                    VARCHAR2(10 BYTE),
  CALLING_VPN_TOP_GROUP_NUMBER  VARCHAR2(64 BYTE),
  CALLING_VPN_GROUP_NUMBER      VARCHAR2(64 BYTE),
  GROUP_PAY_FLAG                VARCHAR2(10 BYTE)
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
partition by range(CREATED_DATE)
(
  PARTITION PMAXVALUE  VALUES LESS THAN (MAXVALUE) TABLESPACE  MZ_MOB_CDR_DATA);


-- Drop the existing indexes
--
DROP INDEX CDR_INPUT_OCS_MON_IDX1;

DROP INDEX CDR_INPUT_OCS_MON_IDX2;


-- Insert 31 days of data from the old table to the new table
--
INSERT /*+ append */ INTO CDR_INPUT_OCS_MON (SELECT * FROM CDR_INPUT_OCS_MON_OLD WHERE CREATED_DATE >= SYSDATE - 31);


-- Recreate the indexes on the partitioned table
--
CREATE INDEX CDR_INPUT_OCS_MON_IDX1 ON CDR_INPUT_OCS_MON (A_NUMBER) LOCAL;

CREATE INDEX CDR_INPUT_OCS_MON_IDX2 ON CDR_INPUT_OCS_MON (TRANSACTION_ID) LOCAL;


-- Create partition local index on created_date
--
CREATE INDEX CDR_INPUT_OCS_MON_IDX3 ON CDR_INPUT_OCS_MON (CREATED_DATE) LOCAL;



