-- MZMOB-175 - Increase OCS field sizes to accommodate cell id data
--
ALTER TABLE CDR_INPUT_OCS_VOICE
  MODIFY CALLED_CELL_ID VARCHAR2(60);  

ALTER TABLE CDR_INPUT_OCS_VOICE
  MODIFY CALLING_CELL_ID VARCHAR2(60);

ALTER TABLE CDR_INPUT_OCS_GPRS
  MODIFY CALLING_CELL_ID VARCHAR2(60);

ALTER TABLE CDR_INPUT_OCS_SMS
  MODIFY CALLED_CELL_ID VARCHAR2(60);
  
ALTER TABLE CDR_INPUT_OCS_SMS
  MODIFY CALLING_CELL_ID VARCHAR2(60);

ALTER TABLE CDR_INPUT_OCS_MMS
  MODIFY CALLED_CELL_ID VARCHAR2(60);

ALTER TABLE CDR_INPUT_OCS_MMS
  MODIFY CALLING_CELL_ID VARCHAR2(60);
