-- MZMOB-454 - Recreate indexes in the CDR_INPUT_IMS table
--
DROP INDEX CDR_INPUT_IMS_IDX1;
 
DROP INDEX CDR_INPUT_IMS_IDX2;
 
CREATE INDEX CDR_INPUT_IMS_IDX1 ON CDR_INPUT_IMS (A_NUMBER) LOCAL PARALLEL 16;
 
CREATE INDEX CDR_INPUT_IMS_IDX2 ON CDR_INPUT_IMS (B_NUMBER) LOCAL PARALLEL 16;
 
ALTER INDEX CDR_INPUT_IMS_IDX1 NOPARALLEL;
 
ALTER INDEX CDR_INPUT_IMS_IDX2 NOPARALLEL;


-- MZMOB-454 - Recreate the indexes in the CDR_INPUT_OCS_GPRS table
--
DROP INDEX CDR_INPUT_OCS_GPRS_IDX1;

CREATE INDEX CDR_INPUT_OCS_GPRS_IDX1 ON CDR_INPUT_OCS_GPRS (A_NUMBER) LOCAL PARALLEL 16;

ALTER INDEX CDR_INPUT_OCS_GPRS_IDX1 NOPARALLEL;


-- MZMOB-454 - Recreate the indexes in the CDR_INPUT_OCS_SMS table
--
DROP INDEX CDR_INPUT_OCS_SMS_IDX1;
 
DROP INDEX CDR_INPUT_OCS_SMS_IDX2;
 
CREATE INDEX CDR_INPUT_OCS_SMS_IDX1 ON CDR_INPUT_OCS_SMS (A_NUMBER) LOCAL PARALLEL 16;
 
CREATE INDEX CDR_INPUT_OCS_SMS_IDX2 ON CDR_INPUT_OCS_SMS (B_NUMBER) LOCAL PARALLEL 16;
 
ALTER INDEX CDR_INPUT_OCS_SMS_IDX1 NOPARALLEL;
 
ALTER INDEX CDR_INPUT_OCS_SMS_IDX2 NOPARALLEL;