CREATE TABLE MZ_CDR_OWNER.ESIMGO_LONGTERM_MSISDN_INFO_UK
(
   TRANSACTION_ID                NUMBER	NOT NULL,
   CREATED_DATE                  DATE	DEFAULT sysdate	NOT NULL,
   INPUT_FILENAME                VARCHAR2(80),  
   MSISDN_COUNT                  NUMBER(15),
   TOTAL_COUNT_IN_REPORT         NUMBER(15)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;

 
CREATE TABLE MZ_CDR_OWNER.ESIMGO_LONGTERM_MSISDN_INFO_ROI
(
   TRANSACTION_ID                NUMBER	NOT NULL,
   CREATED_DATE                  DATE	DEFAULT sysdate	NOT NULL,
   INPUT_FILENAME                VARCHAR2(80),  
   MSISDN_COUNT                  NUMBER(15),
   TOTAL_COUNT_IN_REPORT         NUMBER(15)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;

