-- MZMOB-376 - Add new columns into CDR_INPUT_IMS
--
ALTER TABLE CDR_INPUT_IMS
  ADD POS_IN_FILE NUMBER;

ALTER TABLE CDR_INPUT_IMS
  ADD ANI_UE_TIMEZONE VARCHAR2(20);

ALTER TABLE CDR_INPUT_IMS  
  ADD MSC_NUMBER VARCHAR2(128);

ALTER TABLE CDR_INPUT_IMS   
  ADD VLR_NUMBER VARCHAR2(128);

ALTER TABLE CDR_INPUT_IMS 
  ADD DELIVERY_START_FRACTION NUMBER;

ALTER TABLE CDR_INPUT_IMS
  ADD DELIVERY_END_FRACTION NUMBER;

ALTER TABLE CDR_INPUT_IMS
  ADD ONLINE_CHARGING_FLAG NUMBER;

ALTER TABLE CDR_INPUT_IMS
  ADD MMT_SUBSCRIBER_ROLE NUMBER;

ALTER TABLE CDR_INPUT_IMS
  ADD MMT_SERVICE_TYPE1 NUMBER;

ALTER TABLE CDR_INPUT_IMS
  ADD MMT_SERVICE_MODE1 NUMBER;

ALTER TABLE CDR_INPUT_IMS
  ADD MMT_ASSOC_PARTY_ADDRESS1 VARCHAR2(128);

ALTER TABLE CDR_INPUT_IMS
  ADD MMT_SERVICE_TYPE2 NUMBER;

ALTER TABLE CDR_INPUT_IMS
  ADD MMT_SERVICE_MODE2 NUMBER;

ALTER TABLE CDR_INPUT_IMS
  ADD MMT_ASSOC_PARTY_ADDRESS2 VARCHAR2(128);

ALTER TABLE CDR_INPUT_IMS
  ADD MMT_SERVICE_TYPE3 NUMBER;

ALTER TABLE CDR_INPUT_IMS
  ADD MMT_SERVICE_MODE3 NUMBER;

ALTER TABLE CDR_INPUT_IMS
  ADD MMT_ASSOC_PARTY_ADDRESS3 VARCHAR2(128);

ALTER TABLE CDR_INPUT_IMS
  ADD MMT_SERVICE_TYPE4 NUMBER;

ALTER TABLE CDR_INPUT_IMS
  ADD MMT_SERVICE_MODE4 NUMBER;

ALTER TABLE CDR_INPUT_IMS
  ADD MMT_ASSOC_PARTY_ADDRESS4 VARCHAR2(128);

ALTER TABLE CDR_INPUT_IMS
  ADD MMT_SERVICE_TYPE5 NUMBER;

ALTER TABLE CDR_INPUT_IMS
  ADD MMT_SERVICE_MODE5 NUMBER;

ALTER TABLE CDR_INPUT_IMS
  ADD MMT_ASSOC_PARTY_ADDRESS5 VARCHAR2(128);

ALTER TABLE CDR_INPUT_IMS
  ADD MMT_SERVICE_TYPE6 NUMBER;

ALTER TABLE CDR_INPUT_IMS
  ADD MMT_SERVICE_MODE6 NUMBER;

ALTER TABLE CDR_INPUT_IMS
  ADD MMT_ASSOC_PARTY_ADDRESS6 VARCHAR2(128);

ALTER TABLE CDR_INPUT_IMS
  ADD MMT_SERVICE_TYPE7 NUMBER;

ALTER TABLE CDR_INPUT_IMS
  ADD MMT_SERVICE_MODE7 NUMBER;

ALTER TABLE CDR_INPUT_IMS
  ADD MMT_ASSOC_PARTY_ADDRESS7 VARCHAR2(128);

ALTER TABLE CDR_INPUT_IMS
  ADD MMT_SERVICE_TYPE8 NUMBER;

ALTER TABLE CDR_INPUT_IMS
  ADD MMT_SERVICE_MODE8 NUMBER;

ALTER TABLE CDR_INPUT_IMS
  ADD MMT_ASSOC_PARTY_ADDRESS8 VARCHAR2(128);

ALTER TABLE CDR_INPUT_IMS
  ADD MMT_SERVICE_TYPE9 NUMBER;

ALTER TABLE CDR_INPUT_IMS
  ADD MMT_SERVICE_MODE9 NUMBER;

ALTER TABLE CDR_INPUT_IMS
  ADD MMT_ASSOC_PARTY_ADDRESS9 VARCHAR2(128);

ALTER TABLE CDR_INPUT_IMS
  ADD MMT_SERVICE_TYPE10 NUMBER;

ALTER TABLE CDR_INPUT_IMS
  ADD MMT_SERVICE_MODE10 NUMBER;

ALTER TABLE CDR_INPUT_IMS
  ADD MMT_ASSOC_PARTY_ADDRESS10 VARCHAR2(128);
