-- MZMOB-1014.Consumer ISR resources extract - NAP refinement

DROP INDEX MZ_MOB_DATA_OWNER.AOCS_ISR_RESOURCES_IDX1;

CREATE INDEX AOCS_ISR_RESOURCES_IDX1 ON MZ_MOB_DATA_OWNER.AOCS_ISR_RESOURCES ("RESOURCE_VALUE", "RESOURCE_TYPE", "EFFECTIVE_DATE", "TRANSACTION_ID");
