-- MZMOB-891. [ROI - TAP] Open ROI TAP issues. Issue 2
Update MZ_MOB_DATA_OWNER.DN_FREEPHONE_PREFIX_CODES_TAP_ROI 
set FREEPHONE_PREFIX_CODE = '353800' where FREEPHONE_PREFIX_CODE = '+800';

Update MZ_MOB_DATA_OWNER.DN_FREEPHONE_PREFIX_CODES_TAP_ROI 
set FREEPHONE_PREFIX_CODE = '35315126416', FREEPHONE_PREFIX_DESC = 'Sky Ireland Customer care outside RoI' where FREEPHONE_PREFIX_CODE = '00800';