-- MZMOB-764. CR2022-07 Secondary RAT reporting (5G)

ALTER TABLE CDR_INPUT_PGW_NOKIA
  ADD (
  DATAVOLUMEUPLINK_5G   NUMBER(20,0), 
  DATAVOLUMEDOWNLINK_5G NUMBER(20,0),
  RANSTARTTIME_5G       VARCHAR2(30 BYTE),
  RANENDTIME_5G         VARCHAR2(30 BYTE),
  SECONDARYRATTYPE_5G   VARCHAR2(5 BYTE)
  );